/*
 * Copyright (c) 2025 OceanBase.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef OCEANBASE_ARCHIVE_OB_ARCHIVE_SEQUENCER_H_
#define OCEANBASE_ARCHIVE_OB_ARCHIVE_SEQUENCER_H_

#include "share/ob_thread_pool.h"          // ObThreadPool
#include "common/ob_queue_thread.h"        // ObCond
#include "lib/utility/ob_print_utils.h"    // Print*
#include "ob_archive_define.h"             // DEFAULT_THREAD_RUN_INTERVAL
#include "share/ob_ls_id.h"        // ObLSID
#include "logservice/palf/lsn.h"           // LSN
#include "share/scn.h"           // SCN
#include <cstdint>

namespace oceanbase
{
namespace share
{
class ObLSID;
}

namespace logservice
{
class ObLogService;
}

namespace archive
{
class ObArchiveFetcher;
class ObArchiveLSMgr;
class ObArchiveRoundMgr;
class ObLSArchiveTask;
class ObArchiveLogFetchTask;
using oceanbase::share::ObLSID;
using oceanbase::palf::LSN;
using oceanbase::logservice::ObLogService;

/*
 * Sequencer is the module that generates archiving tasks for each log stream, as well as the module that handles ordering among different log streams
 *
 * Sequencer traverses log streams and generates archiving log range [start_offset, end_offset) tasks for each log stream,
 * where start_offset and end_offset are the starting offsets of a complete log, and each task data range is one
 * complete archive file size, such as 64M/128M..
 *
 * According to the backlog quantity and lag degree of each log stream, it decides how many tasks to generate for each log stream each time,
 * since the Sequencer module itself cannot perceive the relationship between log stream log offset and scn, sequencer uses the progress of the fetcher module
 * and the number of already allocated tasks as a reference for archiving progress
 *
 * NB: The single task generated by Sequencer can include a log range that currently does not exist, i.e., start_offset < commit_lsn < end_offset
 * */
class ObArchiveSequencer : public share::ObThreadPool
{
  // sequencer thread default working cycle
  static const int64_t DEFAULT_THREAD_RUN_INTERVAL = 5 * 1000 * 1000L;
  // Number of LogFetchTasks generated by a single log stream at once
  static const int64_t MAX_TASK_COUNT_SINGLE_CYCLE = 4;

public:
  ObArchiveSequencer();
  ~ObArchiveSequencer();

public:
  int init(const uint64_t tenant_id,
           ObLogService *log_service,
           ObArchiveFetcher *fetcher,
           ObArchiveLSMgr *mgr,
           ObArchiveRoundMgr *round_mgr);
  void destroy();
  int start();
  void stop();
  void wait();
  // Notify sequencer to start for archive service
  void notify_start();
  void signal();

private:

private:
  void run1();
  void do_thread_task_();
  int produce_log_fetch_task_();

private:
  bool                         inited_;
  uint64_t                     tenant_id_;
  int64_t                      round_;
  ObLogService                 *log_service_;
  ObArchiveFetcher             *archive_fetcher_;
  ObArchiveLSMgr               *ls_mgr_;
  ObArchiveRoundMgr            *round_mgr_;
  // All log stream minimum ordering task scn
  share::SCN                      min_scn_;
  // Add enable archive/log stream archive task/as well as consume LogFetchTask to wake up sequencer
  common::ObCond               seq_cond_;
};

/*
 * Iterate through all log streams to determine the sequence progress of the most lagging log stream
 * This log stream serves as the reference for generating archive tasks in this round
 * */
class QueryMinLogTsFunctor
{
public:
  explicit QueryMinLogTsFunctor(const int64_t incarnation, const int64_t round)
    : incarnation_(incarnation),
    round_(round),
    succ_count_(0),
    total_count_(0),
    min_scn_(),
    id_() {}
  bool operator()(const ObLSID &id, ObLSArchiveTask *ls_archive_task);
  void get_min_log_info(ObLSID &id, share::SCN &min_scn);
  TO_STRING_KV(K_(incarnation), K_(round), K_(succ_count), K_(total_count), K_(min_scn), K_(id));

private:
  int64_t incarnation_;
  int64_t round_;
  int64_t succ_count_;
  int64_t total_count_;
  share::SCN min_scn_;
  //MaxLogFileInfo  min_log_info_;
  ObLSID id_;
};

class GenFetchTaskFunctor
{
public:
  explicit GenFetchTaskFunctor(const uint64_t tenant_id,
                               const ArchiveKey &key,
                               const ObLSID &id,
                               ObLogService *log_service,
                               ObArchiveFetcher *fetcher,
                               ObArchiveLSMgr *ls_mgr)
    : tenant_id_(tenant_id),
    key_(key),
    max_delayed_id_(id),
    log_service_(log_service),
    archive_fetcher_(fetcher),
    ls_mgr_(ls_mgr) {}
  bool operator()(const ObLSID &id, ObLSArchiveTask *ls_archive_task);

private:
  void cal_end_lsn_(const LSN &seq_lsn, const LSN &fetch_lsn, const LSN &commit_lsn, LSN &end_lsn);
  int get_commit_index_(const ObLSID &id, LSN &commit_lsn);
  int generate_log_fetch_task_(const ObLSID &id,
      const ArchiveWorkStation &station,
      const LSN &start_lsn,
      const LSN &end_lsn,
      ObArchiveLogFetchTask *&task);
private:
  uint64_t tenant_id_;
  ArchiveKey key_;
  ObLSID max_delayed_id_;
  ObLogService *log_service_;
  ObArchiveFetcher *archive_fetcher_;
  ObArchiveLSMgr *ls_mgr_;

private:
  DISALLOW_COPY_AND_ASSIGN(GenFetchTaskFunctor);
};

} // namespace archive
} // namespace oceanbase

#endif /* OCEANBASE_ARCHIVE_OB_ARCHIVE_SEQUENCER_H_ */
