CREATE TABLE "SA_DB_RESTYPE_SALEPRICE" 
("RES_TYPE_ID" VARCHAR2(32), 
"ORGID" VARCHAR2(32), 
"CHARGEITEMID" VARCHAR2(32), 
"PRICE" NUMBER(12,0), 
"STARTTIME" DATE, 
"ENDTIME" DATE, 
"STATUS" VARCHAR2(32), 
"OPERATOR" VARCHAR2(32), 
"LOWEST_PRICE" NUMBER(12,0), 
"DEALMETHOD" VARCHAR2(16), 
"PRICETYPE" VARCHAR2(32) DEFAULT 'retail', 
"ADDEDTAXRATE" NUMBER(3,0) DEFAULT 0, 
"ADDEDTAXMETHOD" NUMBER(1,0) DEFAULT 0, 
"SCORETYPE" VARCHAR2(32), 
"DEDUCTSCORE" NUMBER(16,0)
);


CREATE TABLE "IM_IF_BB_ACTIVITYCHECK" 
("INTF_DATE" VARCHAR2(8), 
"REC_SEQ" NUMBER(14,0), 
"CHECKMONTH" VARCHAR2(6), 
"PACKAGECODE" VARCHAR2(16), 
"MOBILENO" VARCHAR2(16), 
"IMEI" VARCHAR2(32), 
"STATUS" VARCHAR2(32), 
"STATUS_DATE" DATE, 
"MEMO" VARCHAR2(50)
);

CREATE TABLE "IM_IF_BB_CUSTACTIVATE" 
("INTF_DATE" VARCHAR2(8), 
"REC_SEQ" NUMBER(14,0), 
"REGION" NUMBER(5,0), 
"MOBILENO" VARCHAR2(32), 
"IMEI" VARCHAR2(20), 
"PACKAGECODE" VARCHAR2(32), 
"ACTIVEDATE" DATE, 
"STATUS" VARCHAR2(32), 
"STATUS_DATE" DATE, 
"MEMO" VARCHAR2(50), 
"DELIVERPROVINCE" NUMBER(5,0), 
"CHANNELTYPE" NUMBER(1,0), 
"CHANNELMODEL" NUMBER(1,0), 
"MATERIELCODE" VARCHAR2(32)
);

CREATE TABLE "IM_IF_BB_PRODUCTINFO" 
("INTF_DATE" VARCHAR2(8), 
"REC_SEQ" NUMBER(14,0), 
"PRODUCT_ID" VARCHAR2(32), 
"IDU_TYPE" NUMBER(1,0), 
"MATERIEL_CODE" VARCHAR2(16), 
"VENDOR_ID" VARCHAR2(32), 
"PRD_NAME" VARCHAR2(256), 
"COLOR" VARCHAR2(100), 
"CONF_INFO" VARCHAR2(64), 
"NET_VER" VARCHAR2(64), 
"RECOM_PRICE" NUMBER(12,2), 
"HIGH_PRIC" NUMBER(12,2), 
"BRAND_ID" VARCHAR2(32), 
"PIC_FILE_NAME" VARCHAR2(256), 
"REGISTED_DATE" DATE, 
"PRD_STATUS" VARCHAR2(64), 
"ACESY" VARCHAR2(600), 
"CUSTOMNORM" VARCHAR2(64), 
"VERSION" VARCHAR2(64), 
"STATUS" VARCHAR2(32), 
"STATUS_DATE" DATE, 
"MEMO" VARCHAR2(50), 
"SELLTYPE" NUMBER(1,0), 
"PRODUCTIONSTATUS" VARCHAR2(50), 
"INDATE" DATE, 
"PICTURETYPE" VARCHAR2(50), 
"CUSTOMERTYPE" VARCHAR2(50), 
"PRODUCTPACKAGE" VARCHAR2(1000), 
"LOWEND" VARCHAR2(10), 
"PILOTPRODUCT" VARCHAR2(10), 
"STEERFLAG" VARCHAR2(10), 
"PRD_MODE" VARCHAR2(15), 
"JOIN_TYPE" VARCHAR2(10)
);

CREATE TABLE "IM_IF_BB_PROPACKAGES" 
("INTF_DATE" VARCHAR2(8), 
"REC_SEQ" NUMBER(14,0), 
"PACKAGE_CODE" VARCHAR2(16), 
"PACKAGE_CONTENT" VARCHAR2(1023), 
"STATUS" VARCHAR2(32), 
"STATUS_DATE" DATE, 
"MEMO" VARCHAR2(50)
);

CREATE TABLE "IM_IF_BB_REEXACTIVITY" 
("INTF_DATE" VARCHAR2(8), 
"REC_SEQ" NUMBER(14,0), 
"BUSITYPE" VARCHAR2(4), 
"OPTYPE" NUMBER(1,0), 
"IMEI" VARCHAR2(32), 
"OUT_IMEI" VARCHAR2(32), 
"BUSIDATE" DATE, 
"CHANNELTYPE" NUMBER(1,0), 
"REGION" NUMBER(5,0), 
"MOBILENO" VARCHAR2(16), 
"PACKAGECODE" VARCHAR2(16), 
"STATUS" VARCHAR2(32), 
"STATUS_DATE" DATE, 
"MEMO" VARCHAR2(50), 
"CHANNELMODEL" NUMBER(1,0)
);

CREATE TABLE "IM_IF_BB_RESOURCE" 
("PARAM_TYPE_ID" VARCHAR2(32), 
"PARAM_TYPE_NAME" VARCHAR2(128), 
"PARAM_ID" VARCHAR2(32), 
"PARAM_NAME" VARCHAR2(64), 
"STATE" NUMBER(1,0)
);

CREATE TABLE "IM_IF_BB_TASK" 
("TASK_NO" VARCHAR2(20), 
"TASK_NAME" VARCHAR2(50), 
"TRANS_DIRECT" VARCHAR2(10), 
"TASK_OPERATOR" VARCHAR2(20), 
"TASK_STATUS" VARCHAR2(10), 
"STATUS_TIME" DATE
);

CREATE TABLE "IM_BUSI_SET" 
("RES_TYPE_ID" VARCHAR2(32), 
"BUSI_TYPE" VARCHAR2(32), 
"BUSI_NAME" VARCHAR2(64), 
"BUSI_MEMO" VARCHAR2(200), 
"STATUS" VARCHAR2(32), 
"EFF_DATE" DATE, 
"EXP_DATE" DATE
);

CREATE TABLE "IM_BUSI_SET_PARAMCHG" 
("BUSI_TYPE" VARCHAR2(32), 
"BUSI_NAME" VARCHAR2(64), 
"BUSI_MEMO" VARCHAR2(200), 
"STATUS" VARCHAR2(32), 
"EFF_DATE" DATE, 
"EXP_DATE" DATE, 
"EVENT_TYPE" VARCHAR2(32), 
"IF_LOG" NUMBER(1,0), 
"HANDLE_DO" VARCHAR2(32), 
"ORDER_SEQ" NUMBER(3,0)
);

CREATE TABLE "IM_DICT_ITEM" 
("ITEMID" VARCHAR2(32), 
"ITEMNAME" VARCHAR2(64), 
"GROUPID" VARCHAR2(32), 
"SORTORDER" NUMBER(3,0) DEFAULT 0, 
"DESCRIPTION" VARCHAR2(256), 
"CREATEDATE" DATE, 
"STATUS" NUMBER(1,0) DEFAULT 0, 
"STATUSDATE" DATE
);

CREATE TABLE "IM_IF_SEGMENT_SCPINFO" 
("REGION" NUMBER(6,0), 
"SCP_ID" VARCHAR2(32), 
"SCP_NAME" VARCHAR2(32), 
"STATUS" VARCHAR2(32)
);

CREATE TABLE "IM_QRY_COND_MATCHER" 
("QUERY_ID" VARCHAR2(32), 
"COND_NAME" VARCHAR2(32), 
"MATCHER" VARCHAR2(32), 
"SQL" VARCHAR2(2000), 
"PARAM_1" VARCHAR2(32), 
"PARAM_2" VARCHAR2(32), 
"PARAM_3" VARCHAR2(32), 
"PARAM_4" VARCHAR2(32)
);

CREATE TABLE "IM_QUERY" 
("QUERY_ID" VARCHAR2(32), 
"QUERY_NAME" VARCHAR2(64), 
"SQL" VARCHAR2(2000), 
"MEMO" VARCHAR2(500), 
"IS_HEAD" CHAR(1) DEFAULT 'Y', 
"IF_ORDER" VARCHAR2(8) DEFAULT 'NO'
);

CREATE TABLE "IM_RES_TYPE" 
("RES_TYPE_ID" VARCHAR2(32), 
"RES_TYPE_NAME" VARCHAR2(64), 
"RES_TABLE_NAME" VARCHAR2(50), 
"IF_STOCKS" VARCHAR2(32), 
"PARENT_RES_ID" VARCHAR2(32), 
"IF_BASE" VARCHAR2(32), 
"SUPPLIER_ID" VARCHAR2(32) DEFAULT 'UNKNOWN', 
"IF_SEQUENCE" VARCHAR2(32), 
"RES_TYPE_MEMO" VARCHAR2(500), 
"STATUS" VARCHAR2(32), 
"EFF_DATE" DATE, 
"EXP_DATE" DATE, 
"CREATE_ORG_ID" VARCHAR2(32), 
"RES_KIND_ID" VARCHAR2(32), 
"IF_PHYSICAL" VARCHAR2(32), 
"VERSION_NUMBER" VARCHAR2(50), 
"RES_LIMIT" VARCHAR2(32), 
"INV_NAME" VARCHAR2(32), 
"INV_ID_LENGTH" NUMBER(3,0) DEFAULT 0, 
"INV_SEG_LEN" NUMBER(3,0) DEFAULT 0, 
"NET_TYPE" VARCHAR2(32) DEFAULT 'ALL', 
"REGION" NUMBER(6,0), 
"LAST_BUSI_ID" VARCHAR2(32), 
"STATUS_DATE" DATE DEFAULT sysdate, 
"OPER_ID" VARCHAR2(32), 
"BRAND_ID" VARCHAR2(32), 
"SPECTPLT_ID" VARCHAR2(32), 
"MEASURE_UNIT" VARCHAR2(32), 
"IS_BATCH_MGR" NUMBER(1,0), 
"RES_MODULE_TYPE" NUMBER(1,0), 
"IF_SYN" VARCHAR2(32), 
"GOODS_KIND_ID" VARCHAR2(32), 
"PARENT_GOODS_ID" VARCHAR2(32), 
"CREATE_DATE" DATE DEFAULT sysdate, 
"PARTICULAR_ATTR" VARCHAR2(128), 
"RES_SPECIAL_MODEL" VARCHAR2(32)
);

CREATE TABLE "IM_RES_TYPE_ATTR_SET" 
("RES_TYPE_ID" VARCHAR2(32), 
"ATTR_ID" VARCHAR2(32), 
"ATTR_VALUE" VARCHAR2(500), 
"STATUS" VARCHAR2(32), 
"STATUS_DATE" DATE, 
"STATUS_OPER_ID" VARCHAR2(32), 
"CREATE_DATE" DATE, 
"CREATE_OPER_ID" VARCHAR2(32), 
"IF_SYSTEM" VARCHAR2(32), 
"IS_PRIMARY_KEY" NUMBER(1,0), 
"TPLT_ID" VARCHAR2(32), 
"ATTR_NAME" VARCHAR2(64), 
"ATTR_VALUE_DESC" VARCHAR2(1024), 
"EXTVALUE1" VARCHAR2(256), 
"EXTVALUE2" VARCHAR2(256), 
"EXTVALUE3" VARCHAR2(256)
);

CREATE TABLE "IM_RES_TYPE_COLOR" 
("RES_TYPE_ID" VARCHAR2(32), 
"COLOR" VARCHAR2(32)
);

CREATE TABLE "IM_VENDOR_INFO" 
("VENDOR_ID" VARCHAR2(32), 
"MIS_VENDOR_ID" VARCHAR2(32), 
"RES_KIND_ID" VARCHAR2(32), 
"VENDOR_NAME" VARCHAR2(64), 
"ADDRESS" VARCHAR2(128), 
"POST_CODE" NUMBER(6,0), 
"LINK_MAN" VARCHAR2(32), 
"LINK_PHONE" VARCHAR2(32), 
"FAX_PHONE" VARCHAR2(32), 
"STATUS" NUMBER(1,0), 
"CREATE_DATE" DATE, 
"CREATE_OPERATOR" VARCHAR2(32), 
"MAPPING_ID" VARCHAR2(32), 
"REGION" NUMBER(6,0) DEFAULT 999
);

CREATE TABLE "PSI_CFG_RESBRAND" 
("RES_KIND_ID" VARCHAR2(32), 
"BRAND_ID" VARCHAR2(32), 
"BRAND_NAME" VARCHAR2(64), 
"BRAND_DESC" VARCHAR2(256), 
"VENDOR_ID" VARCHAR2(32), 
"CREATE_DATE" DATE, 
"STATUS" VARCHAR2(32), 
"STATUS_DATE" DATE, 
"CREATE_OPER" VARCHAR2(32), 
"BRAND_IMAGE_NAME" VARCHAR2(256), 
"BRAND_IMAGE_UNIFIEDNAME" VARCHAR2(256), 
"BRAND_LEVEL" VARCHAR2(32), 
"GOODS_KIND_ID" VARCHAR2(32), 
"SORT_ORDER" NUMBER(3,0)
);

CREATE TABLE "IM_IF_SEGMENT_HLRINFO" 
("REGION" number(6), 
"MAIN_HLR_ID" VARCHAR2(32), 
"MAIN_HLR_NAME" VARCHAR2(256), 
"BK_HLR_ID" VARCHAR2(32),
"STATUS" VARCHAR2(32)
);


