CREATE TABLE "REPLX_LOG" 
("REGION" NUMBER(4,0), 
"INSTANCE_ID" NUMBER(2,0), 
"SEQNUM" NUMBER(14,0), 
"TABLE_OWNER" VARCHAR2(32), 
"TABLE_NAME" VARCHAR2(64), 
"OPERATION" CHAR(1), 
"HASH_VAL" NUMBER(4,0), 
"ROW_ID" VARCHAR2(128), 
"PKEY" VARCHAR2(1024), 
"PRIORITY" NUMBER(2,0), 
"SCN" NUMBER(14,0), 
"SRC_DB" VARCHAR2(32), 
"DST_DB" VARCHAR2(32), 
"INTIME" DATE DEFAULT sysdate
 ) 
PARTITION BY LIST ("INSTANCE_ID") 
(PARTITION "REPLX_LOG_1"  VALUES (1) , 
 PARTITION "REPLX_LOG_2"  VALUES (2) , 
 PARTITION "REPLX_LOG_10"  VALUES (10) , 
 PARTITION "REPLX_LOG_20"  VALUES (20) ) ;

CREATE TABLE "REPLICATE_SWITCH" 
("INSTANCE_ID" NUMBER(2,0), 
"SWITCH_FLAG" NUMBER(1,0), 
"POLL_INTERVAL" NUMBER(4,0), 
"SWITCH_TIME" DATE, 
"MEMO" VARCHAR2(256)
);

CREATE SEQUENCE "REPLX_SEQ"  MINVALUE 1 MAXVALUE 9999999999999 INCREMENT BY 1 START WITH 9539211 CACHE 20000 NOORDER  CYCLE ;

