## hosts for observer and obproxy
1.obs_hosts=HOST,HOST
2.obs_hosts=HOST,HOST
3.obs_hosts=HOST,HOST
4.obs_hosts=HOST,HOST
1.proxy_hosts = HOST,HOST

1.ct_hosts = HOST,HOST

## 多集群配置
2:1.obs_hosts=HOST,HOST
2:2.obs_hosts=HOST,HOST
2:3.obs_hosts=HOST,HOST
2:4.obs_hosts=HOST,HOST

3:1.obs_hosts=HOST,HOST
3:2.obs_hosts=HOST,HOST
# ob静态数据目录配置
data_path = HOME_PATH/obtest_data/datadir

# clog/ilog等目录配置
clog_path = HOME_PATH/obtest_data/datadir

# ob工作目录配置
workdir = HOME_PATH/obtest_data/workdir
# shared_storage模式
shared_storage=s3://test-bucket/clog_and_data?host=http://127.0.0.1:11211&access_id=******&access_key=******&s3_region=us-east-1&max_iops=10000&max_bandwidth=1GB&scope=region
ob_startup_mode=shared_storage
# 端口配置
proxy_port=proxyport
proxy_rpc_port=2929
port_base=PORT_BASE
#mysql_port=2727
#rpc_port=2726
#指定仲裁ip和端口
1.asvr_hosts = HOST
asvr_port = 9878
# 内存配置
memory_size_limit=80G
log_disk_size=150G
# cpu配置
node_cpu_count = 20

# 是否收集core文件
save_core=1

# 是否收集日志文件，默认收集在obtest/collected_log
save_log=1
#结束时是否陈升pstack
gen_pstack=1
# 打开独立子进程
enable_obesi=1
# 启动case前，是否清空环境(配置中所有机器)
cleanup=1
# case运行完后， 是否清空环境(配置中所有机器)
cleanup_after=1
## delete core when rebooting if value is 1
delete_core_on_reboot=0
##配置是否需要统计覆盖率 with_coverage=1时，每个case结束都会stop obs
with_coverage=0
# configserver配置
obconfig=http://ob-jenkins.alibaba.net:8081/oceanbase_configer/v2/
configServer=http://ob-jenkins.alibaba.net:8081/diamond/cgi/a.py
# 数据盘大小配置
disk_avail_space=60G

# proxy和server日志级别配置info/trace/debug
proxy_log_level=info
server_log_level=info
#租户创建后调整合并和备份配置项
extra_tenant_params=ob_compaction_schedule_interval = '3s',compaction_low_thread_score = 100,compaction_mid_thread_score = 100,compaction_high_thread_score = 100,merger_check_interval = '10s',ha_high_thread_score = 100,ha_mid_thread_score = 100,ha_low_thread_score = 100,major_freeze_duty_time = 'disable'
# docker上不带bond0,这里配置网卡为eth0
dev=devport

# 0: 表示oss备份. 1: 表示文件系统备份. 2: 表示cos备份.
backup_restore_mode=storage_mode
restore_delay=15000
backup_regression_mode=true
checkout_time=1800
# the dir name of backup for nfs\oss\cos
file_dir = HOME_PATH/obtest_data/obtest_backup
# for nfs backup_backup_dest
file_dir_1 = HOME_PATH/obtest_data/obtest_backup_backup

#ob_admin配置项
backup_validation_concurrency = 1
backup_validation_io_bandwidth_limit = 1000
#备份恢复的配置
#s3_bucket不支持写桶后加目录
s3_bucket=s3://test-bucket
s3_host=http://127.0.0.1:11211
s3_id=backup_ak
s3_key=backup_sk
s3_region=cn-north-1

# oss备份恢复的配置，如果是文件系统的不需要改这个
#oss_bucket不支持写桶后加目录
oss_bucket=oss://oss-374818-0110-regression-by-shanghai
oss_host=oss-cn-shanghai.aliyuncs.com
oss_id=backup_ak
oss_key=backup_sk
oss_region=cn-north-1
#oss_vip_server=jmenv.tbsite.net
# for oss backup_backup_dest
oss_bucket_1=oss://oss-374818-0110-regression-by-shanghai
oss_host_1=oss-cn-shanghai.aliyuncs.com
oss_id_1=backup_ak
oss_key_1=backup_sk
oss_region_1=cn-north-1
#oss_vip_server_1=jmenv.tbsite.net
#oss_vip_host_1=cn-hangzhou-alipay-b.oss-cdn.aliyun-inc.com

# cos备份恢复的配置
#cos_bucket不支持写桶后加目录
cos_bucket=cos://cos-374818-0211-regression-1317978819
cos_host=cos.ap-shanghai.myqcloud.com
cos_id=backup_ak
cos_key=backup_sk
cos_region=ap-shanghai
cos_appid=1317978819
# for cos backup backup
cos_bucket_1=cos://cos-374818-0211-regression-1317978819
cos_host_1=os.ap-shanghai.myqcloud.com
cos_id_1=backup_ak
cos_key_1=backup_sk
cos_region_1=ap-shanghai
cos_appid_1=1317978819
#obs_bucket不支持写桶后加目录
obs_bucket=obs://obs-374818-0211-regression
obs_host=obs.cn-north-4.myhuaweicloud.com
obs_id=backup_ak
obs_key=backup_sk
obs_region=cn-north-4

obs_bucket_1=obs://obs-374818-0211-regression
obs_host_1=obs.cn-north-4.myhuaweicloud.com
obs_id_1=backup_ak
obs_key_1=backup_sk
obs_region_1=cn-north-4
