## hosts for observer and obproxy
1.obs_hosts=10.101.61.84,10.101.66.184,10.101.62.185
2.obs_hosts=10.101.63.155,10.101.63.114,10.101.67.9
3.obs_hosts=10.101.63.103,10.218.79.192,10.101.63.149
4.obs_hosts=10.218.79.192,10.101.62.185,10.101.67.9
5.obs_hosts=10.101.67.9,10.101.63.149,10.101.63.155
6.obs_hosts=10.101.62.185
7.obs_hosts=10.101.67.9
8.obs_hosts=10.101.63.149
9.obs_hosts=10.101.63.155
10.obs_hosts=10.101.62.179

proxy_hosts = 10.101.67.9

use_static_connection = 0

## data path
# workdir, data_path and clog_path will be replaced by ak obtest, don't modify the following lines
data_path=~/data
clog_path=~/clog

# resource limit
memory_size_limit =68719476736
node_cpu_count=16
node_cpu_reserved=0
disk_avail_space=5G
server_log_level=info

## save core to collected_log if value is 1
## default value : 1
save_core=0

## save server log to collected_log if values is 1
## default value : 1
save_log=0

## kill all observer and obproxy in machine before the execution
## default value : 1
cleanup=1
with_coverage=1

## 增加配置项cleanup_after用于控制跑完case之后是否清理环境,0为不清理环境,1为清理,默认为0;
cleanup_after=0

## 增加配置项portOffest,用于配置端口号的便宜,默认为0;
# port_offset will be replaced by ak obtest, don't modify the following line
port_offset=0

## for obproxy
configServer=10.244.4.23:8080/diamond/cgi/a.py
proxy_log_level=info
mock_server_path=/home/hudson/obtest_1.0/mockobserver
