## hosts for observer and obproxy
1.obs_hosts=127.0.0.1,127.0.0.2,127.0.0.3,127.0.0.4
2.obs_hosts=100.69.197.162,100.69.197.180,100.69.197.48,100.69.198.71
3.obs_hosts=100.69.199.124,100.69.199.167,100.69.199.226,100.69.199.238

proxy_hosts = 127.0.0.1

ct_hosts =127.0.0.1

# ob静态数据目录配置
data_path = /data/1

# clog等目录配置
clog_path = /data/1

# ob工作目录配置
workdir = ~/

# 内存配置
#memory_size_limit=51539607552

# cpu配置
node_cpu_count = 16

# 是否收集core文件
save_core=0

# 是否收集日志文件，默认收集在obtest/collected_log
save_log=1

# 启动case前，是否清空环境(配置中所有机器)
cleanup=1

# configserver配置

# 数据盘大小配置
disk_avail_space=5G

# proxy和server日志级别配置info/trace/debug
proxy_log_level=info
server_log_level=info
