## hosts for observer and obproxy
1.obs_hosts=10.101.61.84,10.101.66.184,10.101.62.185
2.obs_hosts=10.101.63.155,10.101.63.114,10.101.67.9
3.obs_hosts=10.101.63.103,10.218.79.192,10.101.63.149
4.obs_hosts=10.218.79.192,10.101.62.185,10.101.67.9
5.obs_hosts=10.101.67.9,10.101.63.149,10.101.63.155
6.obs_hosts=10.101.62.185
7.obs_hosts=10.101.67.9
8.obs_hosts=10.101.63.149
9.obs_hosts=10.101.63.155
10.obs_hosts=10.101.62.179

proxy_hosts = 10.101.67.9

use_static_connection = 0

2:1.obs_hosts=10.101.67.9,10.101.63.149
2:2.obs_hosts=10.101.63.155,10.101.62.179
2:3.obs_hosts=10.101.62.185,10.218.79.192

## data path
# workdir, data_path and clog_path will be replaced by ak obtest, don't modify the following lines
data_path=/home/hudson/ak_obtest/data
clog_path=/home/hudson/ak_obtest/clog
workdir=/home/hudson/ak_obtest/
user              = hudson
ob_version        = 1.0

# resource limit
memory_size_limit =68719476736
node_cpu_count=16
node_cpu_reserved=0
disk_avail_space=5G
server_log_level=info

## save core to collected_log if value is 1
## default value : 1
save_core=1

## save server log to collected_log if values is 1
## default value : 1
save_log=1

## kill all observer and obproxy in machine before the execution
## default value : 1
cleanup=0

## 增加配置项cleanup_after用于控制跑完case之后是否清理环境,0为不清理环境,1为清理,默认为0;
cleanup_after=1

## 增加配置项portOffest,用于配置端口号的便宜,默认为0;
# port_offset will be replaced by ak obtest, don't modify the following line
port_offset=0

## for obproxy
#configServer=https://obconfig.alibaba.net/diamond/cgi/a.py
proxy_log_level=info
mock_server_path=/home/hudson/obtest_1.0/mockobserver

##
#obconfig = http://10.244.4.22:8080/oceanbase_obconfig/
configServer = http://10.244.4.22:8080/diamond/cgi/a.py
obConfig=http://10.244.4.22:8080/oceanbase_configer/v2/
