create or replace TYPE "NT" as table of number;
create or replace TYPE "VT" as table of varchar2(32767);
create or replace TYPE "ARRAY" as table of VT;

CREATE TABLE "PDMS"."DM_DATA_SEG" (
  "DATA_SEG" VARCHAR2(7) NOT NULL,
  "ATTR_ID" VARCHAR2(3) NOT NULL,
  "MSISDN_COUNT" NUMBER(6) NOT NULL,
  "DATA_SEG_STATE" NUMBER(1) NOT NULL,
  "NOTES" VARCHAR2(100),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_DATA_SEG" PRIMARY KEY ("DATA_SEG")
);

CREATE TABLE "PDMS"."DM_DATA_SEG_TEMP" (
  "DATA_SEG_SEQ" VARCHAR2(20) NOT NULL,
  "REGION_NAME" VARCHAR2(15),
  "REGION_CODE" VARCHAR2(15),
  "HLR_NAME" VARCHAR2(15),
  "HLR_CODE" VARCHAR2(15),
  "DATA_SEG" VARCHAR2(7),
  "ATTR_ID" VARCHAR2(5),
  "DATA_SEG_TIME" DATE,
  "DATA_TYPE" VARCHAR2(10),
  "NOTES" VARCHAR2(100),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
) ;

CREATE TABLE "PDMS"."DM_DATASEG_BATCH" (
  "DATA_BATCH_NUM" VARCHAR2(20) DEFAULT '' NOT NULL,
  "DATA_BATCH_FILE" VARCHAR2(500) DEFAULT '',
  "DATA_BATCH_FLAG" NUMBER(1) DEFAULT 0,
  "DATA_BATCH_COUNT" NUMBER(11) DEFAULT 0,
  "DATA_BATCH_TIME" DATE DEFAULT '',
  "STATUS" NUMBER(5) DEFAULT 0,
  "NOTES" VARCHAR2(500) DEFAULT '',
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
) ;

CREATE TABLE "PDMS"."DM_HLR_LINK" (
  "ATTR_ID" NUMBER(3) NOT NULL,
  "ATTR_NAME" VARCHAR2(24) NOT NULL,
  "PARENT_ID" NUMBER(3) NOT NULL,
  "ATTR_LEVEL" NUMBER(2) NOT NULL,
  "END_TAG" VARCHAR2(10) NOT NULL,
  "NOTES" VARCHAR2(100),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_ATTR_ID" PRIMARY KEY ("ATTR_ID")
);

CREATE TABLE "PDMS"."DM_HLR" (
  "HLR_NAME" VARCHAR2(24) NOT NULL,
  "HLR_CODE" VARCHAR2(10) NOT NULL,
  "REGION_CODE" VARCHAR2(5) NOT NULL,
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
);

CREATE TABLE "PDMS"."DM_REGION" (
  "REGION_ID" NUMBER(11) NOT NULL,
  "REGION_CODE" VARCHAR2(5) NOT NULL,
  "REGION_NAME" VARCHAR2(20) NOT NULL,
  "REGION_SHORT" VARCHAR2(10) NOT NULL,
  "SMSP" VARCHAR2(14) NOT NULL,
  "CONTACT_PERSON" VARCHAR2(20),
  "CONTACT_TEL" VARCHAR2(20),
  "FAX_NUM" VARCHAR2(20),
  "POST_NUM" VARCHAR2(10),
  "POST_ADDR" VARCHAR2(200),
  "NOTES" VARCHAR2(100),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_REGION_ID" PRIMARY KEY ("REGION_ID")
);

CREATE TABLE "PDMS"."DM_ORDER" (
  "ORDER_CODE" VARCHAR2(9) NOT NULL,
  "FACTORY_NAME" VARCHAR2(20) NOT NULL,
  "CARD_TYPE" VARCHAR2(40) NOT NULL,
  "ORDER_COUNT" NUMBER(11) NOT NULL,
  "ORDER_TIME" DATE DEFAULT sysdate NOT NULL,
  "ORDER_STATUS" NUMBER(1) NOT NULL,
  "NOTES" VARCHAR2(100),
  "FACTORY_CODE" VARCHAR2(5),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_ORDER_CODE" PRIMARY KEY ("ORDER_CODE")
);

CREATE TABLE "PDMS"."DM_BATCH" (
  "BATCH_NUM" VARCHAR2(12) NOT NULL,
  "BATCH_REGION" VARCHAR2(16) NOT NULL,
  "SMSP" VARCHAR2(14) NOT NULL,
  "HLR_NAME" VARCHAR2(24) NOT NULL,
  "BRAND_NAME" VARCHAR2(30),
  "FACTORY_NAME" VARCHAR2(20) NOT NULL,
  "CARD_TYPE" VARCHAR2(40) NOT NULL,
  "MSISDN_START" VARCHAR2(11) NOT NULL,
  "MSISDN_END" VARCHAR2(11) NOT NULL,
  "DATA_TYPE" VARCHAR2(12) NOT NULL,
  "BATCH_COUNT" NUMBER(11) NOT NULL,
  "IMSI_START" VARCHAR2(15) NOT NULL,
  "IMSI_END" VARCHAR2(15) NOT NULL,
  "ICCID_START" VARCHAR2(20) NOT NULL,
  "ICCID_END" VARCHAR2(20) NOT NULL,
  "BATCH_TIME" DATE DEFAULT sysdate NOT NULL,
  "BATCH_STATUS" NUMBER(1) NOT NULL,
  "PRODUCE_STATUS" NUMBER(1) NOT NULL,
  "ORDER_CODE" VARCHAR2(9) NOT NULL,
  "NOTES" VARCHAR2(100),
  "FACTORY_CODE" VARCHAR2(5),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_BATCH_CODE" PRIMARY KEY ("BATCH_NUM")
);
CREATE TABLE "PDMS"."DM_LBYK_RPM_TEMP" (
  "ORDER_CODE" VARCHAR2(9) NOT NULL,
  "IMSI" VARCHAR2(15) NOT NULL,
  "ICCID" VARCHAR2(20) NOT NULL,
  "PIN1" VARCHAR2(4) NOT NULL,
  "PIN2" VARCHAR2(4) NOT NULL,
  "PUK1" VARCHAR2(8) NOT NULL,
  "PUK2" VARCHAR2(8) NOT NULL,
  "SMSP" VARCHAR2(14) NOT NULL,
  "KIND_ID" NUMBER(3) NOT NULL,
  "RESERVE1" NUMBER(11),
  "RESERVE2" VARCHAR2(128),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "DM_LBYK_RPM_TEMP_PK" PRIMARY KEY ("ICCID"),
  CONSTRAINT "UE_RPM_IMSI" UNIQUE ("IMSI")
) ;

CREATE TABLE "PDMS"."DM_LBYK_MSISDN_TEMP" (
  "ORDER_CODE" VARCHAR2(9) NOT NULL,
  "MSISDN" VARCHAR2(13) NOT NULL,
  "DATA_SEG" VARCHAR2(7) NOT NULL,
  "RESERVE1" NUMBER(11),
  "RESERVE2" VARCHAR2(128),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
);

CREATE TABLE "PDMS"."DM_BLANK_CARD" (
  "BATCH_NUM" VARCHAR2(9) NOT NULL,
  "CARD_SN" VARCHAR2(20) NOT NULL,
  "K1" VARCHAR2(32) NOT NULL,
  "EKI" VARCHAR2(32),
  "K" VARCHAR2(32),
  "OPC" VARCHAR2(32),
  "VICE_EKI" VARCHAR2(32),
  "VICE_K" VARCHAR2(32),
  "VICE_OPC" VARCHAR2(32),
  "SN_TIME" DATE DEFAULT sysdate NOT NULL,
  "SEID" VARCHAR2(20),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_CARD_SN" PRIMARY KEY ("CARD_SN")
);

CREATE TABLE "PDMS"."DM_LBYK_DATA_TEMP" (
  "ORDER_CODE" VARCHAR2(9) NOT NULL,
  "MSISDN" VARCHAR2(13) NOT NULL,
  "CARD_SN" VARCHAR2(20) NOT NULL,
  "K" VARCHAR2(32) NOT NULL,
  "OPC" VARCHAR2(32),
  "K1" VARCHAR2(32) NOT NULL,
  "IMSI" VARCHAR2(15) NOT NULL,
  "ICCID" VARCHAR2(20) NOT NULL,
  "PIN1" VARCHAR2(4) NOT NULL,
  "PIN2" VARCHAR2(4) NOT NULL,
  "PUK1" VARCHAR2(8) NOT NULL,
  "PUK2" VARCHAR2(8) NOT NULL,
  "SMSP" VARCHAR2(14) NOT NULL,
  "KIND_ID" NUMBER(3) NOT NULL,
  "RESERVE1" NUMBER(11),
  "RESERVE2" NUMBER(11),
  "RESERVE3" VARCHAR2(128),
  "RESERVE4" VARCHAR2(128),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "DM_LBYK_DATA_TEMP_PK" PRIMARY KEY ("CARD_SN"),
  CONSTRAINT "UE_DATA_IMSI" UNIQUE ("IMSI"),
  CONSTRAINT "UE_DATA_MSISDN" UNIQUE ("MSISDN")
) ;

CREATE TABLE "PDMS"."DM_USER" (
  "USER_ID" NUMBER(11) NOT NULL,
  "USER_NAME" VARCHAR2(32) NOT NULL,
  "PASS_WORD" VARCHAR2(32) NOT NULL,
  "REG_DATE" DATE DEFAULT sysdate NOT NULL,
  "LOGIN_FAILED_TIMES" NUMBER(2) DEFAULT 0 NOT NULL,
  "ALIAS" VARCHAR2(64) DEFAULT '操作员' NOT NULL,
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_DM_USER_ID" PRIMARY KEY ("USER_ID"),
  CONSTRAINT "UE_DM_USER_NAME" UNIQUE ("USER_NAME")
);

CREATE TABLE "PDMS"."DM_LOG" (
  "LOG_ID" NUMBER(11) NOT NULL,
  "USER_NAME" VARCHAR2(20) NOT NULL,
  "LOG_TYPE" NUMBER(1) NOT NULL,
  "LOG_IP" VARCHAR2(15) DEFAULT '127.0.0.1' NOT NULL,
  "LOG_CONTENT" VARCHAR2(1024),
  "LOG_TIME" DATE DEFAULT sysdate NOT NULL,
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_DM_LOG_ID" PRIMARY KEY ("LOG_ID")
) ;

CREATE TABLE "PDMS"."DM_CHECK_CODE" (
  "REQUEST_IP" VARCHAR2(15) NOT NULL,
  "CHECK_CODE" VARCHAR2(10) NOT NULL,
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_DM_REQUEST_IP" PRIMARY KEY ("REQUEST_IP")
);
CREATE TABLE "PDMS"."DM_LOGIN_IDKEY" (
  "ID_KEY" VARCHAR2(8) NOT NULL,
  "RESERVE1" NUMBER(11),
  "RESERVE2" VARCHAR2(32),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_ID_KEY" PRIMARY KEY ("ID_KEY")
);

CREATE TABLE "PDMS"."DM_ENCRYPTED_KI" (
  "DATA_ID" NUMBER(6) NOT NULL,
  "ENCRYPTED_DATA" VARCHAR2(4) NOT NULL,
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_DATA_ID" PRIMARY KEY ("DATA_ID")
);

CREATE TABLE "PDMS"."DM_FACTORY" (
  "FACTORY_ID" NUMBER(11) NOT NULL,
  "FACTORY_CODE" VARCHAR2(2) NOT NULL,
  "FACTORY_NAME" VARCHAR2(20) NOT NULL,
  "CONTACT_PERSON" VARCHAR2(20),
  "CONTACT_TEL" VARCHAR2(20),
  "FAX_NUM" VARCHAR2(20),
  "POST_NUM" VARCHAR2(10),
  "POST_ADDR" VARCHAR2(100),
  "NOTES" VARCHAR2(100),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_FACTORY_ID" PRIMARY KEY ("FACTORY_ID")
) ;

CREATE TABLE "PDMS"."DM_CARD_TYPE" (
  "CARD_ID" NUMBER(11) NOT NULL,
  "CARD_CODE" VARCHAR2(3) NOT NULL,
  "CARD_NAME" VARCHAR2(50) NOT NULL,
  "CARD_CAPACITY" VARCHAR2(20),
  "CARD_STATE" VARCHAR2(1) NOT NULL,
  "ATTR" NUMBER(1) NOT NULL,
  "NOTES" VARCHAR2(100),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_CARD_ID" PRIMARY KEY ("CARD_ID")
) ;

CREATE TABLE "PDMS"."DM_BLANK_CARD_BATCH" (
  "BATCH_NUM" VARCHAR2(9) NOT NULL,
  "FACTORY_NAME" VARCHAR2(20) NOT NULL,
  "CARD_NAME" VARCHAR2(50) NOT NULL,
  "PRESET_FLAG" VARCHAR2(1) NOT NULL,
  "SINGLE_FLAG" VARCHAR2(1) NOT NULL,
  "SIM_FLAG" VARCHAR2(2) NOT NULL,
  "SWP_FLAG" VARCHAR2(1) NOT NULL,
  "M2M_FLAG" VARCHAR2(1) NOT NULL,
  "CARD_SN_START" VARCHAR2(20) NOT NULL,
  "CARD_SN_END" VARCHAR2(20) NOT NULL,
  "BATCH_COUNT" NUMBER NOT NULL,
  "BATCH_TIME" DATE DEFAULT sysdate NOT NULL,
  "STATUS" VARCHAR2(1) NOT NULL,
  "ALLOT" VARCHAR2(1024),
  "NOTES" VARCHAR2(100),
  "FACTORY_CODE" VARCHAR2(5),
  "SEID_START" VARCHAR2(20),
  "SEID_END" VARCHAR2(20),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_BC_BATCH_NUM" PRIMARY KEY ("BATCH_NUM")
);

CREATE TABLE "PDMS"."DM_BLANK_CARD_TEMP" (
  "BATCH_NUM" VARCHAR2(9) NOT NULL,
  "CARD_SN" VARCHAR2(20) NOT NULL,
  "K1" VARCHAR2(32) NOT NULL,
  "EKI" VARCHAR2(32),
  "K" VARCHAR2(32),
  "OPC" VARCHAR2(32),
  "VICE_EKI" VARCHAR2(32),
  "VICE_K" VARCHAR2(32),
  "VICE_OPC" VARCHAR2(32),
  "SN_TIME" DATE NOT NULL,
  "SEID" VARCHAR2(20),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
) ;

CREATE TABLE "PDMS"."DM_IMSI" (
  "IMSI_SEG" VARCHAR2(11) NOT NULL,
  "IMSI_COUNT" NUMBER(5) NOT NULL,
  "DATA_SEG" VARCHAR2(7) NOT NULL,
  "IMSI_TYPE" VARCHAR2(20) NOT NULL,
  "STATUS" NUMBER(1) NOT NULL,
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_IMSI_SEG" PRIMARY KEY ("IMSI_SEG")
);

CREATE TABLE "PDMS"."DM_COMPANY" (
  "COMPANY_NAME" VARCHAR2(60),
  "CONTACT_PERSON" VARCHAR2(20),
  "CONTACT_TEL" VARCHAR2(20),
  "FAX_NUM" VARCHAR2(20),
  "E_MAIL" VARCHAR2(30),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
);

CREATE TABLE "PDMS"."DM_SYS_CONFIG" (
  "ID" NUMBER(9) NOT NULL,
  "CONFIG_KEY" VARCHAR2(64) NOT NULL,
  "CONFIG_VALUE" VARCHAR2(255) DEFAULT '',
  "IS_ENABLE" NUMBER(1) NOT NULL,
  "REMARK" VARCHAR2(255),
  "CREATE_USER_NAME" VARCHAR2(50) NOT NULL,
  "CREATE_TIME" DATE NOT NULL,
  "LAST_UPDATE_USER_NAME" VARCHAR2(50),
  "LAST_UPDATE_TIME" DATE,
  "SORT_NO" NUMBER(1) DEFAULT 0,
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_SYS_CONFIG_ID" PRIMARY KEY ("ID")
);
CREATE TABLE "PDMS"."DM_RESOURCE_WARNING" (
  "DATA_NUM" VARCHAR2(15) NOT NULL,
  "REGION_CODE" VARCHAR2(10) NOT NULL,
  "HLR_CODE" VARCHAR2(10),
  "ATTR_ID" NUMBER(3),
  "NET_SEG" VARCHAR2(10) NOT NULL,
  "DATA_COUNT" NUMBER(11) NOT NULL,
  "DATA_TIME" DATE DEFAULT sysdate,
  "MAKE_DATA_COUNT" NUMBER(11) DEFAULT 0,
  "MAKE_DATA_TYPE" NUMBER(2) DEFAULT 1,
  "STATUS" NUMBER(2) DEFAULT 0,
  "NOTES" VARCHAR2(1048) DEFAULT '',
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
);
CREATE TABLE "PDMS"."DM_RESOURCE_DATA_DETAIL" (
  "ORDER_CODE" VARCHAR2(12),
  "BATCH_NUM" VARCHAR2(12) NOT NULL,
  "IMSI" VARCHAR2(15) NOT NULL,
  "ICCID" VARCHAR2(20) NOT NULL,
  "KI" VARCHAR2(32),
  "OPC" VARCHAR2(32),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
);
CREATE TABLE "PDMS"."DM_RESOURCE_DATA_BACKUP" (
  "ORDER_CODE" VARCHAR2(12),
  "BATCH_NUM" VARCHAR2(12) NOT NULL,
  "IMSI" VARCHAR2(15) NOT NULL,
  "ICCID" VARCHAR2(20) NOT NULL,
  "KI" VARCHAR2(32),
  "OPC" VARCHAR2(32),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
);

CREATE TABLE "PDMS"."DM_XH_BATCH" (
  "BATCH_NUM" VARCHAR2(14) NOT NULL,
  "BATCH_REGION" VARCHAR2(16) NOT NULL,
  "SMSP" VARCHAR2(14) NOT NULL,
  "HLR_NAME" VARCHAR2(24),
  "BRAND_NAME" VARCHAR2(30),
  "FACTORY_NAME" VARCHAR2(20) NOT NULL,
  "CARD_TYPE" VARCHAR2(40) NOT NULL,
  "MSISDN_START" VARCHAR2(11) NOT NULL,
  "MSISDN_END" VARCHAR2(11) NOT NULL,
  "DATA_TYPE" VARCHAR2(12),
  "BATCH_COUNT" NUMBER(11) NOT NULL,
  "IMSI_START" VARCHAR2(15) NOT NULL,
  "IMSI_END" VARCHAR2(15) NOT NULL,
  "ICCID_START" VARCHAR2(20) NOT NULL,
  "ICCID_END" VARCHAR2(20) NOT NULL,
  "BATCH_TIME" DATE DEFAULT sysdate NOT NULL,
  "BATCH_STATUS" NUMBER(1) NOT NULL,
  "PRODUCE_STATUS" NUMBER(1) NOT NULL,
  "ORDER_CODE" VARCHAR2(9) NOT NULL,
  "NOTES" VARCHAR2(100),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_XH_BATCH_NUM" PRIMARY KEY ("BATCH_NUM")
);
CREATE TABLE "PDMS"."DM_XH_NET_SEG" (
  "ATTR_ID" NUMBER(3),
  "NET_SEG" VARCHAR2(24) NOT NULL,
  "SEG_COUNT" NUMBER(7),
  "SEG_STATE" NUMBER(1),
  "OPERATORS" NUMBER(1) NOT NULL,
  "NOTES" VARCHAR2(100),
  "XH_RULE_FLAG" NUMBER(1) NOT NULL,
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "DM_XH_NET_SEG_PK" PRIMARY KEY ("NET_SEG")
);
CREATE TABLE "PDMS"."DM_XH_IMSI" (
  "XH_IMSI_SEG" VARCHAR2(11) NOT NULL,
  "XH_IMSI_COUNT" NUMBER(6) NOT NULL,
  "XH_NET_SEG" VARCHAR2(7) NOT NULL,
  "XH_IMSI_TYPE" VARCHAR2(20) NOT NULL,
  "XH_STATUS" NUMBER(1) NOT NULL,
  "XH_REGION_CODE" VARCHAR2(5),
  "XH_REGION_NAME" VARCHAR2(20),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "PK_XH_IMSI_SEG" PRIMARY KEY ("XH_IMSI_SEG")
);

CREATE TABLE "PDMS"."DM_IMSI_CYC_TEMP" (
  "SEQ_NUM" VARCHAR2(15) NOT NULL,
  "REGION_CODE" VARCHAR2(5) NOT NULL,
  "HLR_CODE" VARCHAR2(32) NOT NULL,
  "ATTR_ID" NUMBER(3),
  "DATA_SEG" VARCHAR2(7) NOT NULL,
  "IMSI" VARCHAR2(15) NOT NULL,
  "STATUS" NUMBER(1) NOT NULL,
  "BATCH_NUM" VARCHAR2(12),
  "GENERATE_TIME" DATE,
  "NOTES" VARCHAR2(100),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
);
CREATE TABLE "PDMS"."DM_IMSI_CYC_BATCH" (
  "SEQ_NUM" VARCHAR2(15) NOT NULL,
  "REGION_CODE" VARCHAR2(5) NOT NULL,
  "HLR_CODE" VARCHAR2(32) NOT NULL,
  "ATTR_ID" NUMBER(3),
  "DATA_SEG" VARCHAR2(7) NOT NULL,
  "IMSI_COUNT" VARCHAR2(15) NOT NULL,
  "IMPORT_TIME" DATE DEFAULT sysdate,
  "NOTES" VARCHAR2(100),
  "CYC_BATCH_STAUTS" VARCHAR2(15),
  "CYC_ERRCOUNT" NUMBER(10) DEFAULT 0,
  "CYC_SUCCCOUNT" NUMBER(10) DEFAULT 0,
  "IMPORT_TYPE" NUMBER(1) DEFAULT 0 NOT NULL,
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
);
CREATE TABLE "PDMS"."DM_IMSI_CYC_XH_TEMP" (
  "SEQ_NUM" VARCHAR2(15) NOT NULL,
  "REGION_CODE" VARCHAR2(5) NOT NULL,
  "HLR_CODE" VARCHAR2(32),
  "ATTR_ID" NUMBER(3),
  "DATA_SEG" VARCHAR2(7) NOT NULL,
  "IMSI" VARCHAR2(15) NOT NULL,
  "STATUS" NUMBER(1) NOT NULL,
  "BATCH_NUM" VARCHAR2(20),
  "GENERATE_TIME" DATE,
  "NOTES" VARCHAR2(100),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
);
CREATE TABLE "PDMS"."DM_IMSI_CYC_XH_BATCH" (
  "SEQ_NUM" VARCHAR2(15) NOT NULL,
  "REGION_CODE" VARCHAR2(5) NOT NULL,
  "HLR_CODE" VARCHAR2(32),
  "ATTR_ID" NUMBER(3),
  "DATA_SEG" VARCHAR2(7) NOT NULL,
  "IMSI_COUNT" VARCHAR2(15) NOT NULL,
  "IMPORT_TIME" DATE DEFAULT sysdate,
  "NOTES" VARCHAR2(100),
  "CYC_BATCH_STAUTS" VARCHAR2(15),
  "CYC_ERRCOUNT" NUMBER(10) DEFAULT 0,
  "CYC_SUCCCOUNT" NUMBER(10) DEFAULT 0,
  "IMPORT_TYPE" NUMBER(1) DEFAULT 0 NOT NULL,
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
);
CREATE TABLE "PDMS"."DM_SYNC_IMSI_CYC" (
  "REGION_CODE" VARCHAR2(4) NOT NULL,
  "NET_SEG" VARCHAR2(10) NOT NULL,
  "DATA_SEG" VARCHAR2(7) NOT NULL,
  "IMSI" VARCHAR2(15) NOT NULL,
  "STATUS" NUMBER(1) NOT NULL,
  "CYC_TIME" DATE DEFAULT sysdate,
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
);
CREATE TABLE "PDMS"."DM_SYNC_IMSI_CYC_ERR_REOCRD" (
  "SEQ_NUM" VARCHAR2(15) NOT NULL,
  "REGION_CODE" VARCHAR2(4) NOT NULL,
  "NET_SEG" VARCHAR2(10) NOT NULL,
  "DATA_SEG" VARCHAR2(7) NOT NULL,
  "IMSI" VARCHAR2(15) NOT NULL,
  "STATUS" NUMBER(1) NOT NULL,
  "CYC_TIME" DATE DEFAULT sysdate,
  "ERR_MESSAGE" VARCHAR2(256) DEFAULT '',
  "OPRATE_TIME" DATE,
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
);
CREATE TABLE "PDMS"."DM_SYNC_IMSI_CYC_ERROR" (
  "REGION_CODE" VARCHAR2(4) NOT NULL,
  "NET_SEG" VARCHAR2(10) NOT NULL,
  "DATA_SEG" VARCHAR2(7) NOT NULL,
  "IMSI" VARCHAR2(15) NOT NULL,
  "STATUS" NUMBER(1) NOT NULL,
  "CYC_TIME" DATE DEFAULT sysdate,
  "ERR_MESSAGE" VARCHAR2(256) DEFAULT '',
  "OPRATE_TIME" DATE,
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
);
CREATE TABLE "PDMS"."DM_IMSI_CYC_RPM_TEMP" (
  "ORDER_CODE" VARCHAR2(9),
  "BATCH_NUM" VARCHAR2(20) NOT NULL,
  "IMSI" VARCHAR2(15) NOT NULL,
  "ICCID" VARCHAR2(20) NOT NULL,
  "PIN1" VARCHAR2(4) NOT NULL,
  "PIN2" VARCHAR2(4) NOT NULL,
  "PUK1" VARCHAR2(8) NOT NULL,
  "PUK2" VARCHAR2(8) NOT NULL,
  "SMSP" VARCHAR2(14) NOT NULL,
  "K" VARCHAR2(32),
  "OPC" VARCHAR2(32),
  "KIND_ID" NUMBER(3),
  "RESERVE1" NUMBER(11),
  "RESERVE2" VARCHAR2(128),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
);
CREATE TABLE "PDMS"."DM_IMSI_CYC_BACKUP" (
  "SEQ_NUM" VARCHAR2(15) NOT NULL,
  "REGION_CODE" VARCHAR2(5) NOT NULL,
  "HLR_CODE" VARCHAR2(32) NOT NULL,
  "ATTR_ID" NUMBER(3),
  "DATA_SEG" VARCHAR2(7) NOT NULL,
  "IMSI" VARCHAR2(15) NOT NULL,
  "STATUS" NUMBER(1) NOT NULL,
  "BATCH_NUM" VARCHAR2(20),
  "GENERATE_TIME" DATE,
  "NOTES" VARCHAR2(100),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
) ;
CREATE TABLE "PDMS"."DM_IMSI_DEL" (
  "IMSI_COUNT" NUMBER(11) NOT NULL,
  "DELETE_TIME" DATE DEFAULT sysdate NOT NULL,
  "NOTES" VARCHAR2(100),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE
);

CREATE TABLE "PDMS"."DM_IMSI_CYC_XH" (
  "SEQ_NUM" VARCHAR2(15) NOT NULL,
  "REGION_CODE" VARCHAR2(5) NOT NULL,
  "HLR_CODE" VARCHAR2(32),
  "ATTR_ID" NUMBER(3),
  "DATA_SEG" VARCHAR2(7) NOT NULL,
  "IMSI" VARCHAR2(15) NOT NULL,
  "STATUS" NUMBER(1) NOT NULL,
  "BATCH_NUM" VARCHAR2(20),
  "GENERATE_TIME" DATE DEFAULT sysdate,
  "NOTES" VARCHAR2(100),
  "OMS_OBJECT_NUMBER" NUMBER INVISIBLE,
  "OMS_RELATIVE_FNO" NUMBER INVISIBLE,
  "OMS_BLOCK_NUMBER" NUMBER INVISIBLE,
  "OMS_ROW_NUMBER" NUMBER INVISIBLE,
  CONSTRAINT "DM_IMSI_CYC_XH_PK" PRIMARY KEY ("IMSI")
);
CREATE SEQUENCE  "PDMS"."SEQ_DM_USER"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 20000 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "PDMS"."SEQ_DM_LOG"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 20000 NOORDER  NOCYCLE ;
CREATE SEQUENCE "PDMS"."SEQ_DM_FACTORY" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 20000 NOORDER  NOCYCLE ;
CREATE SEQUENCE "PDMS"."SEQ_DM_REGION" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 20000 NOORDER  NOCYCLE ;
CREATE SEQUENCE "PDMS"."SEQ_DM_CARD_TYPE" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 20000 NOORDER  NOCYCLE ;
CREATE SEQUENCE "PDMS"."SEQ_DM_ATTR" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 20000 NOORDER  NOCYCLE ;
