#!/usr/bin/python
# -*- coding: utf8 -*-
#### readme: step 1: ./expire.py pre_check    do the check before operation
                        #   (a) Check whether all tables partitioned by range have corresponding records in part_expire_meta_table to avoid some unknown tables being missed for expiration. If any are missed, record them in missed_table_pre.
                        #   (b) First check if the partition name and partition range date are consistent, which helps to confirm the partition range during manual intervention. If there is inconsistency, print a prompt, and dump to the file part_diff_with_name.txt
                        #   (c) The upper boundary of the maximum partition cannot be MAXVALUE, otherwise it will affect the addition of new partitions. If so, dump the statements to delete these partitions to drop_max_part_xxx_pre, where xxx is the tenant name"""
                        #   (d) Dump the required ddl operations to the corresponding file drop_and_add_part_xxx_pre, xxx is the tenant name, pre indicates generated by pre_check
##           step 2: ./expire.py drop_max   delete maxvalue partition, each tenant loads its corresponding drop_max_part_xxx_pre, execute the DDL statements within, check if it is in merge state before execution, only perform this operation when the cluster is in idle state
##           step 3: ./expire.py drop_and_add   delete expired partitions, and create partitions for the last two months, each tenant loads their corresponding drop_and_add_part_xxx_pre, execute the ddl statements within, check if it is in merge state before execution, only perform this operation when the cluster is in idle state
##           step 4: ./expire.py post_check    Final check of the previous operations, mainly checking if there are any missed tables that were not checked, if maxvalue partitions have been deleted cleanly, if expired partitions have already been deleted, and if new partitions have been created successfully
###  Any step that goes wrong will print an error level log, otherwise the operation will proceed smoothly
##### structure of part_expire_meta_table:
"""
CREATE TABLE `part_expire_meta_table` (
          `gmt_create` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
          `gmt_modifid` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
          `tenant_name` varchar(128) NOT NULL,
          `db_name` varchar(128) NOT NULL,
          `table_name` varchar(128) NOT NULL,
          `expire_time_of_days` bigint(20) DEFAULT NULL,
          `range_interval` bigint(20) DEFAULT NULL,
          PRIMARY KEY (`tenant_name`, `db_name`, `table_name`));
"""
####
import MySQLdb
import traceback
from datetime import *
import time
import sys,getopt,os
import logging
from sys import argv

log_filename="expire.log"
#Number of partitions reserved from today
RESERVE_DAYS=50
OB_SUCCESS = 0
OB_FAILED = 1
dir_name = date.today().strftime("%Y-%m-%d");
proxy_ip = ""
proxy_port = 2883
cluster_name = ""
sys_user = ""
sys_pwd=""

pre_check_postfix = "_pre"
post_check_postfix = "_post"
drop_max_str = "drop_max_part_"
drop_and_add_part_str = "drop_and_add_part_"

tenant_info = (("", ""))


def config_logging_module(filename):
  logging.basicConfig(level=logging.DEBUG,\
      format='[%(asctime)s] %(levelname)s %(filename)s:%(lineno)d %(message)s',\
      datefmt='%Y-%m-%d %H:%M:%S',\
      filename=filename,\
      filemode='a')
  # Define log print format
  formatter = logging.Formatter('[%(asctime)s] %(levelname)s %(filename)s:%(lineno)d %(message)s', '%Y-%m-%d %H:%M:%S')
  #######################################
  # Define a Handler to print INFO and above level logs to sys.stdout
  stdout_handler = logging.StreamHandler(sys.stdout)
  stdout_handler.setLevel(logging.INFO)
  # Set log print format
  stdout_handler.setFormatter(formatter)
  # Add the defined stdout_handler log handler to the root logger
  logging.getLogger('').addHandler(stdout_handler)


def load_file_and_execute_part_ddl(fwriter, tenant_name, pwd, ddl_type_str):
    ret = OB_SUCCESS
    conn=None
    cursor=None
    try:
        filename = os.path.join(dir_name, ddl_type_str + tenant_name + pre_check_postfix);
        if os.path.exists(filename):
            conn=MySQLdb.connect(host=proxy_ip, port=proxy_port, user="root@" + tenant_name + "#"+ cluster_name, passwd=pwd, db="oceanbase")
            cursor = conn.cursor()
            with open(filename, 'rt') as f_reader:
                for line in f_reader.readlines():
                    cursor.execute(line.strip())
                    cursor.fetchall()
                    time.sleep(1)
                    fwriter.write(line.strip()+ "\n")
                    logging.info(line.strip())
        else :
            print "nothing need to do for tenant:%s for ddl:%s" %(tenant_name, ddl_type_str)
    except MySQLdb.Error, e:
        print "MySQL Error:%s" % str(e)
        traceback.print_exc()
        raise e
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()
    return ret

def check_is_in_merging():
    ret = True
    conn=None
    cursor=None
    try:
        conn=MySQLdb.connect(host=proxy_ip, port=proxy_port, user=sys_user,passwd=sys_pwd, db="oceanbase")
        cursor = conn.cursor()
        cursor.execute("""set @@ob_read_consistency='weak'""")
        merge_sql = """select 1 from __all_zone where zone="" and name ="merge_status" and info !="IDLE" """
        cursor.execute(merge_sql)
        result = cursor.fetchall()
        if len(result) != 0:
            ret = True
        else :
            ret = False
        logging.debug("is_merge:%d result:%s" %(ret, str(result)))

    except MySQLdb.Error, e:
        print "MySQL Error:%s" % str(e)
        traceback.print_exc()
        raise e
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()
    return ret;


def do_part_ddl(ddl_str):
    ret = OB_SUCCESS
    try:
        filename = os.path.join (dir_name, "ddl_records.txt");
        with open(filename, 'a') as f_writer:
            for tenant in tenant_info:
                ret = load_file_and_execute_part_ddl(f_writer, tenant[0], tenant[1], ddl_str)
                if OB_SUCCESS != ret:
                    logging.ERROR("FAILED to do expire for %s " %(tenant[0]))
                    break
    except MySQLdb.Error, e:
        print "MySQL Error:%s" % str(e)
        traceback.print_exc()
        raise e
    return ret

def do_drop_and_add_part():
    logging.debug("########### BEGIN do_drop_and_add_part")
    if check_is_in_merging() == True:
        logging.error("can not do ddl during merging")
    else :
        ret = do_part_ddl(drop_and_add_part_str)
    logging.info("FINISH do_drop_and_add_part")


def do_drop_max_part():
    logging.debug("########### BEGIN do_drop_max_part")
    if check_is_in_merging():
        logging.error("can not do ddl during merging")
    else :
        ret = do_part_ddl(drop_max_str)
    logging.info("FINISH do_drop_max_part")

##function for do_operate_pre
def gen_del_max_parts_for_tenant(tenant_id, tenant_name, cursor, check_type_str):
    ret = OB_SUCCESS
    try:
        logging.info("gen del max part for %s" %(tenant_name))
        max_part_sql = """ select /*+read_consistency(weak)*/  B.table_name, A.part_name , A.high_bound_val , C.database_name, B.table_id from __all_part A join __all_table  B  join __all_database C where
                (A.table_id, A.part_id) in (Select  table_id,  max(part_id) from  __all_part where tenant_id=%d and table_id in (select table_id from __All_table where  tenant_id = %d and
                 part_level >=1 and part_func_type in (3,4)) group by  table_id)  and A.high_bound_val  = 'MAXVALUE'  and A.table_id = B.table_id and A.tenant_id = %d
                  and B.tenant_id = %d and B.database_id = C.database_id and C.tenant_id=%d  order by b.table_id; """ %(tenant_id, tenant_id, tenant_id, tenant_id, tenant_id)
        logging.debug(max_part_sql)
        cursor.execute(max_part_sql);
        max_part_result = cursor.fetchall()
        if len(max_part_result) > 0:
            filename = os.path.join (dir_name, drop_max_str + tenant_name + check_type_str);
            with open(filename, 'w') as f_writer:
                for i in range(0, len(max_part_result)):
                    db_name = max_part_result[i][3]
                    table_name = max_part_result[i][0]
                    part_name = max_part_result[i][1]

                    f_writer.write("alter table %s.%s drop partition (%s)\n"  %(db_name, table_name, part_name))
                    logging.debug("alter table %s.%s drop partition (%s); high_bound_val:%s \n"  %(db_name, table_name, part_name, max_part_result[i][2]))
                if check_type_str == post_check_postfix:
                    if 0 == len(max_part_result):
                        logging.info("")
                        logging.info("FAIL to do post check of max part, there is max part for tenant:%s" %(tenant_name))
                    else :
                        logging.info("SUCC to do post check of max part, there is no max part for tenant:%s" %(tenant_name))
        else :
            logging.info("DIDIDIDI: there is no max part for tenant:%s" %(tenant_name))

    except MySQLdb.Error, e:
        print "MySQL Error:%s" % str(e)
        traceback.print_exc()
        raise e
    return ret


def gen_del_max_parts_ddl(check_type_str, cursor):
    logging.debug("########### BEGIN gen_del_max_part_ddl : %s ##############" %(check_type_str))
    ret = OB_SUCCESS
    try:
        tenant_sql = """ select tenant_id, tenant_name from __all_tenant where tenant_id > 1000"""
        cursor.execute(tenant_sql)
        tenant_results = cursor.fetchall()
        if (len(tenant_results)) <= 0 :
           ret = OB_FAILED
           logging.error("gen_del_max_parts failed, there is no tenant except sys tenant")
        else :
           for i in range(0, len(tenant_results)):
                ret = gen_del_max_parts_for_tenant(tenant_results[i][0], tenant_results[i][1], cursor, check_type_str)
                if ret == OB_FAILED :
                    break;
    except MySQLdb.Error, e:
        print "MySQL Error:%s" % str(e)
        traceback.print_exc()
        raise e
    logging.info("FINISH gen_del_max_part_ddl : %s" %(check_type_str))
    return ret

def check_if_covered_all_table(check_type_str, cursor):
    ret = OB_SUCCESS
    logging.debug("########### BEGIN check_if_covered_all_table : %s ##############" %(check_type_str))
    file_name_pre = "missed_tables" +check_type_str
    try:
        missed_tables_sql = """select c.tenant_name,  B.database_name ,  A.table_name, A.tenant_id as tenant_id, A.table_id as table_id  from  __all_table A join __all_database B   join __all_tenant c
         where  A.tenant_id = B.tenant_id and A.tenant_id = c.tenant_id and A.database_id =  B.database_id and A.tenant_id >1000 and
         A.part_level >=1  and A.part_func_type in (3,4) and A.table_name not in (select table_name from part_expire_meta_table) order by tenant_id, table_id """
        cursor.execute(missed_tables_sql)
        results = cursor.fetchall()
        if len(results) > 0:
            ret = OB_FAILED
            logging.error("Table missed to expire, check file %s for detail,but you can go on to do expire" %(file_name_pre))
            full_filename = os.path.join(dir_name, file_name_pre);
            with open(full_filename, 'w') as f_writer:
                f_writer.write("%-20s %-20s %-20s \n" %("tenant_name",  "database_name", "table_name"))
                for i in range(0, len(results)):
                    f_writer.write("%-20s %-20s %-20s \n" %(results[i][0], results[i][1], results[i][2]))
        else:
            logging.info("DIDIDI :all table are covered")

    except MySQLdb.Error, e:
        print "MySQL Error:%s" % str(e)
        traceback.print_exc()
        raise e
    logging.info("FINISH check_if_covered_all_table : %s " %(check_type_str))


def check_if_range_interval_match(cursor):
    ret = OB_SUCCESS
    is_not_match = False    
    try:
        logging.debug("########### BEGIN check_if_range_interval_match ##############")
        table_sql= """select A.tenant_name, A.db_name, A.table_name, B.tenant_id, C.database_id, D.table_id, A.range_interval from part_expire_meta_table as A join __all_tenant as B join __all_database as C
         join __all_table as D where A.tenant_name = B.tenant_name and A.db_name = C.database_name and A.table_name = D.table_name and B.tenant_id = C.tenant_id and B.tenant_id = D.tenant_id and
         C.database_id = D.database_id"""
        logging.debug(table_sql)
        cursor.execute(table_sql)
        results = cursor.fetchall()
        if len(results) > 0:
            filename = os.path.join(dir_name, "range_interval_not_match");
            with open(filename, 'w') as f_writer:
                f_writer.write("%-10s %-20s %-20s %-30s %-20s %-20s %-10s\n" %("tenant_id", "tenant_name", "table_id", "table_name", "pre_part_name", "part_name", "range_interval_meta" ))
                for i in range(0, len(results)):
                    tenant_name = results[i][0]
                    table_name = results[i][2]
                    tenant_id = results[i][3]
                    table_id = results[i][5]
                    range_interval = results[i][6]
                    check_sql = """select part_name, cast(substr(high_bound_val, 2,length(high_bound_val)-2) as date) from __all_part where tenant_id = %d and table_id =%d""" %(tenant_id, table_id)
                    cursor.execute(check_sql)
                    check_results = cursor.fetchall()
                    if len(results) > 0:
                        for j in range(1, len(check_results)):
                           pre_lower_bound_date = datetime.strptime(str(check_results[j-1][1]), "%Y-%m-%d").date()
                           high_bound_date = datetime.strptime(str(check_results[j][1]), "%Y-%m-%d").date()
                           next_range_date =  pre_lower_bound_date + timedelta(days=range_interval)
                           pre_part_name = check_results[j-1][0]
                           part_name = check_results[j][0]
                           if high_bound_date != next_range_date:
                               is_not_match = True    
                               f_writer.write("%-10d %-20s %-20d %-30s %-20s %-20s %-10d\n" %(tenant_id, tenant_name, table_id, table_name, pre_part_name, part_name, range_interval ))
                    else :
                        ret = OB_FAILED
                        logging.error("DIDIDI: no part exists tenant_name:%s, table_name%s" %(tenant_name, table_name))
        else :
            ret = OB_FAILED
            logging.error("DIDIDI: no table exists")
    except MySQLdb.Error, e:
        print "MySQL Error:%s" % str(e)
        traceback.print_exc()
        raise e
    if is_not_match:
       logging.error("FINISH check_if_range_interval_match, FAILED check file range_interval_not_match for detail")
    else :
       logging.info("FINISH check_if_range_interval_match, SUCCESS no invalid range interval")
    return ret



def check_if_part_name_match(cursor):
    ret = OB_SUCCESS
    try:
        logging.debug("########### BEGIN check_if_part_name_match ##############")
        diff_sql= """select A.tenant_id, C.tenant_name, A.table_id, B.table_name, A.part_id, A.part_name, A.high_bound_val  from  __all_part A join __all_table B
                  on (A.table_id=B.table_id)  join __all_tenant  C on  (A.tenant_id = c.tenant_id)
                  where concat("p", date_format(substr(A.high_bound_val, 2, length(A.high_bound_val)-2), "%Y%m%d")) != A.part_name
                  and A.table_id in (select table_id from __all_table where tenant_id >1000 and  part_level >=1  and  part_func_type in (3,4)) and A.high_bound_val != "MAXVALUE";"""
        logging.debug(diff_sql)
        cursor.execute(diff_sql)
        results = cursor.fetchall()
        if len(results) > 0:
            filename = os.path.join(dir_name, "part_diff_with_name");
            with open(filename, 'w') as f_writer:
                f_writer.write("%-10s %-20s %-20s %-30s %-10s %-20s %-20s\n" %("tenant_id", "tenant_name", "table_id", "table_name", "part_id", "part_name", "high_bound_val"))
                for i in range(0, len(results)):
                    f_writer.write("%-10d %-20s %-20d %-30s %-10d %-20s %-20s\n" %(results[i][0], results[i][1], results[i][2], results[i][3], results[i][4], results[i][5], results[i][6]))
                if (len(results) > 0):
                    ret = OB_FAILED
                    logging.error("invalid part_name with high_bound_val, check file part_diff_with_name.txt for detail")
        else :
            logging.info("DIDIDI: all part name match")
    except MySQLdb.Error, e:
        print "MySQL Error:%s" % str(e)
        traceback.print_exc()
        raise e
    logging.info("FINISH check_if_part_name_match ")
    return ret


def dump_drop_and_add_ddls_for_tenant(tenant_id, tenant_name, cursor, check_type_str):
    ###Delete expired partition, and create partition within two months
    ###Get expiration information and range interval information of each table from part_expire_meta_table. expire_time_of_days stores how many days until expiration, range_interval stores the time interval
    ret = OB_SUCCESS
    logging.debug(" BEGIN dump_drop_and_add_ddls_for_tenant : %s" %(tenant_name))
    try:
        filename = os.path.join (dir_name, drop_and_add_part_str + tenant_name + check_type_str);
        with open(filename, 'w') as f_writer:
            table_sql = """ Select  A.db_name, A.table_name, C.table_id, A.expire_time_of_days, A.range_interval  from part_expire_meta_table A join __all_database B join __all_table C where
                           B.tenant_id = %d  and C.tenant_id = %d and B.database_name= A.db_name and B.database_id = C.database_id and  C.table_name = A.table_name""" %(tenant_id, tenant_id)
            logging.debug(table_sql)
            cursor.execute(table_sql)
            table_result = cursor.fetchall()
            for i in range(0, len(table_result)):
                db_name = table_result[i][0]

                table_name = table_result[i][1]
                table_id = table_result[i][2]
                expire_time_of_days = table_result[i][3]
                range_interval = table_result[i][4]

                where_condition =  """ %d and tenant_id = %d and table_id = %d  order by part_id """ %(expire_time_of_days, tenant_id, table_id)
                drop_parts_sql = """select  A.part_name, A.high_bound_val from __all_part A
                          where datediff(now(), str_to_date(substr(A.high_bound_val, 2, length(A.high_bound_val)-2), "%Y-%m-%d")) > """ + where_condition
                logging.debug(drop_parts_sql)
                cursor.execute(drop_parts_sql);
                drop_parts_result = cursor.fetchall()
                if check_type_str == post_check_postfix:
                    if len(drop_parts_result) > 0:
                        logging.error("DIDIDIDI: NO, expired part exists, for %s##%s##%s" %(tenant_name, db_name, table_name))
                    else :
                        logging.info("DIDIDIDI:  YES,no expired part, for %s##%s##%s" %(tenant_name, db_name, table_name))
                for j in range(0, len(drop_parts_result)):
                    f_writer.write("alter table %s.%s drop partition (%s)\n"  %(db_name, table_name, drop_parts_result[j][0]))
                    logging.debug("alter table %s.%s drop partition (%s)\n"  %(db_name, table_name, drop_parts_result[j][0]))

                cur_max_part_sql =  """ select cast(substr(high_bound_val, 2,length(high_bound_val)-2) as date) from  __all_part where (tenant_id, table_id, part_id) in
                 (select  tenant_id, table_id, part_id  from __all_part  where tenant_id = %d and table_id =%d  order by part_id desc limit 2 )
                 and high_bound_val  != "MAXVALUE" order by part_id desc limit 1;"""  %(tenant_id, table_id)
                logging.debug(cur_max_part_sql)
                cursor.execute(cur_max_part_sql);
                cur_max_part_result = cursor.fetchall()

                if (len(cur_max_part_result)) != 1:
                    logging.error("FATAL ERROR, there is no high_bound_val for table :%s, db:%s tenant_name:%s, table_id:%d" %(table_name, db_name, tenant_name, table_id))
                    ret = OB_FAILED
                else :
                    date_today = date.today();
                    high_bound_value = str(cur_max_part_result[0][0]);
                    high_bound_date = datetime.strptime(str(cur_max_part_result[0][0]), "%Y-%m-%d").date()

                    next_expire_date = date_today + timedelta(days=RESERVE_DAYS)
                    if check_type_str == post_check_postfix:
                        if high_bound_date < next_expire_date:
                            logging.error("DIDIDIDI: NO, high bound（%s）is not high enough for %s##%s##%s" %(high_bound_value, tenant_name, db_name, table_name))
                        else :
                            logging.info("DIDIDIDI: YES, high bound（%s）is  high enough for %s##%s##%s" %(high_bound_value, tenant_name, db_name, table_name))

                    while (high_bound_date <= next_expire_date):
                         high_bound_date = high_bound_date + timedelta(days=range_interval)
                         part_name = "p" + high_bound_date.strftime("%Y%m%d")
                         f_writer.write("""alter table %s.%s add partition (partition %s  values less than("%s"))\n"""  %(db_name, table_name, part_name, high_bound_date.isoformat()))
                         logging.debug("""alter table %s.%s add partition  (partition %s  values less than("%s"))\n"""  %(db_name, table_name, part_name, high_bound_date.isoformat()))

    except MySQLdb.Error, e:
        print "MySQL Error:%s" % str(e)
        traceback.print_exc()
        raise e
    logging.info(" FINISH dump_drop_and_add_ddls_for_tenant : %s" %(tenant_name))
    return ret

def dump_drop_and_add_ddls(check_type_str, cursor):
    ret = OB_SUCCESS
    logging.debug("########### BEGIN dump_drop_and_add_ddls ##############")
    try:
        tenant_sql = """ select tenant_id, tenant_name from __all_tenant where tenant_id > 1000"""
        cursor.execute(tenant_sql)
        tenant_results = cursor.fetchall()
        if (len(tenant_results)) <= 0 :
           ret = OB_FAILED
           logging.error("failed to dump_drop_and_add_ddls there is no tenant except sys tenant")
        else :
           for i in range(0, len(tenant_results)):
                ret = dump_drop_and_add_ddls_for_tenant(tenant_results[i][0], tenant_results[i][1], cursor, check_type_str)
                if ret == OB_FAILED:
                    break;
    except MySQLdb.Error, e:
        print "MySQL Error:%s" % str(e)
        traceback.print_exc()
        raise e
    logging.info("FINISH dump_drop_and_add_ddls")
    return ret


def do_pre_check():

    #"""
    #   (1) Check whether all tables partitioned by range have corresponding records in part_expire_meta_table to avoid some unknown tables being missed for expiration
    #   (2) First check if the partition name and partition range date are consistent, which helps to confirm the partition range during manual intervention. If there is inconsistency, print a prompt, and dump to the file part_diff_with_name.txt
    #   (3) Check if the interval of the table is consistent with the records in part_expire_meta_table, print a prompt message if not consistent, and dump the information to a file
    #   (4) The upper boundary of the maximum partition cannot be MAXVALUE, otherwise it will affect the addition of new partitions. If so, dump the statements to delete these partitions to xxx_del_max_part.txt, where xxx is the tenant name"""
    #   (5) dump the required ddl operations to the corresponding file
    logging.info("do_post_check")
    if os.path.isdir(dir_name):
        logging.error("%s exists, rm it or rename it before pre_check" %(dir_name))
    else:
        os.mkdir(dir_name)
        ret = OB_SUCCESS
        conn=None
        cursor=None
        try:
            conn=MySQLdb.connect(host=proxy_ip, port=proxy_port, user=sys_user,passwd=sys_pwd, db="oceanbase")
            cursor = conn.cursor()
            cursor.execute("""set @@ob_read_consistency='weak'""")
            ret = check_if_covered_all_table(pre_check_postfix, cursor)

            tmp_ret = check_if_range_interval_match(cursor)
            if OB_FAILED == tmp_ret:
                ret = tmp_ret

            tmp_ret = check_if_part_name_match(cursor)
            if OB_FAILED == tmp_ret:
                ret = tmp_ret

            tmp_ret = gen_del_max_parts_ddl(pre_check_postfix, cursor)
            if OB_FAILED == tmp_ret:
                ret = tmp_ret

            tmp_ret = dump_drop_and_add_ddls(pre_check_postfix, cursor)

            if OB_FAILED == tmp_ret:
                ret = tmp_ret

        except MySQLdb.Error, e:
            print "MySQL Error:%s" % str(e)
            traceback.print_exc()
            raise e
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
        return ret

def double_post_check(cursor):
    ret = OB_SUCCESS
    file_name_pre = "high_bound_not_match_tables"
    try:
        condition_sql = """ <= %d) as A join __all_table as B  join __all_tenant C where A.table_id = B.table_id and b.tenant_id = c.tenant_id """ %(RESERVE_DAYS)
        invalid_tables_sql = """select  c.tenant_name, B.table_name, A.high_bound_val  from (select  table_id, part_id, high_bound_val from __all_part where (table_id, part_id) in (select table_id, max(part_id) from __all_part  where table_id in (select table_id from __all_table where part_func_type in (3,4))   group by table_id)  and datediff(str_to_date(substr(high_bound_val, 2, length(high_bound_val)-2), "%Y-%m-%d"), now()) """ + condition_sql
        cursor.execute(invalid_tables_sql)
        results = cursor.fetchall()
        if len(results) > 0:
            ret = OB_FAILED
            logging.error("Table parts not enough, check file %s for detail,but you can go on to do expire" %(file_name_pre))
            full_filename = os.path.join(dir_name, file_name_pre);
            with open(full_filename, 'w') as f_writer:
                f_writer.write("%-20s %-20s %-20s \n" %("tenant_name",  "database_name", "high_bound_val"))
                for i in range(0, len(results)):
                    f_writer.write("%-20s %-20s %-20s \n" %(results[i][0], results[i][1], results[i][2]))
        else:
            logging.info("DIDIDI :all table are of enough parts")

    except MySQLdb.Error, e:
        print "MySQL Error:%s" % str(e)
        traceback.print_exc()
        raise e
    logging.info("FINISH double_post_check ")


def do_post_check():
    ret = OB_SUCCESS
    logging.info("do_post_check")
    if not os.path.isdir(dir_name):
        logging.error("result dir:%s is not exist, do_check_pre fisrt" %dir_name)
    else:
        conn=None
        cursor=None
        try:
            conn=MySQLdb.connect(host=proxy_ip, port=proxy_port, user=sys_user,passwd=sys_pwd, db="oceanbase")
            cursor = conn.cursor()
            cursor.execute("""set @@ob_read_consistency='weak'""")
            ret = check_if_covered_all_table(post_check_postfix, cursor)

            tmp_ret = gen_del_max_parts_ddl(post_check_postfix, cursor)
            if OB_FAILED == tmp_ret:
                ret = tmp_ret

            tmp_ret = dump_drop_and_add_ddls(post_check_postfix, cursor)
            if OB_FAILED == tmp_ret:
                ret = tmp_ret

            tmp_ret = double_post_check(cursor)
            if OB_FAILED == tmp_ret:
                ret = tmp_ret


        except MySQLdb.Error, e:
            print "MySQL Error:%s" % str(e)
            traceback.print_exc()
            raise e
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    return ret


def usage(cmd):
  usage_str = """Usages: you must follow the following step
  \t%s pre_check  ##check the system and generate ddl sql files
  \t%s  ##drop maxvalue partition before add partitions
  \t%s drop_and_and  ##drop partitions that are expire and add partitions needed
  \t%s post_check  ##check the system after all ddl operations are done""" %(cmd, cmd, cmd, cmd)
  return usage_str

if __name__ == "__main__":
    config_logging_module(log_filename)
    if  len(argv) != 2:
        print usage(argv[0])
    else:
        if "pre_check" == argv[1]:
            do_pre_check()
        elif "drop_max" == argv[1]:
            do_drop_max_part()
        elif "drop_and_add" == argv[1]:
            do_drop_and_add_part()
        elif  "post_check"  == argv[1]:
            do_post_check()
        else:
            print usage(argv[0])


