- name: sysbench_prepare
  scope:
    branch:
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-存储-索引与DDL
  must_success:
    true
- name: pass_prepare
  scope:
    branch: 
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept: 
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-共享存储-事务
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-RS组
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-共享存储-日志
  must_success:
    false
- name: ss_prepare
  scope:
    branch: 
      - master
      - 4_3_5_release
    dept: 
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-共享存储-云存储
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-存储-索引与DDL
  must_success:
    false
- name: transaction_team2_prepare
  scope:
    branch: 
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept: 
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-共享存储-事务
  must_success:
    false
- name: duplicate_table_access
  scope:
    branch: 
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept: 
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-共享存储-事务
  must_success:
    false
- name: PREPARE_STANDBY
  scope:
    branch: 
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept: 
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-RS组
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-日志
  must_success:
    false
- name: direct_load
  scope:
    branch: 
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept: 
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-存储-索引与DDL
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-存储-物化
  must_success:
    false
- name: ddlhome
  scope:
    branch: 
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept: 
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-存储-索引与DDL
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-存储-分析处理
  must_success:
    false
- name: mv_home
  scope:
    branch: 
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept: 
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-数据组
  must_success:
    false
- name: obtest
  scope:
    branch: 
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept: 
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-存储-高可靠
  must_success:
    false
- name: obbstool_farm
  scope:
    branch: 
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept: 
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-存储-高可靠
  must_success:
    false
- name: stress_json
  scope:
    branch: 
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept: 
      - OceanBase-OceanBase-产品技术部-技术部-深圳研发中心
  must_success:
    false
- name: pass_duomo
  scope:
    branch: 
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept: 
      - OceanBase-OceanBase-产品技术部-技术部-深圳研发中心
  must_success:
    false
- name: stress_lob
  scope:
    branch:
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-深圳研发中心
  must_success:
    false
- name: FARM_SQL
  scope:
    branch: 
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept: 
      - OceanBase-OceanBase-产品技术部-技术部-SQL-执行器
      - OceanBase-OceanBase-产品技术部-技术部-SQL-优化器
  must_success:
    false
- name: PASS_PL
  scope:
    branch:
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-SQL-存储过程
  must_success:
    false
- name: VOS_PASS
  scope:
    branch: 
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept: 
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-系统
  must_success:
    false
- name: PASS_DAS
  scope:
    branch: 
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept: 
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-交互诊断
  must_success:
    false
- name: compaction_small_farm
  scope:
    branch:
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-存储-分析处理
  must_success:
    false
- name: storage_engine_jobs
  scope:
    branch:
      - master
      - 4_3_5_release
      - 4_2_x_release
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎-存储-单机引擎
  must_success:
    false
