
eval select @@time_zone, c1 from t$cnt order by id;

if ($cnt < 4)
{

  eval select @@time_zone, $str01 from dual;
  eval select @@time_zone, c1, $str01 from t$cnt where c1 = $str01 order by id;
  eval select @@time_zone, c1, $str01 from t$cnt where c1 > $str01 order by id;
  eval select @@time_zone, c1, $str01 from t$cnt where c1 >= $str01 order by id;
  eval select @@time_zone, c1, $str01 from t$cnt where c1 < $str01 order by id;
  eval select @@time_zone, c1, $str01 from t$cnt where c1 <= $str01 order by id;
  eval select @@time_zone, c1, $str01 from t$cnt where c1 <> $str01 order by id;
  eval select @@time_zone, c1, $str01 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str01 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str01 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str01 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str02 from dual;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 = $str02 order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 > $str02 order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 >= $str02 order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 < $str02 order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 <= $str02 order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 <> $str02 order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str03 from dual;
  eval select @@time_zone, c1, $str03 from t$cnt where c1 = $str03 order by id;
  eval select @@time_zone, c1, $str03 from t$cnt where c1 > $str03 order by id;
  eval select @@time_zone, c1, $str03 from t$cnt where c1 >= $str03 order by id;
  eval select @@time_zone, c1, $str03 from t$cnt where c1 < $str03 order by id;
  eval select @@time_zone, c1, $str03 from t$cnt where c1 <= $str03 order by id;
  eval select @@time_zone, c1, $str03 from t$cnt where c1 <> $str03 order by id;
  eval select @@time_zone, c1, $str03 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str03 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str03 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str03 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str04 from dual;
  eval select @@time_zone, c1, $str04 from t$cnt where c1 = $str04 order by id;
  eval select @@time_zone, c1, $str04 from t$cnt where c1 > $str04 order by id;
  eval select @@time_zone, c1, $str04 from t$cnt where c1 >= $str04 order by id;
  eval select @@time_zone, c1, $str04 from t$cnt where c1 < $str04 order by id;
  eval select @@time_zone, c1, $str04 from t$cnt where c1 <= $str04 order by id;
  eval select @@time_zone, c1, $str04 from t$cnt where c1 <> $str04 order by id;
  eval select @@time_zone, c1, $str04 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str04 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str04 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str04 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str05 from dual;
  eval select @@time_zone, c1, $str05 from t$cnt where c1 = $str05 order by id;
  eval select @@time_zone, c1, $str05 from t$cnt where c1 > $str05 order by id;
  eval select @@time_zone, c1, $str05 from t$cnt where c1 >= $str05 order by id;
  eval select @@time_zone, c1, $str05 from t$cnt where c1 < $str05 order by id;
  eval select @@time_zone, c1, $str05 from t$cnt where c1 <= $str05 order by id;
  eval select @@time_zone, c1, $str05 from t$cnt where c1 <> $str05 order by id;
  eval select @@time_zone, c1, $str05 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str05 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str05 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str05 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str06 from dual;
  eval select @@time_zone, c1, $str06 from t$cnt where c1 = $str06 order by id;
  eval select @@time_zone, c1, $str06 from t$cnt where c1 > $str06 order by id;
  eval select @@time_zone, c1, $str06 from t$cnt where c1 >= $str06 order by id;
  eval select @@time_zone, c1, $str06 from t$cnt where c1 < $str06 order by id;
  eval select @@time_zone, c1, $str06 from t$cnt where c1 <= $str06 order by id;
  eval select @@time_zone, c1, $str06 from t$cnt where c1 <> $str06 order by id;
  eval select @@time_zone, c1, $str06 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str06 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str06 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str06 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str07 from dual;
  eval select @@time_zone, c1, $str07 from t$cnt where c1 = $str07 order by id;
  eval select @@time_zone, c1, $str07 from t$cnt where c1 > $str07 order by id;
  eval select @@time_zone, c1, $str07 from t$cnt where c1 >= $str07 order by id;
  eval select @@time_zone, c1, $str07 from t$cnt where c1 < $str07 order by id;
  eval select @@time_zone, c1, $str07 from t$cnt where c1 <= $str07 order by id;
  eval select @@time_zone, c1, $str07 from t$cnt where c1 <> $str07 order by id;
  eval select @@time_zone, c1, $str07 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str07 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str07 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str07 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str11 from dual;
  eval select @@time_zone, c1, $str11 from t$cnt where c1 = $str11 order by id;
  eval select @@time_zone, c1, $str11 from t$cnt where c1 > $str11 order by id;
  eval select @@time_zone, c1, $str11 from t$cnt where c1 >= $str11 order by id;
  eval select @@time_zone, c1, $str11 from t$cnt where c1 < $str11 order by id;
  eval select @@time_zone, c1, $str11 from t$cnt where c1 <= $str11 order by id;
  eval select @@time_zone, c1, $str11 from t$cnt where c1 <> $str11 order by id;
  eval select @@time_zone, c1, $str11 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str11 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str11 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str11 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str12 from dual;
  eval select @@time_zone, c1, $str12 from t$cnt where c1 = $str12 order by id;
  eval select @@time_zone, c1, $str12 from t$cnt where c1 > $str12 order by id;
  eval select @@time_zone, c1, $str12 from t$cnt where c1 >= $str12 order by id;
  eval select @@time_zone, c1, $str12 from t$cnt where c1 < $str12 order by id;
  eval select @@time_zone, c1, $str12 from t$cnt where c1 <= $str12 order by id;
  eval select @@time_zone, c1, $str12 from t$cnt where c1 <> $str12 order by id;
  eval select @@time_zone, c1, $str12 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str12 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str12 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str12 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str13 from dual;
  eval select @@time_zone, c1, $str13 from t$cnt where c1 = $str13 order by id;
  eval select @@time_zone, c1, $str13 from t$cnt where c1 > $str13 order by id;
  eval select @@time_zone, c1, $str13 from t$cnt where c1 >= $str13 order by id;
  eval select @@time_zone, c1, $str13 from t$cnt where c1 < $str13 order by id;
  eval select @@time_zone, c1, $str13 from t$cnt where c1 <= $str13 order by id;
  eval select @@time_zone, c1, $str13 from t$cnt where c1 <> $str13 order by id;
  eval select @@time_zone, c1, $str13 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str13 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str13 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str13 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str14 from dual;
  eval select @@time_zone, c1, $str14 from t$cnt where c1 = $str14 order by id;
  eval select @@time_zone, c1, $str14 from t$cnt where c1 > $str14 order by id;
  eval select @@time_zone, c1, $str14 from t$cnt where c1 >= $str14 order by id;
  eval select @@time_zone, c1, $str14 from t$cnt where c1 < $str14 order by id;
  eval select @@time_zone, c1, $str14 from t$cnt where c1 <= $str14 order by id;
  eval select @@time_zone, c1, $str14 from t$cnt where c1 <> $str14 order by id;
  eval select @@time_zone, c1, $str14 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str14 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str14 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str14 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str15 from dual;
  eval select @@time_zone, c1, $str15 from t$cnt where c1 = $str15 order by id;
  eval select @@time_zone, c1, $str15 from t$cnt where c1 > $str15 order by id;
  eval select @@time_zone, c1, $str15 from t$cnt where c1 >= $str15 order by id;
  eval select @@time_zone, c1, $str15 from t$cnt where c1 < $str15 order by id;
  eval select @@time_zone, c1, $str15 from t$cnt where c1 <= $str15 order by id;
  eval select @@time_zone, c1, $str15 from t$cnt where c1 <> $str15 order by id;
  eval select @@time_zone, c1, $str15 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str15 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str15 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str15 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str16 from dual;
  eval select @@time_zone, c1, $str16 from t$cnt where c1 = $str16 order by id;
  eval select @@time_zone, c1, $str16 from t$cnt where c1 > $str16 order by id;
  eval select @@time_zone, c1, $str16 from t$cnt where c1 >= $str16 order by id;
  eval select @@time_zone, c1, $str16 from t$cnt where c1 < $str16 order by id;
  eval select @@time_zone, c1, $str16 from t$cnt where c1 <= $str16 order by id;
  eval select @@time_zone, c1, $str16 from t$cnt where c1 <> $str16 order by id;
  eval select @@time_zone, c1, $str16 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str16 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str16 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str16 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str17 from dual;
  eval select @@time_zone, c1, $str17 from t$cnt where c1 = $str17 order by id;
  eval select @@time_zone, c1, $str17 from t$cnt where c1 > $str17 order by id;
  eval select @@time_zone, c1, $str17 from t$cnt where c1 >= $str17 order by id;
  eval select @@time_zone, c1, $str17 from t$cnt where c1 < $str17 order by id;
  eval select @@time_zone, c1, $str17 from t$cnt where c1 <= $str17 order by id;
  eval select @@time_zone, c1, $str17 from t$cnt where c1 <> $str17 order by id;
  eval select @@time_zone, c1, $str17 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str17 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str17 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str17 from t$cnt where c1 is not null order by id;


  eval select @@time_zone, $str21 from dual;
  eval select @@time_zone, c1, $str21 from t$cnt where c1 = $str21 order by id;
  eval select @@time_zone, c1, $str21 from t$cnt where c1 > $str21 order by id;
  eval select @@time_zone, c1, $str21 from t$cnt where c1 >= $str21 order by id;
  eval select @@time_zone, c1, $str21 from t$cnt where c1 < $str21 order by id;
  eval select @@time_zone, c1, $str21 from t$cnt where c1 <= $str21 order by id;
  eval select @@time_zone, c1, $str21 from t$cnt where c1 <> $str21 order by id;
  eval select @@time_zone, c1, $str21 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str21 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str21 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str21 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str22 from dual;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 = $str22 order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 > $str22 order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 >= $str22 order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 < $str22 order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 <= $str22 order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 <> $str22 order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str23 from dual;
  eval select @@time_zone, c1, $str23 from t$cnt where c1 = $str23 order by id;
  eval select @@time_zone, c1, $str23 from t$cnt where c1 > $str23 order by id;
  eval select @@time_zone, c1, $str23 from t$cnt where c1 >= $str23 order by id;
  eval select @@time_zone, c1, $str23 from t$cnt where c1 < $str23 order by id;
  eval select @@time_zone, c1, $str23 from t$cnt where c1 <= $str23 order by id;
  eval select @@time_zone, c1, $str23 from t$cnt where c1 <> $str23 order by id;
  eval select @@time_zone, c1, $str23 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str23 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str23 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str23 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str24 from dual;
  eval select @@time_zone, c1, $str24 from t$cnt where c1 = $str24 order by id;
  eval select @@time_zone, c1, $str24 from t$cnt where c1 > $str24 order by id;
  eval select @@time_zone, c1, $str24 from t$cnt where c1 >= $str24 order by id;
  eval select @@time_zone, c1, $str24 from t$cnt where c1 < $str24 order by id;
  eval select @@time_zone, c1, $str24 from t$cnt where c1 <= $str24 order by id;
  eval select @@time_zone, c1, $str24 from t$cnt where c1 <> $str24 order by id;
  eval select @@time_zone, c1, $str24 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str24 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str24 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str24 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str25 from dual;
  eval select @@time_zone, c1, $str25 from t$cnt where c1 = $str25 order by id;
  eval select @@time_zone, c1, $str25 from t$cnt where c1 > $str25 order by id;
  eval select @@time_zone, c1, $str25 from t$cnt where c1 >= $str25 order by id;
  eval select @@time_zone, c1, $str25 from t$cnt where c1 < $str25 order by id;
  eval select @@time_zone, c1, $str25 from t$cnt where c1 <= $str25 order by id;
  eval select @@time_zone, c1, $str25 from t$cnt where c1 <> $str25 order by id;
  eval select @@time_zone, c1, $str25 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str25 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str25 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str25 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str26 from dual;
  eval select @@time_zone, c1, $str26 from t$cnt where c1 = $str26 order by id;
  eval select @@time_zone, c1, $str26 from t$cnt where c1 > $str26 order by id;
  eval select @@time_zone, c1, $str26 from t$cnt where c1 >= $str26 order by id;
  eval select @@time_zone, c1, $str26 from t$cnt where c1 < $str26 order by id;
  eval select @@time_zone, c1, $str26 from t$cnt where c1 <= $str26 order by id;
  eval select @@time_zone, c1, $str26 from t$cnt where c1 <> $str26 order by id;
  eval select @@time_zone, c1, $str26 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str26 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str26 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str26 from t$cnt where c1 is not null order by id;


  eval select @@time_zone, $str27 from dual;
  eval select @@time_zone, c1, $str27 from t$cnt where c1 = $str27 order by id;
  eval select @@time_zone, c1, $str27 from t$cnt where c1 > $str27 order by id;
  eval select @@time_zone, c1, $str27 from t$cnt where c1 >= $str27 order by id;
  eval select @@time_zone, c1, $str27 from t$cnt where c1 < $str27 order by id;
  eval select @@time_zone, c1, $str27 from t$cnt where c1 <= $str27 order by id;
  eval select @@time_zone, c1, $str27 from t$cnt where c1 <> $str27 order by id;
  eval select @@time_zone, c1, $str27 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str27 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str27 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str27 from t$cnt where c1 is not null order by id;
}


if ($cnt == 4)
{
  eval select @@time_zone, $str02 from dual;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 = $str02 order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 > $str02 order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 >= $str02 order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 < $str02 order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 <= $str02 order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 <> $str02 order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str02 from t$cnt where c1 is not null order by id;

  eval select @@time_zone, $str22 from dual;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 = $str22 order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 > $str22 order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 >= $str22 order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 < $str22 order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 <= $str22 order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 <> $str22 order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 not like '2012-06-02 08:00:01%' order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 is null order by id;
  eval select @@time_zone, c1, $str22 from t$cnt where c1 is not null order by id;
}
