
select @@time_zone, t1.c1, t2.c1 from t1, t2 where t1.c1 = t2.c1 order by t1.id, t2.id;
select @@time_zone, t1.c1, t2.c1 from t1, t2 where t1.c1 > t2.c1 order by t1.id, t2.id;
select @@time_zone, t1.c1, t2.c1 from t1, t2 where t1.c1 >= t2.c1 order by t1.id, t2.id;
select @@time_zone, t1.c1, t2.c1 from t1, t2 where t1.c1 < t2.c1 order by t1.id, t2.id;
select @@time_zone, t1.c1, t2.c1 from t1, t2 where t1.c1 <= t2.c1 order by t1.id, t2.id;
select @@time_zone, t1.c1, t2.c1 from t1, t2 where t1.c1 <> t2.c1 order by t1.id, t2.id;
select @@time_zone, t1.c1, t2.c1 from t1, t2 where t1.c1 like t2.c1 order by t1.id, t2.id;
select @@time_zone, t1.c1, t2.c1 from t1, t2 where t1.c1 not like t2.c1 order by t1.id, t2.id;

select @@time_zone, t1.c1, t3.c1 from t1, t3 where t1.c1 = t3.c1 order by t1.id, t3.id;
select @@time_zone, t1.c1, t3.c1 from t1, t3 where t1.c1 > t3.c1 order by t1.id, t3.id;
select @@time_zone, t1.c1, t3.c1 from t1, t3 where t1.c1 >= t3.c1 order by t1.id, t3.id;
select @@time_zone, t1.c1, t3.c1 from t1, t3 where t1.c1 < t3.c1 order by t1.id, t3.id;
select @@time_zone, t1.c1, t3.c1 from t1, t3 where t1.c1 <= t3.c1 order by t1.id, t3.id;
select @@time_zone, t1.c1, t3.c1 from t1, t3 where t1.c1 <> t3.c1 order by t1.id, t3.id;
select @@time_zone, t1.c1, t3.c1 from t1, t3 where t1.c1 like t3.c1 order by t1.id, t3.id;
select @@time_zone, t1.c1, t3.c1 from t1, t3 where t1.c1 not like t3.c1 order by t1.id, t3.id;

select @@time_zone, t1.c1, t4.c1 from t1, t4 where t1.c1 = t4.c1 order by t1.id, t4.id;
select @@time_zone, t1.c1, t4.c1 from t1, t4 where t1.c1 > t4.c1 order by t1.id, t4.id;
select @@time_zone, t1.c1, t4.c1 from t1, t4 where t1.c1 >= t4.c1 order by t1.id, t4.id;
select @@time_zone, t1.c1, t4.c1 from t1, t4 where t1.c1 < t4.c1 order by t1.id, t4.id;
select @@time_zone, t1.c1, t4.c1 from t1, t4 where t1.c1 <= t4.c1 order by t1.id, t4.id;
select @@time_zone, t1.c1, t4.c1 from t1, t4 where t1.c1 <> t4.c1 order by t1.id, t4.id;
select @@time_zone, t1.c1, t4.c1 from t1, t4 where t1.c1 like t4.c1 order by t1.id, t4.id;
select @@time_zone, t1.c1, t4.c1 from t1, t4 where t1.c1 not like t4.c1 order by t1.id, t4.id;

select @@time_zone, t2.c1, t3.c1 from t2, t3 where t2.c1 = t3.c1 order by t2.id, t3.id;
select @@time_zone, t2.c1, t3.c1 from t2, t3 where t2.c1 > t3.c1 order by t2.id, t3.id;
select @@time_zone, t2.c1, t3.c1 from t2, t3 where t2.c1 >= t3.c1 order by t2.id, t3.id;
select @@time_zone, t2.c1, t3.c1 from t2, t3 where t2.c1 < t3.c1 order by t2.id, t3.id;
select @@time_zone, t2.c1, t3.c1 from t2, t3 where t2.c1 <= t3.c1 order by t2.id, t3.id;
select @@time_zone, t2.c1, t3.c1 from t2, t3 where t2.c1 <> t3.c1 order by t2.id, t3.id;
select @@time_zone, t2.c1, t3.c1 from t2, t3 where t2.c1 like t3.c1 order by t2.id, t3.id;
select @@time_zone, t2.c1, t3.c1 from t2, t3 where t2.c1 not like t3.c1 order by t2.id, t3.id;

select @@time_zone, t2.c1, t4.c1 from t2, t4 where t2.c1 = t4.c1 order by t2.id, t4.id;
select @@time_zone, t2.c1, t4.c1 from t2, t4 where t2.c1 > t4.c1 order by t2.id, t4.id;
select @@time_zone, t2.c1, t4.c1 from t2, t4 where t2.c1 >= t4.c1 order by t2.id, t4.id;
select @@time_zone, t2.c1, t4.c1 from t2, t4 where t2.c1 < t4.c1 order by t2.id, t4.id;
select @@time_zone, t2.c1, t4.c1 from t2, t4 where t2.c1 <= t4.c1 order by t2.id, t4.id;
select @@time_zone, t2.c1, t4.c1 from t2, t4 where t2.c1 <> t4.c1 order by t2.id, t4.id;
select @@time_zone, t2.c1, t4.c1 from t2, t4 where t2.c1 like t4.c1 order by t2.id, t4.id;
select @@time_zone, t2.c1, t4.c1 from t2, t4 where t2.c1 not like t4.c1 order by t2.id, t4.id;

select @@time_zone, t3.c1, t4.c1 from t3, t4 where t3.c1 = t4.c1 order by t3.id, t4.id;
select @@time_zone, t3.c1, t4.c1 from t3, t4 where t3.c1 > t4.c1 order by t3.id, t4.id;
select @@time_zone, t3.c1, t4.c1 from t3, t4 where t3.c1 >= t4.c1 order by t3.id, t4.id;
select @@time_zone, t3.c1, t4.c1 from t3, t4 where t3.c1 < t4.c1 order by t3.id, t4.id;
select @@time_zone, t3.c1, t4.c1 from t3, t4 where t3.c1 <= t4.c1 order by t3.id, t4.id;
select @@time_zone, t3.c1, t4.c1 from t3, t4 where t3.c1 <> t4.c1 order by t3.id, t4.id;
select @@time_zone, t3.c1, t4.c1 from t3, t4 where t3.c1 like t4.c1 order by t3.id, t4.id;
select @@time_zone, t3.c1, t4.c1 from t3, t4 where t3.c1 not like t4.c1 order by t3.id, t4.id;


select @@time_zone, t1.c1, t2.c1 from t1 left join t2 on t1.c1 = t2.c1 order by t1.id, t2.id;
select @@time_zone, t1.c1, t3.c1 from t1 left join t3 on t1.c1 = t3.c1 order by t1.id, t3.id;
select @@time_zone, t1.c1, t4.c1 from t1 left join t4 on t1.c1 = t4.c1 order by t1.id, t4.id;
select @@time_zone, t2.c1, t3.c1 from t2 left join t3 on t2.c1 = t3.c1 order by t2.id, t3.id;
select @@time_zone, t2.c1, t4.c1 from t2 left join t4 on t2.c1 = t4.c1 order by t2.id, t4.id;
select @@time_zone, t3.c1, t4.c1 from t3 left join t4 on t3.c1 = t4.c1 order by t3.id, t4.id;


select @@time_zone, t1.c1, t2.c1 from t1 right join t2 on t1.c1 = t2.c1 order by t1.id, t2.id;
select @@time_zone, t1.c1, t3.c1 from t1 right join t3 on t1.c1 = t3.c1 order by t1.id, t3.id;
select @@time_zone, t1.c1, t4.c1 from t1 right join t4 on t1.c1 = t4.c1 order by t1.id, t4.id;
select @@time_zone, t2.c1, t3.c1 from t2 right join t3 on t2.c1 = t3.c1 order by t2.id, t3.id;
select @@time_zone, t2.c1, t4.c1 from t2 right join t4 on t2.c1 = t4.c1 order by t2.id, t4.id;
select @@time_zone, t3.c1, t4.c1 from t3 right join t4 on t3.c1 = t4.c1 order by t3.id, t4.id;

select /*+ use_merge(t2) */ @@time_zone, t1.c1, t2.c1 from t1 join t2 on t1.c1 = t2.c1 order by t1.id, t2.id;
select /*+ use_merge(t3) */ @@time_zone, t1.c1, t3.c1 from t1 join t3 on t1.c1 = t3.c1 order by t1.id, t3.id;
select /*+ use_merge(t4) */ @@time_zone, t1.c1, t4.c1 from t1 join t4 on t1.c1 = t4.c1 order by t1.id, t4.id;
select /*+ use_merge(t3) */ @@time_zone, t2.c1, t3.c1 from t2 join t3 on t2.c1 = t3.c1 order by t2.id, t3.id;
select /*+ use_merge(t4) */ @@time_zone, t2.c1, t4.c1 from t2 join t4 on t2.c1 = t4.c1 order by t2.id, t4.id;
select /*+ use_merge(t4) */ @@time_zone, t3.c1, t4.c1 from t3 join t4 on t3.c1 = t4.c1 order by t3.id, t4.id;

select /*+ use_nl(t2) */ @@time_zone, t1.c1, t2.c1 from t1 join t2 on t1.c1 = t2.c1 order by t1.id, t2.id;
select /*+ use_nl(t3) */ @@time_zone, t1.c1, t3.c1 from t1 join t3 on t1.c1 = t3.c1 order by t1.id, t3.id;
select /*+ use_nl(t4) */ @@time_zone, t1.c1, t4.c1 from t1 join t4 on t1.c1 = t4.c1 order by t1.id, t4.id;
select /*+ use_nl(t3) */ @@time_zone, t2.c1, t3.c1 from t2 join t3 on t2.c1 = t3.c1 order by t2.id, t3.id;
select /*+ use_nl(t4) */ @@time_zone, t2.c1, t4.c1 from t2 join t4 on t2.c1 = t4.c1 order by t2.id, t4.id;
select /*+ use_nl(t4) */ @@time_zone, t3.c1, t4.c1 from t3 join t4 on t3.c1 = t4.c1 order by t3.id, t4.id;

select /*+ use_hash(t2) */ @@time_zone, t1.c1, t2.c1 from t1 join t2 on t1.c1 = t2.c1 order by t1.id, t2.id;
select /*+ use_hash(t3) */ @@time_zone, t1.c1, t3.c1 from t1 join t3 on t1.c1 = t3.c1 order by t1.id, t3.id;
select /*+ use_hash(t4) */ @@time_zone, t1.c1, t4.c1 from t1 join t4 on t1.c1 = t4.c1 order by t1.id, t4.id;
select /*+ use_hash(t3) */ @@time_zone, t2.c1, t3.c1 from t2 join t3 on t2.c1 = t3.c1 order by t2.id, t3.id;
select /*+ use_hash(t4) */ @@time_zone, t2.c1, t4.c1 from t2 join t4 on t2.c1 = t4.c1 order by t2.id, t4.id;
select /*+ use_hash(t4) */ @@time_zone, t3.c1, t4.c1 from t3 join t4 on t3.c1 = t4.c1 order by t3.id, t4.id;
