CREATE TABLE "PM_MODIFY_LOG" 
("TABLE_NAME" VARCHAR2(32), 
"MODIFY_SCN" NUMBER(14,0), 
"MODIFY_TIME" DATE DEFAULT sysdate
);

CREATE TABLE "PM_NODE_STATUS" 
("NODE_ID" VARCHAR2(30), 
"CPU_USAGE" NUMBER(3,0), 
"MEM_USAGE" NUMBER(3,0), 
"TPMC_USAGE" NUMBER(10,0), 
"STATUS" NUMBER(1,0) DEFAULT 1, 
"STATUS_TIME" DATE DEFAULT sysdate, 
"MEMO" VARCHAR2(128), 
"BILLING_CONTROL_STATUS" VARCHAR2(50) DEFAULT 'auto_control', 
"BILLING_CONTROL_TIME" DATE DEFAULT sysdate
);

CREATE TABLE "PM_NODE" 
("NODE_ID" VARCHAR2(30), 
"NAME" VARCHAR2(60), 
"CLUSTER_ID" VARCHAR2(30), 
"HOST_NAME" VARCHAR2(60), 
"IP_ADDR" VARCHAR2(32), 
"TPMC" NUMBER(10,0), 
"OS_TYPE" VARCHAR2(32), 
"CPU_HW" NUMBER(3,0) DEFAULT 100, 
"MEM_HW" NUMBER(3,0) DEFAULT 100, 
"IS_CRASH" NUMBER(1,0) DEFAULT 0, 
"STATUS" NUMBER(1,0) DEFAULT 1, 
"STATUS_TIME" DATE DEFAULT sysdate, 
"MEMO" VARCHAR2(128), 
"GROUP_ID" VARCHAR2(32), 
"LABEL_LIST" VARCHAR2(1000)
);

CREATE SEQUENCE  "SEQ_LOGOID"  MINVALUE 1 MAXVALUE 100000000000 INCREMENT BY 1 START WITH 313962165 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE "PM_PROC_STATUS" 
("PROC_ID" VARCHAR2(30), 
"PID" NUMBER(10,0) DEFAULT 0, 
"PGID" NUMBER(10,0) DEFAULT 0, 
"PROC_NO" VARCHAR2(30), 
"PROC_NAME" VARCHAR2(128), 
"NODE_ID" VARCHAR2(30), 
"NODE_NAME" VARCHAR2(60), 
"FLOW_ID" VARCHAR2(30), 
"FLOW_NO" VARCHAR2(30), 
"STATUS" NUMBER(1,0), 
"PROGRESS" NUMBER(3,0) DEFAULT 0, 
"RETCODE" NUMBER(3,0) DEFAULT 0, 
"START_OPER" VARCHAR2(30), 
"TERM_OPER" VARCHAR2(30), 
"TERM_REASON" VARCHAR2(30), 
"START_TIME" DATE DEFAULT sysdate, 
"END_TIME" DATE, 
"STATUS_TIME" DATE DEFAULT sysdate, 
"CHILDCNT" NUMBER(6,0), 
"AUTOSTARTED_NUMS" NUMBER(4,0) DEFAULT 0
);

CREATE TABLE "PM_PROCESS" 
("REGION" VARCHAR2(32), 
"MODULES" VARCHAR2(30), 
"PROC_ID" VARCHAR2(30), 
"NAME" VARCHAR2(60), 
"CAT_ID" VARCHAR2(30), 
"PROGRAM" VARCHAR2(256), 
"EXE_NAME" VARCHAR2(60), 
"ARGS" VARCHAR2(1024), 
"WORKING_DIR" VARCHAR2(128), 
"ENV_FILE" VARCHAR2(128), 
"CRON_EXPR" VARCHAR2(128), 
"CRON_POLICY" NUMBER DEFAULT 1, 
"MASTER_NODE" VARCHAR2(30), 
"CLUSTER_ID" VARCHAR2(30), 
"HEARTBEAT" NUMBER(10,0) DEFAULT 0, 
"NOHB_ACTION" NUMBER(1,0) DEFAULT 0, 
"MAX_RUNTIME" NUMBER(10,0) DEFAULT 0, 
"TIMEOUT_ACTION" NUMBER(1,0) DEFAULT 0, 
"PRI" NUMBER(1,0) DEFAULT 0, 
"FLOATABLE" NUMBER(1,0) DEFAULT 1, 
"STATUS_NOTIFY" NUMBER(1,0) DEFAULT 0, 
"TPMC" NUMBER(10,0) DEFAULT 0, 
"MEMO" VARCHAR2(1024), 
"STATUS" NUMBER(1,0) DEFAULT 1, 
"STATUS_TIME" DATE DEFAULT sysdate, 
"OWNER_GROUP" VARCHAR2(32), 
"OWNER" VARCHAR2(64), 
"TERM_CMD" VARCHAR2(128), 
"ATTR" NUMBER(1,0) DEFAULT 0, 
"AUTOSTART_NUMS" NUMBER(4,0) DEFAULT 0, 
"TERM_CMD_TYPE" NUMBER(3,0)
);

CREATE TABLE "PM_TASKFLOW" 
("REGION" VARCHAR2(32), 
"MODULES" VARCHAR2(30), 
"FLOW_ID" VARCHAR2(30), 
"NAME" VARCHAR2(60), 
"CRON_EXPR" VARCHAR2(128), 
"CRON_POLICY" NUMBER DEFAULT 1, 
"STATUS_NOTIFY" NUMBER(1,0) DEFAULT 0, 
"MEMO" VARCHAR2(128), 
"STATUS" NUMBER(1,0) DEFAULT 1, 
"STATUS_TIME" DATE DEFAULT sysdate
);

CREATE TABLE "PM_TASKFLOW_STATUS" 
("FLOW_ID" VARCHAR2(30), 
"FLOW_NO" VARCHAR2(30) DEFAULT 0, 
"CUR_STEP" NUMBER(4,0) DEFAULT 0, 
"START_OPER" VARCHAR2(30), 
"TERM_OPER" VARCHAR2(30), 
"START_TIME" DATE, 
"END_TIME" DATE, 
"STATUS" NUMBER(1,0) DEFAULT 0, 
"STATUS_TIME" DATE DEFAULT sysdate
);

CREATE TABLE "PM_PROCESS_STDOUT" 
("PROC_ID" VARCHAR2(30), 
"STDOUT_DUP" NUMBER(1,0), 
"STDOUT_POLICY" NUMBER(1,0) DEFAULT 0, 
"STDOUT_NUM" NUMBER(2,0), 
"STDOUT_MAXSIZE" NUMBER(10,0), 
"STDOUT_FILE" VARCHAR2(256)
);

CREATE TABLE "PM_PROGRAM" 
("PROGRAM_ID" VARCHAR2(30), 
"FILE_PATH" VARCHAR2(128), 
"FILE_TYPE" VARCHAR2(30), 
"FILE_MODE" VARCHAR2(4), 
"VERSION" VARCHAR2(16), 
"RELEASE_TIME" DATE DEFAULT sysdate, 
"STATUS" NUMBER(1,0) DEFAULT 1, 
"STATUS_TIME" DATE DEFAULT sysdate, 
"PROGRAM_GROUP" VARCHAR2(4), 
"PROGRAM_NAME" VARCHAR2(256)
);

