# configure.ini for mysqltest java

# data path
data_path = /home/yujing.cyj/ob1/data

# use fake mergeserver
ob_version=0.5
configServer = 10.232.4.35:9002
# abort_on_error = 0
use_ob_connector = 0
#ps = 0
