CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;



CREATE TABLE "NECONFIGCONTENTINFO" 
("TASK_ID" NUMBER(10,0), 
"OPR_TYPE" VARCHAR2(10), 
"YN_COLLECT_END_FILE" VARCHAR2(10), 
"TRANSMIT_PROTOCOL" VARCHAR2(10), 
"TRANSMIT_SUB_PROTOCOL" VARCHAR2(10), 
"TRANSMIT_MODE" VARCHAR2(10), 
"SOURCE_FILE" VARCHAR2(64), 
"DEST_FILE" VARCHAR2(64), 
"SOURCE_FILE_DIR" VARCHAR2(128), 
"DEST_FILE_DIR" VARCHAR2(128), 
"SOURCE_FILE_BEGIN_NO" NUMBER(10,0), 
"SOURCE_FILE_END_NO" NUMBER(10,0), 
"TIME_SPLIT" NUMBER(10,0), 
"COLLECT_COUNT" NUMBER(10,0), 
"SOURCE_FILE_TYPE" VARCHAR2(10), 
"PROCESS_RESULT" VARCHAR2(128), 
"TRANSMIT_AREA" VARCHAR2(32), 
"REMARK" VARCHAR2(128), 
"TEMP_FILE_DIR" VARCHAR2(64), 
"YN_COLLATE_FILE" VARCHAR2(10), 
"NEID" NUMBER(10,0), 
"PRIORITY" NUMBER(3,0) DEFAULT 999, 
"FILETIME_ADJUST_HOUR" NUMBER(4,0), 
"INUSE" NUMBER(1,0), 
"ACTION_CONDITION" VARCHAR2(100), 
"HARDLINKDIRS" VARCHAR2(4000)
);

CREATE TABLE "NEINFO" 
("NEID" NUMBER(10,0), 
"NENAME" VARCHAR2(32), 
"IPADDRESS" VARCHAR2(32), 
"NEUSERNAME" VARCHAR2(32), 
"NEPASSWORD" VARCHAR2(256), 
"OSTYPE" VARCHAR2(32)
);

CREATE TABLE "OPERATIONCTL" 
("OPERATION_NAME" VARCHAR2(64), 
"DEAL_FLAG" NUMBER(2,0), 
"ADDTION_INFO" VARCHAR2(256), 
"NOTES" VARCHAR2(64)
);

CREATE TABLE "PHYSICAL_DS_DEF" 
("DATASTORE_NAME" VARCHAR2(256), 
"NODEID" NUMBER(4,0), 
"DIR_NAME" VARCHAR2(256), 
"TMP_NAME" VARCHAR2(256), 
"CUR_SEQ" VARCHAR2(32), 
"INUSE" NUMBER(1,0), 
"BAK_DIR" VARCHAR2(128), 
"ATTR_CLASS" NUMBER(3,0) DEFAULT 0, 
"SUBQ_COUNT" NUMBER(3,0) DEFAULT 0, 
"BYDATE" NUMBER(1,0) DEFAULT 0, 
"NO_LOG" NUMBER(1,0) DEFAULT 0, 
"FILELIST_READ_MODE" NUMBER(1,0) DEFAULT 0, 
"SERVER_NAME" VARCHAR2(50)
);

CREATE TABLE "PRESENT_DEF" 
("REGION" NUMBER(4,0), 
"RENTORDERTYPE" NUMBER(2,0) DEFAULT -1, 
"RENTORDERID" VARCHAR2(64), 
"ITEMCODE" VARCHAR2(64), 
"ITEMADDCODE" VARCHAR2(64), 
"ENTITYTYPE" NUMBER(4,0), 
"ATTRID" VARCHAR2(512), 
"PRESENTNAME" NVARCHAR2(64), 
"SRCEVENTID" NUMBER(10,0) DEFAULT 0, 
"CONDITION" VARCHAR2(512), 
"CONDITIONNAME" VARCHAR2(512), 
"FREEVOLUME" VARCHAR2(512), 
"FREEVOLUMENAME" VARCHAR2(512), 
"CYCLECOUNT" VARCHAR2(512), 
"CYCLECOUNTNAME" VARCHAR2(512), 
"ADDUPFLAG" NUMBER(1,0) DEFAULT -1, 
"ATTRIDNAME" VARCHAR2(512), 
"USAGE_CONFIG_FLAG" NUMBER(1,0) DEFAULT 0, 
"ITEMCODE_EXP" VARCHAR2(512), 
"ITEMCODE_NAME" VARCHAR2(512)
);

CREATE TABLE "PRINT_CUST_DEF" 
("ID" NUMBER(5,0), 
"DATAQUERYID" NUMBER(20,0), 
"ENTITYID" NUMBER(1,0), 
"ISUSED" NUMBER(1,0) DEFAULT 1, 
"HEAD" VARCHAR2(200), 
"INFO" VARCHAR2(200)
);

CREATE TABLE "PRIV_DESIGNATE" 
("OPERATOR_NAME" VARCHAR2(256), 
"RESOURCE_TYPE" NUMBER(1,0), 
"RESOURCE_ID" NUMBER(4,0), 
"PRIV_SET" NUMBER(4,0)
);

CREATE TABLE "PRIVILEGE_CALL_FEE" 
("HREGION" CHAR(3), 
"ITEMCODE" VARCHAR2(8), 
"ITEMNAME" VARCHAR2(200), 
"OWNER" CHAR(1), 
"FEETYPE" VARCHAR2(4), 
"METHOD" CHAR(1), 
"VALUE" NUMBER(10,2), 
"BILLINGCODE" NUMBER(8,0)
);

CREATE TABLE "PRIVILEGE_USAGE_DEF" 
("HREGION" CHAR(3), 
"BILLINGCODE" VARCHAR2(8), 
"ITEMNAME" VARCHAR2(60), 
"FREEVOLUME" NUMBER(15,2), 
"ATTR_ID" NUMBER(8,0), 
"FREETYPE" NUMBER(4,0), 
"STARTCYCLE" NUMBER(10,0) DEFAULT 0, 
"ENDCYCLE" NUMBER(10,0) DEFAULT 88888888, 
"ENTITY_ID" NUMBER(4,0) DEFAULT 1, 
"SHARE_ENTITY_ID" NUMBER(4,0) DEFAULT 0, 
"SHARE_ATTRID" NUMBER(4,0) DEFAULT 0, 
"LIMIT_ATTRID" NUMBER(4,0) DEFAULT 0, 
"LIMIT_ENTITY" NUMBER(4,0) DEFAULT 0, 
"LIMIT_TYPE" NUMBER(4,0) DEFAULT 0, 
"HALFTYPE" NUMBER(1,0)
);

CREATE TABLE "PRODUCT_TEMPLATE_BUSINESS_DEF" 
("ID" NUMBER(4,0), 
"SEQUENCE" NUMBER(4,0), 
"BUSINESS_COND" VARCHAR2(512), 
"BUSINESS" VARCHAR2(60), 
"BUSINESS_KEY" VARCHAR2(512), 
"NOTE" VARCHAR2(200)
);

CREATE TABLE "PROCDESCRIBE" 
("PROCESSID" NUMBER(5,0), 
"OPERATION" NUMBER(2,0), 
"STATUS" NUMBER(2,0), 
"NOTE" VARCHAR2(100), 
"FILELIST_READ_MODE" NUMBER(1,0) DEFAULT 0, 
"SERVER_NAME" VARCHAR2(50)
);

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');

