CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;



CREATE TABLE "Q2F_TASK_DEF" 
("TASKID" NUMBER(10,0), 
"TASKNAME" VARCHAR2(128), 
"MAXEVENTCOUNT" NUMBER(9,0), 
"SLEEPSECONDS" NUMBER(9,0), 
"BATCHMAXCNT" NUMBER(9,0) DEFAULT 0
);

CREATE TABLE "Q2F_TASK_ITEM" 
("TASKID" NUMBER(10,0), 
"SUBID" NUMBER(10,0), 
"SUBNAME" VARCHAR2(128), 
"TRIMEVENTID" NUMBER(4,0), 
"SOURCETYPE" VARCHAR2(1) DEFAULT 's', 
"QUEUENAME" VARCHAR2(256), 
"FILEFORMAT" NUMBER(3,0), 
"MODULEID" NUMBER(16,0), 
"DELIMITER" VARCHAR2(10), 
"PROCESSMODULEID" NUMBER(10,0) DEFAULT 0, 
"FILEHEAD_EVENTID" NUMBER(5,0), 
"FILEBODY_EVENTID" NUMBER(5,0), 
"FILETAIL_EVENTID" NUMBER(5,0), 
"HEADTAIL_PROCESSSCHEMA" NUMBER(5,0), 
"FILTER_NONAME_ATTR" NUMBER(1,0) DEFAULT 0, 
"IS_ORDER_OUT" NUMBER(1,0) DEFAULT 0
);

CREATE TABLE "QUSAGE_DEF" 
("TRANSACTION_CODE" NUMBER(4,0), 
"CURRENT_QUERY" VARCHAR2(200), 
"HISTORY_QUERY" VARCHAR2(200)
);

CREATE TABLE "QUSAGE_ITEM_DEF" 
("TRANSACTION_CODE" NUMBER(4,0), 
"QUERY_ORDER" NUMBER(2,0), 
"QUERY_NAME" VARCHAR2(50), 
"ENTITY_ID" NUMBER(2,0) DEFAULT 1, 
"CACHE_QUERY_ID" NUMBER(9,0), 
"CORRELATIVE_QUERY_ID" NUMBER(9,0), 
"CACHE_STORE_PROC" VARCHAR2(200)
);

CREATE TABLE "RECUPERATING_STRATEGY_DEF" 
("STRATEGY_ID" VARCHAR2(20), 
"NAME" VARCHAR2(80), 
"UNDUP_MODULE" NUMBER(4,0), 
"CHECK_DUP" NUMBER(1,0), 
"ROLLBACK_FROM" NUMBER(2,0), 
"CLEAR_CYCLE" NUMBER(1,0), 
"FLOW_MODULE" NUMBER(4,0), 
"STAT_MODULE" NUMBER(4,0), 
"CHARGING_MODULE" NUMBER(4,0), 
"FIELD_PREFIX" VARCHAR2(60), 
"FORMAT_PROC" NUMBER(5,0), 
"ROLLBACK_COPY_USAGES" NUMBER(1,0), 
"ROLLBACK_RENTAL_LOG" NUMBER(1,0) DEFAULT 0, 
"KEY_TYPE" NUMBER(1,0) DEFAULT 2, 
"ADDITION_COND" VARCHAR2(500), 
"CONVERT_R_PROC" NUMBER(5,0)
);

CREATE TABLE "REFERRED_OBJECT" 
("OBJECT_ID" NUMBER(4,0), 
"OBJECT_NAME" VARCHAR2(40), 
"ENTITY_ID" NUMBER(9,0), 
"ISONEINST" NUMBER(1,0), 
"ENTITY_TYPE" NUMBER(4,0)
);

CREATE TABLE "REGION_ATTR" 
("REGION_ID" NUMBER(4,0), 
"ATTR_ID" VARCHAR2(30), 
"VALUE_ORDER" NUMBER(4,0) DEFAULT 0, 
"ATTR_VALUE" VARCHAR2(50)
);

CREATE TABLE "REGION_DEF" 
("REGION_ID" NUMBER(4,0), 
"REGION_CODE" VARCHAR2(30), 
"REGION_TYPE" NUMBER(1,0), 
"REGION_NAME" NVARCHAR2(50), 
"NOTE" NVARCHAR2(200)
);

CREATE TABLE "REGION_ENTITY_SCOPE" 
("REGION_ID" NUMBER(4,0), 
"ENTITY_ID" NUMBER(4,0), 
"MAX_KEY_ID" NUMBER(13,0), 
"MIN_KEY_ID" NUMBER(13,0), 
"ENTITY_MAX" NUMBER(10,0), 
"STATIC_ATTR_MAX" NUMBER(10,0), 
"USAGE_ATTR_MAX" NUMBER(10,0), 
"BILLPLAN_ATTR_MAX" NUMBER(10,0), 
"STATIC_ATTR_PERCENT" NUMBER(2,0) DEFAULT 0, 
"STATIC_ATTR_AVG_LEN" NUMBER(6,0) DEFAULT 0
);

CREATE TABLE "REGION_INDEX_SCOPE" 
("REGION_ID" NUMBER(4,0), 
"ENTITY_ID" NUMBER(4,0), 
"INDEX_ID" NUMBER(4,0), 
"INDEX_MAX" NUMBER(10,0)
);

CREATE TABLE "REGION_RECUPERATING_ENV_INFO" 
("REGION" NUMBER(5,0), 
"DATABASE" VARCHAR2(100), 
"CDR_DBLINK" VARCHAR2(100), 
"HOST_ID" VARCHAR2(60), 
"PROC_COUNT" NUMBER(5,0) DEFAULT 1, 
"PROC_ID_LIST" VARCHAR2(1000), 
"LOG_FILE" VARCHAR2(100)
);

CREATE TABLE "REMIND_BATCH_DEF" 
("BATCH_ID" NUMBER(5,0), 
"NAME" VARCHAR2(32), 
"REMIND_COND" VARCHAR2(1024), 
"G_REMIND_COND" VARCHAR2(1024)
);

CREATE TABLE "REMIND_CONTROL_BATCH" 
("REMIND_ENTRY_ID" NUMBER(2,0), 
"REMIND_SEQ" NUMBER(4,0), 
"BATCH_TYPE" NUMBER(1,0), 
"BATCH_ID" NUMBER(4,0) DEFAULT -1, 
"IS_DYNAMIC" NUMBER(1,0) DEFAULT 0, 
"STATUS_LOG_TYPE" NUMBER(2,0), 
"OUTPUT_TYPE" NUMBER(2,0) DEFAULT 1, 
"SHARED_FLAG" NUMBER(1,0)
);

CREATE TABLE "REMIND_CONTROL_DEF" 
("REMIND_ENTRY_ID" NUMBER(2,0), 
"REMIND_PARAM_ID" NUMBER(4,0), 
"REMIND_ENTRY_NAME" VARCHAR2(20), 
"NOTYFY_TYPE" NUMBER(2,0), 
"TRIGGER_TYPE" NUMBER(1,0), 
"TRIGGER_EVENT_ID" NUMBER(4,0), 
"CONDITION" VARCHAR2(256), 
"G_CONDITION" VARCHAR2(256), 
"REMIND_ENTITY" NUMBER(2,0) DEFAULT 1, 
"APPLY_METHOD" NUMBER(1,0) DEFAULT 8
);

CREATE TABLE "REMIND_CONTROL_PARAM" 
("REMIND_PARAM_ID" NUMBER(4,0), 
"REMIND_PARAM_NAME" VARCHAR2(20), 
"CDR_EVENT_ID" NUMBER(4,0), 
"REMIND_EVENT_ID" NUMBER(4,0), 
"ACCUMULATE_EVENT_ID" NUMBER(4,0), 
"UNDUP_ID" NUMBER(4,0), 
"FLOW_ID" NUMBER(4,0), 
"PROCESS_ID" NUMBER(5,0), 
"REMINDFLAG_EVENT_ID" NUMBER(4,0)
);

CREATE TABLE "REMIND_LIMIT_PARA" 
("PARAID" NUMBER(6,0), 
"REGION" NUMBER(4,0), 
"TARIFFID" NUMBER(8,0), 
"ATTRID" VARCHAR2(256), 
"ATTRTYPE" NUMBER(2,0) DEFAULT 0, 
"LIMITVALUE" VARCHAR2(128) DEFAULT 0, 
"TARIFFNAME" VARCHAR2(128), 
"STDFEE" VARCHAR2(32), 
"TEMPLATENO" VARCHAR2(512), 
"AVAILTIME" DATE DEFAULT SYSDATE, 
"EXPIRETIME" DATE DEFAULT to_date('20370101', 'YYYYMMDD'), 
"RATE" NUMBER(10,2) DEFAULT 1, 
"LOGICEXPR" VARCHAR2(2) DEFAULT '>=', 
"REMINDDEFAULT" NUMBER(1,0) DEFAULT 1, 
"STDFREE" VARCHAR2(64) DEFAULT 0, 
"HALFFREE" NUMBER(1,0) DEFAULT 0, 
"HALFLIMIT" NUMBER(1,0) DEFAULT 0, 
"REMINDATTRVALUE" VARCHAR2(32) DEFAULT '1', 
"RTCCTEMPLATENO" VARCHAR2(512) DEFAULT '0', 
"BATCH_ID" NUMBER(5,0) DEFAULT 0, 
"REMIND_TYPE" NUMBER(3,0) DEFAULT 0, 
"EXPR_COND" VARCHAR2(256), 
"G_EXPR_COND" VARCHAR2(512), 
"G_LIMITVALUE" VARCHAR2(512), 
"G_STDFREE" VARCHAR2(128), 
"ENTITY_ID" NUMBER(2,0) DEFAULT 1, 
"RECURRENT_FLAG" NUMBER(1,0) DEFAULT 0, 
"RECURRENT_OFFSET" NUMBER(10,0) DEFAULT 0, 
"LIMITTYPE" NUMBER(1,0) DEFAULT 0, 
"USAGE_CONFIG_FLAG" NUMBER(1,0) DEFAULT 0, 
"G_TEMPLATENO" VARCHAR2(512), 
"G_RTCCTEMPLATENO" VARCHAR2(512)
);

CREATE TABLE "RENT_DEF" 
("REGION" NUMBER(4,0), 
"RENTORDERTYPE" NUMBER(2,0) DEFAULT -1, 
"RENTORDERID" VARCHAR2(64), 
"ITEMCODE" VARCHAR2(64), 
"ITEMADDCODE" VARCHAR2(64), 
"SRCEVENTID" NUMBER(10,0) DEFAULT 0, 
"CONDITION" VARCHAR2(512), 
"CONDITIONNAME" VARCHAR2(512), 
"RENTADDTYPE" NUMBER(2,0) DEFAULT -1, 
"RENTAMNT" VARCHAR2(512), 
"RENTAMNTNAME" VARCHAR2(512), 
"CYCLETYPE" NUMBER(2,0) DEFAULT -1, 
"CYCLECNT" VARCHAR2(512), 
"CYCLECNTNAME" VARCHAR2(512), 
"CALCULATETYPE" NUMBER(2,0) DEFAULT -1, 
"EFFAPPORTIONTYPE" NUMBER(2,0) DEFAULT -1, 
"EXPAPPORTIONTYPE" NUMBER(2,0) DEFAULT -1, 
"HALFCYCLETYPE" NUMBER(2,0) DEFAULT 0, 
"CONVERTTYPE" NUMBER(2,0) DEFAULT -1, 
"CONVERTEXPR" NUMBER(2,0) DEFAULT -1, 
"ISSALEPRICE" NUMBER(1,0) DEFAULT 0, 
"PRECEDENCE" NUMBER(9,0) DEFAULT 0, 
"MERGEMODE" NUMBER(2,0) DEFAULT 1, 
"ITEMCODE_EXP" VARCHAR2(512), 
"ITEMCODE_NAME" VARCHAR2(512)
);

CREATE TABLE "RENT_PLAN" 
("RENTPLANID" NUMBER(9,0), 
"RENTPLANNAME" NVARCHAR2(64), 
"ENTITYTYPE" NUMBER(5,0) DEFAULT 0, 
"CONDITION" VARCHAR2(512), 
"CONDITIONNAME" VARCHAR2(512), 
"ISVALID" NUMBER(1,0) DEFAULT 0, 
"CYCLESCHEMAID" NUMBER(10,0) DEFAULT 0, 
"UNDUPMODULEID" NUMBER(10,0) DEFAULT 0, 
"MAPMULTIPROCID" NUMBER(10,0) DEFAULT 0, 
"SRCEVTPROCID" NUMBER(10,0) DEFAULT 0, 
"STDEVTPROCID" NUMBER(10,0) DEFAULT 0, 
"STDEVTFITPROCID" NUMBER(10,0) DEFAULT 0, 
"CHARGINGMODULEID" NUMBER(10,0) DEFAULT 0, 
"FLOWID" NUMBER(10,0) DEFAULT 0, 
"SWITCHPROCID" NUMBER(10,0) DEFAULT 0, 
"ADJUSTPROCID" NUMBER(10,0) DEFAULT 0
);

CREATE TABLE "RENT_QUERYSET_DEF" 
("RENTPLANID" NUMBER(9,0), 
"QUERYSETNAME" NVARCHAR2(64), 
"RENTORDERTYPE" NUMBER(2,0) DEFAULT -1, 
"RENTMATCHTYPE" NUMBER(2,0) DEFAULT -1, 
"PRECEDENCE" NUMBER(5,0) DEFAULT 0, 
"DATAQUERYSETID" NUMBER(10,0) DEFAULT 0, 
"SRCEVENTID" NUMBER(10,0) DEFAULT 0, 
"CONDITION" VARCHAR2(512), 
"CONDITIONNAME" VARCHAR2(512)
);

CREATE TABLE "REPORT_ELEMENT" 
("REPORT_VIEW_ID" NUMBER(4,0), 
"ELEMENT_TYPE" NUMBER(1,0), 
"SEQUENCENO" NUMBER(4,0), 
"STATISTICS_TYPE" NUMBER(1,0), 
"STATUS" NUMBER(1,0), 
"FIELD_ID" NUMBER(4,0), 
"EVENT_ATTR_ID" NUMBER(4,0) DEFAULT 0
);

CREATE TABLE "REPORT_FIELD_DEF" 
("REPORT_STORAGE_ID" NUMBER(4,0), 
"FIELD_ID" NUMBER(4,0), 
"FIELD_NAME" VARCHAR2(32), 
"DATATYPE" NUMBER(1,0), 
"NULL_OK" NUMBER(1,0), 
"DEFAULT_VALUE" VARCHAR2(32), 
"LENGTH" NUMBER(4,0), 
"SCALE" NUMBER(1,0), 
"ISUNIQUE" NUMBER(2,0), 
"FIELD_DESC" VARCHAR2(32), 
"STATUS" NUMBER(1,0), 
"MODIFY_FLAG" NUMBER(1,0)
);

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');

CREATE TABLE "RECURRENT_TRIGGER_DEF" 
("REGION" NUMBER(5,0), 
"TASK_NO" NUMBER(4,0), 
"ENTITY_ID" NUMBER(4,0), 
"TRIGGER_TYPE" NUMBER(2,0), 
"DEST_EVENT_ID" NUMBER(5,0), 
"FILTER_CONDITION" VARCHAR2(256), 
"G_FILTER_CONDITION" VARCHAR2(256), 
"FLOW_ID" NUMBER(5,0), 
"PROCESS_ID" NUMBER(9,0) DEFAULT 0
);

