CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;



CREATE TABLE "BILLITEM_CELL_DEF" 
("TEMPLATE_ID" NUMBER(10,0), 
"CELL_ID" VARCHAR2(32), 
"ITEMTYPE" VARCHAR2(32), 
"ITEMCODE" VARCHAR2(32), 
"ITEMADDCODE" VARCHAR2(32), 
"ISWRTOFFED" NUMBER(1,0), 
"INCL_SUBJECTID" VARCHAR2(256), 
"EXCL_SUBJECTID" VARCHAR2(256), 
"EXCL_ITEMCODE" VARCHAR2(256), 
"COEFFICIENT" NUMBER(2,0) DEFAULT 1, 
"CELL_TYPE" NUMBER(1,0) DEFAULT 1, 
"INCLUDEPACKAGE" NUMBER(1,0) DEFAULT 0, 
"GETNAMEORDER" NUMBER(1,0) DEFAULT 0, 
"FEEGROUPLIMIT" NUMBER(1,0) DEFAULT 0, 
"SELFDEFAULT" NUMBER(1,0) DEFAULT -1, 
"INCLUDETARIFF" NUMBER(1,0) DEFAULT 0
);

CREATE TABLE "BUFACCTEXTENT" 
("BUFID" NUMBER(8,0), 
"MINACCTID" NUMBER(15,0), 
"MAXACCTID" NUMBER(15,0), 
"ACCTCOUNT" NUMBER(10,0)
);

CREATE TABLE "BUFSUBSEXTENT" 
("BUFID" NUMBER(8,0), 
"MINSUBSID" NUMBER(15,0), 
"MAXSUBSID" NUMBER(15,0), 
"SUBSCOUNT" NUMBER(10,0)
);

CREATE TABLE "CDR_SUPPLEMENT_DEF" 
("SUPPLEMENT_ID" NUMBER(4,0), 
"CLUE_CDR_TABLE" VARCHAR2(64), 
"CLUE_CDR_WHERE_CLAUSE" VARCHAR2(120), 
"OFFLINE_CDR_TABLE" VARCHAR2(64), 
"OFFLINE_CDR_WHERE_CLAUSE" VARCHAR2(120), 
"ONLINE_CDR_TABLE" VARCHAR2(64), 
"ONLINE_CDR_WHERE_CLAUSE" VARCHAR2(120), 
"OFFLINE_QUERY_WHERE_CLAUSE" VARCHAR2(120), 
"ATTR_ID" NUMBER(4,0), 
"FIRST_SEQ" NUMBER(4,0) DEFAULT 1, 
"ONLINE_CYCLE" NUMBER(1,0) DEFAULT 2
);

CREATE TABLE "CDR_SUPPLEMENT_TASK" 
("TASK_ID" NUMBER(4,0), 
"SUPPLEMENT_ID" NUMBER(4,0), 
"CLUE_EVENT_ID" NUMBER(4,0), 
"CLUE_QUERY" VARCHAR2(256), 
"CDR_EVENT_ID" NUMBER(4,0), 
"FLOW_ID" NUMBER(4,0)
);

CREATE TABLE "CECONFILEINFO" 
("TASK_ID" NUMBER(10,0), 
"TASK_NOTE" VARCHAR2(128), 
"CEID" NUMBER(10,0), 
"CONFILECATA" VARCHAR2(128), 
"CONFILENAME" VARCHAR2(32), 
"LOGFILECATA" VARCHAR2(128), 
"LOGFILENAMEEXP" VARCHAR2(32), 
"BACKUPCATA" VARCHAR2(128), 
"CONFIGFILE_TYPE" VARCHAR2(32), 
"TEST_COMMAND" VARCHAR2(128), 
"COMMAND_RETURN_STRING" VARCHAR2(256)
);

CREATE TABLE "CHARGE_RATE" 
("RATECODE" NUMBER(8,0), 
"RATENAME" VARCHAR2(64), 
"CURRENCY" NUMBER(15,7), 
"CURRENCYTYPE" NUMBER(1,0), 
"UNITS" NUMBER(13,3), 
"UNITTYPE" NUMBER(2,0), 
"ROUND_UNIT" NUMBER(13,3), 
"ROUND_TYPE" NUMBER(1,0), 
"ATTR_CLASS" NUMBER(2,0), 
"REGION" NUMBER(5,0) DEFAULT 0
);

CREATE TABLE "CHARGING_CYCLE" 
("CYCLE_SCHEMA_ID" NUMBER(4,0), 
"CYCLE_ID" NUMBER(8,0), 
"CHARGING_EVENT_ID" NUMBER(4,0), 
"BILLING_COND" VARCHAR2(512), 
"G_BILLING_COND" VARCHAR2(512)
);

CREATE TABLE "CHARGING_EVENT_DEF" 
("EVENT_TYPE" NUMBER(1,0), 
"EVENT_ID" NUMBER(4,0), 
"EVENT_NAME" VARCHAR2(100), 
"TABLE_NAME" VARCHAR2(50), 
"EVENT_SCOPE" NUMBER(5,0), 
"VERSION" NUMBER(4,0) DEFAULT 1, 
"SERV_RANGE" VARCHAR2(128), 
"G_SERV_RANGE" VARCHAR2(256)
);

CREATE TABLE "CHARGING_MODULE" 
("MODULE_ID" NUMBER(4,0), 
"MODULE_NAME" VARCHAR2(64), 
"MODULE_TYPE" NUMBER(1,0), 
"CYCLE_SCHEMA_ID" NUMBER(4,0), 
"CHARGING_TYPE" NUMBER(1,0) DEFAULT 1
);

CREATE TABLE "CLEAN_DATASET_ACTION" 
("ACTION_ID" VARCHAR2(32), 
"DATASET_ID" VARCHAR2(32), 
"ACTION_NAME" VARCHAR2(80), 
"PROC_ORDER" NUMBER(4,0), 
"BACKUP_SELECT_SQL" VARCHAR2(2048), 
"BACKUP_INSERT_SQL" VARCHAR2(2048), 
"DELETE_SQL" VARCHAR2(512), 
"BIND_VARS" VARCHAR2(128), 
"FLOW_SELECT_SQL" VARCHAR2(512), 
"FLOW_INSERT_SQL" VARCHAR2(512)
);

CREATE TABLE "CLEAN_DATASET_COND" 
("DATASET_COND_ID" VARCHAR2(32), 
"DATASET_ID" VARCHAR2(32), 
"COND_NAME" VARCHAR2(80), 
"PROC_ORDER" NUMBER(4,0), 
"SQL_TEXT" VARCHAR2(512), 
"BIND_PARAM" VARCHAR2(128), 
"SERVER_NAME" VARCHAR2(64)
);

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');

