CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;



CREATE TABLE "PARAM_ID_CHANGE" 
("GROUP_NAME" VARCHAR2(20), 
"ID_NUMBER" NUMBER(10,0), 
"CHANGE_TIME" DATE
);

CREATE TABLE "SET_VALUE" 
("SET_ID" NUMBER(4,0), 
"APPLYTIME" DATE, 
"EXPIRETIME" DATE, 
"VALUE" VARCHAR2(128), 
"NOTE" VARCHAR2(128)
);

CREATE TABLE "SHM_ENTITY_ATTR_DEF" 
("ENTITY_ID" NUMBER(4,0), 
"ATTR_ID" NUMBER(8,0), 
"ENTITY_EVENT_ID" NUMBER(9,0), 
"ATTR_NAME" NVARCHAR2(80), 
"IMDB_ENTITY_ID" NUMBER(9,0), 
"IMDB_ATTR_ID" NUMBER(4,0)
);

CREATE TABLE "SHM_ENTITY_LOAD_DEF" 
("SHM_ENTITY_ID" NUMBER(4,0), 
"LOAD_ORDER" NUMBER(9,0), 
"DATA_SOURCE_NAME" VARCHAR2(80), 
"DATA_QUERY_ID" NUMBER(9,0), 
"SERVER_LIST" VARCHAR2(128), 
"ATTR_TYPE" NUMBER(1,0)
);

CREATE TABLE "SPLIT_FILE" 
("TASK_ID" NUMBER(4,0), 
"SPLIT_FILE_ID" NUMBER(4,0), 
"PATH_NAME" VARCHAR2(100), 
"BACKUP_PATH" VARCHAR2(100), 
"ERROR_PATH" VARCHAR2(100), 
"TMP_PATH" VARCHAR2(100), 
"DEST_PATH" VARCHAR2(100), 
"VERSION" NUMBER(2,0), 
"FILENAME_PREFIX" VARCHAR2(30), 
"SPLIT_TYPE" NUMBER(1,0), 
"DEST_FILE_SIZE" NUMBER(12,0), 
"WRITE_HEAD_TAIL" CHAR(1) DEFAULT 0
);

CREATE TABLE "SPLIT_FILE_ITEM" 
("SPLIT_FILE_ID" NUMBER(4,0), 
"UNIQUENO" NUMBER(5,0), 
"ITEM_CODE" VARCHAR2(7), 
"TAG_CODE" VARCHAR2(7), 
"MIN_VERSION" NUMBER(2,0), 
"MAX_VERSION" NUMBER(2,0), 
"ITEM_NAME" VARCHAR2(100), 
"ITEM_TYPE" CHAR(1), 
"LENGTH_TYPE" CHAR(1), 
"DATA_LENTH" NUMBER(4,0), 
"CHECK_FILE_SIZE" NUMBER(1,0) DEFAULT 0
);

CREATE TABLE "SPLIT_FILE_ITEM_CONTENT" 
("UNIQUENO" NUMBER(5,0), 
"SEQUENCE" NUMBER(3,0), 
"CONTENT_NAME" VARCHAR2(100), 
"CONTENT_TYPE" CHAR(1), 
"LENGTH_TYPE" CHAR(1)
);

CREATE TABLE "SPLIT_FILE_LIST" 
("SPLIT_FILE_NAME" VARCHAR2(40), 
"SPLIT_FILE_ID" NUMBER(4,0), 
"STOREFORMAT" NUMBER(1,0), 
"NOTE" VARCHAR2(100)
);

CREATE TABLE "SPLIT_FILE_SUBITEM_LIST" 
("UNIQUENO" NUMBER(5,0), 
"SEQUENCE" NUMBER(3,0), 
"SUBITEMSEQUENCE" NUMBER(3,0), 
"ITEMCODE" VARCHAR2(7), 
"TAGCODE" VARCHAR2(7), 
"ITEM_QTY" CHAR(1) DEFAULT 1, 
"VALID" CHAR(1) DEFAULT 1
);

CREATE TABLE "SPLIT_FILE_TASK" 
("TASK_ID" NUMBER(4,0), 
"NAME" VARCHAR2(100)
);

CREATE TABLE "SQL_DEF" 
("DB_TYPE" VARCHAR2(10), 
"SQL_ID" VARCHAR2(128), 
"SQL_SCRIPT" VARCHAR2(4000), 
"NOTE" VARCHAR2(256)
);

CREATE TABLE "STAT_SCOPE" 
("MODULE_ID" NUMBER(4,0), 
"REPORT_VIEW_ID" NUMBER(4,0), 
"BUFFER_ROWS" NUMBER(10,0), 
"DUMP_TYPE" NUMBER(1,0)
);

CREATE TABLE "STATISTICS_MODULE" 
("MODULE_ID" NUMBER(4,0), 
"MODULE_NAME" VARCHAR2(64), 
"MODULE_TYPE" NUMBER(1,0)
);

CREATE TABLE "SUBITEMLIST" 
("UNIQUENO" NUMBER(5,0), 
"SEQUENCE" NUMBER(3,0), 
"SUBITEMSEQUENCE" NUMBER(3,0), 
"ITEMCODE" VARCHAR2(7), 
"TAGCODE" VARCHAR2(7), 
"ITEMQTY" CHAR(1) DEFAULT '1', 
"SELECTOR" CHAR(1), 
"VALID" CHAR(1)
);

CREATE TABLE "SUBJECT_DEF" 
("SUBJECTID" VARCHAR2(16), 
"SUBJECTNAME" VARCHAR2(64), 
"PERCENT_OF_REFUND" NUMBER(5,2), 
"CYCLES_OF_REFUND" NUMBER(4,0), 
"DRAW_ORDER" NUMBER(8,0), 
"OFFSET_SCOPE" VARCHAR2(1024), 
"AVAILABLE_CYCLE" NUMBER(10,0), 
"START_CYCLE" NUMBER(10,0), 
"IN_USE" NUMBER(1,0), 
"DRAW_AMT" NUMBER(14,0), 
"FLOWIN_TYPE" NUMBER(8,0), 
"SUBJECT_SIGN" VARCHAR2(8), 
"SUBJECT_TYPE" NUMBER(2,0) DEFAULT 1, 
"SUBJECTIDN" NUMBER(8,0), 
"MIN_DRAW_AMT" NUMBER(15,0) DEFAULT 0, 
"REF_TYPE" NUMBER(1,0) DEFAULT 0, 
"COMP_METHOD" NUMBER(1,0) DEFAULT 0, 
"BILLFEE_DRAW_AMT" NUMBER(14,0) DEFAULT 0, 
"BILLFEE_REF_TYPE" NUMBER(1,0) DEFAULT 0, 
"MAX_DRAW_AMT" NUMBER(15,0), 
"NOTE" VARCHAR2(200), 
"IS_CAL_SCORE" NUMBER(1,0) DEFAULT 0, 
"CYCLE_UNIT" NUMBER(1,0) DEFAULT 1, 
"IS_VIRTUAL_SUBJECT" NUMBER(1,0) DEFAULT 0, 
"WRTOFF_HIS_TYPE" NUMBER(2,0) DEFAULT 0, 
"EXLUDE_OFFSET_SCOPE" VARCHAR2(1024), 
"CANINVOICE" NUMBER(2,0) DEFAULT 0, 
"WRTOFFNEGATIVE" NUMBER(1,0) DEFAULT 0, 
"LIMITFORSUBSID" NUMBER(1,0) DEFAULT 1
);

CREATE TABLE "SUBSCRIBER_MATCH" 
("CHARGING_EVENT_ID" NUMBER(4,0), 
"MATCH_ATTR_CLASS" NUMBER(4,0), 
"PRECEDENCE" NUMBER(4,0)
);


insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');

