CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;



CREATE TABLE "EVENT_RTCC_DEF" 
("EVENTID" NUMBER(4,0), 
"PRECEDENCE" NUMBER(4,0), 
"MATCHCOND" VARCHAR2(256), 
"EVENTTYPE" NUMBER(2,0), 
"SLICETYPE" NUMBER(2,0), 
"SLICEVALUE" NUMBER(8,0), 
"SLICEMINVALUE" NUMBER(8,0), 
"SLICEATTRID" NUMBER(4,0), 
"RATESWITCHTIME" VARCHAR2(64), 
"BALANCETHRESHOLD" NUMBER(12,2), 
"UPDATETIMER" NUMBER(8,0), 
"FCIENABLE" NUMBER(1,0), 
"G_MATCHCOND" VARCHAR2(512), 
"OVERDRAFTSUM" NUMBER(8,0) DEFAULT 0, 
"ISSPLIT" NUMBER(2,0) DEFAULT 0, 
"SPLITCOND" VARCHAR2(256), 
"G_SPLITCOND" NVARCHAR2(512), 
"ATTR_LIST" VARCHAR2(64), 
"G_ATTR_LIST" VARCHAR2(512), 
"AUTH_CALC_TYPE" NUMBER(1,0) DEFAULT 0, 
"PARAM_PROC_SCHEMA_ID" NUMBER(5,0) DEFAULT 0
);

CREATE TABLE "EVENT_STORE_DEF" 
("EVENT_ID" NUMBER(4,0), 
"TABLE_NAME" VARCHAR2(32), 
"CYCLE_FLAG" NUMBER(1,0), 
"TABLE_TYPE" VARCHAR2(1) DEFAULT 0, 
"TABLE_CHINESENAME" VARCHAR2(32), 
"EVENT_TYPE" VARCHAR2(5), 
"REGION" NUMBER(1,0) DEFAULT 0, 
"SPLIT_ATTR" VARCHAR2(60)
);

CREATE TABLE "EVENT_TARIFF_ITEM" 
("PLAN_ID" NUMBER(6,0), 
"ITEM_VALUE" VARCHAR2(128), 
"TARIFF_PLAN_ID" NUMBER(6,0), 
"APPLYTIME" DATE, 
"EXPIRETIME" DATE, 
"NOTE" VARCHAR2(400)
);

CREATE TABLE "EVENT_TARIFF_PLAN" 
("PLAN_ID" NUMBER(6,0), 
"PLAN_NAME" VARCHAR2(128), 
"EVENT_ID" NUMBER(4,0), 
"COND" VARCHAR2(512), 
"G_COND" VARCHAR2(1024), 
"ITEM_EXPR" VARCHAR2(256), 
"G_ITEM_EXPR" VARCHAR2(1024), 
"MATCH_ORDER" NUMBER(1,0), 
"MATCH_TYPE" NUMBER(1,0), 
"APPLY_METHOD" NUMBER(1,0), 
"NOTE" VARCHAR2(400)
);

CREATE TABLE "EVENT_UNDUP_DEF" 
("UNDUP_ID" NUMBER(4,0), 
"UNDUP_NAME" VARCHAR2(32), 
"EVENT_ID" NUMBER(4,0), 
"KEY_TABLE" VARCHAR2(64), 
"DUPEVENT_TABLE" VARCHAR2(64), 
"UNDUP_CON" VARCHAR2(512), 
"G_UNDUP_COND" VARCHAR2(800), 
"UNDUP_COND" VARCHAR2(512)
);

CREATE TABLE "EXPR_MAPPING_LIST" 
("RULE_ID" NUMBER(5,0), 
"DEST_ATTR_ID" VARCHAR2(10), 
"EXPR_COND" VARCHAR2(512), 
"EXPR" VARCHAR2(256), 
"EXPR_TYPE" NUMBER(1,0), 
"G_DEST_ATTR" VARCHAR2(64), 
"G_EXPR_COND" VARCHAR2(768), 
"G_EXPR" VARCHAR2(320), 
"SEQNO" NUMBER(6,0) DEFAULT 0, 
"NOTE" VARCHAR2(256), 
"PROCESS_SCHEMA_ID" NUMBER(5,0)
);

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');
