CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;


CREATE TABLE "DATASOURCE" 
("DATASOURCEID" NUMBER(3,0), 
"NAME" VARCHAR2(40), 
"NOTE" VARCHAR2(120), 
"BYTESEQUENCE" CHAR(1) DEFAULT '0', 
"FILECLASS" NUMBER(2,0), 
"STOREFORMAT" CHAR(1), 
"PROCESSTYPE" NUMBER(4,0), 
"NEED_CHECK_SEQUENCE" NUMBER(1,0) DEFAULT 0, 
"MERGE_SCHEMA_ID" NUMBER(6,0) DEFAULT 0
);


CREATE TABLE "DB_AUTH_DEF" 
("DB_AUTH_ID" VARCHAR2(20), 
"USER_NAME" VARCHAR2(30), 
"USER_PASSWORD" VARCHAR2(128), 
"VIRTUAL_USER" VARCHAR2(30), 
"VIRTUAL_PASS" VARCHAR2(128), 
"DESCRIPTION" NVARCHAR2(200), 
"PASSCHANGETIME" DATE DEFAULT sysdate
);

CREATE TABLE "DB_CHECK_CLUSTER_DEF" 
("CLUSTER_ID" VARCHAR2(4), 
"ZK_CLUSTER" VARCHAR2(100), 
"SQL_TIMEOUT" NUMBER(4,0) DEFAULT 1, 
"RETRY_INTERVAL" NUMBER(4,0) DEFAULT 1, 
"RETRY_TIMES" NUMBER(4,0) DEFAULT 3, 
"CHECK_INTERVAL" NUMBER(4,0) DEFAULT 3, 
"CUST_PHY_DB" VARCHAR2(20), 
"NOTE" VARCHAR2(100)
);

CREATE TABLE "DB_CHECK_CLUSTER_LIST" 
("CLUSTER_ID" VARCHAR2(4), 
"SERVER_ID" NUMBER(3,0), 
"SERVER_NAME" VARCHAR2(20), 
"NOTE" VARCHAR2(100)
);

CREATE TABLE "DB_CONNECTION_LIST" 
("DB_AUTH_ID" VARCHAR2(20), 
"DB_CONNECTION_NAME" VARCHAR2(50), 
"DRIVER_NAME" VARCHAR2(250), 
"URL" VARCHAR2(800), 
"IP_RANGE_NAME" VARCHAR2(60), 
"DB_TYPE" VARCHAR2(10), 
"IP" VARCHAR2(20), 
"PORT" VARCHAR2(10), 
"SERVER_NAME" VARCHAR2(50), 
"LAN_TYPE" VARCHAR2(5) DEFAULT 'C', 
"SERVER_ID" NUMBER(3,0), 
"EXTRAURL" VARCHAR2(800)
);

CREATE TABLE "DCC_BASE_CLIENT_DEF" 
("DCC_SERVICE_ID" NUMBER(10,0), 
"IP" VARCHAR2(100), 
"PORT" NUMBER(5,0), 
"DCC_ID" NUMBER(10,0), 
"DCC_HOST_NAME" VARCHAR2(100), 
"DCC_REALM_NAME" VARCHAR2(100), 
"DCC_GROUP_NAME" VARCHAR2(100)
);

CREATE TABLE "DCC_BASE_DEF" 
("DCC_SERVICE_ID" NUMBER(10,0), 
"NAME" VARCHAR2(30), 
"SERVICE_EVENT_ID" NUMBER(5,0) DEFAULT 0, 
"NOTE" VARCHAR2(200)
);

CREATE TABLE "DCC_BASE_GROUP_DEF" 
("DCC_SERVICE_ID" NUMBER(10,0), 
"GROUP_ID" NUMBER(5,0), 
"GROUP_NAME" VARCHAR2(100)
);

CREATE TABLE "DCC_BASE_LOCAL_DEF" 
("DCC_SERVICE_ID" NUMBER(10,0), 
"LOCAL_ID" NUMBER(10,0), 
"LOCAL_NAME" VARCHAR2(100), 
"IP" VARCHAR2(100), 
"PORT" NUMBER(5,0), 
"DCC_ID" NUMBER(10,0), 
"DCC_HOST_NAME" VARCHAR2(100), 
"DCC_REALM_NAME" VARCHAR2(100), 
"DCC_GROUP_NAME" VARCHAR2(100)
);

CREATE TABLE "DCC_BASE_PARAM_DEF" 
("DCC_SERVICE_ID" NUMBER(10,0), 
"ATTACHING_LOCAL_ID" NUMBER(10,0) DEFAULT 0, 
"PARAM_CATALOG" VARCHAR2(30), 
"PARAM_NAME" VARCHAR2(50), 
"PARAM_VALUE" VARCHAR2(256), 
"PARAM_SEQ" NUMBER(10,0) DEFAULT 0
);

CREATE TABLE "DCC_INTERFACE" 
("MMQ_DEVID" NUMBER(8,0), 
"TRACE_PERFORMANCE" NUMBER(1,0) DEFAULT 0, 
"DUMP_QUEUE" VARCHAR2(64), 
"SEND_DWR" NUMBER(1,0) DEFAULT 0, 
"DWR_TIME" NUMBER(10,0) DEFAULT 0, 
"DPR_WAIT_TIME" NUMBER(15,0) DEFAULT 3000000, 
"LOG_POLICY" NUMBER(1,0) DEFAULT 1, 
"CONTROL_EVENT_ID" NUMBER(6,0), 
"CONTROL_SCHEMA" NUMBER(6,0), 
"DATA_SOURCE_ID" NUMBER(3,0)
);

CREATE TABLE "DCC_REAL_NODE_DEF" 
("DCC_SERVICE_ID" NUMBER(10,0), 
"GROUP_ID" NUMBER(5,0), 
"IP" VARCHAR2(100), 
"PORT" NUMBER(5,0), 
"DCC_ID" NUMBER(10,0), 
"DCC_HOST_NAME" VARCHAR2(100), 
"DCC_REALM_NAME" VARCHAR2(100), 
"DCC_GROUP_NAME" VARCHAR2(100), 
"MAX_CPS" NUMBER(10,0) DEFAULT 0, 
"MAX_SESSION" NUMBER(10,0) DEFAULT 0, 
"MAX_RESP_TIME" NUMBER(10,0) DEFAULT 0, 
"WEIGHT" NUMBER(10,0) DEFAULT 0, 
"STATUS" NUMBER(1,0) DEFAULT 0, 
"LC_NODE_ID" NUMBER(4,0)
);

CREATE TABLE "DCC_REAL_NODE_WEIGHT" 
("DCC_SERVICE_ID" NUMBER(10,0), 
"LOCAL_ID" NUMBER(10,0), 
"GROUP_ID" NUMBER(5,0), 
"IP" VARCHAR2(100), 
"PORT" NUMBER(5,0), 
"WEIGHT" NUMBER(10,0) DEFAULT 0, 
"PREOCESS_TIME" DATE
);

CREATE TABLE "DISCNT_TO_PRODUCT" 
("DISCNT_CODE" VARCHAR2(32), 
"PRODUCT_CODE" VARCHAR2(60)
);

CREATE TABLE "DISCOUNT_PARAM_ITEM" 
("FEETYPE" VARCHAR2(10), 
"FIELD_NAME" VARCHAR2(60)
);


insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');

CREATE TABLE "DATAITEMCONTENT" 
("UNIQUENO" NUMBER(5,0), 
"SEQUENCE" NUMBER(3,0), 
"SEQUENCENAME" VARCHAR2(100), 
"SUBITEMTYPETAG" CHAR(1) DEFAULT '1', 
"TAGLENGTHTYPE" CHAR(1), 
"TAGDATATYPE" CHAR(1), 
"TAGTOTALLENGTH" NUMBER(5,0) DEFAULT 0, 
"TODATATYPE" CHAR(1), 
"TAGEXTRACTALL" CHAR(1) DEFAULT '0'
);

CREATE TABLE "DATA_ROUTE_HEAD" 
("BEGINNO" VARCHAR2(32), 
"ENDNO" VARCHAR2(32), 
"STARTTIME" DATE, 
"ENDTIME" DATE, 
"NBRTYPE" NUMBER(2,0) DEFAULT 0, 
"REGION" NUMBER(5,0), 
"DATA_NODEID" NUMBER(4,0), 
"DBTYPE" NUMBER(2,0)
);

CREATE TABLE "ENTITY_SYNC_QUEUE" 
("REGION" VARCHAR2(30), 
"CREATE_TIME" DATE, 
"TRANS_SN" VARCHAR2(60), 
"REFRESH_INDEX" NUMBER(18,0), 
"ENTITY_TABLE" VARCHAR2(100), 
"ENTITY_KEY" VARCHAR2(2000), 
"REFRESH_TYPE" CHAR(1), 
"SOURCE_TABLE" VARCHAR2(30), 
"SOURCE_KEY" VARCHAR2(2000), 
"PROCESS_FLAG" NUMBER(1,0) DEFAULT 0, 
"ROUTE_CUSTID" NUMBER(14,0), 
"PROCESS_TIME" DATE DEFAULT SYSDATE
);
