CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;



CREATE TABLE "TOTAL_USAGE_ATTR_DEF" 
("ENTITY_ID" NUMBER(4,0), 
"ATTR_ID" NUMBER(8,0), 
"USAGE_TYPE" NUMBER(1,0), 
"RE_ATTR_ID" NUMBER(4,0)
);

CREATE TABLE "TRACE_SET_DEF" 
("PROGNUM" NUMBER(4,0), 
"PROGNAME" VARCHAR2(64), 
"OBJECTTYPE" NUMBER(2,0), 
"VALUE" VARCHAR2(64), 
"APPLYTIME" DATE, 
"EXPIRETIME" DATE, 
"TRACELEVEL" NUMBER(2,0) DEFAULT 1, 
"TRACEAPP" NUMBER(2,0) DEFAULT 1
);

CREATE TABLE "TRIGGER_MAPPING_DEF" 
("TRIGGER_TYPE" NUMBER(2,0), 
"SOURCE_EVENT_ID" NUMBER(4,0), 
"SOURCE_ATTR_ID" NUMBER(4,0), 
"DEST_EVENT_ID" NUMBER(5,0), 
"DEST_ATTR_ID" NUMBER(5,0), 
"IS_KEY" NUMBER(1,0) DEFAULT 0, 
"SOURCE_TYPE" NUMBER(1,0) DEFAULT 1
);

CREATE TABLE "TRIGGER_RULE_DEF" 
("TRIGGER_TYPE" NUMBER(2,0), 
"RULE_ID" NUMBER(5,0), 
"RTCC_FLAG" NUMBER(1,0) DEFAULT 0, 
"REQUEST_TYPE" VARCHAR2(2) DEFAULT '0', 
"EVENT_OBJECT" NUMBER(2,0), 
"FILTER_TYPE" NUMBER(2,0), 
"TRIGGER_CONDITION" VARCHAR2(64), 
"DELAY_DAY_LIST" VARCHAR2(100), 
"DELAY_BEGIN_TIME" VARCHAR2(6) DEFAULT '000000', 
"DELAY_END_TIME" VARCHAR2(6) DEFAULT '240000', 
"DELAY_FLAG" NUMBER(1,0) DEFAULT 3, 
"DIRECT_CALL" NUMBER(5,0) DEFAULT 0, 
"CALL_SERVER_TYPE" VARCHAR2(60) DEFAULT 'ALL', 
"APP_TASK_ID" VARCHAR2(60)
);

CREATE TABLE "TRIGGER_TYPE_DEF" 
("NAME" VARCHAR2(20), 
"TRIGGER_TYPE" NUMBER(2,0), 
"FLOW_ID" NUMBER(5,0), 
"DUPLICATE_CHECK" NUMBER(1,0) DEFAULT 1, 
"PROC_SCHEMA_ID" NUMBER(5,0)
);

CREATE TABLE "UNDUP_MODULE" 
("MODULE_ID" NUMBER(4,0), 
"NAME" VARCHAR2(100), 
"UNDUP_MODE" NUMBER(1,0) DEFAULT 0, 
"NOTE" VARCHAR2(100)
);

CREATE TABLE "UNDUP_MODULE_DEF" 
("MODULE_ID" NUMBER(4,0), 
"UNDUP_ID" NUMBER(4,0), 
"APPLY_TIME" DATE, 
"EXPIRE_TIME" DATE
);

CREATE TABLE "USAGE_CONFIG_DEF" 
("TARIFF_ID" NUMBER(8,0), 
"ENTITY_ID" NUMBER(2,0), 
"ATTR_TYPE" NUMBER(2,0), 
"ATTR_ID" VARCHAR2(128), 
"NOTE" VARCHAR2(128), 
"STD_FREE_EXPR" VARCHAR2(512) DEFAULT 0, 
"G_STD_FREE_EXPR" VARCHAR2(512), 
"CBE_STD_FREE_EXPR" VARCHAR2(512) DEFAULT 0, 
"G_CBE_STD_FREE_EXPR" VARCHAR2(512), 
"HALF_FREE" NUMBER(1,0) DEFAULT 0, 
"SHARE_CROSS_CYCLE" NUMBER(2,0), 
"CYCLE_COUNT_EXPR" VARCHAR2(512), 
"G_CYCLE_COUNT_EXPR" VARCHAR2(512), 
"START_CYCLE" NUMBER(8,0) DEFAULT 199801, 
"END_CYCLE" NUMBER(8,0) DEFAULT 999999
);

CREATE TABLE "WRTOFF_ORDER_DEF" 
("WRTOFF_ORDER_PLANID" NUMBER(10,0), 
"ITEMCODE" VARCHAR2(32), 
"WRTOFF_ORDER" NUMBER(5,0)
);

CREATE TABLE "WRTOFF_ORDER_PLAN_DEF" 
("WRTOFF_ORDER_PLANID" NUMBER(10,0), 
"WRTOFF_ORDER_PLANNAME" VARCHAR2(64), 
"IN_USE" NUMBER(1,0)
);

CREATE TABLE "WRTOFF_PLAN_DEF" 
("WRTOFF_PLANID" NUMBER(10,0), 
"WRTOFF_ORDER_PLANID" NUMBER(10,0), 
"AMERCE_PLANID" NUMBER(10,0), 
"SMALL_CHANGE" NUMBER(10,0), 
"PENALTY_TYPE" NUMBER(10,0), 
"VALID_CYCLE" NUMBER(10,0), 
"EXPIRE_CYCLE" NUMBER(10,0), 
"REGION" NUMBER(5,0)
);

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');

