CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;



CREATE TABLE "SERV_EXPR" 
("SERV_ID" NUMBER(4,0), 
"SERV_DESC" VARCHAR2(128), 
"PARENT_SERV_ID" NUMBER(4,0) DEFAULT 0, 
"SERV_TYPE" VARCHAR2(16), 
"HAVE_EXPR" NUMBER(1,0) DEFAULT 0, 
"CHARGE_EVENT_ID" NUMBER(4,0) DEFAULT 0, 
"EXPR" VARCHAR2(512), 
"G_EXPR" VARCHAR2(512), 
"NOTE" VARCHAR2(512), 
"SERV_RANGE" VARCHAR2(128), 
"G_SERV_RANGE" VARCHAR2(256)
);

CREATE TABLE "SERVICE_CLASS_PARAM_DEF" 
("SERVICE_CLASS_ID" VARCHAR2(60), 
"PARAM_NAME" VARCHAR2(60), 
"PARAM_CAPTION" VARCHAR2(120), 
"DEFAULT_VALUE" VARCHAR2(512), 
"MANDATORY" NUMBER(1,0) DEFAULT (0), 
"PARAM_DESC" VARCHAR2(300), 
"PARAM_TYPE" VARCHAR2(100)
);

CREATE TABLE "SERVICE_DEF" 
("SERVICE_CLASS_ID" VARCHAR2(60), 
"SERVICE_ID" VARCHAR2(60), 
"SERVICE_NAME" VARCHAR2(300), 
"SERVICE_DESC" VARCHAR2(500), 
"SERVICE_TYPE" NUMBER(1,0), 
"SERVICE_CATEGORY" VARCHAR2(60)
);

CREATE TABLE "SERVICE_GROUP_DEF" 
("GROUP_CODE" VARCHAR2(50), 
"GROUP_TYPE" VARCHAR2(20), 
"GROUP_NAME" VARCHAR2(100), 
"ZK_SERVER" VARCHAR2(100), 
"CONNECT_STRATEGY" NUMBER(2,0) DEFAULT 1, 
"REPORT_INTERVAL" NUMBER(5,0) DEFAULT 10
);

CREATE TABLE "SERVICE_MAPPING_DEF" 
("REGION" NUMBER(4,0) DEFAULT -1, 
"NODE_ID" NUMBER(4,0) DEFAULT -1, 
"DATA_NODE_ID" NUMBER(4,0) DEFAULT -1, 
"SERVICE_NAME" VARCHAR2(50), 
"SERVICE_GROUP" VARCHAR2(50)
);

CREATE TABLE "SERVICE_PARAM_DEF" 
("SERVICE_ID" VARCHAR2(60), 
"PARAM_NAME" VARCHAR2(60), 
"PARAM_VALUE" VARCHAR2(500), 
"PARAM_TYPE" VARCHAR2(100)
);

CREATE TABLE "SERVICE_REMIND_BATCH_DEF" 
("BATCH_ID" NUMBER(5,0), 
"NAME" VARCHAR2(32), 
"REMIND_ID" NUMBER(4,0)
);

CREATE TABLE "SERVICE_REMIND_DEF" 
("REMIND_ID" NUMBER(4,0), 
"REMIND_NOTE" VARCHAR2(32), 
"SERVICE_TYPE" VARCHAR2(20), 
"REMIND_TYPE" NUMBER(4,0), 
"EVENT_ID" NUMBER(4,0), 
"PROCESS_SCHEME" NUMBER(5,0), 
"UNDUP_ID" NUMBER(4,0), 
"FLOW_ID" NUMBER(4,0), 
"MERGE_TYPE" NUMBER(1,0) DEFAULT 1
);

CREATE TABLE "SERVICE_REMIND_FREE_DEF" 
("REMIND_ID" NUMBER(4,0), 
"REGION" NUMBER(4,0), 
"TARIFFID" NUMBER(8,0), 
"TARIFFNAME" VARCHAR2(64), 
"ATTRTYPE" NUMBER(2,0), 
"ATTRID" VARCHAR2(128), 
"USAGE_TYPE_LIST" VARCHAR2(20), 
"FREE_TYPE" NUMBER(1,0), 
"STDFREE" VARCHAR2(64), 
"HALFFREE" NUMBER(1,0), 
"G_STDFREE" VARCHAR2(128), 
"ENTITY_ID" NUMBER(2,0) DEFAULT 1, 
"SHARE_CROSS_CYCLE" NUMBER(1,0) DEFAULT 0, 
"SHARE_USAGE_TYPE_LIST" VARCHAR2(60), 
"CONDITION" VARCHAR2(512), 
"G_CONDITION" VARCHAR2(1024) DEFAULT null, 
"USAGE_CONFIG_FLAG" NUMBER(1,0) DEFAULT 0
);

CREATE TABLE "SERVICE_REMIND_LIMIT_DEF" 
("REMIND_ID" NUMBER(4,0), 
"PARAID" NUMBER(6,0), 
"REMIND_COMB_TYPE" VARCHAR2(10), 
"REMIND_COND" VARCHAR2(1024), 
"G_REMIND_COND" VARCHAR2(1024), 
"TEMPLATENO" VARCHAR2(512), 
"RTCC_TEMPLATENO" VARCHAR2(512), 
"AVAIL_TIME" DATE, 
"EXPIRE_TIME" DATE, 
"RECURRENT_USAGE_EXPR" VARCHAR2(500), 
"G_RECURRENT_USAGE_EXPR" VARCHAR2(500), 
"RECURRENT_UNIT" NUMBER(10,0) DEFAULT 0, 
"RECURRENT_OFFSET" NUMBER(10,0) DEFAULT 0, 
"SUB_REMIND_ID" NUMBER(8,0) DEFAULT 0, 
"G_TEMPLATENO" VARCHAR2(512), 
"G_RTCC_TEMPLATENO" VARCHAR2(512), 
"SUB_REMIND_FREE_ID" NUMBER(4,0)
);

CREATE TABLE "SERVICE_REMIND_USAGE_DEF" 
("REMIND_ID" NUMBER(4,0), 
"USAGE_TYPE" NUMBER(1,0), 
"ATTRTYPE" NUMBER(2,0), 
"ATTRID" VARCHAR2(128), 
"FILTER_COND" VARCHAR2(256), 
"G_FILTER_COND" VARCHAR2(256), 
"USAGE_EVENT_ATTR_ID" NUMBER(4,0) DEFAULT 0, 
"ENTITY_ID" NUMBER(2,0) DEFAULT 1, 
"OFFSET_CYCLE_CNT" NUMBER(2,0) DEFAULT 0
);

CREATE TABLE "SESSION_INDEX_DEF" 
("REGION_ID" NUMBER(4,0), 
"MODULE_NAME" VARCHAR2(16) DEFAULT 'COMMON', 
"INDEX_TYPE" NUMBER(1,0), 
"ATTRID_PATH" VARCHAR2(125), 
"G_ATTRID_PATH" VARCHAR2(1024), 
"BUCKET_CNT" NUMBER(10,0), 
"CHAIN_CNT" NUMBER(10,0), 
"NODEID" NUMBER(4,0) DEFAULT -1
);

CREATE TABLE "SESSION_MEM_DEF" 
("REGION_ID" NUMBER(4,0), 
"MODULE_NAME" VARCHAR2(16) DEFAULT 'COMMON', 
"SHM_KEYID" NUMBER(10,0), 
"AREA_MATCH" VARCHAR2(128), 
"EVENT_ID" NUMBER(4,0), 
"EVENT_SIZE" NUMBER(8,0), 
"BUCKET_CNT" NUMBER(10,0), 
"CHAIN_CNT" NUMBER(10,0), 
"ACCESS_TYPE" NUMBER(1,0) DEFAULT 1, 
"SERVER_NAME_LIST" VARCHAR2(128), 
"NODEID" NUMBER(4,0) DEFAULT -1
);

CREATE TABLE "PARAM_ID_CHANGE" 
("GROUP_NAME" VARCHAR2(20), 
"ID_NUMBER" NUMBER(10,0), 
"CHANGE_TIME" DATE
);

CREATE TABLE "SET_DEF" 
("SET_ID" NUMBER(4,0), 
"SET_NAME" VARCHAR2(64), 
"VALUE_NAME" VARCHAR2(64), 
"MATCH_ORDER" NUMBER(1,0), 
"SET_PARAM_ATTR" VARCHAR2(20), 
"OFTEN_USED" NUMBER(1,0) DEFAULT 0
);

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');

