CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;



CREATE TABLE "DISC_BATCH_DEF" 
("BATCH_ID" NUMBER(8,0), 
"BATCH_DESC" VARCHAR2(64), 
"SOURCE_EVENT_ID" NUMBER(4,0), 
"DISC_EVENT_ID" NUMBER(4,0), 
"FREE_EVENT_ID" NUMBER(4,0), 
"PREPAY_EVENT_ID" NUMBER(4,0), 
"BILL_CYCLE" NUMBER(8,0), 
"DISC_VALID_DATE" DATE, 
"APPLY_METHOD" NUMBER(1,0) DEFAULT 2, 
"FEETYPE" NUMBER(2,0), 
"PERIOD_TYPE" NUMBER(1,0) DEFAULT 0
);


CREATE TABLE "DISC_BATCH_LIST" 
("BATCH_ID" NUMBER(8,0), 
"TARIFFPLAN_ID" NUMBER(8,0), 
"START_CYCLE" NUMBER(8,0), 
"END_CYCLE" NUMBER(8,0)
);

CREATE TABLE "DISCITEM_DEF" 
("TARIFFPLAN_ID" NUMBER(8,0), 
"PLANITEM_ID" NUMBER(8,0), 
"DISCITEM_ID" NUMBER(8,0), 
"MIN_REFVALUE" NUMBER(16,0), 
"MAX_REFVALUE" NUMBER(16,0), 
"CALC_TYPE" NUMBER(1,0), 
"DISC_VALUE" NUMBER(18,2), 
"MAX_DISC_VALUE" NUMBER(16,0), 
"INUSE" NUMBER(1,0), 
"REFVALUE_ADD" NUMBER(16,0), 
"DISCT_EXPR" VARCHAR2(128) DEFAULT ' ', 
"G_DISCT_EXPR" VARCHAR2(200), 
"DISCITEM_COND" VARCHAR2(256), 
"G_DISCITEM_COND" VARCHAR2(256)
 ) ;

CREATE TABLE "DISCOUNT_PARAM_DEF" 
("PARAMDESC" VARCHAR2(100), 
"FEETYPE" VARCHAR2(10), 
"EXCLUSIVE_TYPE" NUMBER(1,0), 
"SEQ" NUMBER(10,0)
);

CREATE TABLE "DISCREFITEM_DEF" 
("TARIFFPLAN_ID" NUMBER(8,0), 
"PLANITEM_ID" NUMBER(8,0), 
"ITEM_CODE" VARCHAR2(32), 
"ITEM_DESC" VARCHAR2(64), 
"INUSE" NUMBER(1,0), 
"REF_ITEM_EXPR" VARCHAR2(512), 
"G_REF_ITEM_EXPR" VARCHAR2(512), 
"REF_ITEMADD_EXPR" VARCHAR2(512), 
"G_REF_ITEMADD_EXPR" VARCHAR2(512)
);

CREATE TABLE "DISCVALUEPERCENT_DEF" 
("TARIFFPLAN_ID" NUMBER(8,0), 
"PLANITEM_ID" NUMBER(8,0), 
"COND_EXPR" VARCHAR2(256), 
"PERCENT" NUMBER(10,0), 
"G_COND_EXPR" VARCHAR2(256), 
"SEQNO" NUMBER(5,0) DEFAULT 0
);

CREATE TABLE "DIST_PLAN_ITEM" 
("PLAN_ID" NUMBER(4,0) DEFAULT 1, 
"REGION" NUMBER(5,0) DEFAULT 0, 
"CUST_SHARD" NUMBER(8,0), 
"CONTAINER_ID" NUMBER(8,0), 
"NEW_CONTAINER_ID" NUMBER(8,0)
);

CREATE TABLE "DISTRIBUTED_DB_DEF" 
("REGION" NUMBER(5,0), 
"DBTYPE" NUMBER(2,0), 
"DISTRIBUTED_TYPE" NUMBER(1,0)
);

CREATE TABLE "DISTRIBUTED_DBNODE_DEF" 
("REGION" NUMBER(5,0), 
"DBTYPE" NUMBER(2,0), 
"NODEID" NUMBER(5,0), 
"NODEDESC" VARCHAR2(32)
);

CREATE TABLE "EVENT_ACCUMULATE_MAPPING_DEF" 
("RULE_ID" NUMBER(4,0), 
"MATCH_ORDER" NUMBER(4,0) DEFAULT 1, 
"SUB_ORDER" NUMBER(2,0) DEFAULT 1, 
"SOURCE_EVENT_FIELDS" VARCHAR2(1000), 
"BILLING_COND" VARCHAR2(600), 
"G_BILLING_CODE" VARCHAR2(600), 
"ITEM_CODE" VARCHAR2(40), 
"ITEMADD_EXPR" VARCHAR2(130), 
"G_ITEMADD_EXPR" VARCHAR2(130), 
"FEE_EXPR" VARCHAR2(130), 
"G_FEE_EXPR" VARCHAR2(130)
);

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');





