CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;


CREATE TABLE "EVENT_ACCUMULATE_MAPPING_RULE" 
("RULE_ID" NUMBER(4,0), 
"AUDIT_CHECK" NUMBER(1,0) DEFAULT 1, 
"EVENT_ID" NUMBER(4,0), 
"DST_EVENT_ID" NUMBER(4,0), 
"ITEM_TYPE" NUMBER(1,0), 
"SRC_FIELDS_LIST" VARCHAR2(300), 
"SRC_FIELDS_LIST_TEXT" VARCHAR2(300)
);

CREATE TABLE "PRODUCT_ELEMENT_TARIFF" 
("PRODUCT_ELEMENT_TYPE" VARCHAR2(10), 
"PRODUCT_ELEMENT_CODE" VARCHAR2(60), 
"TARIFF_PLAN_ID" NUMBER(6,0)
);

CREATE TABLE "ENTITY_ATTR_DEF" 
("ENTITY_ID" NUMBER(4,0), 
"ATTR_ID" NUMBER(8,0), 
"ATTR_NAME" VARCHAR2(32), 
"ATTR_TYPE" NUMBER(1,0), 
"MULTIVALUE" NUMBER(1,0), 
"ISUNIQUE" NUMBER(1,0), 
"ISRESIDENT" NUMBER(1,0), 
"ATTR_CLASS" NUMBER(3,0), 
"DATATYPE" NUMBER(1,0), 
"LENGTH" NUMBER(4,0), 
"SCALE" NUMBER(1,0), 
"EXPIRE_DAYS" NUMBER(6,0), 
"SERVICE_TYPE" VARCHAR2(32), 
"UNIT" VARCHAR2(32), 
"FIXEDFEE_FLAG" NUMBER(1,0) DEFAULT 0, 
"TABLE_NAME" VARCHAR2(32), 
"INC_APPSYSLIST" VARCHAR2(64), 
"EXC_APPSYSLIST" VARCHAR2(64), 
"ABM_RESOURCE_ID" NUMBER(10,0) DEFAULT 0, 
"ROUND_TYPE" CHAR(1) DEFAULT 'D', 
"ROUND_UNIT" NUMBER(10,0) DEFAULT 0, 
"BASE_UNIT" NUMBER(10,0) DEFAULT 0, 
"IS_RECORD_OVER_USAGE" CHAR(1) DEFAULT 'T', 
"ATTR_ADD_CODE_DEF" VARCHAR2(50), 
"VALID_CYCLE_COUNT" NUMBER(8,0) DEFAULT 0, 
"VALID_CYCLE_UNIT" NUMBER(1,0) DEFAULT 1, 
"CYCLE_ATTR_ID" NUMBER(4,0) DEFAULT 0, 
"NEED_NOTIFY_DETAIL" NUMBER(1,0) DEFAULT 0, 
"IS_BIND_PRODUCT_INST" NUMBER(1,0) DEFAULT 0, 
"BIND_PRODUCT_ELEMENT_CODE" VARCHAR2(60), 
"MERGE_TYPE" NUMBER(1,0) DEFAULT 0, 
"CARRYOVER_FLAG" NUMBER(1,0) DEFAULT 0, 
"SHARED_MODE" NUMBER(2,0) DEFAULT -1, 
"SHARED_MODE_SYNC_FLAG" NUMBER(1,0) DEFAULT 1, 
"ADDCODE_DEAL_TYPE" NUMBER(1,0) DEFAULT 0
);

CREATE TABLE "ENTITY_CACHE_DEF" 
("SCHEMA_ID" NUMBER(9,0), 
"ENTITY_ID" NUMBER(9,0), 
"ATTR_ID" NUMBER(8,0), 
"CACHE_MODE" NUMBER(1,0)
);

CREATE TABLE "ENTITY_CACHE_SCHEMA" 
("SCHEMA_ID" NUMBER(9,0), 
"SCHEMA_NAME" NVARCHAR2(80)
);

CREATE TABLE "ENTITY_DEF" 
("ENTITY_ID" NUMBER(9,0), 
"ENTITY_TABLE" VARCHAR2(30), 
"ENTITY_NAME" VARCHAR2(80), 
"ENTITY_EVENT_ID" NUMBER(9,0), 
"HAS_KEY" CHAR(1), 
"DEFAULT_QUERY_INSTANCE_ID" NUMBER(9,0), 
"SCAN_QUERY_ID" NUMBER(9,0), 
"INSERT_SQL" VARCHAR2(4000), 
"UPDATE_SQL" VARCHAR2(4000), 
"DELETE_SQL" VARCHAR2(4000), 
"ATTR_EVENT_ID" NUMBER(9,0), 
"DBTYPE" NUMBER(2,0), 
"MODULE_NAME" VARCHAR2(20), 
"AUDIT_ENTITY_TYPE" VARCHAR2(20), 
"AUDIT_KEY_ID" VARCHAR2(20), 
"UPDATE_CHECK_SQL" VARCHAR2(4000)
);

CREATE TABLE "ENTITY_DEPENDENCY_DEF" 
("ENTITY_ID" NUMBER(9,0), 
"DEPENDENT_ENTITY_ID" NUMBER(9,0)
);

CREATE TABLE "ENTITY_INDEX_DEF" 
("ENTITY_ID" NUMBER(4,0), 
"INDEX_ID" NUMBER(4,0), 
"INDEX_NAME" VARCHAR2(32), 
"ATTR_ID" NUMBER(8,0), 
"INDEX_TYPE" NUMBER(1,0) DEFAULT 1
);

CREATE TABLE "ENTITY_MEM_REGION" 
("REGION_ID" NUMBER(4,0), 
"REGION_NAME" VARCHAR2(32), 
"SHM_KEYID" NUMBER(10,0), 
"QUEUE_NAME" VARCHAR2(32), 
"NODE_ID" NUMBER(2,0), 
"AREA_COUNT" NUMBER(2,0), 
"AREA_ID" VARCHAR2(64), 
"PORT" NUMBER(8,0)
);

CREATE TABLE "ENTITY_QUERY_DEF" 
("ENTITY_ID" NUMBER(9,0), 
"QUERY_NAME" VARCHAR2(160), 
"DATA_QUERY_ID" NUMBER(9,0)
);

CREATE TABLE "ENTITY_STORE_DEF" 
("RULE_ID" NUMBER(9,0), 
"ENTITY_ID" NUMBER(9,0), 
"ATTR_ID" NUMBER(8,0), 
"RULE_TYPE" VARCHAR2(30), 
"RULE_PARAM" VARCHAR2(200), 
"RULE_PRIORITY" NUMBER(9,0), 
"STORE_TYPE" VARCHAR2(30), 
"IS_STORE" CHAR(1)
);

CREATE TABLE "EVENT_ATTR_DATATYPE_DEF" 
("EVENT_ID" NUMBER(4,0), 
"ATTR_ID" NUMBER(4,0), 
"MINVERSION" NUMBER(4,0) DEFAULT 1, 
"MAXVERSION" NUMBER(4,0) DEFAULT 0, 
"DATATYPE" NUMBER(5,0), 
"NOTE" VARCHAR2(32)
);

CREATE TABLE "EVENT_ATTR_DEF" 
("EVENT_ID" NUMBER(4,0), 
"ATTR_ID" NUMBER(4,0) DEFAULT -1, 
"ATTR_NAME" VARCHAR2(30), 
"DATATYPE" NUMBER(3,0), 
"ATTR_CLASS" NUMBER(3,0), 
"NULL_OK" NUMBER(1,0), 
"DEFAULT_VALUE" VARCHAR2(50), 
"AMBIGUOUS_VALUE" VARCHAR2(50), 
"ISUNIQUE" NUMBER(1,0), 
"POSITION" NUMBER(5,0), 
"LENGTH" NUMBER(5,0), 
"SCALE" NUMBER(1,0), 
"ALIGN_STYLE" NUMBER(1,0), 
"PADDED_CHAR" VARCHAR2(1), 
"FIELD_NAME" VARCHAR2(30), 
"FEE_ID" NUMBER(3,0), 
"VERSION" NUMBER(4,0), 
"DISPLAYSEQUENCE" NUMBER(4,0) DEFAULT 0, 
"SUB_EVENT_ID" NUMBER(4,0) DEFAULT 0, 
"ATTR_DESC" VARCHAR2(128), 
"OUT_SEQUENCE" NUMBER(4,0) DEFAULT 0
);

CREATE TABLE "EVENT_FLOW_DEF" 
("MODULE_ID" NUMBER(4,0), 
"FLOW_ID" NUMBER(4,0), 
"FLOW_NAME" VARCHAR2(64), 
"FLOW_COND" VARCHAR2(512), 
"FLOW_TYPE" NUMBER(1,0), 
"STORE_TYPE" CHAR(1), 
"STORE_NAME" VARCHAR2(100), 
"PRECEDENCE" NUMBER(4,0), 
"APPLY_TIME" DATE, 
"EXPIRE_TIME" DATE, 
"G_FLOW_COND" VARCHAR2(512), 
"EVENT_ID" NUMBER(4,0), 
"LOG_TYPE" CHAR(1) DEFAULT 'D', 
"NAME_MODE" CHAR(1) DEFAULT 'N', 
"EVENT_FLAG" VARCHAR2(5) DEFAULT ' ', 
"NEXT_SECTION" VARCHAR2(32), 
"STORE_PRIORITY" NUMBER(2,0) DEFAULT 50, 
"APPTYPE" NUMBER(4,0), 
"CLASSID" NUMBER(3,0), 
"PROC_SEGMENT" NUMBER(2,0) DEFAULT 0, 
"NOSET_APPROUTEID" NUMBER(1,0) DEFAULT 0
);

CREATE TABLE "EVENT_FLOW_MODULE" 
("MODULE_ID" NUMBER(4,0), 
"MODULE_NAME" VARCHAR2(40), 
"MODULE_NOTE" VARCHAR2(30), 
"SOURCE_FILE_FLAG" NUMBER(1,0) DEFAULT 0, 
"FLOW_SECTION" VARCHAR2(32)
);


CREATE TABLE "EVENT_KEY_DEF" 
("UNDUP_ID" NUMBER(4,0), 
"SEQUENCENO" NUMBER(4,0), 
"ATTR_ID" NUMBER(4,0), 
"STARTPOS" NUMBER(4,0), 
"LEN" NUMBER(4,0)
);

CREATE TABLE "EVENT_MATCH_COND" 
("EVENT_MATCH_ID" NUMBER(4,0), 
"TARGET_ATTR_ID" NUMBER(4,0), 
"MATCH_EXPRESSION" VARCHAR2(500), 
"SEQUENCE_NO" NUMBER(4,0)
);

CREATE TABLE "EVENT_MATCH_DEF" 
("EVENT_MATCH_ID" NUMBER(4,0), 
"SRC_EVENT_ID" NUMBER(4,0), 
"SRC_TABLE_FROM" VARCHAR2(64), 
"SRC_TABLE_TO" VARCHAR2(64), 
"TARGET_EVENT_ID" NUMBER(4,0), 
"TARGET_TABLE_FROM" VARCHAR2(64), 
"TARGET_TABLE_TO" VARCHAR2(64)
);

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');

