CREATE TABLE "PARAM_TABLE_DEF" 
("TABLE_NAME" VARCHAR2(64), 
"TABLE_NOTE" VARCHAR2(64), 
"SERIOUS" NUMBER(1,0), 
"LASTCHANGETIME" DATE
);

CREATE TABLE "AM_ACCT_INOUTMODEBOOK" 
("RECTYPE" VARCHAR2(32), 
"ACCESSTYPE" VARCHAR2(32), 
"PAYTYPE" VARCHAR2(32), 
"INOUTMODE" VARCHAR2(128)
);

CREATE TABLE "AM_ACCT_ITEM" 
("ACCT_TYPE" NUMBER(2,0), 
"ACCT_ITEM" NUMBER(2,0), 
"FLOW_TYPE" NUMBER(2,0) DEFAULT 0, 
"NOTE" VARCHAR2(64)
);

CREATE TABLE "AM_ACCT_RULE" 
("SUBJECT_TYPE" NUMBER(1,0), 
"SUBJECT_ID" VARCHAR2(32) DEFAULT -1, 
"FLOW_TYPE" NUMBER(2,0), 
"FLOW_TIME_RANGE" NUMBER(1,0), 
"FLOW_DIRECTION" NUMBER(1,0), 
"FEE_SIGN" NUMBER(1,0) DEFAULT -1, 
"FEE_SOURCE" NUMBER(1,0), 
"ACCT_TYPE" NUMBER(1,0), 
"ACCT_ITEM" NUMBER(2,0)
);

CREATE TABLE "AM_FUNC_CTL" 
("FUNCID" VARCHAR2(32), 
"FUNCNAME" VARCHAR2(32), 
"STATUSDATE" DATE, 
"INUSE" NUMBER(1,0), 
"DESCR" VARCHAR2(256), 
"OPER" VARCHAR2(32), 
"REGION" NUMBER(5,0) DEFAULT 999, 
"VALUE" VARCHAR2(64)
);

CREATE TABLE "BILLITEM_CELL_DEF" 
("TEMPLATE_ID" NUMBER(10,0), 
"CELL_ID" VARCHAR2(32), 
"ITEMTYPE" VARCHAR2(32), 
"ITEMCODE" VARCHAR2(32), 
"ITEMADDCODE" VARCHAR2(32), 
"ISWRTOFFED" NUMBER(1,0), 
"INCL_SUBJECTID" VARCHAR2(256), 
"EXCL_SUBJECTID" VARCHAR2(256), 
"EXCL_ITEMCODE" VARCHAR2(256), 
"COEFFICIENT" NUMBER(2,0) DEFAULT 1, 
"CELL_TYPE" NUMBER(1,0) DEFAULT 1, 
"INCLUDEPACKAGE" NUMBER(1,0) DEFAULT 0, 
"GETNAMEORDER" NUMBER(1,0) DEFAULT 0, 
"FEEGROUPLIMIT" NUMBER(1,0) DEFAULT 0, 
"SELFDEFAULT" NUMBER(1,0) DEFAULT -1, 
"INCLUDETARIFF" NUMBER(1,0) DEFAULT 0
);

CREATE TABLE "PC_REC_UPLOADDETAIL" 
("REGION" NUMBER(5,0), 
"OID" NUMBER(14,0), 
"RECOID" NUMBER(14,0), 
"RECDATE" DATE, 
"TABLENAME" VARCHAR2(32), 
"ENTITYID" NUMBER(14,0), 
"DOMAIN" VARCHAR2(16), 
"CONTENT" VARCHAR2(4000)
);
 
CREATE TABLE "PC_REC_UPLOADLOG" 
("REGION" NUMBER(5,0), 
"OID" NUMBER(14,0), 
"RECOID" NUMBER(14,0), 
"RECDEFID" VARCHAR2(32), 
"CONTACTTYPE" VARCHAR2(32), 
"ENTITYTYPE" VARCHAR2(32), 
"ENTITYID" NUMBER(14,0), 
"RECDATE" DATE, 
"PRIORITY" NUMBER(2,0), 
"PROCESSID" NUMBER(5,0), 
"STATUS" NUMBER(1,0), 
"STATUSCHANGEDATE" DATE, 
"AUDITSTATUS" NUMBER(1,0), 
"AUDITSTATUSDATE" DATE, 
"RETCODE" NUMBER(5,0), 
"ERRORMESSAGE" VARCHAR2(256)
);
 

CREATE TABLE "PC_BILLING_PLAN" 
("ITEMID" VARCHAR2(32), 
"ITEMNAME" VARCHAR2(64), 
"PLANTYPE" VARCHAR2(32), 
"NETWORKID" VARCHAR2(32), 
"ISBASEPLAN" NUMBER(1,0), 
"ADDCOUNT" NUMBER(2,0), 
"ADD1NAME" VARCHAR2(64), 
"ADD1DATATYPE" VARCHAR2(32), 
"ADD1GROUPID" VARCHAR2(32), 
"ADD2NAME" VARCHAR2(64), 
"ADD2DATATYPE" VARCHAR2(32), 
"ADD2GROUPID" VARCHAR2(32), 
"EFFECTTYPE" VARCHAR2(32), 
"EFFECTOFFSET" VARCHAR2(64), 
"INVALIDTYPE" VARCHAR2(32), 
"INVALIDOFFSET" VARCHAR2(64), 
"DESCRIPTION" VARCHAR2(256), 
"CREATEDATE" DATE, 
"STATUS" NUMBER(1,0), 
"STATUSDATE" DATE, 
"REGION" NUMBER(4,0), 
"PLAN_TYPE" VARCHAR2(32), 
"BASESTATIONGRPID" VARCHAR2(32)
);

CREATE SEQUENCE  seq_syn_log110  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  seq_syn_log999  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  seq_syn_detail110  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  seq_syn_detail999  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_OID"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 59434717 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE "PC_PRIV_PREPAY" 
("PRIVID" VARCHAR2(32), 
"EBOXDISCID" NUMBER(14,0), 
"EBOXUNITID" VARCHAR2(32), 
"INPLANID" NUMBER(14,0), 
"ISPOSTPONE" NUMBER(1,0), 
"EFFECTIVETYPE" VARCHAR2(32), 
"EFFECTIVEDATE" DATE, 
"EFFECTIVEINTERVAL" NUMBER(5,0), 
"PAYTIMES" NUMBER(5,0), 
"PAYINTERVAL" NUMBER(5,0), 
"ISPRESENT" NUMBER(1,0), 
"PRESENTTYPE" VARCHAR2(16), 
"AMOUNT" NUMBER(16,0), 
"RELADISCID" NUMBER(14,0), 
"AFFIXID" VARCHAR2(32), 
"ENTERUNITDETFLAG" NUMBER(1,0), 
"DISCTYPE" VARCHAR2(32), 
"ROLLOVERTYPE" VARCHAR2(32), 
"EXPIREDCYCLES" NUMBER(5,0), 
"REMARK" VARCHAR2(255), 
"FEESOURCETYPE" VARCHAR2(16), 
"FEESOURCEID" VARCHAR2(32), 
"CREATEDATE" DATE, 
"STATUS" NUMBER(1,0), 
"STATUSDATE" DATE, 
"VALIDITY" NUMBER(14,0), 
"CHGAFFECTOFFSET" NUMBER(1,0) DEFAULT 0, 
"BUFFERSUBJECT" VARCHAR2(32), 
"BREAKFULE" NUMBER(14,0), 
"USETYPE" NUMBER(1,0) DEFAULT 0, 
"MINBALANCE" NUMBER(16,0) DEFAULT 0, 
"CHARGEITEM" VARCHAR2(32) DEFAULT 'Charge_P01', 
"RATEPLAN" VARCHAR2(32), 
"ISCALCAGREEMENTFEE" NUMBER(1,0) DEFAULT 0, 
"AUDIT_CHANGE_TIME" DATE
);

CREATE TABLE "PC_PRIV_RATEPLAN" 
("PRIVID" VARCHAR2(32), 
"RATEPLAN" VARCHAR2(32), 
"AFFECTTYPE" VARCHAR2(32), 
"AFFECTOFFSET" VARCHAR2(32), 
"INVALIDTYPE" VARCHAR2(32), 
"INVALIDOFFSET" VARCHAR2(32), 
"DELENDTYPE" VARCHAR2(32), 
"REQUIREID" VARCHAR2(32), 
"CREATEDATE" DATE, 
"STATUS" NUMBER(1,0), 
"STATUSDATE" DATE, 
"AUDIT_CHANGE_TIME" DATE
);

CREATE TABLE "PC_PRIV_RATEPLAN_CONFIGLOG" 
("OID" NUMBER(14,0), 
"PRIVID" VARCHAR2(32), 
"CONFIGNOTE" VARCHAR2(1024), 
"REQUIREID" VARCHAR2(32), 
"CREATEDATE" DATE, 
"DEALDATE" DATE, 
"FINISHDATE" DATE, 
"STATUS" NUMBER(1,0), 
"RETMSG" VARCHAR2(512), 
"AUDIT_CHANGE_TIME" DATE
);

CREATE TABLE "INT_BILLING2BES" 
("OID" NUMBER(18,0), 
"DATA_TYPE" VARCHAR2(60), 
"OPER_TYPE" VARCHAR2(1), 
"DATA" VARCHAR2(800), 
"STATUS" NUMBER(1,0), 
"STATUS_DATE" DATE
) 
PARTITION BY RANGE ("STATUS_DATE") 
(
PARTITION "P201707"  VALUES LESS THAN (TO_DATE(' 2017-08-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , 
PARTITION "PMAX"  VALUES LESS THAN (TO_DATE(' 2050-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')));

CREATE TABLE "PRODUCT_DEF" 
("PRODUCT_TYPE" VARCHAR2(10), 
"PRODUCT_CODE" VARCHAR2(60), 
"PRODUCT_NAME" VARCHAR2(256), 
"NOTE" VARCHAR2(2000), 
"HISTORY" VARCHAR2(2000), 
"MERGE_MODE" NUMBER(1,0) DEFAULT 0, 
"TRIGGER_RENT" NUMBER(1,0) DEFAULT 0, 
"TRIGGER_PRESENT" NUMBER(1,0) DEFAULT 0, 
"CARRYOVER_FLAG" NUMBER(1,0) DEFAULT 0
);

CREATE SEQUENCE  "SEQ_BILLING2BES"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 32419 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "SUBJECT_DEF" 
("SUBJECTID" VARCHAR2(16), 
"SUBJECTNAME" VARCHAR2(64), 
"PERCENT_OF_REFUND" NUMBER(5,2), 
"CYCLES_OF_REFUND" NUMBER(4,0), 
"DRAW_ORDER" NUMBER(8,0), 
"OFFSET_SCOPE" VARCHAR2(1024), 
"AVAILABLE_CYCLE" NUMBER(10,0), 
"START_CYCLE" NUMBER(10,0), 
"IN_USE" NUMBER(1,0), 
"DRAW_AMT" NUMBER(14,0), 
"FLOWIN_TYPE" NUMBER(8,0), 
"SUBJECT_SIGN" VARCHAR2(8), 
"SUBJECT_TYPE" NUMBER(2,0) DEFAULT 1, 
"SUBJECTIDN" NUMBER(8,0), 
"MIN_DRAW_AMT" NUMBER(15,0) DEFAULT 0, 
"REF_TYPE" NUMBER(1,0) DEFAULT 0, 
"COMP_METHOD" NUMBER(1,0) DEFAULT 0, 
"BILLFEE_DRAW_AMT" NUMBER(14,0) DEFAULT 0, 
"BILLFEE_REF_TYPE" NUMBER(1,0) DEFAULT 0, 
"MAX_DRAW_AMT" NUMBER(15,0), 
"NOTE" VARCHAR2(200), 
"IS_CAL_SCORE" NUMBER(1,0) DEFAULT 0, 
"CYCLE_UNIT" NUMBER(1,0) DEFAULT 1, 
"IS_VIRTUAL_SUBJECT" NUMBER(1,0) DEFAULT 0, 
"WRTOFF_HIS_TYPE" NUMBER(2,0) DEFAULT 0, 
"EXLUDE_OFFSET_SCOPE" VARCHAR2(1024), 
"CANINVOICE" NUMBER(2,0) DEFAULT 0, 
"WRTOFFNEGATIVE" NUMBER(1,0) DEFAULT 0, 
"LIMITFORSUBSID" NUMBER(1,0) DEFAULT 1
);

CREATE TABLE "ACCTBUFDEF" 
("BUFID" NUMBER(8,0), 
"KEYID" NUMBER(10,0), 
"ACCTCOUNT" NUMBER(12,0), 
"CYCLECOUNT" NUMBER(4,0), 
"ITEMCYCLECOUNT" NUMBER(4,0), 
"SUBSCOUNT" NUMBER(12,0), 
"BILLCOUNT" NUMBER(15,0), 
"SUBJECTCOUNT" NUMBER(15,0), 
"FREELISTCOUNT" NUMBER(10,0), 
"NODEID" NUMBER(4,0), 
"HOSTNAME" VARCHAR2(128), 
"STATUS" NUMBER(1,0), 
"BILLITEMCOUNT" NUMBER(15,0) DEFAULT 0, 
"BILLCYCLE" NUMBER(10,0), 
"BILLINGBUFCOUNT" NUMBER(2,0) DEFAULT 20, 
"FOREWARDCYCLE" NUMBER(2,0) DEFAULT 0, 
"BACKWARDCYCLE" NUMBER(2,0) DEFAULT 0, 
"PORT" NUMBER(8,0)
);

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "ACCTITEM_DEF" 
("ITEMCODE" VARCHAR2(30), 
"ITEMNAME" VARCHAR2(64), 
"ITEMLEVEL" NUMBER(2,0), 
"PARENTITEMCODE" VARCHAR2(32), 
"WRTOFF_ORDER" NUMBER(2,0), 
"SERV_ID" VARCHAR2(12) DEFAULT '0', 
"SUBSERV_ID" VARCHAR2(12), 
"IN_USE" NUMBER(1,0), 
"ITEMCODEN" NUMBER(8,0), 
"FINANCEITEM_CODE" VARCHAR2(32), 
"IS_NEW_SERVICE" NUMBER(1,0) DEFAULT 1, 
"IS_CAL_SCORE" NUMBER(1,0) DEFAULT 1, 
"MONTH_FEE_PRECHARGE_COUNT" NUMBER(4,0) DEFAULT -1, 
"IN_PAUSE" NUMBER(1,0) DEFAULT 0, 
"PAUSE_TIME" DATE, 
"PAUSE_REASON" VARCHAR2(256), 
"ADD_REASON" VARCHAR2(256), 
"ODD_ROUND_TYPE" CHAR(1), 
"UNIT" NUMBER(2,0) DEFAULT 0
);

CREATE TABLE "ACCTWS_CLIENT_PWD" 
("SEQNO" NUMBER(6,0), 
"PASSWORD" VARCHAR2(128), 
"EFFECTIVE_DATE" DATE, 
"EXPIRE_DATE" DATE, 
"MODIFY_DATE" DATE DEFAULT SYSDATE
);

CREATE TABLE "AM_ACCT_ITEMPAYDEF" 
("OID" VARCHAR2(32), 
"ITEMCODE" VARCHAR2(32), 
"RECTYPE" VARCHAR2(32), 
"SUBJECTID" VARCHAR2(32), 
"INUSE" NUMBER(1,0)
);

CREATE TABLE "AM_ACCT_ITEMPAYDETAIL" 
("DEFOID" VARCHAR2(32), 
"DEDUCTORDER" NUMBER(2,0), 
"SUBJECTID" VARCHAR2(32), 
"INUSE" NUMBER(1,0)
);

CREATE TABLE "AM_ACCT_REBATE_ITEM" 
("REBATE_SCHEMA_ID" NUMBER(15,0), 
"BEGIN_SEQ" NUMBER(5,0), 
"END_SEQ" NUMBER(5,0), 
"SUBJECTID" VARCHAR2(32), 
"FEE" NUMBER(12,0), 
"MAXUSABLECYCLECOUNT" NUMBER(5,0), 
"STATUS" NUMBER(1,0), 
"PROLONG_TYPE" NUMBER(2,0), 
"PROLONG_DAYS" NUMBER(10,0), 
"RESTYPE" NUMBER(2,0), 
"POSTPONE_CHECK" NUMBER(1,0), 
"POSTPONE_CHECK_AMT" NUMBER(10,0), 
"RES_FLOWIN_TYPE" NUMBER(1,0), 
"RECSUBTYPE" VARCHAR2(32), 
"USABLECYCLETYPE" NUMBER(2,0), 
"SRC_SUBJECTID" VARCHAR2(32)
);

CREATE TABLE "AM_ACCT_REBATE_SCHEMA" 
("REBATE_SCHEMA_ID" NUMBER(15,0), 
"REBATE_SCHEMA_NAME" NVARCHAR2(128), 
"TOTALFEE" NUMBER(12,0), 
"DATAQUERYID" VARCHAR2(16), 
"DATAQUERYTYPE" NUMBER(2,0), 
"CYCLECOUNT" NUMBER(5,0), 
"OFFSETCYCLES" NUMBER(5,0), 
"OFFSETDAYS" NUMBER(2,0), 
"CYCLETYPE" VARCHAR2(3), 
"CREATE_DATE" DATE DEFAULT sysdate, 
"PRESENT_BEGIN_TYPE" NUMBER(3,0), 
"BEGIN_DATE" DATE, 
"REBATE_DAY" NUMBER(8,0), 
"CONDITION" VARCHAR2(128), 
"CONDITIONNAME" VARCHAR2(256), 
"BRANDID" VARCHAR2(16), 
"REBATE_REC_TYPE" VARCHAR2(16), 
"TRANS_CASH_AMT" NUMBER(10,0), 
"REBATE_DAY_TYPE" NUMBER(2,0), 
"OWNERLIMIT" NUMBER(1,0), 
"CANCEL_RULE_TYPE" NUMBER(3,0), 
"PRODID" VARCHAR2(32), 
"DES_SUBJECTID" VARCHAR2(16), 
"CONTRACT_AMT" NUMBER(10,0)
);

