CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;


CREATE TABLE "DATA_QUERY_PARAM_DEF" 
("QUERY_ID" NUMBER(9,0), 
"PARAM_INDEX" NUMBER(9,0), 
"PARAM_NAME" NVARCHAR2(160), 
"DATA_TYPE" NUMBER(1,0), 
"G_PARAM_VALUE" VARCHAR2(512), 
"VAR_NAME" VARCHAR2(30)
);

CREATE TABLE "DATA_QUERY_SET" 
("SET_ID" NUMBER(9,0), 
"INSTANCE_NAME" NVARCHAR2(160), 
"RESULT_EVENT_ID" NUMBER(9,0)
);

CREATE TABLE "DATA_QUERY_SET_ITEM" 
("SET_ID" NUMBER(9,0), 
"EXEC_INDEX" NUMBER(9,0), 
"INSTANCE_ID" NUMBER(9,0)
);

CREATE TABLE "DATA_ROUTE_HEAD" 
("BEGINNO" VARCHAR2(32), 
"ENDNO" VARCHAR2(32), 
"STARTTIME" DATE, 
"ENDTIME" DATE, 
"NBRTYPE" NUMBER(2,0) DEFAULT 0, 
"REGION" NUMBER(5,0), 
"DATA_NODEID" NUMBER(4,0), 
"DBTYPE" NUMBER(2,0)
);

CREATE TABLE "GLOBAL_CONFIG" 
("PARAM_NAME" VARCHAR2(128), 
"PARAM_VALUE" VARCHAR2(256), 
"NOTE" NVARCHAR2(128), 
"INC_APPSYSLIST" VARCHAR2(64), 
"EXC_APPSYSLIST" VARCHAR2(64), 
"MODULE_NAME" VARCHAR2(128) DEFAULT 'COMMON', 
"SCOPE_LEVEL" VARCHAR2(16) DEFAULT 'System', 
"SCOPE_VALUE" VARCHAR2(32)
);

CREATE TABLE "ENTITY_SYNC_QUEUE" 
("REGION" VARCHAR2(30), 
"CREATE_TIME" DATE, 
"TRANS_SN" VARCHAR2(60), 
"REFRESH_INDEX" NUMBER(18,0), 
"ENTITY_TABLE" VARCHAR2(100), 
"ENTITY_KEY" VARCHAR2(2000), 
"REFRESH_TYPE" CHAR(1), 
"SOURCE_TABLE" VARCHAR2(30), 
"SOURCE_KEY" VARCHAR2(2000), 
"PROCESS_FLAG" NUMBER(1,0) DEFAULT 0, 
"ROUTE_CUSTID" NUMBER(14,0), 
"PROCESS_TIME" DATE DEFAULT SYSDATE
);

CREATE SEQUENCE  "SEQ_REFRESH_INDEX"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 399963 CACHE 100 NOORDER  NOCYCLE ;

CREATE TABLE "DATA_SERVICE_CONFIG" 
("REGION" NUMBER(9,0) DEFAULT -1, 
"NODE_ID" NUMBER(4,0) DEFAULT -1, 
"APP_NAME" VARCHAR2(32) DEFAULT 'ALL', 
"MAINDB" VARCHAR2(64) DEFAULT 'ALL', 
"DESTDB" VARCHAR2(64), 
"DAL_SERVER_NAME" VARCHAR2(64), 
"PRIORITY" NUMBER(4,0) DEFAULT 0, 
"ACCESS_TYPE" NUMBER(1,0) DEFAULT 0, 
"GROUP_CODE" VARCHAR2(50)
);

CREATE TABLE "DATA_SERVICE_DEF" 
("DB_SERVER_NAME" VARCHAR2(64), 
"DAL_SERVER_NAME" VARCHAR2(64), 
"IP" VARCHAR2(64), 
"PORT" NUMBER(5,0), 
"PROTOCOL" NUMBER(1,0) DEFAULT 0, 
"IPC_KEY" NUMBER(10,0), 
"FETCHER_COUNT" NUMBER(5,0), 
"DISPATCHER_COUNT" NUMBER(5,0), 
"MAX_FETCHER_COUNT" NUMBER(5,0), 
"MAX_DISPATCHER_COUNT" NUMBER(5,0), 
"LOG_DIR" VARCHAR2(64), 
"SOCK_DIR" VARCHAR2(64), 
"LOW_WL" NUMBER(3,0) DEFAULT 0, 
"HIGHT_WL" NUMBER(3,0) DEFAULT 100, 
"TRANS_TMO" NUMBER(10,0) DEFAULT 600, 
"REFRESH_TMO" NUMBER(10,0) DEFAULT 10, 
"CONNECT_TMO" NUMBER(10,0) DEFAULT 60000, 
"SEND_TMO" NUMBER(10,0) DEFAULT 10000, 
"RECV_TMO" NUMBER(10,0) DEFAULT 60000, 
"LOCK_TMO" NUMBER(10,0) DEFAULT 10000, 
"DEAD_DETECT_TMO" NUMBER(10,0) DEFAULT 600, 
"QRY_RECORD_LIMIT" NUMBER(10,0) DEFAULT 4194304, 
"COMPRESS_FLAG" NUMBER(1,0) DEFAULT 1, 
"COMPRESS_LIMIT" NUMBER(10,0) DEFAULT 409600, 
"BYTE_ORDER" VARCHAR2(1) DEFAULT 'B', 
"CONCURRENCE_COUNT" NUMBER(5,0) DEFAULT 10, 
"DISP_CON_CNT" NUMBER(5,0) DEFAULT 10, 
"GROUP_CODE" VARCHAR2(50)
);

CREATE TABLE "DATA_SYNC_DEF" 
("SYNC_TYPE" NUMBER(2,0), 
"SYNC_NAME" VARCHAR2(65), 
"KEY_BEGIN" NUMBER(3,0) DEFAULT 0, 
"KEY_END_POS" NUMBER(3,0), 
"QUERY_SQL" VARCHAR2(1024), 
"UPDATE_SQL" VARCHAR2(1024), 
"INSERT_SQL" VARCHAR2(2048), 
"DELETE_SQL" VARCHAR2(1024)
);

CREATE TABLE "DATA_SYNC_MAPPING_DEF" 
("SYNC_TYPE" NUMBER(2,0), 
"EVENT_ID" NUMBER(4,0), 
"EVENT_ATTR_ID" NUMBER(4,0) DEFAULT 0, 
"MATCH_VALUE" VARCHAR2(64)
);

CREATE TABLE "DATABASE_CONFIG" 
("REGION" NUMBER(9,0), 
"NODE_ID" NUMBER(4,0), 
"DBTYPE" NUMBER(2,0), 
"MODULE_NAME" VARCHAR2(20), 
"DATA_NODEID" NUMBER(4,0), 
"SERVER_NAME" VARCHAR2(20), 
"PRIORITY" NUMBER(4,0), 
"RECTYPE" VARCHAR2(32) DEFAULT 'ALL', 
"CENTRE_SEQ" NUMBER(2,0) DEFAULT -1
);

CREATE TABLE "DATAFILE" 
("DATASOURCEID" NUMBER(3,0), 
"TASKNO" NUMBER(3,0), 
"PATHNAME" VARCHAR2(100), 
"BACKUPPATH" VARCHAR2(100), 
"ERRORCDRPATH" VARCHAR2(100), 
"VERSION" NUMBER(5,2), 
"DEVICEIDINFILE" CHAR(1), 
"DEVICEID" VARCHAR2(30), 
"FILENAMEPREFIX" VARCHAR2(30), 
"SELECTOR" CHAR(1), 
"SORT" CHAR(1), 
"BATCHTYPE" NUMBER(1,0), 
"BATCHSIZE" NUMBER(8,0), 
"PICKSOURCEID" NUMBER(8,0)
);

CREATE TABLE "DATAITEM" 
("DATASOURCEID" NUMBER(3,0), 
"UNIQUENO" NUMBER(5,0), 
"ITEMCODE" VARCHAR2(7), 
"TAGCODE" VARCHAR2(7), 
"MINVERSION" NUMBER(5,2) DEFAULT 0, 
"MAXVERSION" NUMBER(5,2) DEFAULT 0, 
"NAME" VARCHAR2(100), 
"ITEMTYPE" CHAR(1), 
"LENGTHTAG" CHAR(1), 
"TAGLENGTHTYPE" CHAR(1), 
"TAGDATATYPE" CHAR(1), 
"TAGTOTALLENGTH" NUMBER(5,0) DEFAULT 0, 
"MINUSTAGLENGTH" NUMBER(1,0) DEFAULT 0, 
"SEPERATOR" VARCHAR2(6), 
"ITEMTOTALLENGTH" NUMBER(6,0) DEFAULT 0, 
"PREFIX" CHAR(1), 
"SUFFIX" CHAR(1), 
"DATATYPE" CHAR(1), 
"SWAP" CHAR(1), 
"DESTATTRID" NUMBER(5,0) DEFAULT -1, 
"CHARGEEVENTID" NUMBER(4,0), 
"TODATATYPE" CHAR(1), 
"EXTRACTALL" CHAR(1) DEFAULT '0', 
"TAGEXTRACTALL" CHAR(1) DEFAULT '0', 
"DESTATTR_SETMODE" CHAR(1) DEFAULT 'r', 
"DESTATTR_LENGTH" NUMBER(3,0) DEFAULT 0, 
"DEST_TYPE" NUMBER(1,0) DEFAULT ('1'), 
"DEST_ATTR_PATH" VARCHAR2(64), 
"G_DEST_ATTR_PATH" VARCHAR2(512)
);

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');

