CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;



CREATE TABLE "PROCESS_FLOW" 
("PROCESS_STEP_ID" NUMBER(5,0), 
"PROCESS_STEP_NAME" VARCHAR2(50), 
"PROCESS_ORDER" NUMBER(4,0), 
"RULE_COND" VARCHAR2(256), 
"IF_RULE_TYPE" NUMBER(1,0), 
"IF_RULE_ID" NUMBER(5,0), 
"ELSE_RULE_TYPE" NUMBER(1,0), 
"ELSE_RULE_ID" NUMBER(5,0), 
"APPLYTIME" DATE, 
"EXPIRETIME" DATE, 
"SEQUENCENO" NUMBER(5,0), 
"G_RULE_COND" VARCHAR2(512), 
"SOUR_EVENT_ID" NUMBER(5,0), 
"DEST_EVENT_ID" NUMBER(5,0), 
"IF_RULE_NAME" VARCHAR2(100), 
"ELSE_RULE_NAME" VARCHAR2(100)
);

CREATE TABLE "PROCESS_SCHEMA" 
("PROC_SCHEMA_ID" NUMBER(5,0), 
"PROC_SCHEMA_NAME" VARCHAR2(64)
);

CREATE TABLE "PROCESSED_EVENT" 
("PROC_SCHEMA_ID" NUMBER(5,0), 
"SOURCE_EVENT_ID" NUMBER(4,0), 
"DEST_EVENT_ID" NUMBER(4,0), 
"START_STEP_ID" NUMBER(5,0), 
"PROCESS_COND" VARCHAR2(512), 
"G_PROCESS_COND" VARCHAR2(512), 
"PREPROCESS_NAME" VARCHAR2(50), 
"PROCESS_ORDER" NUMBER(4,0) DEFAULT 0
);

CREATE TABLE "PRODUCT_ATTR" 
("PRODUCT_TYPE" VARCHAR2(10), 
"PRODUCT_CODE" VARCHAR2(60), 
"ATTR_CODE" VARCHAR2(30), 
"ATTR_VALUE" VARCHAR2(50)
);

CREATE TABLE "PRODUCT_DEF" 
("PRODUCT_TYPE" VARCHAR2(10), 
"PRODUCT_CODE" VARCHAR2(60), 
"PRODUCT_NAME" VARCHAR2(256), 
"NOTE" VARCHAR2(2000), 
"HISTORY" VARCHAR2(2000), 
"MERGE_MODE" NUMBER(1,0) DEFAULT 0, 
"TRIGGER_RENT" NUMBER(1,0) DEFAULT 0, 
"TRIGGER_PRESENT" NUMBER(1,0) DEFAULT 0, 
"CARRYOVER_FLAG" NUMBER(1,0) DEFAULT 0
);


CREATE TABLE "PRODUCT_ELEMENT" 
("PRODUCT_ELEMENT_TYPE" VARCHAR2(10), 
"PRODUCT_ELEMENT_CODE" VARCHAR2(60), 
"PRODUCT_ELEMENT_NAME" VARCHAR2(256), 
"NOTE" VARCHAR2(2000), 
"HISTORY" VARCHAR2(2000), 
"TRIGGER_RENT" NUMBER(1,0) DEFAULT 0, 
"MERGE_MODE" NUMBER(1,0) DEFAULT 0
);

CREATE TABLE "GLOBAL_CONFIG" 
("PARAM_NAME" VARCHAR2(128), 
"PARAM_VALUE" VARCHAR2(256), 
"NOTE" NVARCHAR2(128), 
"INC_APPSYSLIST" VARCHAR2(64), 
"EXC_APPSYSLIST" VARCHAR2(64), 
"MODULE_NAME" VARCHAR2(128) DEFAULT 'COMMON', 
"SCOPE_LEVEL" VARCHAR2(16) DEFAULT 'System', 
"SCOPE_VALUE" VARCHAR2(32)
);

CREATE TABLE "ENTITY_SYNC_QUEUE" 
("REGION" VARCHAR2(30), 
"CREATE_TIME" DATE, 
"TRANS_SN" VARCHAR2(60), 
"REFRESH_INDEX" NUMBER(18,0), 
"ENTITY_TABLE" VARCHAR2(100), 
"ENTITY_KEY" VARCHAR2(2000), 
"REFRESH_TYPE" CHAR(1), 
"SOURCE_TABLE" VARCHAR2(30), 
"SOURCE_KEY" VARCHAR2(2000), 
"PROCESS_FLAG" NUMBER(1,0) DEFAULT 0, 
"ROUTE_CUSTID" NUMBER(14,0), 
"PROCESS_TIME" DATE DEFAULT SYSDATE
);

CREATE SEQUENCE  "SEQ_REFRESH_INDEX"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 399963 CACHE 100 NOORDER  NOCYCLE ;

CREATE TABLE "PRODUCT_SERVICE_ATTR" 
("PRODUCT_TYPE" VARCHAR2(10), 
"PRODUCT_CODE" VARCHAR2(60), 
"SERVICE_PLAN_TYPE" VARCHAR2(60), 
"SERVICE_PLAN_ID" NUMBER(6,0), 
"ATTR_CODE" VARCHAR2(60), 
"ATTR_VALUE" VARCHAR2(100), 
"ATTR_NAME" VARCHAR2(200)
);

CREATE TABLE "PRODUCT_SERVICE_PLAN" 
("PRODUCT_TYPE" VARCHAR2(10), 
"PRODUCT_CODE" VARCHAR2(60), 
"SERVICE_PLAN_TYPE" VARCHAR2(20), 
"SERVICE_PLAN_ID" NUMBER(6,0), 
"SHARE_SERVICE" VARCHAR2(10), 
"START_CYCLE" NUMBER(6,0) DEFAULT 200000, 
"END_CYCLE" NUMBER(6,0) DEFAULT 999999
);

CREATE TABLE "PRODUCT_TEMPLATE_ATTR_DEF" 
("ID" NUMBER(4,0), 
"BUSINESS" VARCHAR2(60), 
"SEQUENCE" NUMBER(4,0), 
"BUSINESS_VALUE" VARCHAR2(60), 
"ATTR_CODE" VARCHAR2(100), 
"ATTR_VALUE" VARCHAR2(512), 
"ATTR_CATALOG" VARCHAR2(60), 
"NOTE" VARCHAR2(200), 
"START_TIME" DATE, 
"END_TIME" DATE
);

CREATE TABLE "PRODUCT_UNLIMITED_INFO" 
("PRODUCT_TYPE" VARCHAR2(2) DEFAULT 'T', 
"PRODUCT_ID" VARCHAR2(32), 
"OWNER_ENTITY_TYPE" NUMBER(1,0), 
"USAGE_TYPE" VARCHAR2(4), 
"FREE_TIME" NUMBER(1,0) DEFAULT 0, 
"SERVICE_CODE" VARCHAR2(256), 
"LAC_CELL_ENTITY_TYPE" NUMBER(1,0) DEFAULT -1, 
"LAC_CELL_ENTITY_ATTR_ID" VARCHAR2(8), 
"AREA_CODE" VARCHAR2(32)
);

CREATE TABLE "PRODUCT_USAGE_ATTR" 
("PRODUCT_TYPE" VARCHAR2(10), 
"PRODUCT_CODE" VARCHAR2(60), 
"ENTITY_ID" NUMBER(18,0), 
"ATTR_ID" NUMBER(8,0), 
"SHARE_SERVICE" VARCHAR2(10), 
"LIMIT_TYPE" CHAR(1), 
"LIMIT_VALUE" NUMBER(10,0), 
"NOTE" VARCHAR2(100), 
"STDFREE_EXPR" VARCHAR2(64), 
"G_STDFREE_EXPR" VARCHAR2(128), 
"USAGE_CLASS" VARCHAR2(4), 
"USAGE_SUBCLASS" VARCHAR2(4), 
"USAGE_PRECEDENCE" NUMBER(4,0) DEFAULT 0, 
"USAGE_TYPE" NUMBER(1,0) DEFAULT 9
);

CREATE TABLE "PROG_LICENSE_DEF" 
("NODEID" NUMBER(2,0), 
"PROGNAME" VARCHAR2(64), 
"LICENSETYPE" VARCHAR2(64), 
"APPLYCODE" VARCHAR2(128), 
"AUTHCODE" VARCHAR2(256), 
"LICENSEVALUE" NUMBER(8,0)
);

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');

