CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;



CREATE TABLE "REPORT_STAT_DEF" 
("REPORT_VIEW_ID" NUMBER(4,0), 
"ELEMENT_TYPE" NUMBER(1,0), 
"SEQUENCENO" NUMBER(4,0), 
"PRECEDENCE" NUMBER(3,0), 
"CHARGING_EVENT_ID" NUMBER(4,0), 
"ELEMENT_DEF" VARCHAR2(1024), 
"DEF_TYPE" NUMBER(1,0), 
"STAT_COND" VARCHAR2(1024), 
"STATUS" NUMBER(1,0), 
"G_ELEMENT_DEF" VARCHAR2(1024), 
"G_STAT_COND" VARCHAR2(1024), 
"PARTIAL_FLAG" NUMBER(1,0) DEFAULT 0, 
"START_POS" NUMBER(4,0) DEFAULT 0, 
"LENGTH" NUMBER(4,0) DEFAULT 0
);

CREATE TABLE "REPORT_STORAGE_DEF" 
("REPORT_STORAGE_ID" NUMBER(4,0), 
"REPORT_STORAGE_NAME" VARCHAR2(64), 
"TABLE_NAME" VARCHAR2(64), 
"INDEX_NAME" VARCHAR2(64), 
"TABLE_STORAGE_ATTR" VARCHAR2(128), 
"INDEX_STORAGE_ATTR" VARCHAR2(128), 
"PARTITION_KEY" NUMBER(2,0), 
"STATUS" NUMBER(1,0), 
"CHARGING_EVENT_ID" NUMBER(4,0)
);

CREATE TABLE "REPORT_VIEW" 
("REPORT_VIEW_ID" NUMBER(4,0), 
"REPORT_VIEW_NAME" VARCHAR2(64), 
"REPORT_STORAGE_ID" NUMBER(4,0), 
"STATUS" NUMBER(1,0), 
"CHARGE_EVENT_ID" NUMBER(4,0) DEFAULT 0
);

CREATE TABLE "REPORT_VIEW_FILTER" 
("REPORT_VIEW_ID" NUMBER(4,0), 
"CHARGING_EVENT_ID" NUMBER(4,0), 
"FILTER_COND" VARCHAR2(256), 
"G_FILTER_COND" VARCHAR2(256)
);

CREATE TABLE "RERATING_TASK" 
("TASKID" NUMBER(8,0), 
"TASKNAME" VARCHAR2(32), 
"TYPEID" NUMBER(6,0), 
"BILLCYCLE" NUMBER(8,0), 
"TASK_WHERE" VARCHAR2(512), 
"PLANTIME" DATE DEFAULT Sysdate + 1/48, 
"TASKCOUNT" NUMBER(3,0) DEFAULT 1, 
"BATCHUSER" NUMBER(3,0) DEFAULT 10, 
"TESTROWS" NUMBER(2,0) DEFAULT 5, 
"ISTEST" NUMBER(1,0) DEFAULT 0, 
"WHERETYPE" NUMBER(1,0) DEFAULT 0, 
"STATUS" NUMBER(1,0) DEFAULT 0, 
"UPTIME" DATE DEFAULT sysdate, 
"OPERATOR" VARCHAR2(32), 
"STATUSTIME" DATE DEFAULT sysdate
);

CREATE TABLE "ROLE_LIST" 
("ROLE_ID" NUMBER(4,0), 
"ROLE_NAME" VARCHAR2(256), 
"CREATEDATE" DATE, 
"PREDEF_TYPE" NUMBER(1,0)
);

CREATE TABLE "ROLE_PRIV_LIST" 
("ROLE_NAME" VARCHAR2(256), 
"RESOURCE_TYPE" NUMBER(1,0) DEFAULT 0, 
"RESOURCE_ID" NUMBER(4,0), 
"PRIV_SET" NUMBER(4,0)
);

CREATE TABLE "RTCC_CLIENT_DEF" 
("MMQ_DEVID" NUMBER(8,0), 
"IPADDR" VARCHAR2(30), 
"PORT" NUMBER(8,0), 
"SENDQ" VARCHAR2(30), 
"RECVQ" VARCHAR2(30), 
"DISPQ" VARCHAR2(30), 
"TRACEQ" VARCHAR2(30), 
"DEVICE_ID" VARCHAR2(30), 
"DEVICE_VERSION" NUMBER(5,2)
);

CREATE TABLE "SAFETY_STRATEGY" 
("INVALID_CYCLE" NUMBER(4,0) DEFAULT 0, 
"PWDHIS_LIMIT" NUMBER(4,0) DEFAULT 0, 
"COMPOSE_LIMIT" VARCHAR2(10), 
"FAILCOUNT_LIMIT" NUMBER(4,0) DEFAULT 0, 
"PWDLEN_LIMIT" NUMBER(4,0) DEFAULT 6, 
"PWDLEN_MAX" NUMBER(4,0) DEFAULT 32, 
"PWDDUP_MAX" NUMBER(4,0) DEFAULT 3, 
"INVALID_LIMIT" NUMBER(4,0) DEFAULT 5, 
"PWDVLD_PROMPT" NUMBER(4,0) DEFAULT 7, 
"LOGONLOCKDUR" NUMBER(4,0) DEFAULT 30, 
"WAITLOCKDUR" NUMBER(4,0) DEFAULT 10, 
"WRONGLOCKDUR" NUMBER(4,0) DEFAULT 30, 
"LOGONAFTERDAYS" NUMBER(4,0) DEFAULT 90, 
"LAST_CALL_ET" NUMBER(5,0) DEFAULT 60, 
"IFCHECKUNIQUEID" NUMBER(1,0) DEFAULT 1, 
"ADM_PWDLEN_LIMIT" NUMBER(4,0) DEFAULT 8, 
"DIFCHARACTER_COUNT" NUMBER(2,0) DEFAULT 2, 
"RELOGONDUR" NUMBER(4,0) DEFAULT 0
);

CREATE TABLE "SEP_RULE_PROCESS" 
("RULEID" NUMBER(8,0), 
"ACTION" NUMBER(8,0), 
"SOUREVENT" NUMBER(8,0), 
"DESTEVENT" NUMBER(8,0), 
"PARAM" VARCHAR2(60), 
"APPLYTIME" DATE, 
"EXPIRETIME" DATE, 
"PRIORITY" NUMBER(8,0), 
"ASSOCIATE" NUMBER(8,0), 
"NOTE" VARCHAR2(2048)
);

CREATE TABLE "SEP_TASK" 
("TASKNO" NUMBER(3,0), 
"NAME" VARCHAR2(100), 
"RAWBUFFER" NUMBER(6,0), 
"BUFFER1" NUMBER(6,0), 
"BUFFER2" NUMBER(6,0), 
"DATABUFFER" NUMBER(8,0), 
"ADJUST_RAWBUFFER" NUMBER(8,0) DEFAULT 0, 
"PROCESSTYPE" NUMBER(2,0) DEFAULT 0, 
"FILELIST_READ_MODE" NUMBER(1,0) DEFAULT 0, 
"SERVER_NAME" VARCHAR2(50)
);

CREATE TABLE "SERVICE_CLASS_DEF" 
("SERVICE_CLASS_ID" VARCHAR2(60), 
"SERVICE_CLASS_NAME" VARCHAR2(120), 
"SERVICE_TYPE" NUMBER(1,0)
);

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');

CREATE TABLE "RERATING_TYPE" 
("TYPEID" NUMBER(6,0), 
"TYPENAME" VARCHAR2(32), 
"EVENTID" NUMBER(4,0), 
"CDRTABLE" VARCHAR2(32), 
"DBLINKNAME" VARCHAR2(32), 
"FIELDNAME" VARCHAR2(64), 
"UNDUP_MODULE" NUMBER(4,0) DEFAULT 0, 
"CHECK_DUP" NUMBER(1,0) DEFAULT 0, 
"ROLLBACK_FROM" NUMBER(4,0) DEFAULT 50, 
"CLEAR_CYCLE" NUMBER(1,0) DEFAULT 0, 
"FLOW_MODULE" NUMBER(4,0), 
"STAT_MODULE" NUMBER(4,0) DEFAULT 0, 
"CHARGING_MODULE" NUMBER(4,0), 
"FIELD_PREFIX" VARCHAR2(127), 
"FORMAT_PROC" NUMBER(4,0), 
"COPYATTRFLAG" NUMBER(1,0), 
"RERATING_WHERE" VARCHAR2(512), 
"INUSE" NUMBER(1,0) DEFAULT 1
);
