CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');


CREATE TABLE "ACCTBUFDEF" 
("BUFID" NUMBER(8,0), 
"KEYID" NUMBER(10,0), 
"ACCTCOUNT" NUMBER(12,0), 
"CYCLECOUNT" NUMBER(4,0), 
"ITEMCYCLECOUNT" NUMBER(4,0), 
"SUBSCOUNT" NUMBER(12,0), 
"BILLCOUNT" NUMBER(15,0), 
"SUBJECTCOUNT" NUMBER(15,0), 
"FREELISTCOUNT" NUMBER(10,0), 
"NODEID" NUMBER(4,0), 
"HOSTNAME" VARCHAR2(128), 
"STATUS" NUMBER(1,0), 
"BILLITEMCOUNT" NUMBER(15,0) DEFAULT 0, 
"BILLCYCLE" NUMBER(10,0), 
"BILLINGBUFCOUNT" NUMBER(2,0) DEFAULT 20, 
"FOREWARDCYCLE" NUMBER(2,0) DEFAULT 0, 
"BACKWARDCYCLE" NUMBER(2,0) DEFAULT 0, 
"PORT" NUMBER(8,0)
);

CREATE TABLE "ACCTITEM_DEF" 
("ITEMCODE" VARCHAR2(30), 
"ITEMNAME" VARCHAR2(64), 
"ITEMLEVEL" NUMBER(2,0), 
"PARENTITEMCODE" VARCHAR2(32), 
"WRTOFF_ORDER" NUMBER(2,0), 
"SERV_ID" VARCHAR2(12) DEFAULT '0', 
"SUBSERV_ID" VARCHAR2(12), 
"IN_USE" NUMBER(1,0), 
"ITEMCODEN" NUMBER(8,0), 
"FINANCEITEM_CODE" VARCHAR2(32), 
"IS_NEW_SERVICE" NUMBER(1,0) DEFAULT 1, 
"IS_CAL_SCORE" NUMBER(1,0) DEFAULT 1, 
"MONTH_FEE_PRECHARGE_COUNT" NUMBER(4,0) DEFAULT -1, 
"IN_PAUSE" NUMBER(1,0) DEFAULT 0, 
"PAUSE_TIME" DATE, 
"PAUSE_REASON" VARCHAR2(256), 
"ADD_REASON" VARCHAR2(256), 
"ODD_ROUND_TYPE" CHAR(1), 
"UNIT" NUMBER(2,0) DEFAULT 0
);

CREATE TABLE "ACCTWS_CLIENT_PWD" 
("SEQNO" NUMBER(6,0), 
"PASSWORD" VARCHAR2(128), 
"EFFECTIVE_DATE" DATE, 
"EXPIRE_DATE" DATE, 
"MODIFY_DATE" DATE DEFAULT SYSDATE
);

CREATE TABLE "AM_ACCT_INOUTMODEBOOK" 
("RECTYPE" VARCHAR2(32), 
"ACCESSTYPE" VARCHAR2(32), 
"PAYTYPE" VARCHAR2(32), 
"INOUTMODE" VARCHAR2(128)
);

CREATE TABLE "AM_ACCT_ITEM" 
("ACCT_TYPE" NUMBER(2,0), 
"ACCT_ITEM" NUMBER(2,0), 
"FLOW_TYPE" NUMBER(2,0) DEFAULT 0, 
"NOTE" VARCHAR2(64)
);

CREATE TABLE "AM_ACCT_ITEMPAYDEF" 
("OID" VARCHAR2(32), 
"ITEMCODE" VARCHAR2(32), 
"RECTYPE" VARCHAR2(32), 
"SUBJECTID" VARCHAR2(32), 
"INUSE" NUMBER(1,0)
);

CREATE TABLE "AM_ACCT_ITEMPAYDETAIL" 
("DEFOID" VARCHAR2(32), 
"DEDUCTORDER" NUMBER(2,0), 
"SUBJECTID" VARCHAR2(32), 
"INUSE" NUMBER(1,0)
);

CREATE TABLE "AM_ACCT_REBATE_ITEM" 
("REBATE_SCHEMA_ID" NUMBER(15,0), 
"BEGIN_SEQ" NUMBER(5,0), 
"END_SEQ" NUMBER(5,0), 
"SUBJECTID" VARCHAR2(32), 
"FEE" NUMBER(12,0), 
"MAXUSABLECYCLECOUNT" NUMBER(5,0), 
"STATUS" NUMBER(1,0), 
"PROLONG_TYPE" NUMBER(2,0), 
"PROLONG_DAYS" NUMBER(10,0), 
"RESTYPE" NUMBER(2,0), 
"POSTPONE_CHECK" NUMBER(1,0), 
"POSTPONE_CHECK_AMT" NUMBER(10,0), 
"RES_FLOWIN_TYPE" NUMBER(1,0), 
"RECSUBTYPE" VARCHAR2(32), 
"USABLECYCLETYPE" NUMBER(2,0), 
"SRC_SUBJECTID" VARCHAR2(32)
);

CREATE TABLE "AM_ACCT_REBATE_SCHEMA" 
("REBATE_SCHEMA_ID" NUMBER(15,0), 
"REBATE_SCHEMA_NAME" NVARCHAR2(128), 
"TOTALFEE" NUMBER(12,0), 
"DATAQUERYID" VARCHAR2(16), 
"DATAQUERYTYPE" NUMBER(2,0), 
"CYCLECOUNT" NUMBER(5,0), 
"OFFSETCYCLES" NUMBER(5,0), 
"OFFSETDAYS" NUMBER(2,0), 
"CYCLETYPE" VARCHAR2(3), 
"CREATE_DATE" DATE DEFAULT sysdate, 
"PRESENT_BEGIN_TYPE" NUMBER(3,0), 
"BEGIN_DATE" DATE, 
"REBATE_DAY" NUMBER(8,0), 
"CONDITION" VARCHAR2(128), 
"CONDITIONNAME" VARCHAR2(256), 
"BRANDID" VARCHAR2(16), 
"REBATE_REC_TYPE" VARCHAR2(16), 
"TRANS_CASH_AMT" NUMBER(10,0), 
"REBATE_DAY_TYPE" NUMBER(2,0), 
"OWNERLIMIT" NUMBER(1,0), 
"CANCEL_RULE_TYPE" NUMBER(3,0), 
"PRODID" VARCHAR2(32), 
"DES_SUBJECTID" VARCHAR2(16), 
"CONTRACT_AMT" NUMBER(10,0)
);

CREATE TABLE "BILLING_CYCLE_CONTROL" 
("REGION" NUMBER(5,0), 
"CYCLEID" NUMBER(8,0), 
"MODIFYTIME" DATE DEFAULT sysdate, 
"OPENDAY" NUMBER(2,0) DEFAULT 0, 
"OFFSET_SECOND" NUMBER(6,0) DEFAULT 0
);

CREATE TABLE "BILLING_DEF" 
("EVENT_ID" NUMBER(8,0), 
"BILLING_COND" VARCHAR2(512), 
"EXPR_TYPE" NUMBER(1,0), 
"ITEM_EXPR" VARCHAR2(128), 
"ITEMCODE" VARCHAR2(32), 
"ITEMTYPE" NUMBER(2,0), 
"ITEMADD_TYPE" NUMBER(1,0), 
"ITEMADD_EXPR" VARCHAR2(128), 
"START_CYCLE" NUMBER(8,0), 
"END_CYCLE" NUMBER(8,0), 
"TEMPITEM_FLAG" NUMBER(1,0), 
"ITEM_UNIT" NUMBER(2,0), 
"PAYPLAN_FLAG" NUMBER(1,0), 
"G_BILLING_COND" VARCHAR2(1024), 
"G_ITEMADD_EXPR" VARCHAR2(128), 
"G_ITEM_EXPR" VARCHAR2(1024), 
"RULEID" NUMBER(4,0) DEFAULT 1, 
"NEXTRULEID" NUMBER(4,0) DEFAULT 0, 
"PROCSCHEMAID" NUMBER(5,0) DEFAULT 0, 
"PROCEVENTID" NUMBER(4,0) DEFAULT 0, 
"RULENAME" VARCHAR2(32), 
"FEE_ID" NUMBER(9,0), 
"SPLITTYPE" NUMBER(1,0) DEFAULT 0, 
"UNIQUE_ID" NUMBER(10,0), 
"ROUNDTYPE" NUMBER(1,0) DEFAULT 0, 
"SHOW_ZERO_FEE_FLAG" NUMBER(1,0) DEFAULT 0
);

CREATE SEQUENCE  "SEQ_BILLING_DEF_UNIQUEID"  MINVALUE 0 MAXVALUE 999999999 INCREMENT BY 1 START WITH 3121 CACHE 20 ORDER  NOCYCLE ;

CREATE TABLE "BILLINGCYCLE" 
("CYCLE_SCHEMA_ID" NUMBER(4,0), 
"CYCLE_ID" NUMBER(8,0), 
"CYCLE_NAME" VARCHAR2(64), 
"CYCLE_STATUS" NUMBER(1,0), 
"OPENDATE" DATE, 
"CLOSEDATE" DATE, 
"INVOICEDATE" DATE
);

CREATE TABLE "BILLINGCYCLE_SCHEMA" 
("CYCLE_SCHEMA_ID" NUMBER(4,0), 
"CYCLE_SCHEMA_NAME" VARCHAR2(64), 
"CYCLE_UNIT" NUMBER(1,0), 
"UNIT_COUNT" NUMBER(4,0), 
"OPENDATE" VARCHAR2(32), 
"INVOICE_DELAY" NUMBER(4,0), 
"PREBUILT_CYCLES" NUMBER(4,0), 
"FIRSTCYCLE_OPENDATE" VARCHAR2(32), 
"STATUS" NUMBER(1,0), 
"MULTIACTIVATION" NUMBER(1,0), 
"FIXED_CYCLE" NUMBER(1,0), 
"CYCLEID_BASE" NUMBER(1,0) DEFAULT 1
);

