CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;



CREATE TABLE "FILENAME_ITEM" 
("MODULEID" NUMBER(8,0), 
"PERIODICTYPE" NUMBER(4,0), 
"PERIODICPARAM" VARCHAR2(64), 
"TIMEOFFSET" NUMBER(10,0), 
"TIMES" NUMBER(10,0), 
"GENFROM" NUMBER(10,0), 
"GENTO" NUMBER(10,0), 
"FILENAMEPROCID" NUMBER(10,0), 
"INITSEQ" NUMBER(10,0), 
"MAXSEQ" NUMBER(10,0), 
"BACKWARD" NUMBER(4,0), 
"TMPPATH" VARCHAR2(128), 
"DESTPATH" VARCHAR2(128), 
"EMPTYTYPE" NUMBER(4,0), 
"EVENTID" NUMBER(4,0)
);

CREATE TABLE "FILERULE" 
("FILEID" NUMBER(5,0), 
"RELATEORDER" NUMBER(3,0), 
"SOUREVENTTYPE" NUMBER(3,0), 
"DESTEVENTTYPE" NUMBER(3,0), 
"SCHEMAID" NUMBER(5,0), 
"PROCMETHOD" NUMBER(3,0), 
"PROCCOUNT" NUMBER(7,0), 
"PROCORDER" NUMBER(3,0), 
"NOTE" VARCHAR2(100)
);

CREATE TABLE "FILESTRUCT" 
("FILEID" NUMBER(5,0), 
"EVENTTYPE" NUMBER(2,0), 
"EVENTID" NUMBER(5,0), 
"INITCOUNT" NUMBER(5,0), 
"ADDCOUNT" NUMBER(5,0), 
"INITORDER" NUMBER(3,0), 
"NODE" VARCHAR2(100)
);

CREATE TABLE "FINANCEITEM_DEF" 
("ITEMCODE" VARCHAR2(32), 
"ITEMNAME" VARCHAR2(128), 
"DICTID" VARCHAR2(32), 
"STATUS" CHAR(1), 
"SORT" NUMBER(10,0)
);

CREATE TABLE "FREE_USAGE_ATTR_DEF" 
("ENTITY_ID" NUMBER(4,0), 
"ATTR_ID" NUMBER(8,0), 
"FIXED_FREE_USAGE" NUMBER(15,0), 
"FREE_LIMIT" NUMBER(15,0), 
"FREE_TYPE" NUMBER(1,0), 
"FREE_USE_MODE" NUMBER(1,0) DEFAULT 1, 
"PRECENDENCE_SCHEME" NUMBER(5,0) DEFAULT 0
);

CREATE TABLE "GCPS_PARAM_VALUE" 
("PARAM_ID" VARCHAR2(60), 
"PARAM_NAME" VARCHAR2(60), 
"PARAM_VALUE" VARCHAR2(256)
);

CREATE TABLE "GENERAL_ACCOUNT_PLAN" 
("RECTYPE" VARCHAR2(50), 
"PLAN_ID" NUMBER(5,0), 
"NOTE" VARCHAR2(512)
);

CREATE TABLE "GENERAL_ACCOUNT_PLAN_ITEM" 
("PLAN_ID" NUMBER(5,0), 
"SEQUENCE" NUMBER(5,0), 
"FLOW_DIRECTION" CHAR(1), 
"SUBJECT_ID" VARCHAR2(32), 
"ITEM_CODE" VARCHAR2(32)
);

CREATE TABLE "GENERAL_SERVICE_CONFIG" 
("REGION" NUMBER(9,0) DEFAULT -1, 
"SERVER_NAME" VARCHAR2(64), 
"GROUP_CODE" VARCHAR2(50), 
"GROUP_TYPE" VARCHAR2(50), 
"CENTRE_SEQ" NUMBER(2,0) DEFAULT -1
);

CREATE TABLE "GLOBAL_CONFIG" 
("PARAM_NAME" VARCHAR2(128), 
"PARAM_VALUE" VARCHAR2(256), 
"NOTE" NVARCHAR2(128), 
"INC_APPSYSLIST" VARCHAR2(64), 
"EXC_APPSYSLIST" VARCHAR2(64), 
"MODULE_NAME" VARCHAR2(128) DEFAULT 'COMMON', 
"SCOPE_LEVEL" VARCHAR2(16) DEFAULT 'System', 
"SCOPE_VALUE" VARCHAR2(32)
);

CREATE TABLE "HIGHCOSTFILEPROC" 
("FILEID" NUMBER(4,0), 
"PROCSCHEMAID" NUMBER(5,0), 
"FILETYPE" NUMBER(1,0), 
"IFHAVEHEAD" NUMBER(1,0), 
"HSTATMODULEID" NUMBER(4,0), 
"IFHAVETAIL" NUMBER(1,0), 
"TSTATMODULEID" NUMBER(4,0), 
"APPLYTIME" DATE, 
"EXPIRETIME" DATE, 
"EMPTYHEADPROCSCHEMAID" NUMBER(5,0), 
"EMPTYTAILPROCSCHEMAID" NUMBER(5,0)
);

CREATE TABLE "HIGHCOSTREPORTTYPEDEF" 
("PROCESSID" NUMBER(5,0), 
"REPORTTYPE" VARCHAR2(2), 
"COMFILENAMEMODULEID" NUMBER(4,0), 
"SUMFILENAMEMODULEID" NUMBER(4,0)
);

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');

