CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;




CREATE TABLE "CLEAN_DATASET_DEF" 
("DATASET_ID" VARCHAR2(32), 
"DATASET_NAME" VARCHAR2(60), 
"NOTE" VARCHAR2(200)
);

CREATE TABLE "CLEAN_DATASET_RELATION" 
("RELATION_ID" VARCHAR2(32), 
"DATASET_ID" VARCHAR2(32), 
"RELATION_NAME" VARCHAR2(80), 
"PROC_ORDER" NUMBER(4,0), 
"SQL_TEXT" VARCHAR2(512), 
"BIND_VARS" VARCHAR2(128), 
"RELATE_DATASET_ID" VARCHAR2(32)
);

CREATE TABLE "CLEAN_DATASET_TASK" 
("TASK_ID" VARCHAR2(32), 
"CLEAN_DATASET_ID" VARCHAR2(32), 
"SCAN_SQL" VARCHAR2(512), 
"TASK_NOTE" VARCHAR2(200), 
"DELETE_SQL" VARCHAR2(512), 
"SOURCE_DB" VARCHAR2(64), 
"DELETE_DB" VARCHAR2(64), 
"BACKUP_DB" VARCHAR2(64), 
"FLOW_DB" VARCHAR2(64)
);

CREATE TABLE "CLIENT_AUTH_DEF" 
("APPNAME" VARCHAR2(32), 
"CLIENTIP" VARCHAR2(20), 
"CLIENTPORT" VARCHAR2(10), 
"LISTTYPE" NUMBER(1,0)
);

CREATE TABLE "CLUSTER_ATTR" 
("CLUSTER_ID" NUMBER(2,0), 
"ATTR_ID" VARCHAR2(50), 
"ATTR_ORDER" NUMBER(4,0) DEFAULT 0, 
"ATTR_VALUE" VARCHAR2(100)
);

CREATE TABLE "CLUSTER_DEF" 
("CLUSTER_ID" NUMBER(2,0), 
"CLUSTER_NAME" VARCHAR2(50), 
"NOTE" VARCHAR2(200)
);

CREATE TABLE "CLUSTER_TASK_DEF" 
("TASK_ID" VARCHAR2(32), 
"TASK_NAME" VARCHAR2(64), 
"TASK_DESC" VARCHAR2(128), 
"SUB_TASK_QTY" NUMBER(8,0), 
"PROC_SCHEMA" NUMBER(2,0), 
"DB_CONNECTION_NAME" VARCHAR2(32), 
"TASK_KEY_PARAMLIST" VARCHAR2(256), 
"CLUSTER_ID" NUMBER(2,0)
);
   
CREATE TABLE "CODE_DICT" 
("CATALOG" VARCHAR2(32), 
"CODE" VARCHAR2(32), 
"NAME" VARCHAR2(128), 
"NOTE" VARCHAR2(128)
);

CREATE TABLE "COLLECT_PRIV" 
("CHARGE_PRESENT_PLANID" VARCHAR2(10), 
"USE_REGION" VARCHAR2(10), 
"RECTYPE" VARCHAR2(32), 
"ACCESSTYPE" VARCHAR2(32), 
"PAYTYPE" VARCHAR2(32), 
"STARTTIME" DATE, 
"ENDTIME" DATE, 
"CHARGE_PRESENT_PLANNAME" VARCHAR2(64), 
"EXT_CHKTYPE" VARCHAR2(64), 
"PROCESSTYPE" NUMBER(1,0) DEFAULT 0, 
"PRECEDENCE" NUMBER(8,0) DEFAULT 0
);

CREATE TABLE "COLLECT_PRIV_DEF" 
("CHARGE_PRESENT_PLANID" VARCHAR2(10), 
"CHARGE_PRESENT_PLANNAME" VARCHAR2(128), 
"SUBJECTID" VARCHAR2(128), 
"CONDITION" VARCHAR2(256), 
"REFERENCE_AMTTYPE" NUMBER(1,0), 
"LIMITTYPE" NUMBER(1,0), 
"LIMITCYCLE" NUMBER(10,0), 
"LIMITTIME" NUMBER(10,0), 
"PREPAY_SUBJECT" VARCHAR2(32), 
"PRESENT_SUBJECT" VARCHAR2(32), 
"PRESENT_ROLL_TYPE" NUMBER(1,0), 
"OFFSET_CYCLES" NUMBER(8,0), 
"CYCLE_TYPE" NUMBER(1,0), 
"VALID_CYCLES" NUMBER(8,0), 
"CREATETIME" DATE, 
"IN_USE" NUMBER(1,0), 
"CONDITIONNAME" VARCHAR2(256), 
"FEEGROUPID" VARCHAR2(32), 
"LIMITPRIVILEGE" VARCHAR2(128), 
"LIMITACCTPRIV" VARCHAR2(128), 
"GROUPINFO" NUMBER(2,0) DEFAULT 0, 
"SIMPCONDITION" VARCHAR2(256)
);

CREATE TABLE "COLLECT_PRIV_ITEM_DEF" 
("CHARGE_PRESENT_PLANID" VARCHAR2(10), 
"CHARGE_PRESENT_PLANITEMID" VARCHAR2(10), 
"MINVALUE" NUMBER(14,0), 
"MAXVALUE" NUMBER(14,0), 
"PRESENTTYPE" NUMBER(1,0), 
"PRESENT_OBJECTID" VARCHAR2(32), 
"PRESENT_COMPUTE_METHOD" NUMBER(1,0), 
"REFERENCE_AMTTYPE" NUMBER(1,0), 
"PRESENT_PERCENT" NUMBER(14,0), 
"PRESENT_NUM" NUMBER(12,0) DEFAULT 0, 
"IS_SUPPORT_CARDNUM" NUMBER(1,0) DEFAULT 0, 
"BEGIN_CARD_NUM" VARCHAR2(32) DEFAULT 0, 
"END_CARD_NUM" VARCHAR2(32) DEFAULT 0
);

CREATE TABLE "COLLECT_SUBJECT_DEF" 
("RECTYPE" VARCHAR2(32), 
"ACCESSTYPE" VARCHAR2(32), 
"PAYTYPE" VARCHAR2(32), 
"PREPAYSUBJECTID" VARCHAR2(30), 
"TEMPSUBJECTID" VARCHAR2(32), 
"TEMPLATE_NO" VARCHAR2(16) DEFAULT ' ', 
"SMS_TEMPLATE_NO" VARCHAR2(16) DEFAULT ' ', 
"RECSUBTYPE" VARCHAR2(32) DEFAULT '*'
);

CREATE TABLE "COMMODITY_DEF" 
("COMMODITY_ID" VARCHAR2(30), 
"NAME" VARCHAR2(64), 
"TAX" NUMBER(5,0), 
"CODE" VARCHAR2(64)
);

CREATE TABLE "CONST_DEF" 
("CONST_ID" NUMBER(4,0), 
"CONST_NAME" VARCHAR2(64), 
"DATATYPE" NUMBER(1,0), 
"VALUE" VARCHAR2(64)
);

CREATE TABLE "CREDIT_CALC_RULE" 
("RULE_ID" NUMBER(5,0), 
"PRIORITY" NUMBER(6,0), 
"CONDITION" VARCHAR2(256), 
"G_CONDITION" VARCHAR2(256), 
"CREDIT_ENTITY_ID" NUMBER(5,0), 
"SCHEMA_ENTITY_ID" NUMBER(5,0), 
"DEST_CREDIT_LEVEL" VARCHAR2(128), 
"G_DEST_CREDIT_LEVEL" VARCHAR2(128), 
"CREDIT_VALUE" VARCHAR2(128), 
"G_CREDIT_VALUE" VARCHAR2(128)
);

CREATE TABLE "CREDIT_CONTROL_SCHEMA" 
("REGIONCODE" VARCHAR2(5), 
"SCHEMA_CODE" NUMBER(4,0), 
"CONTROL_METHOD" NUMBER(1,0), 
"CONTROL_VALUE" NUMBER(12,0), 
"SORT_ORDER" NUMBER(2,0), 
"CONTROL_CODE" VARCHAR2(16), 
"STEP_TYPE" NUMBER(1,0) DEFAULT 0, 
"DURATION_STEP" NUMBER(10,0) DEFAULT 0, 
"AMOUNT_STEP" NUMBER(10,0) DEFAULT 0, 
"CREDIT_CALC_TYPE" VARCHAR2(3) DEFAULT '000', 
"SCHEMA_ENTITY_ID" NUMBER(5,0) DEFAULT 3, 
"INTERVAL" NUMBER(10,0) DEFAULT 0, 
"SMS_ID" NUMBER(10,0) DEFAULT 0, 
"ACTION_COUNT" NUMBER(10,0) DEFAULT 0, 
"CTRL_VALUE_EXPR" VARCHAR2(256), 
"G_CTRL_VALUE_EXPR" VARCHAR2(256), 
"CREDIT_VALUE_EXPR" VARCHAR2(128), 
"G_CREDIT_VALUE_EXPR" VARCHAR2(128), 
"EX_NOTIFY_FLAG" VARCHAR2(2) DEFAULT '10', 
"CONDITION" VARCHAR2(128), 
"G_CONDITION" VARCHAR2(128)
);

CREATE TABLE "CREDIT_CTRL_ALERT_DEF" 
("TASK_NO" NUMBER(9,0), 
"MIN_DAY" NUMBER(2,0), 
"MAX_DAY" NUMBER(2,0), 
"MIN_TIME" VARCHAR2(6) DEFAULT '000000', 
"MAX_TIME" VARCHAR2(6) DEFAULT '235959', 
"WEEK_DAYS" VARCHAR2(7), 
"AUDIT_BATCHS" NUMBER(6,0) DEFAULT '10', 
"PRIORITY" NUMBER(4,0), 
"MAX_PERCENT" NUMBER(3,0) DEFAULT '100', 
"MAX_COUNT" NUMBER(8,0) DEFAULT 1, 
"PROCESS_FLAG" VARCHAR2(1), 
"IN_USE" NUMBER(1,0) DEFAULT 1
);

CREATE TABLE "CREDIT_CTRL_DOMAIN_DEF" 
("DOMAIN_ID" NUMBER(5,0), 
"DOMAIN_NAME" VARCHAR2(64), 
"DEFAULT_STATUS" VARCHAR2(64), 
"REAL_BALANCE_EXPR" VARCHAR2(64), 
"G_REAL_BALANCE_EXPR" VARCHAR2(64), 
"IMAGE_BALANCE_EXPR" VARCHAR2(64), 
"G_IMAGE_BALANCE_EXPR" VARCHAR2(64), 
"ADD_BALANCE_EXPR" VARCHAR2(64), 
"G_ADD_BALANCE_EXPR" VARCHAR2(64), 
"ADD_BALANCE_STATUS" VARCHAR2(64)
);

CREATE TABLE "CREDIT_CTRL_RULE_DEF" 
("RULE_ID" NUMBER(5,0), 
"PRIORITY" NUMBER(6,0), 
"DOMAIN_ID" NUMBER(5,0), 
"CONDITION" VARCHAR2(256), 
"G_CONDITION" VARCHAR2(256), 
"CREDIT_ENTITY_ID" NUMBER(5,0), 
"SCHEMA_ENTITY_ID" NUMBER(5,0), 
"DEST_CREDIT_LEVEL" VARCHAR2(64), 
"G_DEST_CREDIT_LEVEL" VARCHAR2(64), 
"CREDIT_VALUE" VARCHAR2(64), 
"G_CREDIT_VALUE" VARCHAR2(64)
);

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');

