CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;



CREATE TABLE "EXPR_MAPPING_RULE" 
("RULE_ID" NUMBER(5,0), 
"RULE_NAME" VARCHAR2(64), 
"SOUR_EVENT_ID" NUMBER(5,0), 
"DEST_EVENT_ID" NUMBER(5,0)
);

CREATE TABLE "EXTRACTIVE" 
("UNIQUENO" NUMBER(5,0), 
"EXTRACTTYPE" CHAR(1), 
"SEQUENCE" NUMBER(3,0) DEFAULT 0, 
"EXTRACTSEQUENCE" NUMBER(3,0), 
"STARTBYTE" NUMBER(5,0), 
"STARTBIT" NUMBER(3,0) DEFAULT 0, 
"QUATITY" NUMBER(5,0), 
"UNIT" CHAR(1), 
"OPERATE" CHAR(1)
);

CREATE TABLE "FEEGROUP_ACCITEM_DEF" 
("FEEGROUPID" VARCHAR2(32), 
"ITEMCODE" VARCHAR2(32), 
"STARTCYCLE" NUMBER(8,0), 
"ENDCYCLE" NUMBER(8,0), 
"PRECEDENCE" NUMBER(4,0), 
"INCLUDEFLAG" CHAR(1) DEFAULT 1
);

CREATE TABLE "FEEGROUP_DEF" 
("FEEGROUPID" VARCHAR2(30), 
"FEEGROUPNAME" VARCHAR2(64), 
"DRAWORDER" NUMBER(4,0) DEFAULT 9, 
"SERVICE_TYPE" VARCHAR2(32), 
"FEEGROUPIDN" NUMBER(8,0) DEFAULT 0
);

CREATE TABLE "FILEDESCRIBE" 
("PROCESSID" NUMBER(5,0), 
"FILEID" NUMBER(5,0), 
"FILENAME" VARCHAR2(100), 
"FILETYPE" NUMBER(2,0), 
"SOURPATH" VARCHAR2(80), 
"DESTPATH" VARCHAR2(80), 
"BACKPATH" VARCHAR2(80), 
"ERRORPATH" VARCHAR2(80), 
"QUEUENAME" VARCHAR2(80), 
"DBNAME" VARCHAR2(80), 
"MAXCAPACITY" NUMBER(7,0), 
"DAYFILECOUNT" NUMBER(4,0), 
"CREATETIME" VARCHAR2(4), 
"LOGDBNAME" VARCHAR2(30), 
"FILENAMESTYLE" VARCHAR2(30), 
"REDO_FILENO_LIST" VARCHAR2(20) DEFAULT null, 
"REDO_TABLE" VARCHAR2(32), 
"REDO_EVENT_ID" NUMBER(10,0), 
"REDO_WHERE_CLAUSE" VARCHAR2(128)
);

CREATE TABLE "FILENAME" 
("FILEID" NUMBER(5,0), 
"CONORDER" NUMBER(5,0), 
"CONTYPE" NUMBER(5,0), 
"CONTENT" VARCHAR2(20)
);


insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');




