CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;

CREATE TABLE "AM_ACCT_RULE" 
("SUBJECT_TYPE" NUMBER(1,0), 
"SUBJECT_ID" VARCHAR2(32) DEFAULT -1, 
"FLOW_TYPE" NUMBER(2,0), 
"FLOW_TIME_RANGE" NUMBER(1,0), 
"FLOW_DIRECTION" NUMBER(1,0), 
"FEE_SIGN" NUMBER(1,0) DEFAULT -1, 
"FEE_SOURCE" NUMBER(1,0), 
"ACCT_TYPE" NUMBER(1,0), 
"ACCT_ITEM" NUMBER(2,0)
);

CREATE TABLE "AM_BILL_MIGRATE_DEF" 
("DATA_TYPE" VARCHAR2(32), 
"NAME" VARCHAR2(64), 
"IS_NEEDUPDATE" NUMBER(1,0) DEFAULT 1, 
"MIN_INTERVAL" NUMBER(5,0), 
"MAX_INTERVAL" NUMBER(5,0), 
"MIN_CYCLE" NUMBER(8,0) DEFAULT 0, 
"UNCERTAIN_DEALMODE" NUMBER(1,0)
);

CREATE TABLE "AM_EMERGENCY_DEF" 
("REGION" NUMBER(5,0), 
"DBTYPE" NUMBER(2,0), 
"MODULE_NAME" VARCHAR2(20), 
"DATA_NODEID" NUMBER(5,0), 
"MEMO" VARCHAR2(64), 
"STATUS" NUMBER(1,0) DEFAULT 0, 
"STATUSDATE" DATE DEFAULT sysdate
);


CREATE TABLE "AM_PROD_PRESENT" 
("PRESENT_RULE_ID" NUMBER(12,0), 
"REGION" NUMBER(5,0), 
"PRODID" VARCHAR2(32), 
"PROD_TYPE" VARCHAR2(2) DEFAULT 'P', 
"EFF_DATE" DATE, 
"EXP_DATE" DATE, 
"PRICING_PLAN_ID" VARCHAR2(32)
);

CREATE TABLE "AM_PROD_PRESENT_ITEM" 
("PRESENT_RULE_ID" NUMBER(12,0), 
"REBATE_SCHEMA_ID" NUMBER(15,0), 
"PRIORITY" NUMBER(5,0), 
"INUSE" NUMBER(1,0) DEFAULT 1
);

CREATE TABLE "AM_TAX_RATE_DEF" 
("RATEDEFID" NUMBER(6,0), 
"ITEMCODE" VARCHAR2(32), 
"TAXRATE" NUMBER(5,0) DEFAULT 0, 
"EFFDATE" DATE, 
"EXPDATE" DATE, 
"INUSE" NUMBER(1,0), 
"UPDATETIME" DATE, 
"COMMODITY_ID" VARCHAR2(30)
);

CREATE TABLE "AM_TAX_SPLIT_DEF" 
("RULEID" NUMBER(6,0), 
"ITEMCODE" VARCHAR2(32), 
"PKGCODE" VARCHAR2(32), 
"SPLITTYPE" NUMBER(1,0), 
"SPLITVALUE" NUMBER(6,0), 
"SUBITEMCODE" VARCHAR2(32), 
"SPLITORDER" NUMBER(2,0), 
"EFFDATE" DATE, 
"EXPDATE" DATE, 
"INUSE" NUMBER(1,0), 
"UPDATETIME" DATE, 
"RULETYPE" NUMBER(1,0) DEFAULT 1, 
"REGION" NUMBER(5,0) DEFAULT 999
);

CREATE TABLE "AM_TRADE_FREEUNIT_TYPE" 
("FU_TYPE_ID" NUMBER(8,0), 
"FU_TYPE_NAME" VARCHAR2(64), 
"PRIORITY" NUMBER(8,0), 
"SERVICE_TYPE" VARCHAR2(32), 
"ATTR_TYPE" NUMBER(1,0), 
"BASE_UNIT" NUMBER(10,0), 
"TRADE_CTAGSET" VARCHAR2(20), 
"INST_PRIORITY" CHAR(1), 
"MERGE_TYPE" NUMBER(1,0), 
"EFF_DATE" DATE, 
"EXP_DATE" DATE, 
"CREATE_DATE" DATE, 
"UPDATE_DATE" DATE, 
"REMARK" VARCHAR2(200), 
"STATUS" CHAR(1), 
"STATUS_DATE" DATE
);

CREATE TABLE "AMERCE_PLAN_DEF" 
("AMERCE_PLANID" NUMBER(10,0), 
"AMERCE_PLANNAME" VARCHAR2(64), 
"EXCLUDED_SUBJECT" VARCHAR2(256), 
"IN_USE" NUMBER(1,0), 
"ROUND_TYPE" NUMBER(1,0), 
"MAXLATEFEE" NUMBER(8,0) DEFAULT 0, 
"CALC_LIMIT_TYPE" NUMBER(1,0) DEFAULT 1
);

CREATE TABLE "AMERCE_RATE_DEF" 
("AMERCE_PLANID" NUMBER(10,0), 
"ITEMTYPE" NUMBER(1,0), 
"CYCLE" NUMBER(10,0), 
"STARTDATE" DATE, 
"ENDDATE" DATE, 
"RATE_OF_AMERCE" NUMBER(5,0), 
"URGEDATE" DATE, 
"STOPDATE" DATE
);

CREATE TABLE "APP_BUNDLED_DATANODE" 
("APPTYPE" NUMBER(4,0), 
"NODEID" NUMBER(5,0), 
"DATA_NODEID" NUMBER(4,0)
);

CREATE TABLE "APP_ROUTE_DEF" 
("APPTYPE" NUMBER(4,0), 
"ROUTE_TYPE" NUMBER(2,0)
);

CREATE TABLE "APP_TASK_DEF" 
("APP_TASK_ID" VARCHAR2(60), 
"APP_TASK_NAME" VARCHAR2(500), 
"APP_NAME" VARCHAR2(60), 
"TASK_DESC" VARCHAR2(500), 
"PARENT_TASK" VARCHAR2(60)
);

CREATE TABLE "APP_TASK_PARAM_DEF" 
("APP_TASK_ID" VARCHAR2(60), 
"PARAM_NAME" VARCHAR2(60), 
"PARAM_VALUE" VARCHAR2(2000)
);

CREATE TABLE "ASSEMBLE_ELEMENT_DEF" 
("RULE_ID" VARCHAR2(30), 
"ELEMENT_SEQ" NUMBER(4,0), 
"ELEMENT_EXPR" VARCHAR2(500), 
"G_ELEMENT_EXPR" VARCHAR2(1000)
);

CREATE TABLE "ASSEMBLE_PROCESS_DEF" 
("RULE_ID" VARCHAR2(30), 
"PROC_SEQ" NUMBER(4,0), 
"RULE_COND" VARCHAR2(500), 
"G_RULE_COND" VARCHAR2(1000), 
"TEXT" VARCHAR2(1000), 
"SOUR_EVENT_ID" NUMBER(4,0), 
"DEST_EVENT_ID" NUMBER(4,0), 
"LOOP_EVENT_EXPR" VARCHAR2(300), 
"G_LOOP_EVENT_EXPR" VARCHAR2(600), 
"SUB_RULE_ID" VARCHAR2(30)
);

CREATE TABLE "ASSEMBLE_TEXT_DEF" 
("RULE_ID" VARCHAR2(30), 
"NAME" VARCHAR2(150), 
"SOUR_EVENT_ID" NUMBER(4,0), 
"DEST_EVENT_ID" NUMBER(4,0)
);

CREATE TABLE "BASE_ATTR_DEF" 
("ENTITY_ID" NUMBER(4,0), 
"ATTR_ID" NUMBER(8,0), 
"BASE_ATTR_TYPE" NUMBER(1,0), 
"BASE_ATTR_ID" NUMBER(4,0), 
"CHARGING_EVENT_ID" NUMBER(4,0), 
"CALL_USAGE_COND" VARCHAR2(256), 
"ROUND_UNIT" NUMBER(8,0), 
"ROUND_TYPE" NUMBER(1,0), 
"G_CALL_USAGE_COND" VARCHAR2(256), 
"SEQNO" NUMBER(14,0) DEFAULT 0, 
"CONVERT_UNIT" NUMBER(10,0) DEFAULT -1, 
"ATTR_ADD_CODE_VALUE" VARCHAR2(100), 
"G_ATTR_ADD_CODE_VALUE" VARCHAR2(200)
);

CREATE TABLE "BILL_DISC" 
("TARIFFPLAN_ID" NUMBER(8,0), 
"REGION" VARCHAR2(200), 
"STARTDATE" DATE, 
"ENDDATE" DATE
);

CREATE TABLE "BILLDISC_DEF" 
("TARIFFPLAN_ID" NUMBER(8,0), 
"PLANITEM_ID" NUMBER(8,0), 
"DISC_ENTITY" NUMBER(1,0), 
"DISC_COND" VARCHAR2(512), 
"G_DISC_COND" VARCHAR2(768), 
"DISC_TYPE" NUMBER(2,0), 
"REFITEM_TYPE" NUMBER(1,0), 
"FREEREFITEM_TYPE" NUMBER(1,0), 
"REFITEM_CODE" VARCHAR2(32), 
"REFITEM_CYCLES" NUMBER(2,0), 
"REFITEM_CYCLE_OFFSET" NUMBER(4,0), 
"REFVALUE_CALC_TYPE" NUMBER(1,0), 
"REFVALUE_UNIT" NUMBER(2,0), 
"DISC_OBJECT_TYPE" NUMBER(1,0), 
"DISC_ITEM_CODE" VARCHAR2(256), 
"START_CYCLE_OFFSET" NUMBER(4,0), 
"VALID_CYCLE_TYPE" NUMBER(1,0), 
"VALID_CYCLES" NUMBER(4,0), 
"INUSE" NUMBER(1,0), 
"TARIFFPLAN_TYPE" NUMBER(4,0), 
"DISC_ITEM_TYPE" NUMBER(1,0) DEFAULT 1, 
"FREEREFITEM_MIN_USAGE" NUMBER(14,0), 
"NOTE" VARCHAR2(255), 
"ISDISCTSPEC" VARCHAR2(1) DEFAULT '0', 
"SPECDISCT_EXPR" VARCHAR2(512) DEFAULT ' ', 
"G_SPECDISCT_EXPR" VARCHAR2(512), 
"CONVERT_TYPE" NUMBER(1,0) DEFAULT 0, 
"REF_ENTITY_TYPE" NUMBER(2,0) DEFAULT 0, 
"DISC_SOURCE" VARCHAR2(64), 
"G_DISC_SOURCE" VARCHAR2(64), 
"DISC_SOURCE_FACTOR" NUMBER(8,0) DEFAULT 1, 
"DISC_ITEM_EXPR_ID" NUMBER(4,0), 
"FORCE_OUTPUT_EVENT" NUMBER(1,0) DEFAULT 0, 
"DISC_SOURCE_TYPE" NUMBER(1,0) DEFAULT 0
);

CREATE TABLE "BILLING_CHECK_DEF" 
("EVENTID" NUMBER(6,0), 
"ATTRID" NUMBER(6,0), 
"ATTRTYPE" NUMBER(3,0), 
"NOTES" VARCHAR2(16)
);

CREATE TABLE "BILLING_CYCLE_CONTROL" 
("REGION" NUMBER(5,0), 
"CYCLEID" NUMBER(8,0), 
"MODIFYTIME" DATE DEFAULT sysdate, 
"OPENDAY" NUMBER(2,0) DEFAULT 0, 
"OFFSET_SECOND" NUMBER(6,0) DEFAULT 0
);

CREATE TABLE "BILLING_DEF" 
("EVENT_ID" NUMBER(8,0), 
"BILLING_COND" VARCHAR2(512), 
"EXPR_TYPE" NUMBER(1,0), 
"ITEM_EXPR" VARCHAR2(128), 
"ITEMCODE" VARCHAR2(32), 
"ITEMTYPE" NUMBER(2,0), 
"ITEMADD_TYPE" NUMBER(1,0), 
"ITEMADD_EXPR" VARCHAR2(128), 
"START_CYCLE" NUMBER(8,0), 
"END_CYCLE" NUMBER(8,0), 
"TEMPITEM_FLAG" NUMBER(1,0), 
"ITEM_UNIT" NUMBER(2,0), 
"PAYPLAN_FLAG" NUMBER(1,0), 
"G_BILLING_COND" VARCHAR2(1024), 
"G_ITEMADD_EXPR" VARCHAR2(128), 
"G_ITEM_EXPR" VARCHAR2(1024), 
"RULEID" NUMBER(4,0) DEFAULT 1, 
"NEXTRULEID" NUMBER(4,0) DEFAULT 0, 
"PROCSCHEMAID" NUMBER(5,0) DEFAULT 0, 
"PROCEVENTID" NUMBER(4,0) DEFAULT 0, 
"RULENAME" VARCHAR2(32), 
"FEE_ID" NUMBER(9,0), 
"SPLITTYPE" NUMBER(1,0) DEFAULT 0, 
"UNIQUE_ID" NUMBER(10,0), 
"ROUNDTYPE" NUMBER(1,0) DEFAULT 0, 
"SHOW_ZERO_FEE_FLAG" NUMBER(1,0) DEFAULT 0
);

CREATE SEQUENCE  "SEQ_BILLING_DEF_UNIQUEID"  MINVALUE 0 MAXVALUE 999999999 INCREMENT BY 1 START WITH 3121 CACHE 20 ORDER  NOCYCLE ;

CREATE TABLE "BILLINGCYCLE" 
("CYCLE_SCHEMA_ID" NUMBER(4,0), 
"CYCLE_ID" NUMBER(8,0), 
"CYCLE_NAME" VARCHAR2(64), 
"CYCLE_STATUS" NUMBER(1,0), 
"OPENDATE" DATE, 
"CLOSEDATE" DATE, 
"INVOICEDATE" DATE
);

CREATE TABLE "BILLINGCYCLE_SCHEMA" 
("CYCLE_SCHEMA_ID" NUMBER(4,0), 
"CYCLE_SCHEMA_NAME" VARCHAR2(64), 
"CYCLE_UNIT" NUMBER(1,0), 
"UNIT_COUNT" NUMBER(4,0), 
"OPENDATE" VARCHAR2(32), 
"INVOICE_DELAY" NUMBER(4,0), 
"PREBUILT_CYCLES" NUMBER(4,0), 
"FIRSTCYCLE_OPENDATE" VARCHAR2(32), 
"STATUS" NUMBER(1,0), 
"MULTIACTIVATION" NUMBER(1,0), 
"FIXED_CYCLE" NUMBER(1,0), 
"CYCLEID_BASE" NUMBER(1,0) DEFAULT 1
);

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');

