CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;



CREATE TABLE "HOSTNODE_DEF" 
("HOSTID" NUMBER(4,0), 
"HOSTNAME" VARCHAR2(64), 
"IPADDR0" VARCHAR2(32), 
"IPADDR1" VARCHAR2(32), 
"INUSE" NUMBER(1,0), 
"DB_LINK_NAME" VARCHAR2(32), 
"CLUSTER_ID" NUMBER(2,0)
);

CREATE TABLE "INFIRMWORD" 
("INFIRMWORD" VARCHAR2(32), 
"INUSE" NUMBER(1,0) DEFAULT 1
);

CREATE TABLE "INFOFILEBATCH_DEF" 
("BATCHNUM" NUMBER(2,0), 
"BATCHNAME" NVARCHAR2(128)
);

CREATE TABLE "INFOFILENAME_DEF" 
("FILEID" NUMBER(5,0), 
"CONORDER" NUMBER(5,0), 
"CONTYPE" NUMBER(5,0), 
"CONTENT" VARCHAR2(512)
);

CREATE TABLE "INFOFILESQL_DEF" 
("SQLQUERYID" NUMBER(4,0), 
"TABLENAME" VARCHAR2(4000), 
"COND" VARCHAR2(2048), 
"QRY_CONTENT_SQL" VARCHAR2(3000), 
"ISDELETE" NUMBER(1,0), 
"CYCLE_FLAG" NUMBER(1,0), 
"INUSE" NUMBER(1,0), 
"SQLQUERYNO" NUMBER(4,0), 
"UPDATE_SQL" VARCHAR2(1024)
);

CREATE TABLE "INFOFILETASK_DEF" 
("TASKID" NUMBER(4,0), 
"TASK_NAME" NVARCHAR2(128), 
"FILEID" NUMBER(4,0), 
"SQLQUERY_ID" NUMBER(4,0), 
"MAX_EVENT_COUNT" NUMBER(9,0), 
"FILESEQBEGIN" NUMBER(6,0), 
"FILESEQEND" NUMBER(6,0), 
"TMPPATH" VARCHAR2(256), 
"DESTPATH" VARCHAR2(256), 
"FILETYPE" NUMBER(1,0), 
"BATCHNUM" NUMBER(2,0), 
"INUSE" NUMBER(1,0) DEFAULT 0, 
"GENEMPTYFILEFLAG" NUMBER(1,0) DEFAULT 0, 
"HEADCONTENT" VARCHAR2(512), 
"TAILCONTENT" VARCHAR2(512), 
"CHECKFILE_POSTFIX" VARCHAR2(20), 
"DATAFILE_POSTFIX" VARCHAR2(20)
);

CREATE TABLE "LC_DYNAMIC_DEF" 
("NODE_ID" NUMBER(4,0) DEFAULT 0, 
"EVENT_ID" NUMBER(4,0) DEFAULT 0, 
"SUB_EVENT_ID" NUMBER(4,0) DEFAULT 0, 
"LCPRIOR" NUMBER(4,0) DEFAULT 0, 
"START_THRESHOLD" NUMBER(8,0) DEFAULT 800, 
"RESUME_THRESHOLD" NUMBER(8,0) DEFAULT 250, 
"SMOOTH_CYCLE" NUMBER(2,0) DEFAULT 2, 
"ADJUST_CYCLE" NUMBER(2,0) DEFAULT 4, 
"ADJUST_DIVISOR" NUMBER(2,0) DEFAULT 16, 
"ADJUST_STEP" NUMBER(2,0) DEFAULT 1, 
"NODE_TYPE" NUMBER(1,0)
);

CREATE TABLE "LC_ESTIMATE_RESULT" 
("NODE_ID" NUMBER(4,0) DEFAULT 0, 
"EVENT_ID" NUMBER(4,0) DEFAULT 0, 
"SUB_EVENT_ID" NUMBER(4,0) DEFAULT 0, 
"LC_STATUS_TIME" DATE DEFAULT sysdate, 
"LC_STATUS" NUMBER(2,0) DEFAULT 0, 
"LC_CUR_STEP" NUMBER(2,0) DEFAULT 0, 
"NODE_TYPE" NUMBER(1,0)
);

CREATE TABLE "LC_STATIC_DEF" 
("NODE_ID" NUMBER(4,0) DEFAULT 0, 
"EVENT_ID" NUMBER(4,0) DEFAULT 0, 
"SUB_EVENT_ID" NUMBER(4,0) DEFAULT 0, 
"CAPS" NUMBER(8,0) DEFAULT 10000, 
"NODE_TYPE" NUMBER(1,0)
);

CREATE TABLE "LIMITLOGON" 
("LIMITID" NUMBER(5,0), 
"IPADDR" VARCHAR2(16), 
"MACADDR" VARCHAR2(20), 
"STARTHOUR" NUMBER(6,0), 
"ENDHOUR" NUMBER(6,0), 
"INUSE" NUMBER(1,0) DEFAULT 1
);

CREATE TABLE "LOGICAL_DS_DEF" 
("DATASTORE_NAME" VARCHAR2(64), 
"FILENAME_PREFIX" VARCHAR2(8), 
"TMP_DIR" VARCHAR2(256), 
"BAK_DIR" VARCHAR2(256), 
"METHOD" NUMBER(1,0), 
"DATA_FORMAT" NUMBER(1,0), 
"INUSE" NUMBER(1,0), 
"FILETYPE" NUMBER(1,0) DEFAULT 1, 
"HAVEVERSION" NUMBER(1,0) DEFAULT 1, 
"STORETYPE" VARCHAR2(1) DEFAULT 'F', 
"QUEUETABLENAME" VARCHAR2(32), 
"QUEUECAPICITY" NUMBER(8,0) DEFAULT (0), 
"QUEUEBLOCKTIME" NUMBER(8,0) DEFAULT (0), 
"READFILEBYLINE" NUMBER(2,0) DEFAULT 0
);

CREATE TABLE "MAIN_DB_SERVER_DEF" 
("SERVER_NAME" VARCHAR2(50), 
"SERVER_ID" NUMBER(4,0), 
"SERVER_DESC" VARCHAR2(200)
);

CREATE TABLE "MAPPING_DEF" 
("MAPPING_ID" NUMBER(5,0), 
"MAPPING_NAME" VARCHAR2(100), 
"SOUR_FIELD_COUNT" NUMBER(4,0), 
"MAPPING_SOUR_DEF" VARCHAR2(240), 
"DEST_FIELD_COUNT" NUMBER(4,0), 
"MAPPING_DEST_DEF" VARCHAR2(240), 
"MATCH_ORDER" NUMBER(1,0), 
"MAPPING_SOUR_ATTR" VARCHAR2(80), 
"MAPPING_DEST_ATTR" VARCHAR2(80), 
"OFTEN_USED" NUMBER(1,0) DEFAULT 0, 
"SOURCE_PROCESS_TYPE" NUMBER(2,0) DEFAULT 0
);

CREATE TABLE "PARAM_ID_CHANGE" 
("GROUP_NAME" VARCHAR2(20), 
"ID_NUMBER" NUMBER(10,0), 
"CHANGE_TIME" DATE
);

CREATE TABLE "MAPPING_LIST" 
("MAPPING_SOUR" VARCHAR2(240), 
"MAPPING_DEST" VARCHAR2(240), 
"APPLYTIME" DATE, 
"EXPIRETIME" DATE, 
"MAPPING_ID" NUMBER(5,0), 
"NOTE" VARCHAR2(120)
);

CREATE TABLE "MAPPING_RULE" 
("RULE_ID" NUMBER(5,0), 
"RULE_NAME" VARCHAR2(64), 
"SOUR_ATTR_DEF" VARCHAR2(256), 
"DEST_ATTR_DEF" VARCHAR2(256), 
"MATCH_METHOD" NUMBER(1,0), 
"MAPPING_ID" NUMBER(5,0), 
"ERROR_CODE" VARCHAR2(10), 
"G_SOUR_ATTR" VARCHAR2(256), 
"G_DEST_ATTR" VARCHAR2(256), 
"SOUR_EVENT_ID" NUMBER(5,0), 
"DEST_EVENT_ID" NUMBER(5,0)
);

CREATE TABLE "MMQ_DEF" 
("MMQ_DEVID" NUMBER(8,0), 
"MMQ_NAME" VARCHAR2(30), 
"MMQ_DESC" VARCHAR2(60), 
"MMQ_SIZE" NUMBER(8,0)
);

CREATE TABLE "MMQ_DEVICE_DEF" 
("MMQ_DEVID" NUMBER(8,0), 
"SHMKEY" NUMBER(8,0), 
"DCB_SIZE" NUMBER(16,0), 
"BLOCK_SIZE" NUMBER(8,0), 
"DCB_NAME" VARCHAR2(30)
);

CREATE TABLE "MODULE_EVENT_TARIFF_PLAN" 
("MODULE_ID" NUMBER(4,0), 
"EVENT_TARIFF_PLAN_ID" NUMBER(6,0), 
"STATUS" NUMBER(1,0)
);

CREATE TABLE "MODULE_RATEPLAN" 
("MODULE_ID" NUMBER(4,0), 
"TARIFF_PLAN_ID" NUMBER(6,0), 
"STATUS" NUMBER(1,0)
);

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');
 
