CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;



CREATE TABLE "CREDIT_CTRL_SCHEMA_DEF" 
("REGIONCODE" VARCHAR2(5), 
"SCHEMA_ENTITY_ID" NUMBER(5,0) DEFAULT 3, 
"DOMAIN_ID" NUMBER(5,0), 
"SCHEMA_CODE" NUMBER(4,0), 
"CONTROL_METHOD" NUMBER(1,0), 
"SORT_ORDER" NUMBER(2,0), 
"CONDITION" VARCHAR2(128), 
"G_CONDITION" VARCHAR2(128), 
"CTRL_VALUE_EXPR" VARCHAR2(256), 
"G_CTRL_VALUE_EXPR" VARCHAR2(256), 
"CONTROL_CODE" VARCHAR2(16), 
"STEP_TYPE" NUMBER(1,0) DEFAULT 0, 
"DURATION_STEP" NUMBER(10,0) DEFAULT 0, 
"AMOUNT_STEP" NUMBER(10,0) DEFAULT 0, 
"INTERVAL" NUMBER(10,0) DEFAULT 0, 
"SMS_ID" NUMBER(10,0) DEFAULT 0, 
"ACTION_COUNT" NUMBER(10,0) DEFAULT 0, 
"CREDIT_VALUE_EXPR" VARCHAR2(128), 
"G_CREDIT_VALUE_EXPR" VARCHAR2(128)
);

CREATE TABLE "CREDIT_CTRL_TASK_DEF" 
("TASK_NO" NUMBER(9,0), 
"TASK_NAME" VARCHAR2(64), 
"CREDIT_EVENT_ID" NUMBER(6,0), 
"FLOW_ID" NUMBER(5,0), 
"PROCESS_ID" NUMBER(9,0), 
"PROCESS_ALL_DOMAIN" NUMBER(1,0) DEFAULT 1
);

CREATE TABLE "CREDIT_CTRL_TASK_DOMAINS" 
("TASK_NO" NUMBER(9,0), 
"DOMAIN_ID" NUMBER(4,0)
);

CREATE TABLE "CREDIT_CTRL_TASK_ITEM_DEF" 
("TASK_NO" NUMBER(9,0), 
"SEQ" NUMBER(9,0), 
"PRIORITY" NUMBER(6,0) DEFAULT 0, 
"SUBTASK_NAME" VARCHAR2(128), 
"SOURCE_TYPE" VARCHAR2(1), 
"SERVER_NAME" VARCHAR2(20), 
"SOURCE_PARAM" VARCHAR2(256), 
"ACTION_TYPE" NUMBER(6,0) DEFAULT 1, 
"IS_DELETE" NUMBER(1,0) DEFAULT 1
);

CREATE TABLE "CREDITDETECT_ALERT_DEF" 
("TASKNO" NUMBER(10,0), 
"MINDAY" NUMBER(2,0), 
"MAXDAY" NUMBER(2,0), 
"MINTIME" VARCHAR2(6) DEFAULT '000000', 
"MAXTIME" VARCHAR2(6) DEFAULT '235959', 
"WEEKDAYS" VARCHAR2(7), 
"AUDITBATCHS" NUMBER(6,0) DEFAULT '10', 
"MAXPERCENT" NUMBER(3,0) DEFAULT '100', 
"MAXCOUNT" NUMBER(8,0), 
"PRECEDENCE" NUMBER(4,0), 
"PROCESSFLAG" VARCHAR2(1), 
"INUSE" NUMBER(1,0) DEFAULT '1'
);

CREATE TABLE "CREDITDETECT_TASK_DEF" 
("TASKNO" NUMBER(10,0), 
"TASKNAME" VARCHAR2(100), 
"CREDITEVENTID" NUMBER(6,0), 
"DOWNEVENTID" NUMBER(6,0), 
"NODEID" NUMBER(10,0), 
"LOGPATH" VARCHAR2(64)
);

CREATE TABLE "CREDITDETECT_TASK_ITEM" 
("TASKNO" NUMBER(10,0), 
"SEQ" NUMBER(10,0), 
"SUBTASKNAME" VARCHAR2(100), 
"SOURCETYPE" NUMBER(10,0), 
"MINACCTID" NUMBER(13,0), 
"MAXACCTID" NUMBER(13,0), 
"FLOWID" NUMBER(13,0), 
"PROCESSID" NUMBER(13,0), 
"SOURCENAME" VARCHAR2(64), 
"SOURCECOND" VARCHAR2(256), 
"PRECEDENCE" NUMBER(3,0) DEFAULT 0
);

CREATE TABLE "CUST_SHELL" 
("ID" VARCHAR2(50), 
"CONTENT" CLOB, 
"NOTE" VARCHAR2(100), 
"SCRIPTTYPE" NUMBER(1,0)
);

CREATE TABLE "CUSTBILL_CELL_DEF" 
("TEMPLATE_ID" NUMBER(10,0), 
"CELL_ID" VARCHAR2(15), 
"CELL_NAME" VARCHAR2(64), 
"SORT_ORDER" NUMBER(5,0), 
"CELL_TYPE" NUMBER(1,0) DEFAULT 0, 
"AUTOGETCELLNAME" NUMBER(2,0) DEFAULT 0, 
"ACCTMATCHTYPE" NUMBER(1,0) DEFAULT 0, 
"PCELL_ID" VARCHAR2(15), 
"DISPLAY" NUMBER(1,0) DEFAULT 1, 
"BILLLEVEL" NUMBER(8,0) DEFAULT 0, 
"FEELIMIT" NUMBER(4,0) DEFAULT 0, 
"SELFFLAG" NUMBER(1,0) DEFAULT 0, 
"PARENTID" VARCHAR2(15), 
"TRANSZEROFEE" NUMBER(1,0) DEFAULT 0, 
"AUTOEXPANDLEVEL" NUMBER(1,0) DEFAULT 1, 
"SELFDEFAULT" NUMBER(1,0) DEFAULT 0, 
"ACCUMULATETYPE" NUMBER(1,0) DEFAULT 0, 
"TAXRATE" NUMBER(5,0) DEFAULT 0, 
"ITEMTYPE" VARCHAR2(32) DEFAULT '0', 
"CELL_INFO" VARCHAR2(32), 
"ISSHOWDISCOUNT" NUMBER(1,0) DEFAULT 0, 
"SUBSMATCHTYPE" NUMBER(1,0) DEFAULT 0, 
"ISADDDISCOUNTSELF" NUMBER(1,0) DEFAULT 0, 
"ISCHECKBILL" NUMBER(1,0) DEFAULT 0
);

CREATE TABLE "CUSTBILL_DEF" 
("TEMPLATE_ID" NUMBER(10,0), 
"TEMPLATE_NAME" VARCHAR2(64), 
"INUSE" NUMBER(1,0), 
"OTHERPAYTYPE" NUMBER(1,0) DEFAULT 0, 
"OFFERTAX" NUMBER(1,0) DEFAULT 0, 
"ZEROCHECKTYPE" VARCHAR2(8)
);

CREATE TABLE "CUSTBILL_FORMAT_DATABIND" 
("RULE_ID" NUMBER(5,0), 
"FORMAT_ID" VARCHAR2(32), 
"ENTITY_TYPE" NUMBER(1,0), 
"TRIGGER_TYPE" VARCHAR2(32)
);

CREATE TABLE "CUSTBILL_FORMAT_DEF" 
("FORMAT_ID" VARCHAR2(32), 
"FORMAT_NAME" VARCHAR2(64), 
"ENTITY_TYPE" NUMBER(1,0), 
"DATATYPE" VARCHAR2(64), 
"PARAM" VARCHAR2(2000)
);

CREATE TABLE "CUSTBILL_VERSION_DEF" 
("VERSION_ID" NUMBER(5,0), 
"MODULE_NAME" VARCHAR2(32), 
"PARAM_LEVEL" NUMBER(1,0), 
"PARAM_NAME" VARCHAR2(32), 
"PARENT_VERSION" NUMBER(5,0), 
"PARAM_VERSION" NUMBER(5,0) DEFAULT 0, 
"VALIDCYCLE" DATE DEFAULT sysdate
);

CREATE TABLE "CUSTOM_CYCLE_SCHEMA" 
("CUSTOM_SCHEMA_ID" NUMBER(2,0), 
"CYCLE_SCHEMA_ID" NUMBER(4,0)
);

CREATE TABLE "DATA_QUERY_DEF" 
("QUERY_ID" NUMBER(9,0), 
"QUERY_NAME" NVARCHAR2(160), 
"QUERY_CLASS" VARCHAR2(1), 
"SELECT_SQL" VARCHAR2(4000), 
"DELETE_SQL" VARCHAR2(4000), 
"RESULT_EVENT_ID" NUMBER(9,0), 
"DB_MODULE_NAME" VARCHAR2(32), 
"QUERY_TYPE" NUMBER(1,0) DEFAULT 0, 
"DBTYPE" NUMBER(2,0) DEFAULT 0, 
"ROUTE_TYPE_PARAM" NVARCHAR2(160), 
"ROUTE_DATA_PARAM" NVARCHAR2(160), 
"NBR_TYPE_PARAM" NVARCHAR2(160), 
"DML_TYPE" NUMBER(1,0) DEFAULT 0, 
"REDO_FLAG" NUMBER(1,0) DEFAULT 0
);

CREATE TABLE "DATA_QUERY_INSTANCE" 
("INSTANCE_ID" NUMBER(9,0), 
"INSTANCE_NAME" NVARCHAR2(160), 
"QUERY_ID" NUMBER(9,0), 
"SOURCE_EVENT_ID" NUMBER(9,0), 
"QUERY_CONDITION" VARCHAR2(512), 
"G_QUERY_CONDITION" VARCHAR2(1024)
);

CREATE TABLE "DATA_QUERY_INSTANCE_PARAM" 
("INSTANCE_ID" NUMBER(9,0), 
"PARAM_INDEX" NUMBER(9,0), 
"PARAM_VALUE" VARCHAR2(256), 
"PARAM_DESC" NVARCHAR2(1024), 
"G_PARAM_VALUE" NVARCHAR2(1024)
);

CREATE TABLE "DATA_QUERY_INSTANCE_TREE" 
("INSTANCE_ID" NUMBER(9,0), 
"SEQ_NO" NUMBER(2,0), 
"SUB_INSTANCE_ID" NUMBER(9,0), 
"DEST_EVENT_ATTR" NVARCHAR2(512), 
"G_DEST_EVENT_ATTR" NVARCHAR2(512), 
"SUB_INSTANCE_TYPE" NUMBER(1,0) DEFAULT 1, 
"CYCLE_EVENT_ATTR" NUMBER(4,0) DEFAULT 0, 
"FIRST_ROW_ATTR" NUMBER(4,0) DEFAULT 0
);

insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');


