CREATE SEQUENCE  "SEQ_AUDIT"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 21605340 CACHE 20 ORDER  CYCLE ;

CREATE SEQUENCE  "SEQ_BILLINGCLIENTLOG"  MINVALUE 0 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 174402 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "SEQ_LOGON"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1388537 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "APP_USER" ("USER_CODE" VARCHAR2(16), "USER_NAME" VARCHAR2(60), "PASSWORD" VARCHAR2(256), "STATUS" CHAR(1), "DESCRIPTION" VARCHAR2(300), "PASSWORD_HIS" VARCHAR2(4000), "MODIFY_DATE" DATE, "FAIL_COUNT" NUMBER(4,0) DEFAULT 0, "USERTYPE" NUMBER(1,0) DEFAULT 0, "PWDTYPE" NUMBER(1,0) DEFAULT 0, "REGION" NUMBER(5,0), "SESSIONID" VARCHAR2(30), "LOGONTIME" DATE, "LOGOUTTIME" DATE, "USERSALT_HIS" VARCHAR2(2200), "USERSALT" VARCHAR2(100), "INUSE_STARTTIME" DATE, "INUSE_ENDTIME" DATE) ;

CREATE TABLE "FEATURE_DEF" ("NAME" VARCHAR2(50), "VALUE" VARCHAR2(100), "NOTE" VARCHAR2(600)) ;

CREATE TABLE "AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(4000), "NEWVALUE" VARCHAR2(4000), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024), "LOGONID" NUMBER(10,0), "LOGONSEQ" VARCHAR2(32), "OPERNUM" VARCHAR2(24))  PARTITION BY RANGE ("LOGTIME")  (PARTITION "P_202006"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , PARTITION "P_MAX"  VALUES LESS THAN (MAXVALUE) ) ;

CREATE TABLE "PARAM_TABLE_DEF" ("TABLE_NAME" VARCHAR2(64), "TABLE_NOTE" VARCHAR2(64), "SERIOUS" NUMBER(1,0), "LASTCHANGETIME" DATE) ;



CREATE TABLE "TARIFF_ITEM" 
("TARIFF_SCHEMA_ID" NUMBER(9,0), 
"APPLYTIME" DATE, 
"EXPIRETIME" DATE, 
"TARIFF_CRITERIA" VARCHAR2(256), 
"SUBTARIFF_TYPE" NUMBER(1,0), 
"TARIFF_ID" NUMBER(9,0), 
"RATIO" NUMBER(5,2), 
"RATETYPE" CHAR(1), 
"PARAM_STRING" VARCHAR2(128), 
"PRECEDENCE" NUMBER(4,0), 
"EXPR_ID" NUMBER(9,0), 
"G_PARAM" VARCHAR2(256), 
"IS_DYNAMIC" NUMBER(1,0) DEFAULT (0), 
"G_CRITERIA" VARCHAR2(512), 
"BILLCODE" VARCHAR2(32), 
"TARIFF_ITEM_SN" VARCHAR2(20) DEFAULT 0, 
"TARIFF_ITEM_NAME" VARCHAR2(64), 
"TEMPLATENO" VARCHAR2(32), 
"USAGE_KEY_INFO" VARCHAR2(500), 
"G_USAGE_KEY_INFO" VARCHAR2(500), 
"LEFT_EVAL_FLAG" NUMBER(1,0) DEFAULT 0, 
"FLAT_RATES_FLAG" NUMBER(2,0) DEFAULT 1
);

CREATE SEQUENCE  "SEQ_TARIFF_SN"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 137637 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "TARIFF_PLAN" 
("TARIFF_PLAN_ID" NUMBER(6,0), 
"TARIFF_PLAN_NAME" VARCHAR2(128), 
"IS_RECURSIVE" NUMBER(1,0) DEFAULT 0, 
"PRECEDENCE" NUMBER(9,0), 
"PROCESS_BEFORE" NUMBER(4,0) DEFAULT 0, 
"PROCESS_AFTER" NUMBER(4,0) DEFAULT 0, 
"PLANTYPE" VARCHAR2(4), 
"NOTE" VARCHAR2(400), 
"PRECEDENCE_ACCDISC" NUMBER(4,0), 
"PRICEPLANTYPE" NUMBER(4,0), 
"REGION" NUMBER(5,0) DEFAULT 0, 
"HISTORY" VARCHAR2(2048), 
"MERGE_MODE" NUMBER(1,0) DEFAULT 1, 
"DYNAMIC_PRECEDENCE" VARCHAR2(200) DEFAULT null, 
"G_DYNAMIC_PRECEDENCE" VARCHAR2(400), 
"CATALOG_TYPE" VARCHAR2(10) DEFAULT '0', 
"SERVICE_FLAG" VARCHAR2(500), 
"G_SERVICE_FLAG" VARCHAR2(500), 
"SUB_DYNAMIC_PRECEDENCE" VARCHAR2(200), 
"G_SUB_DYNAMIC_PRECEDENCE" VARCHAR2(400), 
"PHASE_PRECEDENCE" NUMBER(4,0) DEFAULT 0, 
"TYPE_PRECEDENCE" NUMBER(4,0) DEFAULT 0, 
"CARRYOVER_ENTITYID" NUMBER(4,0), 
"CARRYOVER_ATTRID" NUMBER(8,0)
);

CREATE TABLE "TARIFF_PLAN_ITEM" 
("TARIFF_PLAN_ID" NUMBER(6,0), 
"CALCTYPE" NUMBER(1,0), 
"FEE_ID" NUMBER(9,0), 
"TARIFF_SCHEMA_ID" NUMBER(9,0), 
"CHARGING_EVENT_ID" NUMBER(4,0), 
"PRECEDENCE" NUMBER(4,0), 
"APPLYTIME" DATE, 
"EXPIRETIME" DATE, 
"APPLY_METHOD" NUMBER(1,0), 
"DISCOUNT_TYPE" NUMBER(1,0), 
"BASE_FEE_ID" NUMBER(9,0), 
"DISCOUNT_FEE_ID" NUMBER(9,0), 
"CHARGING_COND" VARCHAR2(512), 
"SWITCH_METHOD" NUMBER(2,0), 
"SWITCH_UNIT" NUMBER(8,0), 
"G_CHARGING_COND" VARCHAR2(1024), 
"BILLCODE" VARCHAR2(32), 
"SELECT_METHOD" NUMBER(1,0), 
"TARIFF_PLAN_ITEM_SN" VARCHAR2(20) DEFAULT 0, 
"TARIFF_PLAN_ITEM_NAME" VARCHAR2(64), 
"SERV_ID" NUMBER(4,0), 
"FEE_ROUND_TYPE" NUMBER(1,0) DEFAULT 0, 
"FEE_ROUND_SCALE" NUMBER(2,0) DEFAULT 2, 
"CATALOG_TYPE" VARCHAR2(10) DEFAULT '0'
);

CREATE TABLE "TARIFF_REDU_AUDIT_LOG" 
("LOGNUM" VARCHAR2(24), 
"OPERATOR" VARCHAR2(16), 
"LOGTIME" DATE, 
"TABLENAME" VARCHAR2(64), 
"MAINTAINTYPE" CHAR(1), 
"KEYVALUE" VARCHAR2(1024), 
"COLNAME" VARCHAR2(64), 
"OLDVALUE" VARCHAR2(1024), 
"NEWVALUE" VARCHAR2(1024), 
"AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, 
"REASON" VARCHAR2(128), 
"AUDIT_TIME" DATE, 
"AUDIT_OPERATOR" VARCHAR2(20), 
"COL_DATATYPE" VARCHAR2(106), 
"CLIENTINFO" VARCHAR2(1024)
);

CREATE TABLE "TARIFF_PLAN_REDU" 
("TARIFF_PLAN_ID" NUMBER(6,0), 
"TARIFF_PLAN_NAME" VARCHAR2(128), 
"IS_RECURSIVE" NUMBER(1,0), 
"PRECEDENCE" NUMBER(9,0), 
"PROCESS_BEFORE" NUMBER(4,0), 
"PROCESS_AFTER" NUMBER(4,0), 
"PLANTYPE" VARCHAR2(4), 
"NOTE" VARCHAR2(400), 
"PRECEDENCE_ACCDISC" NUMBER(4,0), 
"STATUS" NUMBER(1,0)
);

CREATE TABLE "TARIFF_SCHEMA" 
("TARIFF_SCHEMA_ID" NUMBER(9,0), 
"TARIFF_NAME" VARCHAR2(64), 
"TARIFF_TYPE" NUMBER(2,0), 
"FIELDCOUNT" NUMBER(4,0), 
"FIELD_DEF" VARCHAR2(256), 
"MATCH_ORDER" NUMBER(1,0), 
"MATCH_TYPE" NUMBER(1,0), 
"APPLY_METHOD" NUMBER(1,0), 
"REFID" NUMBER(4,0), 
"DISCOUNT_FEE_ID" NUMBER(9,0), 
"G_FIELD_DEF" VARCHAR2(256), 
"ROUND_METHOD" NUMBER(1,0), 
"ROUND_SCALE" NUMBER(2,0), 
"REF_OFFSET" NUMBER(4,0), 
"EVENT_ID" NUMBER(4,0), 
"BILLCODE_ORDER" NUMBER(1,0) DEFAULT 0, 
"CREATETIME" DATE DEFAULT sysdate, 
"REGION" NUMBER(5,0) DEFAULT 0
);

CREATE TABLE "TARIFF_PLAN_ITEM_REDU" 
("TARIFF_PLAN_ID" NUMBER(6,0), 
"CALCTYPE" NUMBER(1,0), 
"FEE_ID" NUMBER(9,0), 
"TARIFF_SCHEMA_ID" NUMBER(9,0), 
"CHARGING_EVENT_ID" NUMBER(4,0), 
"PRECEDENCE" NUMBER(4,0), 
"APPLYTIME" DATE, 
"EXPIRETIME" DATE, 
"APPLY_METHOD" NUMBER(1,0), 
"DISCOUNT_TYPE" NUMBER(1,0), 
"BASE_FEE_ID" NUMBER(9,0), 
"DISCOUNT_FEE_ID" NUMBER(9,0), 
"CHARGING_COND" VARCHAR2(512), 
"SWITCH_METHOD" NUMBER(2,0), 
"SWITCH_UNIT" NUMBER(8,0), 
"G_CHARGING_COND" VARCHAR2(1024), 
"PARAM_SET_TYPE" VARCHAR2(4), 
"PARAM_SET_METHOD" VARCHAR2(4), 
"PARAM_SET_ID" NUMBER(4,0), 
"ATTR_VALUE" NUMBER(9,0)
);

CREATE TABLE "AM_TAX_BILLMERGE_DEF" 
("RULEID" NUMBER(6,0), 
"RULENAME" VARCHAR2(32), 
"RULEORDER" NUMBER(6,0), 
"DESITEMCODE" VARCHAR2(32), 
"ITEMCODE" VARCHAR2(32), 
"PKGCODE" VARCHAR2(32), 
"TARIFFCODE" VARCHAR2(32), 
"INUSE" NUMBER(1,0), 
"REGION" NUMBER(5,0) DEFAULT 999
);


insert into feature_def(name,value) values('system_mode','wb593756');
insert into app_user(user_code) values('JNLH');
insert into app_user(user_code) values('_SYS_');


