#!/usr/bin/env python2.6
# ecoding=utf-8
### cases not in succtest
### Author: yujing.cyj
#Cases that are not suitable to run in succtest can be added below:
# What kind of case is not suitable for rollback:
#1.Execution time exceeds 5min
#2.Dependent on cluster scale, cannot run on a single server

succ_filter=[
'tenant2',
'tenant3',
'tenant_diversity_replica_num_boundary',
'tenant_space_table_refresh',
'tenant',
'tenant.create_many_tin',
'tenant.resource_not_enough',
'tenant.resource_pool_new',
'zz_alter_sys',
'zcreateindex1000',
'zcreate1wpartiton',
'zcreate10000table',
'zaddlmajor_gt64times',
'materialized_view.collect_mv',
'materialized_view.materialized_view',
'materialized_view.mv_basic',
'materialized_view.mv_basic2',
'materialized_view.mv_basic3',
'materialized_view.mv_storage1',
'materialized_view.mv_storage2',
'materialized_view.mv_storage3',
'materialized_view.mv_storage_bug10101539',
'materialized_view.mv_storage_bug10138064',
'materialized_view.mv_storage_bug10414345',
'materialized_view.mv_storage_bug10575767',
'materialized_view.mv_storage_large',
'materialized_view.bug#10432650',
'materialized_view.join_col_collation',
'materialized_view.table_option',
'materialized_view.non_sys_tenant',
'plan_cache.alter_system_flush',
'plan_cache.plan_cache_retry',
'ocp',
'database.database_create',
'database.database_charset',
'database.database_name',
'ddl.multiple_pool',
'outline.outline_use',
'inner_table.all_virtual_core_inner_table',
'alter_system',
#'executor.join_with_part_ddl',
'ctype_utf8mb4_innodb',
'compress_data',
'plan_base_line_for_schema',
'plan_exchange',
'plan_expression_slave',
'spf_bug13044302',
'lob.lob_alter_oracle',
'lob.lob_type_oracle',
'lob.lob_cmp_oracle',
'lob.lob_select_oracle',
'window_function_mysql.window_functions',
'ddl.create_temp_table2_oracle',
'merge_into.merge_insert',
'merge_into.merge_into_normal',
'merge_into.merge_subquery',
'merge_into.merge_update',
'pl.sp_mysql',
'kill_transaction',
'update.update_ignore_multi_row',
'update.update_ignore_multi_stmt',
'update.update_ignore_one_row',
]
