CREATE DATABASE IF NOT EXISTS base_db_1; 
CREATE DATABASE IF NOT EXISTS base_db_2 default CHARACTER SET UTF8;
CREATE DATABASE IF NOT EXISTS base_db_3;
CREATE DATABASE IF NOT EXISTS base_db_4; 
CREATE TABLEGROUP tg1;
CREATE DATABASE IF NOT EXISTS base_db_5 DEFAULT TABLEGROUP tg1; 
CREATE DATABASE IF NOT EXISTS base_db_6;
CREATE DATABASE IF NOT EXISTS base_db_ghost;

DROP DATABASE base_db_ghost;
ALTER DATABASE base_db_3 READ ONLY;
ALTER DATABASE base_db_4 PRIMARY_ZONE = 'z1';



