CREATE DATABASE IF NOT EXISTS inc_db_1; 
CREATE DATABASE IF NOT EXISTS inc_db_2;
CREATE DATABASE IF NOT EXISTS inc_db_3;
CREATE DATABASE IF NOT EXISTS inc_db_4; 
CREATE TABLEGROUP TG2;
CREATE DATABASE IF NOT EXISTS inc_db_5 DEFAULT TABLEGROUP TG2; 
CREATE DATABASE IF NOT EXISTS inc_db_6;
CREATE DATABASE IF NOT EXISTS inc_db_ghost;

DROP DATABASE inc_db_ghost;
ALTER DATABASE inc_db_3 READ ONLY;
ALTER DATABASE inc_db_4 PRIMARY_ZONE = 'z1';
