CREATE OR REPLACE TYPE ty1 IS TABLE OF INT;
CREATE OR REPLACE TYPE ty2 IS TABLE OF VARCHAR2(4000);
CREATE OR REPLACE TYPE ty3 IS OBJECT(col1 INT, col2 DATE);
CREATE OR REPLACE TYPE ty4 IS TABLE OF ty3;
CREATE OR REPLACE TYPE ty5 IS TABLE OF ty4;
CREATE OR REPLACE TYPE ty6 IS OBJECT(col1 ty5, col2 ty4);