
CREATE OR REPLACE PROCEDURE proc IS BEGIN NULL; END;

CREATE OR REPLACE FUNCTION func RETURN INT IS BEGIN RETURN NULL; END;

CREATE OR REPLACE PROCEDURE proc1 IS BEGIN NULL; END;

CREATE OR REPLACE PROCEDURE proc2(x INT, y VARCHAR2, z DATE) IS BEGIN NULL; END;

CREATE OR REPLACE PROCEDURE proc3(x TIMESTAMP WITH TIME ZONE) IS BEGIN NULL; END;

CREATE OR REPLACE PROCEDURE proc4(x PLS_INTEGER) IS BEGIN NULL; END;

CREATE OR REPLACE PROCEDURE proc5(x IN OUT SIMPLE_INTEGER) IS BEGIN NULL; END;

CREATE OR REPLACE FUNCTION func1(x INT) RETURN INT IS BEGIN RETURN 1; END;

CREATE OR REPLACE FUNCTION func2(x INT, y VARCHAR2, z DATE) RETURN VARCHAR2 IS BEGIN NULL; END;

CREATE OR REPLACE FUNCTION func3(x OUT INT, y IN OUT INT) RETURN RAW IS BEGIN NULL; END;

CREATE TABLE t_4_rowtype(col INT);

CREATE OR REPLACE FUNCTION func4(x OUT t_4_rowtype%rowtype) RETURN t_4_rowtype%rowtype IS BEGIN RETURN NULL; END;

CREATE OR REPLACE PROCEDURE proc6(x IN t_4_rowtype%rowtype) IS BEGIN NULL; END;

CREATE OR REPLACE FUNCTION func5(x OUT t_4_rowtype.col%type) RETURN t_4_rowtype.col%type IS BEGIN RETURN NULL; END;

CREATE OR REPLACE PROCEDURE proc7(x IN t_4_rowtype.col%type) IS BEGIN NULL; END;

CREATE OR REPLACE TYPE ty_4_routine IS TABLE OF INT;

CREATE OR REPLACE PROCEDURE proc8(x IN ty_4_routine) IS BEGIN NULL; END;

CREATE OR REPLACE FUNCTION func6(x IN ty_4_routine) RETURN ty_4_routine IS BEGIN NULL; END;

CREATE OR REPLACE PACKAGE pack_4_routine IS TYPE ty IS TABLE OF INT; END;

CREATE OR REPLACE PROCEDURE proc9(x IN pack_4_routine.ty) IS BEGIN NULL; END;

CREATE OR REPLACE FUNCTION func7(x IN pack_4_routine.ty) RETURN pack_4_routine.ty IS BEGIN RETURN NULL; END;

CREATE OR REPLACE FUNCTION view_func RETURN INT IS BEGIN RETURN 1; END;

CREATE VIEW view_dep_func AS SELECT view_func AS COL FROM DUAL;

CREATE OR REPLACE PROCEDURE proc_4_default_val(x INT := 1) IS BEGIN NULL; END;

CREATE OR REPLACE FUNCTION func_4_default_val(x INT := 1) RETURN INT IS BEGIN RETURN 1; END;

CREATE OR REPLACE PACKAGE pack_4_default_val IS PROCEDURE proc(x INT := 1); END;
CREATE OR REPLACE PACKAGE BODY pack_4_default_val IS PROCEDURE proc(x INT := 1) IS BEGIN NULL; END; END;



