CREATE OR REPLACE PACKAGE pack IS TYPE ty IS TABLE OF INT; x INT; PROCEDURE PROC; END;

CREATE OR REPLACE PACKAGE BODY pack IS PROCEDURE PROC IS BEGIN NULL; END; END;

CREATE OR REPLACE PACKAGE view_pack IS FUNCTION func RETURN INT; END;

CREATE OR REPLACE PACKAGE BODY view_pack IS FUNCTION func RETURN INT IS BEGIN RETURN 1; END; END;

CREATE VIEW view_dep_pack AS SELECT view_pack.func() AS COL FROM DUAL;


