CREATE RESOURCE UNIT small_unit MIN_CPU=2, MAX_CPU=4, MEMORY_SIZE='4G';

CREATE RESOURCE UNIT medium_unit MIN_CPU=4, MAX_CPU=8, MEMORY_SIZE='8G';

CREATE RESOURCE UNIT large_unit MIN_CPU=8, MAX_CPU=16, MEMORY_SIZE='20G';

CREATE RESOURCE POOL small_pool UNIT small_unit, UNIT_NUM 1, ZONE_LIST ('z1','z2','z3');
