#package_name:dbms_upgrade
#author: linlin.xll

CREATE OR REPLACE PACKAGE BODY "__DBMS_UPGRADE" IS
  PROCEDURE UPGRADE(package_name VARCHAR2, load_from_file BOOLEAN);
    PRAGMA INTERFACE(c, UPGRADE_SINGLE);
  PROCEDURE UPGRADE_ALL(load_from_file BOOLEAN);
    PRAGMA INTERFACE(c, UPGRADE_ALL);
  PROCEDURE FLUSH_DLL_NCOMP;
    PRAGMA INTERFACE(c, FLUSH_DLL_NCOMP);
END;
//

