#package_name: dbms_application_info
#author: xiaoyi.xy
CREATE OR REPLACE PACKAGE "DBMS_APPLICATION_INFO" IS
  PROCEDURE READ_CLIENT_INFO(CLIENT_INFO OUT VARCHAR2);
  PROCEDURE READ_MODULE(MODULE_NAME OUT VARCHAR2, ACTION_NAME OUT VARCHAR2);
  PROCEDURE SET_ACTION(ACTION_NAME IN VARCHAR2);
  PROCEDURE SET_CLIENT_INFO(CLIENT_INFO IN VARCHAR2);
  PROCEDURE SET_MODULE(MODULE_NAME IN VARCHAR2, ACTION_NAME IN VARCHAR2);
END;

//
