CREATE OR REPLACE PACKAGE BODY DBMS_SESSION IS
  PROCEDURE SET_CONTEXT(NAMESPACE VARCHAR2, ATTRIBUTE VARCHAR2, VALUE VARCHAR2,
                      USERNAME VARCHAR2 DEFAULT NULL,
                      CLIENT_ID VARCHAR2 DEFAULT NULL);
  PRAGMA INTERFACE(c, SET_CONTEXT);
  PROCEDURE SET_IDENTIFIER(CLIENT_ID VARCHAR2);
  PRAGMA INTERFACE(c, SET_IDENTIFIER);
  PROCEDURE CLEAR_CONTEXT(NAMESPACE VARCHAR2, CLIENT_ID VARCHAR2 DEFAULT NULL,
                          ATTRIBUTE VARCHAR2 DEFAULT NULL);
  PRAGMA INTERFACE(c, CLEAR_CONTEXT);
  PROCEDURE CLEAR_ALL_CONTEXT(NAMESPACE VARCHAR2);
  PRAGMA INTERFACE(c, CLEAR_ALL_CONTEXT);
  PROCEDURE CLEAR_IDENTIFIER;
  PRAGMA INTERFACE(c, CLEAR_IDENTIFIER);
  PROCEDURE RESET_PACKAGE;
  PRAGMA INTERFACE(c, RESET_PACKAGE);
END;
//