#package_name: dbms_preprocessor
#author: linlin.xll

CREATE OR REPLACE PACKAGE BODY dbms_preprocessor AS  

  NEW_LINE_C CONSTANT VARCHAR2(1 CHAR) := chr(10);

  MISSING_OBJECT_NAME EXCEPTION;
  PRAGMA EXCEPTION_INIT(MISSING_OBJECT_NAME, -5963);


  PROCEDURE GET_PP_SOURCE_I_1(OBJECT_TYPE VARCHAR2,
                              SCHEMA_NAME VARCHAR2,
                              OBJECT_NAME VARCHAR2,
                              SRC_LINES OUT SOURCE_LINES_T);
  PRAGMA INTERFACE(C, GET_PP_SOURCE_I1);


  PROCEDURE GET_PP_SOURCE_I_2(SOURCE VARCHAR2,
                              SRC_LINES OUT SOURCE_LINES_T);
  PRAGMA INTERFACE(C, GET_PP_SOURCE_I2);


  PROCEDURE GET_PP_SOURCE_I_3(SOURCE SOURCE_LINES_T,
                              SRC_LINES OUT SOURCE_LINES_T);
  PRAGMA INTERFACE(C, GET_PP_SOURCE_I3);


  FUNCTION GET_PP_SOURCE_LINES_INNER(OBJECT_TYPE VARCHAR2, SCHEMA_NAME VARCHAR2, OBJECT_NAME VARCHAR2)
  RETURN SOURCE_LINES_T IS
    SRC_LINES SOURCE_LINES_T;
  BEGIN
    IF SCHEMA_NAME = 'SYS' AND (OBJECT_NAME = 'DBMS_STANDARD' OR OBJECT_NAME = 'STANDARD') THEN
      SELECT TEXT BULK COLLECT INTO SRC_LINES FROM ALL_SOURCE
        WHERE TYPE = OBJECT_TYPE AND OWNER = SCHEMA_NAME AND NAME = OBJECT_NAME;
    ELSE
      GET_PP_SOURCE_I_1(OBJECT_TYPE, SCHEMA_NAME, OBJECT_NAME, SRC_LINES);
    END IF; 
    RETURN SRC_LINES;
  END GET_PP_SOURCE_LINES_INNER;


  PROCEDURE PRINT_POST_PROCESSED_SOURCE(OBJECT_TYPE VARCHAR2, SCHEMA_NAME VARCHAR2, OBJECT_NAME VARCHAR2) IS
    PRINT_LINES SOURCE_LINES_T;
    IDX         PLS_INTEGER;
  BEGIN
    PRINT_LINES := GET_POST_PROCESSED_SOURCE(OBJECT_TYPE, SCHEMA_NAME, OBJECT_NAME);
    IDX := PRINT_LINES.FIRST;
    WHILE IDX IS NOT NULL LOOP
      DBMS_OUTPUT.PUT_LINE(TRIM(TRAILING NEW_LINE_C FROM PRINT_LINES(IDX)));
      IDX := PRINT_LINES.NEXT(IDX);
    END LOOP;
  END PRINT_POST_PROCESSED_SOURCE;


  PROCEDURE PRINT_POST_PROCESSED_SOURCE(SOURCE VARCHAR2) IS
    PRINT_LINES SOURCE_LINES_T;
    IDX       PLS_INTEGER;
  BEGIN
    PRINT_LINES := GET_POST_PROCESSED_SOURCE(SOURCE);
    IDX := PRINT_LINES.FIRST;
    WHILE IDX IS NOT NULL LOOP
      DBMS_OUTPUT.PUT_LINE(TRIM(TRAILING NEW_LINE_C FROM PRINT_LINES(IDX)));
      IDX := PRINT_LINES.NEXT(IDX);
    END LOOP;
  END;

  PROCEDURE PRINT_POST_PROCESSED_SOURCE(SOURCE SOURCE_LINES_T) IS
    SRC_LINES SOURCE_LINES_T;
    IDX       PLS_INTEGER;
  BEGIN
    SRC_LINES := GET_POST_PROCESSED_SOURCE(SOURCE);
        IDX := SRC_LINES.FIRST;
    WHILE IDX IS NOT NULL LOOP
      DBMS_OUTPUT.PUT_LINE(TRIM(TRAILING NEW_LINE_C FROM SRC_LINES(IDX)));
      IDX := SRC_LINES.NEXT(IDX);
    END LOOP;
  END PRINT_POST_PROCESSED_SOURCE;


  FUNCTION GET_POST_PROCESSED_SOURCE(OBJECT_TYPE VARCHAR2, SCHEMA_NAME VARCHAR2, OBJECT_NAME VARCHAR2)
  RETURN SOURCE_LINES_T IS
    SCHE_NAME VARCHAR2(128);
    OBJ_TYPE  VARCHAR2(128);
    OBJ_NAME  VARCHAR2(128);
    LINE_NUM  NUMBER;
  BEGIN
    OBJ_TYPE := UPPER(OBJECT_TYPE);
    IF (OBJ_TYPE IS NULL OR OBJ_TYPE NOT IN ('PACKAGE', 'PACKAGE BODY', 'PROCEDURE', 'FUNCTION', 'TRIGGER', 'TYPE', 'TYPE BODY')) THEN
      DBMS_SYS_ERROR.RAISE_SYSTEM_ERROR(-5961, OBJ_TYPE);
    END IF;

    IF SUBSTR(OBJECT_NAME, 1, 1) = '"' AND SUBSTR(OBJECT_NAME, LENGTH(OBJECT_NAME), 1) = '"' THEN
      OBJ_NAME := SUBSTR(OBJECT_NAME, 2, LENGTH(OBJECT_NAME) - 2);
    ELSE
      OBJ_NAME := UPPER(OBJECT_NAME);
    END IF;

    IF OBJ_NAME IS NULL THEN
      RAISE MISSING_OBJECT_NAME;
    END IF;

    SCHE_NAME := SCHEMA_NAME;
    IF SCHE_NAME IS NULL THEN
      SCHE_NAME := SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA');
    ELSIF SUBSTR(SCHE_NAME, 1, 1) = '"' AND SUBSTR(SCHE_NAME, LENGTH(SCHE_NAME), 1) = '"' THEN
      SCHE_NAME := SUBSTR(SCHE_NAME, 2, LENGTH(SCHE_NAME) - 2);
    ELSE 
      SCHE_NAME := UPPER(SCHE_NAME);
    END IF;

    BEGIN
      SELECT LINE INTO LINE_NUM FROM ALL_SOURCE
        WHERE TYPE = OBJ_TYPE AND
              OWNER = SCHE_NAME AND
              NAME = OBJ_NAME AND ROWNUM = 1;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      DBMS_SYS_ERROR.RAISE_SYSTEM_ERROR(-5962, OBJ_TYPE, SCHE_NAME, OBJ_NAME);
    WHEN OTHERS THEN
      RAISE;
    END;

    RETURN GET_PP_SOURCE_LINES_INNER(OBJ_TYPE, SCHE_NAME, OBJ_NAME);
  END GET_POST_PROCESSED_SOURCE;


  FUNCTION GET_POST_PROCESSED_SOURCE(SOURCE VARCHAR2) 
  RETURN SOURCE_LINES_T IS
    SRC_LINES SOURCE_LINES_T;
  BEGIN
    IF SOURCE IS NOT NULL THEN
      GET_PP_SOURCE_I_2(SOURCE, SRC_LINES);
      RETURN SRC_LINES;
    END IF;
    DBMS_SYS_ERROR.RAISE_SYSTEM_ERROR(-5960);
  END GET_POST_PROCESSED_SOURCE;


  FUNCTION GET_POST_PROCESSED_SOURCE(SOURCE SOURCE_LINES_T)
  RETURN SOURCE_LINES_T IS
    SRC_LINES SOURCE_LINES_T;
  BEGIN

    FOR IDX IN SOURCE.FIRST() .. SOURCE.LAST() LOOP
      IF SOURCE(IDX) IS NOT NULL THEN
        GET_PP_SOURCE_I_3(SOURCE, SRC_LINES);
        RETURN SRC_LINES;
      END IF;
    END LOOP;

    DBMS_SYS_ERROR.RAISE_SYSTEM_ERROR(-5960);
  END GET_POST_PROCESSED_SOURCE;
END;
//
