#package_name:dbms_plancache
#author: xiaoyi.xy
CREATE OR REPLACE PACKAGE BODY "DBMS_PLAN_CACHE" IS
  PROCEDURE PURGE(
    SQL_ID IN VARCHAR,
    SCHEMA IN VARCHAR := NULL,
    GLOBAL IN BOOLEAN DEFAULT FALSE);
    PRAGMA INTERFACE(c, PLAN_CACHE_PURGE);
END;
//

