#package_name:dbms_application_info
#author: xiaoyi.xy
CREATE OR REPLACE PACKAGE BODY "DBMS_APPLICATION_INFO" IS
  PROCEDURE READ_CLIENT_INFO(CLIENT_INFO OUT VARCHAR2);
  PRAGMA INTERFACE(c, READ_CLIENT_INFO);
  PROCEDURE READ_MODULE(MODULE_NAME OUT VARCHAR2, ACTION_NAME OUT VARCHAR2);
  PRAGMA INTERFACE(c, READ_MODULE);
  PROCEDURE SET_ACTION(ACTION_NAME IN VARCHAR2);
  PRAGMA INTERFACE(c, SET_ACTION);
  PROCEDURE SET_CLIENT_INFO(CLIENT_INFO IN VARCHAR2);
  PRAGMA INTERFACE(c, SET_CLIENT_INFO);
  PROCEDURE SET_MODULE(MODULE_NAME IN VARCHAR2, ACTION_NAME IN VARCHAR2);
  PRAGMA INTERFACE(c, SET_MODULE);
END;

//
