#package_name:dbms_types, anydata, anytype
#author: linlin.xll

CREATE OR REPLACE TYPE BODY AnyType AS

  STATIC PROCEDURE BEGINCREATE(TYPECODE IN PLS_INTEGER, ATYPE OUT NOCOPY ANYTYPE);
     PRAGMA INTERFACE (c, BEGINCREATE_ANYTYPE);

  MEMBER PROCEDURE SETINFO(SELF IN OUT NOCOPY ANYTYPE,
         PREC IN PLS_INTEGER, SCALE IN PLS_INTEGER,
         LEN IN PLS_INTEGER,
         CSID IN PLS_INTEGER, CSFRM IN PLS_INTEGER,
         ATYPE IN ANYTYPE DEFAULT NULL,
         ELEM_TC IN PLS_INTEGER DEFAULT NULL,
         ELEM_COUNT IN PLS_INTEGER DEFAULT 0);
     PRAGMA INTERFACE (c, SETINFO);

  MEMBER PROCEDURE ADDATTR(SELF IN OUT NOCOPY ANYTYPE,
         ANAME IN VARCHAR2,
         TYPECODE IN PLS_INTEGER,
         PREC IN PLS_INTEGER, SCALE IN PLS_INTEGER,
         LEN IN PLS_INTEGER,
         CSID IN PLS_INTEGER, CSFRM IN PLS_INTEGER,
         ATTR_TYPE IN ANYTYPE DEFAULT NULL);
     PRAGMA INTERFACE (c, ADDATTR);

  MEMBER PROCEDURE ENDCREATE(SELF IN OUT NOCOPY ANYTYPE);
     PRAGMA INTERFACE (c, ENDCREATE_ANYTYPE);

  STATIC FUNCTION GETPERSISTENT(SCHEMA_NAME IN VARCHAR2,
                    TYPE_NAME IN VARCHAR2,
                    VERSION IN VARCHAR2 DEFAULT NULL) RETURN ANYTYPE;
     PRAGMA INTERFACE (c, GETPERSISTENT);

  MEMBER FUNCTION GETINFO (SELF IN ANYTYPE,
          PREC OUT PLS_INTEGER, SCALE OUT PLS_INTEGER,
          LEN OUT PLS_INTEGER, CSID OUT PLS_INTEGER,
          CSFRM OUT PLS_INTEGER,
          SCHEMA_NAME OUT VARCHAR2, TYPE_NAME OUT VARCHAR2, VERSION OUT VARCHAR2,
          NUMELEMS OUT PLS_INTEGER) RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETINFO);

   MEMBER FUNCTION GETATTRELEMINFO (SELF IN ANYTYPE,
          POS IN PLS_INTEGER, PREC OUT PLS_INTEGER, SCALE OUT PLS_INTEGER,
          LEN OUT PLS_INTEGER, CSID OUT PLS_INTEGER, CSFRM OUT PLS_INTEGER,
          ATTR_ELT_TYPE OUT ANYTYPE, ANAME OUT VARCHAR2) RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETATTRELEMINFO);
END;
//

CREATE OR REPLACE TYPE BODY AnyData AS

  STATIC FUNCTION CONVERTNUMBER(NUM IN NUMBER) RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTNUMBER);
  STATIC FUNCTION CONVERTDATE(DAT IN DATE) RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTDATE);
  STATIC FUNCTION CONVERTCHAR(C IN CHAR) RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTCHAR);
  STATIC FUNCTION CONVERTVARCHAR(C IN VARCHAR) RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTVARCHAR);
  STATIC FUNCTION CONVERTVARCHAR2(C IN VARCHAR2) RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTVARCHAR2);
  STATIC FUNCTION CONVERTRAW(R IN RAW) RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTRAW);
  STATIC FUNCTION CONVERTBLOB(B IN BLOB) RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTBLOB);
  STATIC FUNCTION CONVERTCLOB(C IN CLOB) RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTCLOB);

  STATIC FUNCTION CONVERTOBJECT(OBJ IN "<ADT_1>") RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTOBJECT);

  STATIC FUNCTION CONVERTCOLLECTION(COL IN "<COLLECTION_1>") RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTCOLLECTION);
  STATIC FUNCTION  CONVERTTIMESTAMP(TS IN TIMESTAMP_UNCONSTRAINED) RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTTIMESTAMP);
  STATIC FUNCTION CONVERTTIMESTAMPTZ(TS IN TIMESTAMP_TZ_UNCONSTRAINED) RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTTIMESTAMPTZ);
  STATIC FUNCTION CONVERTTIMESTAMPLTZ(TS IN TIMESTAMP_LTZ_UNCONSTRAINED) RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTTIMESTAMPLTZ);
  STATIC FUNCTION CONVERTINTERVALYM(INV IN YMINTERVAL_UNCONSTRAINED) RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTINTERVALYM);
  STATIC FUNCTION CONVERTINTERVALDS(INV IN DSINTERVAL_UNCONSTRAINED) RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTINTERVALDS);
  STATIC FUNCTION  CONVERTNCHAR(NC IN NCHAR) RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTNCHAR);
  STATIC FUNCTION  CONVERTNVARCHAR2(NC IN NVARCHAR2) RETURN ANYDATA;
     PRAGMA INTERFACE (c, CONVERTNVARCHAR2);

  STATIC FUNCTION CONVERTBFLOAT(FL IN BINARY_FLOAT) RETURN ANYDATA;
     PRAGMA INTERFACE (C, CONVERTBFLOAT);
  STATIC FUNCTION CONVERTBDOUBLE(DBL IN BINARY_DOUBLE) RETURN ANYDATA;
     PRAGMA INTERFACE (C, CONVERTBDOUBLE);
  STATIC FUNCTION CONVERTUROWID(RID IN UROWID) RETURN ANYDATA;
     PRAGMA INTERFACE (C, CONVERTUROWID);

  STATIC PROCEDURE BEGINCREATE(DTYPE IN OUT NOCOPY ANYTYPE,
                               ADATA OUT NOCOPY ANYDATA);
     PRAGMA INTERFACE (c, BEGINCREATE_ANYDATA);

  MEMBER PROCEDURE PIECEWISE(SELF IN OUT NOCOPY ANYDATA);
     PRAGMA INTERFACE (c, PIECEWISE);
  MEMBER PROCEDURE SETNUMBER(SELF IN OUT NOCOPY ANYDATA, NUM IN NUMBER,
                    LAST_ELEM BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETNUMBER);
  MEMBER PROCEDURE SETDATE(SELF IN OUT NOCOPY ANYDATA, DAT IN DATE,
                    LAST_ELEM BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETDATE);
  MEMBER PROCEDURE SETCHAR(SELF IN OUT NOCOPY ANYDATA, C IN CHAR,
                    LAST_ELEM BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETCHAR);
  MEMBER PROCEDURE SETVARCHAR(SELF IN OUT NOCOPY ANYDATA, C IN VARCHAR,
                    LAST_ELEM BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETVARCHAR);
  MEMBER PROCEDURE SETVARCHAR2(SELF IN OUT NOCOPY ANYDATA,
                    C IN VARCHAR2, LAST_ELEM BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETVARCHAR2);
  MEMBER PROCEDURE SETRAW(SELF IN OUT NOCOPY ANYDATA, R IN RAW,
                    LAST_ELEM BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETRAW);
  MEMBER PROCEDURE SETBLOB(SELF IN OUT NOCOPY ANYDATA, B IN BLOB,
                    LAST_ELEM BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETBLOB);
  MEMBER PROCEDURE SETCLOB(SELF IN OUT NOCOPY ANYDATA, C IN CLOB,
                    LAST_ELEM BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETCLOB);

  MEMBER PROCEDURE SETOBJECT(SELF IN OUT NOCOPY ANYDATA,
                    OBJ IN "<ADT_1>", LAST_ELEM BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETOBJECT);

  MEMBER PROCEDURE SETCOLLECTION(SELF IN OUT NOCOPY ANYDATA,
                    COL IN "<COLLECTION_1>", LAST_ELEM BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETCOLLECTION);
  MEMBER PROCEDURE SETTIMESTAMP(SELF IN OUT NOCOPY ANYDATA, TS IN TIMESTAMP_UNCONSTRAINED,
                    LAST_ELEM IN BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETTIMESTAMP);
  MEMBER PROCEDURE SETTIMESTAMPTZ(SELF IN OUT NOCOPY ANYDATA,
                    TS IN TIMESTAMP_TZ_UNCONSTRAINED,
                    LAST_ELEM IN BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETTIMESTAMPTZ);
  MEMBER PROCEDURE SETTIMESTAMPLTZ(SELF IN OUT NOCOPY ANYDATA,
                    TS IN TIMESTAMP_LTZ_UNCONSTRAINED,
                    LAST_ELEM IN BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETTIMESTAMPLTZ);
  MEMBER PROCEDURE SETINTERVALYM(SELF IN OUT NOCOPY ANYDATA,
                    INV IN YMINTERVAL_UNCONSTRAINED,
                    LAST_ELEM IN BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETINTERVALYM);
  MEMBER PROCEDURE SETINTERVALDS(SELF IN OUT NOCOPY ANYDATA,
                    INV IN DSINTERVAL_UNCONSTRAINED,
                    LAST_ELEM IN BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETINTERVALDS);
  MEMBER PROCEDURE SETNCHAR(SELF IN OUT NOCOPY ANYDATA,
                    NC IN NCHAR, LAST_ELEM IN BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETNCHAR);
  MEMBER PROCEDURE SETNVARCHAR2(SELF IN OUT NOCOPY ANYDATA,
                    NC IN NVARCHAR2, LAST_ELEM IN BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (c, SETNVARCHAR2);

  MEMBER PROCEDURE SETBFLOAT(SELF IN OUT NOCOPY ANYDATA,
                             FL IN BINARY_FLOAT,
                            LAST_ELEM IN BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (C, SETBFLOAT);
  MEMBER PROCEDURE SETBDOUBLE(SELF IN OUT NOCOPY ANYDATA,
                              DBL IN BINARY_DOUBLE,
                             LAST_ELEM IN BOOLEAN DEFAULT FALSE);
     PRAGMA INTERFACE (C, SETBDOUBLE);

  MEMBER PROCEDURE ENDCREATE(SELF IN OUT NOCOPY ANYDATA);
     PRAGMA INTERFACE (c, ENDCREATE_ANYDATA);

  MEMBER FUNCTION GETTYPENAME(SELF IN ANYDATA) RETURN VARCHAR2 DETERMINISTIC;
     PRAGMA INTERFACE (c, GETTYPENAME);

  MEMBER FUNCTION GETTYPE(SELF IN ANYDATA, TYP OUT NOCOPY ANYTYPE) RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETTYPE);

  MEMBER FUNCTION GETNUMBER(SELF IN ANYDATA, NUM OUT NOCOPY NUMBER) RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETNUMBER);
  MEMBER FUNCTION GETDATE(SELF IN ANYDATA, DAT OUT NOCOPY DATE) RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETDATE);
  MEMBER FUNCTION GETCHAR(SELF IN ANYDATA, C OUT NOCOPY CHAR) RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETCHAR);
  MEMBER FUNCTION GETVARCHAR(SELF IN ANYDATA, C OUT NOCOPY VARCHAR) RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETVARCHAR);
  MEMBER FUNCTION GETVARCHAR2(SELF IN ANYDATA, C OUT NOCOPY VARCHAR2) RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETVARCHAR2);
  MEMBER FUNCTION GETRAW(SELF IN ANYDATA, R OUT NOCOPY RAW) RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETRAW);
  MEMBER FUNCTION GETBLOB(SELF IN ANYDATA, B OUT NOCOPY BLOB) RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETBLOB);
  MEMBER FUNCTION GETCLOB(SELF IN ANYDATA, C OUT NOCOPY CLOB) RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETCLOB);

  MEMBER FUNCTION GETOBJECT(SELF IN ANYDATA, OBJ OUT NOCOPY "<ADT_1>") RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETOBJECT);

  MEMBER FUNCTION GETCOLLECTION(SELF IN ANYDATA, COL OUT NOCOPY "<COLLECTION_1>") RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETCOLLECTION);
  MEMBER FUNCTION GETTIMESTAMP(SELF IN ANYDATA, TS OUT NOCOPY TIMESTAMP_UNCONSTRAINED)
       RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETTIMESTAMP);
  MEMBER FUNCTION GETTIMESTAMPTZ(SELF IN ANYDATA,
       TS OUT NOCOPY TIMESTAMP_TZ_UNCONSTRAINED) RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETTIMESTAMPTZ);
  MEMBER FUNCTION GETTIMESTAMPLTZ(SELF IN ANYDATA,
       TS OUT NOCOPY TIMESTAMP_LTZ_UNCONSTRAINED) RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETTIMESTAMPLTZ);
  MEMBER FUNCTION GETINTERVALYM(SELF IN ANYDATA,
       INV IN OUT NOCOPY YMINTERVAL_UNCONSTRAINED) RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETINTERVALYM);
  MEMBER FUNCTION GETINTERVALDS(SELF IN ANYDATA,
       INV IN OUT NOCOPY DSINTERVAL_UNCONSTRAINED) RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETINTERVALDS);
  MEMBER FUNCTION GETNCHAR(SELF IN ANYDATA, NC OUT NOCOPY NCHAR)
       RETURN PLS_INTEGER;
     PRAGMA INTERFACE (c, GETNCHAR);
  MEMBER FUNCTION GETNVARCHAR2(SELF IN ANYDATA, NC OUT NOCOPY NVARCHAR2)
       RETURN PLS_INTEGER;
     PRAGMA INTERFACE (C, GETNVARCHAR2);

  MEMBER FUNCTION GETBFLOAT(SELF IN ANYDATA, FL OUT NOCOPY BINARY_FLOAT)
                              RETURN PLS_INTEGER;
     PRAGMA INTERFACE (C, GETBFLOAT);
  MEMBER FUNCTION GETBDOUBLE(SELF IN ANYDATA, DBL OUT NOCOPY BINARY_DOUBLE)
                              RETURN PLS_INTEGER;
     PRAGMA INTERFACE (C, GETBDOUBLE);

  MEMBER FUNCTION ACCESSNUMBER(SELF IN ANYDATA) RETURN NUMBER DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSNUMBER);
  MEMBER FUNCTION ACCESSDATE(SELF IN ANYDATA) RETURN DATE DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSDATE);
  MEMBER FUNCTION ACCESSCHAR(SELF IN ANYDATA) RETURN CHAR DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSCHAR);
  MEMBER FUNCTION ACCESSVARCHAR(SELF IN ANYDATA) RETURN VARCHAR DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSVARCHAR);
  MEMBER FUNCTION ACCESSVARCHAR2(SELF IN ANYDATA) RETURN VARCHAR2 DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSVARCHAR2);
  MEMBER FUNCTION ACCESSRAW(SELF IN ANYDATA) RETURN RAW DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSRAW);
  MEMBER FUNCTION ACCESSBLOB(SELF IN ANYDATA) RETURN BLOB DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSBLOB);
  MEMBER FUNCTION ACCESSCLOB(SELF IN ANYDATA) RETURN CLOB DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSCLOB);

  MEMBER FUNCTION ACCESSTIMESTAMP(SELF IN ANYDATA) RETURN TIMESTAMP_UNCONSTRAINED
             DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSTIMESTAMP);
  MEMBER FUNCTION ACCESSTIMESTAMPTZ(SELF IN ANYDATA)
         RETURN TIMESTAMP_TZ_UNCONSTRAINED DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSTIMESTAMPTZ);
  MEMBER FUNCTION ACCESSTIMESTAMPLTZ(SELF IN ANYDATA)
         RETURN TIMESTAMP_LTZ_UNCONSTRAINED DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSTIMESTAMPLTZ);
  MEMBER FUNCTION ACCESSINTERVALYM(SELF IN ANYDATA)
         RETURN YMINTERVAL_UNCONSTRAINED DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSINTERVALYM);
  MEMBER FUNCTION ACCESSINTERVALDS(SELF IN ANYDATA)
         RETURN DSINTERVAL_UNCONSTRAINED DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSINTERVALDS);
  MEMBER FUNCTION ACCESSNCHAR(SELF IN ANYDATA) RETURN NCHAR DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSNCHAR);
  MEMBER FUNCTION ACCESSNVARCHAR2(SELF IN ANYDATA) RETURN NVARCHAR2
         DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSNVARCHAR2);

  MEMBER FUNCTION ACCESSBFLOAT(SELF IN ANYDATA) RETURN BINARY_FLOAT DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSBFLOAT);
  MEMBER FUNCTION ACCESSBDOUBLE(SELF IN ANYDATA) RETURN BINARY_DOUBLE DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSBDOUBLE);
  MEMBER FUNCTION ACCESSUROWID(SELF IN ANYDATA) RETURN UROWID DETERMINISTIC;
     PRAGMA INTERFACE (C, ACCESSUROWID);
END;
//
