CREATE OR REPLACE PACKAGE BODY dbms_job IS

  FUNCTION EXTRACT_UTC(D DATE) RETURN DATE IS
    DATE_FMT VARCHAR2(30) := 'YYYY-MM-DD HH24:MI:SS';
  BEGIN
    RETURN TO_DATE(TO_CHAR(SYS_EXTRACT_UTC(TO_TIMESTAMP(TO_CHAR(D, DATE_FMT), DATE_FMT)), DATE_FMT), DATE_FMT);
  END;

  FUNCTION FIND_DATE(INTERVAL IN VARCHAR2) RETURN DATE IS
    CUR_DATE DATE;
    TAR_DATE DATE := NULL;
    DATE_FMT VARCHAR2(30) := 'YYYY-MM-DD HH24:MI:SS';
  BEGIN
    IF INTERVAL IS NOT NULL THEN
      BEGIN
        EXECUTE IMMEDIATE 'SELECT ' || INTERVAL || ' FROM DUAL' INTO TAR_DATE;
        TAR_DATE := EXTRACT_UTC(TAR_DATE);
        CUR_DATE := EXTRACT_UTC(SYSDATE);
      EXCEPTION
        WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20000, 'OBE-23319: parameter value "' || INTERVAL || '" is not appropriate');
      END;
      IF TAR_DATE < CUR_DATE THEN
        RAISE_APPLICATION_ERROR(-20000, 'OBE-23420: interval must evaluate to a time in the future');
      END IF;
    END IF;
    RETURN TAR_DATE;
  END;

  PROCEDURE PARSE_JOB(WHAT IN VARCHAR2) IS
    CUR_HANDLER INTEGER;
  BEGIN
    CUR_HANDLER := DBMS_SQL.OPEN_CURSOR;
    DBMS_SQL.PARSE(CUR_HANDLER,
                   'DECLARE '                          ||
                   '  JOB BINARY_INTEGER := 1; '       ||
                   '  BROKEN BOOLEAN := TRUE; '        ||
                   '  NEXT_DATE DATE := SYSDATE + 1; ' ||
                   'BEGIN '                            ||
                      WHAT                             ||
                   ' END;',
                   DBMS_SQL.NATIVE);
    DBMS_SQL.CLOSE_CURSOR(CUR_HANDLER);
    EXCEPTION
      WHEN OTHERS THEN
        IF DBMS_SQL.IS_OPEN(CUR_HANDLER) THEN
          DBMS_SQL.CLOSE_CURSOR(CUR_HANDLER);
        END IF;
        RAISE;
  END;

  PROCEDURE submit(job       OUT BINARY_INTEGER,
                   what      IN  VARCHAR2,
                   next_date IN  DATE DEFAULT sysdate,
                   interval  IN  VARCHAR2 DEFAULT 'null',
                   no_parse  IN  BOOLEAN DEFAULT FALSE,
                   zone      IN  VARCHAR2 DEFAULT NULL,
                   force     IN  BOOLEAN DEFAULT FALSE) IS
    NUM      BINARY_INTEGER;
    LUSER    VARCHAR(128);
    PUSER    VARCHAR(128);
    CUSER    VARCHAR(128);
    TAR_DATE DATE;
    CNT      BINARY_INTEGER := 0;
  BEGIN
    DBMS_IJOB.ZONE_CHECK(ZONE, NVL(FORCE, FALSE));

    IF NOT NO_PARSE THEN
      TAR_DATE := FIND_DATE(INTERVAL);
      PARSE_JOB(WHAT);
    END IF;

    PUSER := DBMS_IJOB.PUSER();
    LUSER := SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA');
    CUSER := SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA');
    TAR_DATE := EXTRACT_UTC(NEXT_DATE);

    LOOP
      IF CNT > 1000 THEN
        RAISE_APPLICATION_ERROR(-20000, 'OBE-23422: Oceanbase Server could not generate an unused job number');
      END IF;
      NUM := DBMS_IJOB.NEXTVALS;
      BEGIN
        DBMS_IJOB.SUBMIT(NUM, LUSER, PUSER, CUSER, TAR_DATE, INTERVAL, FALSE, WHAT, NULL, NULL);
        DBMS_IJOB.SET_JOB_AFFINITY(NUM, ZONE);
        EXIT;
      EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN CNT := CNT + 1;
        WHEN OTHERS THEN RAISE;
      END;
    END LOOP;

    JOB := NUM;
  END;

  PROCEDURE REMOVE(JOB IN  BINARY_INTEGER ) IS
  BEGIN
    DBMS_IJOB.CHECK_PRIVS(JOB);
    DBMS_IJOB.REMOVE(JOB);
  END;

  PROCEDURE change(job       IN  BINARY_INTEGER,
                   what      IN  VARCHAR2,
                   next_date IN  DATE,
                   interval  IN  VARCHAR2,
                   zone      IN  VARCHAR2 DEFAULT NULL,
                   force     IN  BOOLEAN DEFAULT FALSE) IS
  BEGIN
    IF WHAT IS NOT NULL THEN
      DBMS_JOB.WHAT(JOB, WHAT);
    END IF;
    IF NEXT_DATE IS NOT NULL THEN
      DBMS_JOB.NEXT_DATE(JOB, NEXT_DATE);
    END IF;
    IF INTERVAL IS NOT NULL THEN
      DBMS_JOB.INTERVAL(JOB, INTERVAL);
    END IF;
    IF ZONE IS NOT NULL THEN
      DBMS_JOB.ZONE(JOB, ZONE, FORCE);
    END IF;
  END;

  PROCEDURE WHAT(JOB  IN BINARY_INTEGER,
                 WHAT IN VARCHAR2 ) IS
  BEGIN
    DBMS_IJOB.CHECK_PRIVS(JOB);
    PARSE_JOB(WHAT);
    DBMS_IJOB.WHAT(JOB, WHAT);
  END;

  PROCEDURE NEXT_DATE(JOB       IN BINARY_INTEGER,
                      NEXT_DATE IN DATE) IS
    TAR_DATE DATE;
  BEGIN
    TAR_DATE := EXTRACT_UTC(NEXT_DATE);
    DBMS_IJOB.CHECK_PRIVS(JOB);
    DBMS_IJOB.NEXT_DATE(JOB, TAR_DATE);
  END;

  PROCEDURE ZONE (JOB   IN BINARY_INTEGER,
                  ZONE  IN VARCHAR2,
                  FORCE IN BOOLEAN DEFAULT FALSE) IS
  BEGIN
    DBMS_IJOB.CHECK_PRIVS(JOB);
    DBMS_IJOB.ZONE(JOB, ZONE, FORCE);
  END;

  PROCEDURE INTERVAL(JOB      IN BINARY_INTEGER,
                     INTERVAL IN VARCHAR2 ) IS
    NEXT_DATE  DATE;
  BEGIN
    DBMS_IJOB.CHECK_PRIVS(JOB);
    NEXT_DATE := FIND_DATE(INTERVAL);
    DBMS_IJOB.INTERVAL(JOB, INTERVAL);
  END;

  PROCEDURE BROKEN(JOB       IN BINARY_INTEGER,
                   BROKEN    IN BOOLEAN,
                   NEXT_DATE IN DATE DEFAULT SYSDATE) IS
    TAR_DATE DATE;
  BEGIN
    TAR_DATE := EXTRACT_UTC(NEXT_DATE);
    DBMS_IJOB.CHECK_PRIVS(JOB);
    DBMS_IJOB.BROKEN(JOB, BROKEN, TAR_DATE);
  END;

  PROCEDURE RUN(JOB   IN BINARY_INTEGER,
                FORCE IN BOOLEAN DEFAULT FALSE) IS
  BEGIN
    DBMS_IJOB.CHECK_PRIVS(JOB);
    DBMS_IJOB.RUN(JOB, FORCE);
  END;

  PROCEDURE USER_EXPORT(JOB    IN     BINARY_INTEGER,
                        MYCALL IN OUT VARCHAR2) IS
  BEGIN
    DBMS_IJOB.USER_EXPORT(JOB, MYCALL);
  END;

END;
//
