#package_name:utl_encode
#author: longzhong.wlz

CREATE OR REPLACE PACKAGE BODY UTL_ENCODE IS
  FUNCTION BASE64_ENCODE(SRC IN RAW) RETURN RAW;
    PRAGMA INTERFACE(c, BASE64_ENCODE);

  FUNCTION BASE64_DECODE(SRC IN RAW) RETURN RAW;
    PRAGMA INTERFACE(c, BASE64_DECODE);

  FUNCTION QUOTED_PRINTABLE_ENCODE(SRC IN RAW) RETURN RAW;
    PRAGMA INTERFACE(c, QUOTED_PRINTABLE_ENCODE);

  FUNCTION QUOTED_PRINTABLE_DECODE(SRC IN RAW) RETURN RAW;
    PRAGMA INTERFACE(c, QUOTED_PRINTABLE_DECODE);

  FUNCTION MIMEHEADER_ENCODE (
    buf            IN  VARCHAR2 CHARACTER SET ANY_CS,
    encode_charset IN  VARCHAR2 DEFAULT NULL,
    encoding       IN  PLS_INTEGER DEFAULT NULL) RETURN VARCHAR2;
    PRAGMA INTERFACE(c, MIMEHEADER_ENCODE);

  FUNCTION MIMEHEADER_DECODE (
    buf    IN   VARCHAR2 CHARACTER SET ANY_CS) RETURN VARCHAR2;
    PRAGMA INTERFACE(c, MIMEHEADER_DECODE);

  FUNCTION TEXT_ENCODE (
   buf            IN  VARCHAR2 CHARACTER SET ANY_CS,
   encode_charset IN  VARCHAR2 DEFAULT NULL,
   encoding       IN  PLS_INTEGER DEFAULT NULL) RETURN VARCHAR2;
   PRAGMA INTERFACE(c, TEXT_ENCODE);

  FUNCTION TEXT_DECODE(
   buf            IN  VARCHAR2 CHARACTER SET ANY_CS,
   encode_charset IN  VARCHAR2 DEFAULT NULL,
   encoding       IN  PLS_INTEGER DEFAULT NULL) RETURN VARCHAR2;
   PRAGMA INTERFACE(c, TEXT_DECODE);

  FUNCTION UUENCODE (
   r          IN RAW,
   type       IN PLS_INTEGER DEFAULT 1,
   filename   IN VARCHAR2 DEFAULT 'uuencode.txt',
   permission IN VARCHAR2 DEFAULT '0') RETURN RAW;
   PRAGMA INTERFACE(c, UU_ENCODE);
   
  FUNCTION UUDECODE(r IN RAW) RETURN RAW;
   PRAGMA INTERFACE(c, UU_DECODE);
END;
//
