CREATE OR REPLACE PACKAGE BODY dbms_ijob IS

  FUNCTION PUSER RETURN VARCHAR2 IS
  BEGIN
    RETURN SYS_CONTEXT('USERENV','SESSION_USER');
  END;

  FUNCTION CLUSER RETURN VARCHAR2 IS
  BEGIN
    RETURN SYS_CONTEXT('USERENV','CURRENT_SCHEMA');
  END;

  FUNCTION NEXTVALS RETURN BINARY_INTEGER IS
    MYNUM BINARY_INTEGER;
  BEGIN
    SELECT MAX(JOB) INTO MYNUM FROM "SYS"."ALL_VIRTUAL_JOB_REAL_AGENT";
    RETURN NVL( MYNUM, 1);
  END;

  FUNCTION BIT(FLAG IN NUMBER, VAL IN NUMBER) RETURN BOOLEAN IS
  BEGIN
    IF TRUNC(FLAG/VAL) / 2 = TRUNC(TRUNC(FLAG / VAL) / 2) THEN
      RETURN FALSE;
    ELSE
      RETURN TRUE;
    END IF;
  END;

  FUNCTION BIS(FLAG IN NUMBER,
               VAL  IN NUMBER,
               VAL2 IN BOOLEAN) RETURN NUMBER IS
    MYFLAG  NUMBER := FLAG;
  BEGIN
    IF VAL2 IS NULL THEN
      RETURN FLAG;
    END IF;

    IF TRUNC(FLAG / VAL) / 2 = TRUNC(TRUNC(FLAG / VAL) / 2) THEN
      IF VAL2 THEN
        MYFLAG := MYFLAG + VAL;
      END IF;
    ELSE
      IF NOT VAL2 THEN
        MYFLAG := MYFLAG - VAL;
      END IF;
    END IF;
    RETURN MYFLAG;
  END;

  PROCEDURE ZONE_CHECK(ZONE  IN VARCHAR2,
                       FORCE IN BOOLEAN);
    PRAGMA INTERFACE(C, DBMS_JOB_ZONE_CHECK);

  PROCEDURE CHECK_PRIVS (JOB IN BINARY_INTEGER) IS
    DUMMY BINARY_INTEGER;
    PUSER VARCHAR(128);
  BEGIN
    PUSER := DBMS_IJOB.PUSER;
    SELECT 1 INTO DUMMY FROM "SYS"."ALL_VIRTUAL_JOB_REAL_AGENT" 
      WHERE JOB = CHECK_PRIVS.JOB AND POWNER = PUSER
            AND JOB != (SELECT MAX(JOB) FROM "SYS"."ALL_VIRTUAL_JOB_REAL_AGENT");
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20000, 'OBE-23421: job number ' || TO_CHAR(JOB) || ' is not a job in the job queue');
  END;

  PROCEDURE SUBMIT(job             BINARY_INTEGER,
                   luser           VARCHAR2,
                   puser           VARCHAR2,
                   cuser           VARCHAR2,
                   final_next_date DATE,
                   interval        VARCHAR2,
                   myflag          BINARY_INTEGER,
                   what            VARCHAR2,
                   nlsenv          VARCHAR2,
                   env             VARCHAR2);
    PRAGMA INTERFACE(C, DBMS_JOB_SUBMIT);

  PROCEDURE SUBMIT(JOB       IN BINARY_INTEGER,
                   LUSER     IN VARCHAR2,
                   PUSER     IN VARCHAR2,
                   CUSER     IN VARCHAR2,
                   NEXT_DATE IN DATE,
                   INTERVAL  IN VARCHAR2,
                   BROKEN    IN BOOLEAN,
                   WHAT      IN VARCHAR2,
                   NLSENV    IN VARCHAR2,
                   ENV       IN RAW ) IS
    MYFLAG BINARY_INTEGER := 0;
    FINAL_NEXT_DATE DATE;
    INSERT_SQL VARCHAR2(1000);
  BEGIN
    IF JOB < 1 THEN
      RAISE_APPLICATION_ERROR(-20000, 'OBE-23423: job number ' || TO_CHAR(JOB) || ' is not positive');
    END IF;

    IF BROKEN THEN
      MYFLAG := MYFLAG+1;
    END IF;

    IF PUSER = 'SYS' AND DBMS_IJOB.PUSER != 'SYS' THEN
      RAISE_APPLICATION_ERROR(-20000, 'OBE-23300: insufficient privilege');
    END IF;

    FINAL_NEXT_DATE := 
        NVL(SUBMIT.NEXT_DATE,
            TO_DATE(TO_CHAR(SYS_EXTRACT_UTC(TO_TIMESTAMP(TO_CHAR(TO_DATE('4000-01-01', 'YYYY-MM-DD'), 'YYYY-MM-DD'),
              'YYYY-MM-DD HH24:MI:SS')), 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS'));
    SUBMIT(job, luser, puser, cuser, final_next_date, submit.interval, myflag, submit.what, submit.nlsenv, submit.env);
  END;

  PROCEDURE SET_JOB_AFFINITY(MYNUM IN BINARY_INTEGER,
                             ZONE  IN VARCHAR2);
    PRAGMA INTERFACE(C, DBMS_JOB_SET_AFFINITY);

  PROCEDURE REMOVE(JOB IN BINARY_INTEGER);
    PRAGMA INTERFACE(C, DBMS_JOB_REMOVE);

  PROCEDURE WHAT(JOB  IN BINARY_INTEGER,
                 WHAT IN VARCHAR2 );
    PRAGMA INTERFACE(C, DBMS_JOB_SET_WHAT);

  PROCEDURE SET_NEXTDATE(JOB       IN BINARY_INTEGER,
                         NEXT_DATE IN DATE);
    PRAGMA INTERFACE(C, DBMS_JOB_SET_NEXTDATE);

  PROCEDURE NEXT_DATE(JOB       IN BINARY_INTEGER,
                      NEXT_DATE IN DATE) IS
  BEGIN
    SET_NEXTDATE(JOB, NEXT_DATE);
  END;

  PROCEDURE ZONE(JOB   IN BINARY_INTEGER,
                 ZONE  IN VARCHAR2,
                 FORCE IN BOOLEAN DEFAULT FALSE) IS
   MYJOB  BINARY_INTEGER := JOB;
   MYZONE VARCHAR2(128) := ZONE;
  BEGIN
    ZONE_CHECK(ZONE, FORCE);
    SET_JOB_AFFINITY(MYJOB, MYZONE);
  END;

  PROCEDURE INTERVAL(JOB      IN BINARY_INTEGER,
                     INTERVAL IN VARCHAR2);
    PRAGMA INTERFACE(C, DBMS_JOB_SET_INTERVAL);

  PROCEDURE SET_JOB_FLAG(JOB       IN BINARY_INTEGER,
                         NEWFLAG   IN BINARY_INTEGER,
                         NEXT_DATE IN DATE);
    PRAGMA INTERFACE(C, DBMS_JOB_SET_FLAG);

  PROCEDURE BROKEN(JOB       IN BINARY_INTEGER,
                   BROKEN    IN BOOLEAN,
                   NEXT_DATE IN DATE DEFAULT SYSDATE) IS
    MYJOB   BINARY_INTEGER := JOB;
    MYFLAG  BINARY_INTEGER;
    NEWFLAG BINARY_INTEGER;
    MYDATE  DATE := NEXT_DATE;
    MYNEXTDATE DATE;
  BEGIN
    SELECT
      FLAG,
      TO_DATE(TO_CHAR(SYS_EXTRACT_UTC(TO_TIMESTAMP(TO_CHAR(NEXT_DATE, 'YYYY-MM-DD HH24:MI:SS'),
              'YYYY-MM-DD HH24:MI:SS')), 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS')
      INTO MYFLAG, MYNEXTDATE
    FROM
      SYS.ALL_VIRTUAL_JOB_REAL_AGENT
    WHERE JOB = MYJOB;

    NEWFLAG := BIS(MYFLAG, 1, BROKEN);
    IF BIT(NEWFLAG,1) THEN
      MYDATE := TO_DATE(TO_CHAR(SYS_EXTRACT_UTC(TO_TIMESTAMP(TO_CHAR(TO_DATE('4000-01-01', 'YYYY-MM-DD'), 'YYYY-MM-DD'),
                                'YYYY-MM-DD HH24:MI:SS')), 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS');
    END IF;

    SET_JOB_FLAG(MYJOB, NEWFLAG, NVL(MYDATE, MYNEXTDATE));
    SET_NEXTDATE(MYJOB, NVL(MYDATE, MYNEXTDATE));
  END;

  PROCEDURE RUN_JOB(JOB   IN BINARY_INTEGER,
                    FORCE IN BOOLEAN DEFAULT FALSE);
    PRAGMA INTERFACE(C, DBMS_JOB_RUN);

  PROCEDURE RUN(JOB   IN BINARY_INTEGER DEFAULT 0,
                FORCE IN BOOLEAN DEFAULT FALSE) IS
    N NUMBER;
  BEGIN 
    IF DBMS_IJOB.PUSER = 'SYS' THEN
      NULL;
    ELSIF JOB > 0 THEN
      SELECT COUNT(*) INTO N FROM SYS.ALL_VIRTUAL_JOB_REAL_AGENT J WHERE J.JOB = RUN.JOB AND J.POWNER != 'SYS';
      IF N  = 0 THEN
        RAISE_APPLICATION_ERROR(-20000, 'OBE-23421: job number ' || TO_CHAR(JOB) || ' is not a job in the job queue');
      END IF;
    ELSE 
      SELECT COUNT(*) INTO N FROM SYS.ALL_VIRTUAL_JOB_REAL_AGENT J WHERE J.POWNER = 'SYS' ;
      IF N  > 0 THEN
        RAISE_APPLICATION_ERROR(-20000, 'OBE-23300: insufficient privilege');
      END IF;
    END IF;
    RUN_JOB(JOB, FORCE);
  END;

  PROCEDURE USER_EXPORT(JOB    IN     BINARY_INTEGER,
                        MYCALL IN OUT VARCHAR2) IS
    MYJOB  BINARY_INTEGER := JOB;
    MYWHAT VARCHAR2(4000);
    MYINT  VARCHAR2(400);
    MYNEXT VARCHAR2(200);
  BEGIN
    DBMS_IJOB.CHECK_PRIVS( JOB );
    SELECT WHAT,
           TO_CHAR(NEXT_DATE,'YYYY-MM-DD:HH24:MI:SS'), 
           REPLACE(INTERVAL#,'''','''''')
      INTO MYWHAT, MYNEXT, MYINT
      FROM SYS.ALL_VIRTUAL_JOB_REAL_AGENT WHERE JOB = MYJOB;
    MYWHAT := REPLACE(MYWHAT,'''',''''''); 
    MYCALL := 'dbms_job.isubmit(job=>'||MYJOB||
      ',what=>'''||MYWHAT||
      ''',next_date=>to_date('''||MYNEXT||''',''YYYY-MM-DD:HH24:MI:SS'')'||
      ',interval=>'''||MYINT||
      ''',no_parse=>TRUE);';
  END;

END;
//

