#package_name: utl_decode
#author: longzhong.wlz

CREATE OR REPLACE PACKAGE UTL_ENCODE IS
  FUNCTION BASE64_ENCODE(SRC IN RAW) RETURN RAW DETERMINISTIC;

  FUNCTION BASE64_DECODE(SRC IN RAW) RETURN RAW DETERMINISTIC;

  FUNCTION QUOTED_PRINTABLE_ENCODE(SRC IN RAW) RETURN RAW DETERMINISTIC;

  FUNCTION QUOTED_PRINTABLE_DECODE(SRC IN RAW) RETURN RAW DETERMINISTIC;

  FUNCTION MIMEHEADER_ENCODE (
   buf            IN  VARCHAR2 CHARACTER SET ANY_CS,
   encode_charset IN  VARCHAR2 DEFAULT NULL,
   encoding       IN  PLS_INTEGER DEFAULT NULL) RETURN VARCHAR2 DETERMINISTIC;

  FUNCTION MIMEHEADER_DECODE (
   buf    IN   VARCHAR2 CHARACTER SET ANY_CS) RETURN VARCHAR2 DETERMINISTIC;

  FUNCTION TEXT_ENCODE (
   buf            IN  VARCHAR2 CHARACTER SET ANY_CS,
   encode_charset IN  VARCHAR2 DEFAULT NULL,
   encoding       IN  PLS_INTEGER DEFAULT NULL) RETURN VARCHAR2 DETERMINISTIC;

  FUNCTION TEXT_DECODE(
   buf            IN  VARCHAR2 CHARACTER SET ANY_CS,
   encode_charset IN  VARCHAR2 DEFAULT NULL,
   encoding       IN  PLS_INTEGER DEFAULT NULL) RETURN VARCHAR2 DETERMINISTIC;

  FUNCTION UUENCODE (
   r          IN RAW,
   type       IN PLS_INTEGER DEFAULT 1,
   filename   IN VARCHAR2 DEFAULT 'uuencode.txt',
   permission IN VARCHAR2 DEFAULT '0') RETURN RAW DETERMINISTIC;
   
  FUNCTION UUDECODE(r IN RAW) RETURN RAW DETERMINISTIC;
END;
//
