

CREATE OR REPLACE PACKAGE dbms_utility AS

  type uncl_array IS table of VARCHAR2(32767) index by BINARY_INTEGER;

  type name_array IS table of VARCHAR2(128) index by BINARY_INTEGER;

  type quoted_name_array IS table of VARCHAR2(130) index by BINARY_INTEGER;

  type lname_array IS table of VARCHAR2(4000) index by BINARY_INTEGER;

  type maxname_array IS table of VARCHAR2(32767) index by BINARY_INTEGER;

  type dblink_array IS table of VARCHAR2(128) index by BINARY_INTEGER;

  TYPE index_table_type IS TABLE OF BINARY_INTEGER INDEX BY BINARY_INTEGER;

  TYPE number_array IS TABLE OF NUMBER INDEX BY BINARY_INTEGER;

  TYPE instance_record IS RECORD (
       inst_number   NUMBER,
       inst_name     VARCHAR2(60));

  TYPE instance_table IS TABLE OF instance_record INDEX BY BINARY_INTEGER;

  function format_call_stack return varchar2;

  function format_error_stack return varchar2;

  function format_error_backtrace return varchar2;

  procedure name_tokenize ( NAME    IN  VARCHAR2,
                           A       OUT VARCHAR2,
                           B       OUT VARCHAR2,
                           C       OUT VARCHAR2,
                           DBLINK  OUT VARCHAR2,
                           NEXTPOS OUT BINARY_INTEGER);

  PROCEDURE NAME_RESOLVE(NAME IN VARCHAR2, CONTEXT IN NUMBER,
    SCHEMA1 OUT VARCHAR2, PART1 OUT VARCHAR2, PART2 OUT VARCHAR2,
    DBLINK OUT VARCHAR2, PART1_TYPE OUT NUMBER, OBJECT_NUMBER OUT NUMBER);

  FUNCTION GET_PARAMETER_VALUE(PARNAM IN     VARCHAR2,
                               INTVAL IN OUT BINARY_INTEGER,
                               STRVAL IN OUT VARCHAR2,
                               LISTNO IN     BINARY_INTEGER DEFAULT 1) RETURN BINARY_INTEGER;

  FUNCTION GET_SQL_HASH(NAME IN VARCHAR2, HASH OUT RAW,
                        PRE10IHASH OUT NUMBER) RETURN NUMBER;
  FUNCTION IS_BIT_SET(R IN RAW, N IN NUMBER) RETURN NUMBER;
  PROCEDURE CANONICALIZE(NAME           IN   VARCHAR2,
                        CANON_NAME     OUT  VARCHAR2,
                        CANON_LEN      IN   BINARY_INTEGER);

  PROCEDURE TABLE_TO_COMMA( TAB    IN  UNCL_ARRAY,
                            TABLEN OUT BINARY_INTEGER,
                            LIST   OUT VARCHAR2);

  PROCEDURE TABLE_TO_COMMA( TAB    IN  LNAME_ARRAY,
                            TABLEN OUT BINARY_INTEGER,
                            LIST   OUT VARCHAR2);

  PROCEDURE COMMA_TO_TABLE( LIST   IN  VARCHAR2,
                            TABLEN OUT BINARY_INTEGER,
                            TAB    OUT UNCL_ARRAY );
                            
  PROCEDURE COMMA_TO_TABLE( LIST   IN  VARCHAR2,
                            TABLEN OUT BINARY_INTEGER,
                            TAB    OUT LNAME_ARRAY );
  FUNCTION ICD_GET_DBV RETURN VARCHAR2;

  PROCEDURE DB_VERSION(VERSION OUT VARCHAR2, COMPATIBILITY OUT VARCHAR2);

  FUNCTION PORT_STRING RETURN VARCHAR2;

  FUNCTION GET_HASH_VALUE(NAME VARCHAR2, BASE NUMBER, HASH_SIZE NUMBER) RETURN NUMBER;
  FUNCTION ICD_GET_TIME RETURN BINARY_INTEGER;

  FUNCTION GET_TIME RETURN NUMBER;

  FUNCTION IS_CLUSTER_DATABASE RETURN BOOLEAN;

  FUNCTION CURRENT_INSTANCE RETURN NUMBER;

  PROCEDURE ACTIVE_INSTANCES (INSTANCE_TABLE OUT INSTANCE_TABLE, INSTANCE_COUNT OUT NUMBER);

  FUNCTION OLD_CURRENT_SCHEMA RETURN VARCHAR2;
  FUNCTION OLD_CURRENT_USER RETURN VARCHAR2;
  FUNCTION ICD_GET_ENDIANNESS RETURN NUMBER;
  FUNCTION GET_ENDIANNESS RETURN NUMBER;

  PROCEDURE EXEC_DDL_STATEMENT(parse_string IN VARCHAR2);

  PROCEDURE VALIDATE(OBJECT_ID NUMBER, IS_RECOMPILE BOOLEAN DEFAULT FALSE);
  PROCEDURE PL_RECOMPILE;
  PROCEDURE POLLING_ASK_JOB;

END dbms_utility;
//
