#package_name:UTL_INADDR
#author: dachuan.sdc

CREATE OR REPLACE PACKAGE BODY UTL_INADDR AS

  FUNCTION GET_HOST_NAME (
    IP IN VARCHAR2 DEFAULT NULL
  )
  RETURN VARCHAR2;
  PRAGMA INTERFACE(c, UTL_INADDR_GET_HOST_NAME);

  FUNCTION GET_HOST_ADDRESS (
    HOST IN VARCHAR2 DEFAULT NULL
  )
  RETURN VARCHAR2;
  PRAGMA INTERFACE(c, UTL_INADDR_GET_HOST_ADDRESS);

END UTL_INADDR;
//

CREATE OR REPLACE PUBLIC SYNONYM utl_inaddr FOR sys.utl_inaddr;
