-- package_name: utl_file
-- author: jiahua.cjh

CREATE or REPLACE package body utl_file AS

  FILE_TYPE_VARCHAR  CONSTANT BINARY_INTEGER    :=1;
  FILE_TYPE_NVARCHAR CONSTANT BINARY_INTEGER    :=2;

  NEED_CONVERT  BOOLEAN  := FALSE;
  V_TYPE        VARCHAR2(20);

  OPENED_COUNT     BINARY_INTEGER :=0;
  COMPRESS_COUNT   CONSTANT BINARY_INTEGER :=200;

  PROCEDURE CHECK_FILE(FILE IN FILE_TYPE) IS
  BEGIN
    IF NOT IS_OPEN(FILE) THEN
      RAISE INVALID_FILEHANDLE;
    ELSIF FILE.BYTE_MODE THEN
       RAISE INVALID_OPERATION;
    END IF;
    
  END CHECK_FILE;

  FUNCTION FOPEN_INTERFACE(LOCATION IN VARCHAR2, FILENAME IN VARCHAR2,
                           OPEN_MODE IN VARCHAR2, MAX_LINESIZE IN BINARY_INTEGER,
                           FILE OUT BINARY_INTEGER)
  RETURN BINARY_INTEGER;
  PRAGMA INTERFACE(C, UTL_FILE_FOPEN);


  FUNCTION FCLOSE_INTERFACE(FILE   IN  BINARY_INTEGER)
  RETURN BINARY_INTEGER;
  PRAGMA INTERFACE(C, UTL_FILE_FCLOSE);



  PROCEDURE GET_LINE_INTERFACE(FILE IN BINARY_INTEGER, LEN IN BINARY_INTEGER, BUF OUT VARCHAR2 CHARACTER SET ANY_CS);
  PRAGMA INTERFACE(C, UTL_FILE_GET_LINE);



  PROCEDURE GET_LINE_RAW_INTERFACE(FILE IN BINARY_INTEGER, LEN IN BINARY_INTEGER, BUF OUT RAW);
  PRAGMA INTERFACE(C, UTL_FILE_GET_LINE_RAW);



  PROCEDURE PUT_INTO_BUF_INTERFACE(FILE      IN     BINARY_INTEGER,
                         BUF    IN OUT VARCHAR2 CHARACTER SET ANY_CS,
                         NEED_CRLF IN     BOOLEAN DEFAULT FALSE);
  PRAGMA INTERFACE(C, UTL_FILE_PUT_BUFFER);


  PROCEDURE FFLUSH_INTERFACE(FILE   IN  BINARY_INTEGER);
  PRAGMA INTERFACE(C, UTL_FILE_FFLUSH);


  PROCEDURE FOPEN_NCHAR_INTERFACE(TYPE_STR OUT VARCHAR2);
  PRAGMA INTERFACE(C, UTL_FILE_FOPEN_NCHAR);



  PROCEDURE PUT_RAW_INTERFACE(FILE      IN  BINARY_INTEGER,
                              BUF    IN  RAW,
                              AUTO_FLUSH IN  BOOLEAN);
  PRAGMA INTERFACE(C, UTL_FILE_PUT_RAW);



  PROCEDURE FSEEK_INTERFACE(FILE            IN OUT BINARY_INTEGER,
                            ABSOLUTE_OFFSET IN     BINARY_INTEGER,
                            RELATIVE_OFFSET IN     BINARY_INTEGER);
  PRAGMA INTERFACE(C, UTL_FILE_FSEEK);


  PROCEDURE FREMOVE_INTERFACE(LOCATION IN  VARCHAR2,
                              FILENAME IN  VARCHAR2);
  PRAGMA INTERFACE(C, UTL_FILE_FREMOVE);


  PROCEDURE FCOPY_INTERFACE(SRC_LOCATION  IN  VARCHAR2, SRC_FILENAME  IN  VARCHAR2, 
                            DEST_LOCATION IN  VARCHAR2, DEST_FILENAME IN  VARCHAR2,
                            START_LINE    IN  BINARY_INTEGER, END_LINE IN  BINARY_INTEGER);
  PRAGMA INTERFACE(C, UTL_FILE_FCOPY);


  PROCEDURE FGETATTR_INTERFACE(LOCATION IN  VARCHAR2, FILENAME IN  VARCHAR2, FEXISTS OUT BOOLEAN, 
                               FILE_LENGTH OUT NUMBER, BLOCK_SIZE  OUT BINARY_INTEGER);
  PRAGMA INTERFACE(C, UTL_FILE_FGETATTR);


  FUNCTION FGETPOS_INTERFACE(FILE   IN  BINARY_INTEGER)
  RETURN BINARY_INTEGER;
  PRAGMA INTERFACE(C, UTL_FILE_FGETPOS);


  PROCEDURE FRENAME_INTERFACE(SRC_LOCATION    IN  VARCHAR2, SRC_FILENAME  IN  VARCHAR2,
                              DEST_LOCATION   IN  VARCHAR2, DEST_FILENAME IN  VARCHAR2,
                              OVERWRITE       IN  BOOLEAN);
  PRAGMA INTERFACE(C, UTL_FILE_FRENAME);


  FUNCTION FIS_OPEN_INTERFACE(FILE   IN  BINARY_INTEGER)
  RETURN BOOLEAN;
  PRAGMA INTERFACE(C, UTL_FILE_FIS_OPEN);


  PROCEDURE PUT_INTO_BUF(FILE      IN FILE_TYPE,
                         NEED_CRLF IN BOOLEAN DEFAULT FALSE) IS
  BEGIN
    IF (LINE(FILE.ID) IS NOT NULL) THEN
      PUT_INTO_BUF_INTERFACE(FILE.ID, LINE(FILE.ID), NEED_CRLF);
    END IF;
  EXCEPTION WHEN NO_DATA_FOUND THEN
      null;
  END PUT_INTO_BUF;

  PROCEDURE PUT_INTO_BUF_NCHAR(FILE IN FILE_TYPE,
                               NEED_CRLF IN BOOLEAN DEFAULT FALSE) IS
    UTF8_BUF  NVARCHAR2(32767);
  BEGIN
    IF (NCHAR_LINE(FILE.ID) IS NOT NULL) THEN
      IF (NEED_CONVERT) THEN
         UTF8_BUF := CONVERT(NCHAR_LINE(FILE.ID), 'UTF8', V_TYPE);
         PUT_INTO_BUF_INTERFACE(FILE.ID, UTF8_BUF, NEED_CRLF);
      ELSE
         PUT_INTO_BUF_INTERFACE(FILE.ID, NCHAR_LINE(FILE.ID), NEED_CRLF);
      END IF;
    END IF;
  EXCEPTION WHEN NO_DATA_FOUND THEN
      null;
  END PUT_INTO_BUF_NCHAR;

  PROCEDURE COMPRESS_COLL IS
    LINETAB_V       LINETAB;
  BEGIN
    LINETAB_V := LINE;
    LINE.DELETE;
    LINE := LINETAB_V;
  END COMPRESS_COLL;

  PROCEDURE COMPRESS_COLL_NCHAR IS
    NCHAR_LINETAB_V NCHAR_LINETAB;
  BEGIN
    NCHAR_LINETAB_V := NCHAR_LINE;
    NCHAR_LINE.DELETE;
    NCHAR_LINE := NCHAR_LINETAB_V;
  END COMPRESS_COLL_NCHAR;

  FUNCTION FOPEN(LOCATION     IN VARCHAR2, FILENAME     IN VARCHAR2,
                 OPEN_MODE    IN VARCHAR2, MAX_LINESIZE IN BINARY_INTEGER DEFAULT NULL)
  RETURN FILE_TYPE 
  IS
    FILE_ID    BINARY_INTEGER;
    RET_FILE   FILE_TYPE;
    OPEN_RET   BINARY_INTEGER;
    OPEN_MODE_W VARCHAR2(2);
  BEGIN
    RET_FILE.ID := NULL;
    RET_FILE.DATATYPE := FILE_TYPE_VARCHAR;
    OPEN_RET := FOPEN_INTERFACE(LOCATION, FILENAME, OPEN_MODE, MAX_LINESIZE, FILE_ID);
    RET_FILE.ID := FILE_ID;
    LINE(FILE_ID) := '';

    IF (OPENED_COUNT <= COMPRESS_COUNT) THEN
      OPENED_COUNT := OPENED_COUNT + 1;
    ELSE
      COMPRESS_COLL();
      OPENED_COUNT := 0;
    END IF;

    IF (lower(SUBSTR(OPEN_MODE, 2, 1)) = 'b')  THEN
       RET_FILE.BYTE_MODE := TRUE;
    ELSE
       RET_FILE.BYTE_MODE := FALSE;
    END IF;

    RETURN RET_FILE;
  EXCEPTION WHEN UTL_FILE.INVALID_OPERATION THEN
    IF (lower(SUBSTR(OPEN_MODE,1,1)) = 'a') THEN
       OPEN_MODE_W := 'W';
       IF (LENGTH(OPEN_MODE) > 1) THEN
          OPEN_MODE_W := OPEN_MODE_W || SUBSTR(OPEN_MODE, 2, 1);
       END IF;
       OPEN_RET := FOPEN_INTERFACE(LOCATION, FILENAME, OPEN_MODE_W, MAX_LINESIZE, FILE_ID);
       RET_FILE.ID := FILE_ID;
       LINE(FILE_ID) := '';

       IF ( OPENED_COUNT <= COMPRESS_COUNT ) THEN
         OPENED_COUNT := OPENED_COUNT + 1;
       ELSE
         COMPRESS_COLL();
         OPENED_COUNT := 0;
       END IF;

       IF (lower(SUBSTR(OPEN_MODE_W, 2,1)) = 'b')  THEN
          RET_FILE.BYTE_MODE := TRUE;
       ELSE
          RET_FILE.BYTE_MODE := FALSE;
       END IF;
    ELSE
      RAISE INVALID_OPERATION;
    END IF;
    RETURN RET_FILE;
  END FOPEN;


  FUNCTION FOPEN_NCHAR(LOCATION     IN VARCHAR2, FILENAME     IN VARCHAR2,
                       OPEN_MODE    IN VARCHAR2, MAX_LINESIZE IN BINARY_INTEGER DEFAULT NULL)
  RETURN FILE_TYPE
  IS
    FILE        BINARY_INTEGER;
    RET_FILE    FILE_TYPE;
    TYPE_STR    VARCHAR2(20);
    OPEN_RET    BINARY_INTEGER;
    OPEN_MODE_W VARCHAR2(2);
  BEGIN
    RET_FILE.ID := NULL;
    RET_FILE.DATATYPE := FILE_TYPE_NVARCHAR;
    OPEN_RET := FOPEN_INTERFACE(LOCATION, FILENAME, OPEN_MODE, MAX_LINESIZE, FILE);
    RET_FILE.ID := FILE;
    NCHAR_LINE(FILE) := N'';

    IF (OPENED_COUNT <= COMPRESS_COUNT) THEN
      OPENED_COUNT := OPENED_COUNT + 1;
    ELSE
      COMPRESS_COLL_NCHAR;
      OPENED_COUNT := 0;
    END IF;

    IF (lower(SUBSTR(OPEN_MODE, 2,1)) = 'b')  THEN
       RET_FILE.BYTE_MODE := TRUE;
    ELSE
       RET_FILE.BYTE_MODE := FALSE;
    END IF;

    FOPEN_NCHAR_INTERFACE(TYPE_STR);
    V_TYPE := TYPE_STR;

    IF (V_TYPE = 'UTF8') THEN
        NEED_CONVERT := FALSE;
    ELSE
        NEED_CONVERT := TRUE;
    END IF;
    RETURN RET_FILE;

  EXCEPTION WHEN UTL_FILE.INVALID_OPERATION THEN
    IF (lower(SUBSTR(OPEN_MODE,1,1)) = 'a') THEN
      OPEN_MODE_W := 'W';
      IF (LENGTH(OPEN_MODE) > 1) THEN
        OPEN_MODE_W := OPEN_MODE_W || SUBSTR(OPEN_MODE,2,1);
      END IF;
      OPEN_RET := FOPEN_INTERFACE(LOCATION, FILENAME, OPEN_MODE_W, MAX_LINESIZE, FILE);

      RET_FILE.ID := FILE;
      NCHAR_LINE(FILE) := N'';

      IF ( OPENED_COUNT <= COMPRESS_COUNT ) THEN
        OPENED_COUNT := OPENED_COUNT + 1;
      ELSE
        COMPRESS_COLL_NCHAR;
        OPENED_COUNT := 0;
      END IF;

      IF (lower(SUBSTR(OPEN_MODE_W, 2,1)) = 'b')  THEN
        RET_FILE.BYTE_MODE := TRUE;
      ELSE
        RET_FILE.BYTE_MODE := FALSE;
      END IF;
    ELSE
      RAISE INVALID_OPERATION;
    END IF;

    FOPEN_NCHAR_INTERFACE(TYPE_STR);
    V_TYPE := TYPE_STR;

    IF (V_TYPE='UTF8') THEN
        NEED_CONVERT := FALSE;
    ELSE
        NEED_CONVERT := TRUE;
    END IF;
    RETURN RET_FILE;
  END FOPEN_NCHAR;


  FUNCTION IS_OPEN(FILE IN FILE_TYPE) 
  RETURN BOOLEAN IS
  BEGIN
    RETURN (FIS_OPEN_INTERFACE(FILE.ID));
  END IS_OPEN;

  PROCEDURE DO_FCLOSE(FILE IN OUT FILE_TYPE) IS
  BEGIN
    PUT_INTO_BUF(FILE, TRUE);
    LINE.DELETE(FILE.ID);
  EXCEPTION WHEN UTL_FILE.INVALID_OPERATION OR UTL_FILE.WRITE_ERROR THEN
    null;
  END DO_FCLOSE;

  PROCEDURE DO_FCLOSE_NCHAR(FILE IN OUT FILE_TYPE) IS
  BEGIN
    PUT_INTO_BUF_NCHAR(FILE, TRUE);
    NCHAR_LINE.DELETE(FILE.ID);
  EXCEPTION
  WHEN UTL_FILE.INVALID_OPERATION OR UTL_FILE.WRITE_ERROR THEN
    null;
  END DO_FCLOSE_NCHAR;

  PROCEDURE FCLOSE(FILE IN OUT FILE_TYPE) IS
    RET BINARY_INTEGER;
  BEGIN
    IF (IS_OPEN(FILE)) THEN
      BEGIN
        IF (FILE.DATATYPE = FILE_TYPE_NVARCHAR) THEN
          DO_FCLOSE_NCHAR(FILE);
        ELSE
          DO_FCLOSE(FILE);
        END IF;
      END;

      RET := FCLOSE_INTERFACE(FILE.ID);
    END IF;
  END FCLOSE;


  PROCEDURE DO_FCLOSE_ALL IS
    V_FILE FILE_TYPE;
  BEGIN
    V_FILE.ID := LINE.FIRST;
    FOR I IN 0 .. (LINE.COUNT - 1)  LOOP
      IF (IS_OPEN(V_FILE)) THEN
        FCLOSE(V_FILE);
      END IF;
      V_FILE.ID := LINE.NEXT(V_FILE.ID);
    END LOOP;

    LINE.DELETE;
  END DO_FCLOSE_ALL;

  PROCEDURE DO_FCLOSE_ALL_NCHAR IS
    V_FILE FILE_TYPE;
  BEGIN
    V_FILE.ID := NCHAR_LINE.FIRST;
    FOR I IN 0 .. (NCHAR_LINE.COUNT - 1)  LOOP
      IF (IS_OPEN(V_FILE)) THEN
        FCLOSE(V_FILE);
      END IF;
      V_FILE.ID := NCHAR_LINE.NEXT(V_FILE.ID);
    END LOOP;

    NCHAR_LINE.DELETE;
  END DO_FCLOSE_ALL_NCHAR;

  PROCEDURE FCLOSE_ALL IS
  BEGIN
    DO_FCLOSE_ALL;
    DO_FCLOSE_ALL_NCHAR;
  END FCLOSE_ALL;

  PROCEDURE GET_LINE(FILE   IN FILE_TYPE, BUFFER OUT VARCHAR2, LEN    IN BINARY_INTEGER DEFAULT NULL) IS
    BUF VARCHAR2(32767);
  BEGIN
    CHECK_FILE(FILE);

    IF (FILE.DATATYPE != FILE_TYPE_VARCHAR) THEN
       RAISE CHARSETMISMATCH;
    END IF;
    GET_LINE_INTERFACE(FILE.ID, LEN, BUF);
    BUFFER := BUF;
  END GET_LINE;


  PROCEDURE GET_LINE_NCHAR(FILE IN FILE_TYPE, BUFFER OUT NVARCHAR2, LEN IN BINARY_INTEGER DEFAULT NULL)
  IS
    UTF8_BUF NVARCHAR2(32767);
    BUF      NVARCHAR2(32767);
  BEGIN
    CHECK_FILE(FILE);

    IF (FILE.DATATYPE != FILE_TYPE_NVARCHAR) THEN
      RAISE CHARSETMISMATCH;
    END IF;

    IF (NEED_CONVERT) THEN
      GET_LINE_INTERFACE(FILE.ID, LEN, UTF8_BUF);
      BUFFER := CONVERT(UTF8_BUF, V_TYPE, 'UTF8');
    ELSE
      GET_LINE_INTERFACE(FILE.ID, LEN, BUF);
      BUFFER := BUF;
    END IF;
  END GET_LINE_NCHAR;


  PROCEDURE PUT(FILE IN FILE_TYPE, BUFFER IN VARCHAR2)
  IS
    SIZE_OVER_FLOW EXCEPTION;
    PRAGMA EXCEPTION_INIT(SIZE_OVER_FLOW, -4019);
  BEGIN
    CHECK_FILE(FILE);

    IF (FILE.DATATYPE != FILE_TYPE_VARCHAR) THEN
      RAISE CHARSETMISMATCH;
    END IF;

    IF (NOT LINE.EXISTS(FILE.ID) AND NOT FIS_OPEN_INTERFACE(FILE.ID)) THEN
      RAISE INVALID_FILEHANDLE;
    END IF;

    LINE(FILE.ID) := SUBSTRB(LINE(FILE.ID) || BUFFER, 1, 32767);

  EXCEPTION WHEN SIZE_OVER_FLOW THEN
      FFLUSH(FILE);
      LINE(FILE.ID) := SUBSTRB(LINE(FILE.ID)||BUFFER,1,32767);
    WHEN NO_DATA_FOUND THEN
      LINE(FILE.ID) := BUFFER;
  END PUT;

  PROCEDURE PUT_NCHAR(FILE   IN FILE_TYPE, BUFFER IN NVARCHAR2)
  IS
    SIZE_OVER_FLOW EXCEPTION;
    PRAGMA EXCEPTION_INIT(SIZE_OVER_FLOW, -4019);
  BEGIN
    CHECK_FILE(FILE);
    IF (FILE.DATATYPE != FILE_TYPE_NVARCHAR) THEN
      RAISE CHARSETMISMATCH;
    END IF;

    IF (NOT NCHAR_LINE.EXISTS(FILE.ID) AND NOT FIS_OPEN_INTERFACE(FILE.ID)) THEN
      RAISE INVALID_FILEHANDLE;
    END IF;

    NCHAR_LINE(FILE.ID) := SUBSTRB(NCHAR_LINE(FILE.ID) || BUFFER, 1, 32767);

  EXCEPTION WHEN SIZE_OVER_FLOW THEN
      FFLUSH(FILE);
    WHEN NO_DATA_FOUND THEN
      NCHAR_LINE(FILE.ID) := BUFFER;
  END PUT_NCHAR;

  PROCEDURE NEW_LINE(FILE  IN FILE_TYPE, LINES IN NATURAL := 1)
  IS
    SIZE_OVER_FLOW EXCEPTION;
    PRAGMA EXCEPTION_INIT(SIZE_OVER_FLOW, -4019);
  BEGIN
    CHECK_FILE(FILE);

    IF (LINES < 0) THEN
      RAISE INVALID_OPERATION;
    ELSIF (LINES = 0) THEN
      NULL;
    ELSE
      FOR i IN 1 .. LINES
      LOOP
        --suppose line ternimator is '\n'(unix), windows platform is not supported currently
        BEGIN
          LINE(FILE.ID) := SUBSTRB(LINE(FILE.ID)||CHR(10),1,32767);
        EXCEPTION
          WHEN SIZE_OVER_FLOW THEN
            FFLUSH(FILE);
            LINE(FILE.ID) := SUBSTRB(LINE(FILE.ID)||CHR(10),1,32767);
        END;
      END LOOP;
    END IF;
  END NEW_LINE;


  PROCEDURE NEW_LINE_NCHAR(FILE  IN FILE_TYPE, LINES IN NATURAL := 1)
  IS
    SIZE_OVER_FLOW EXCEPTION;
    PRAGMA EXCEPTION_INIT(SIZE_OVER_FLOW, -4019);
  BEGIN
    CHECK_FILE(FILE);

    IF (LINES < 0) THEN
      RAISE INVALID_OPERATION;
    ELSIF (LINES = 0) THEN
      NULL;
    ELSE
      FOR i IN 1 .. LINES
      LOOP
        --suppose line ternimator is '\n'(unix), windows platform is not supported currently
        NCHAR_LINE(FILE.ID) := SUBSTRB(NCHAR_LINE(FILE.ID) || CHR(10), 1, 32767);
      END LOOP;
    END IF;

  EXCEPTION WHEN SIZE_OVER_FLOW THEN
      FFLUSH(FILE);
  END NEW_LINE_NCHAR;


  PROCEDURE PUT_LINE(FILE IN FILE_TYPE, BUFFER IN VARCHAR2, AUTOFLUSH IN BOOLEAN DEFAULT FALSE)
  IS
  BEGIN
    CHECK_FILE(FILE);
    IF (FILE.DATATYPE != FILE_TYPE_VARCHAR) THEN
      RAISE CHARSETMISMATCH;
    END IF;

    IF (NOT LINE.EXISTS(FILE.ID)) THEN
      RAISE INVALID_OPERATION;
    END IF;

    PUT(FILE, BUFFER);
    NEW_LINE(FILE);

    IF AUTOFLUSH THEN
      FFLUSH(FILE);
    END IF;
  END PUT_LINE;

  PROCEDURE PUT_LINE_NCHAR(FILE IN FILE_TYPE, BUFFER IN NVARCHAR2)
  IS
    UTF8_BUF  NVARCHAR2(32767);
  BEGIN
    CHECK_FILE(FILE);
    IF (FILE.DATATYPE != FILE_TYPE_NVARCHAR) THEN
      RAISE CHARSETMISMATCH;
    END IF;

    IF (NEED_CONVERT) THEN
      UTF8_BUF := CONVERT(BUFFER, 'UTF8', V_TYPE);
    ELSE UTF8_BUF := BUFFER;
    END IF;

    IF (NCHAR_LINE.EXISTS(FILE.ID)) THEN
      PUT_NCHAR(FILE, BUFFER);
      NEW_LINE_NCHAR(FILE);
    ELSE
      RAISE INVALID_OPERATION;
    END IF;
  END PUT_LINE_NCHAR;

  PROCEDURE PUTF_LINES(FILE IN FILE_TYPE, BUFFER IN VARCHAR2) IS
    BEGIN_POS NUMBER;
    END_POS   NUMBER;
    BUF_LEN   NUMBER := LENGTH(BUFFER);
  BEGIN
    IF (BUFFER IS NOT NULL) THEN
      BEGIN_POS := 1;
      END_POS := INSTR(BUFFER, '\n', BEGIN_POS);
      WHILE END_POS != 0 LOOP
        PUT_LINE(FILE, SUBSTR(BUFFER, BEGIN_POS, END_POS - BEGIN_POS));
        BEGIN_POS := END_POS + 2;

        IF (BEGIN_POS > BUF_LEN) THEN
          RETURN;
        END IF;
        END_POS := INSTR(BUFFER, '\n', BEGIN_POS);
      END LOOP;

      PUT(FILE, SUBSTR(BUFFER, BEGIN_POS));
    END IF;
  END PUTF_LINES;

  PROCEDURE PUTF_LINES_NCHAR(FILE IN FILE_TYPE, BUFFER IN NVARCHAR2)
  IS
    BEGIN_POS NUMBER;
    END_POS   NUMBER;
    BUF_LEN   NUMBER := LENGTH(BUFFER);
  BEGIN
    IF (BUFFER IS NOT NULL) THEN
      BEGIN_POS := 1;
      END_POS := INSTR(BUFFER, N'\n', BEGIN_POS);
      WHILE END_POS != 0 LOOP
        PUT_LINE_NCHAR(FILE, SUBSTR(BUFFER, BEGIN_POS, END_POS-BEGIN_POS));
        BEGIN_POS := END_POS + 2;

        IF (BEGIN_POS > BUF_LEN) THEN
          RETURN;
        END IF;
        END_POS := INSTR(BUFFER, N'\n', BEGIN_POS);
      END LOOP;

      PUT_NCHAR(FILE, SUBSTR(BUFFER,BEGIN_POS));
    END IF;


  END PUTF_LINES_NCHAR;

  PROCEDURE DO_PUTF(FILE   IN     FILE_TYPE,
                     FORMAT IN     VARCHAR2,
                     ARG    IN     VARCHAR2,
                     DELIMITER_BEG IN OUT NUMBER) IS
    DELIMITER_END NUMBER;
  BEGIN
    DELIMITER_END := INSTR(FORMAT, '%s', DELIMITER_BEG);

    IF (DELIMITER_END != 0) THEN
      PUTF_LINES(FILE, SUBSTR(FORMAT, DELIMITER_BEG, DELIMITER_END-DELIMITER_BEG));
      PUT(FILE, ARG);
      DELIMITER_BEG := DELIMITER_END + 2;
    ELSE
      PUTF_LINES(FILE, SUBSTR(FORMAT, DELIMITER_BEG));
      DELIMITER_BEG := NULL;
    END IF;
  END DO_PUTF;

  PROCEDURE DO_PUTF_NCHAR(FILE   IN     FILE_TYPE,
                           FORMAT IN     NVARCHAR2,
                           ARG    IN     NVARCHAR2,
                           DELIMITER_BEG IN OUT NUMBER) IS
    DELIMITER_END NUMBER;
  BEGIN
    DELIMITER_END := INSTR(FORMAT, N'%s', DELIMITER_BEG);

    IF (DELIMITER_END != 0) THEN
      PUTF_LINES_NCHAR(FILE, SUBSTR(FORMAT, DELIMITER_BEG, DELIMITER_END-DELIMITER_BEG));
      PUT_NCHAR(FILE, ARG);
      DELIMITER_BEG := DELIMITER_END + 2;
    ELSE
      PUTF_LINES_NCHAR(FILE, SUBSTR(FORMAT, DELIMITER_BEG));
      DELIMITER_BEG := NULL;
    END IF;
  END DO_PUTF_NCHAR;

  PROCEDURE PUTF(FILE IN FILE_TYPE, FORMAT IN VARCHAR2,
                 ARG1 IN VARCHAR2 DEFAULT NULL, ARG2 IN VARCHAR2 DEFAULT NULL,
                 ARG3 IN VARCHAR2 DEFAULT NULL, ARG4 IN VARCHAR2 DEFAULT NULL,
                 ARG5 IN VARCHAR2 DEFAULT NULL)
  IS
    DELIMITER_BEG NUMBER := 1;
  BEGIN
    CHECK_FILE(FILE);

    IF (FORMAT IS NULL) THEN
      RETURN;
    END IF;

    DO_PUTF(FILE, FORMAT, ARG1, DELIMITER_BEG);
    IF DELIMITER_BEG IS NOT NULL THEN
      DO_PUTF(FILE, FORMAT, ARG2, DELIMITER_BEG);
      IF DELIMITER_BEG IS NOT NULL THEN
        DO_PUTF(FILE, FORMAT, ARG3, DELIMITER_BEG);
        IF DELIMITER_BEG IS NOT NULL THEN
          DO_PUTF(FILE, FORMAT, ARG4, DELIMITER_BEG);
          IF DELIMITER_BEG IS NOT NULL THEN
            DO_PUTF(FILE, FORMAT, ARG5, DELIMITER_BEG);
            IF DELIMITER_BEG IS NOT NULL THEN
              PUTF_LINES(FILE, SUBSTR(FORMAT, DELIMITER_BEG));
            END IF;
          END IF;
        END IF;
      END IF;
    END IF;
  END PUTF;

  PROCEDURE PUTF_NCHAR(FILE IN FILE_TYPE, FORMAT IN NVARCHAR2,
                       ARG1 IN NVARCHAR2 DEFAULT NULL, ARG2 IN NVARCHAR2 DEFAULT NULL,
                       ARG3 IN NVARCHAR2 DEFAULT NULL,
                       ARG4 IN NVARCHAR2 DEFAULT NULL,
                       ARG5 IN NVARCHAR2 DEFAULT NULL) IS
    DELIMITER_BEG NUMBER := 1;
  BEGIN
    CHECK_FILE(FILE);
    IF (FORMAT IS NULL) THEN
      RETURN;
    END IF;

    DO_PUTF_NCHAR(FILE, FORMAT, ARG1, DELIMITER_BEG);
    IF DELIMITER_BEG IS NOT NULL THEN
      DO_PUTF_NCHAR(FILE, FORMAT, ARG2, DELIMITER_BEG);
      IF DELIMITER_BEG IS NOT NULL THEN
        DO_PUTF_NCHAR(FILE, FORMAT, ARG3, DELIMITER_BEG);
        IF DELIMITER_BEG IS NOT NULL THEN
          DO_PUTF_NCHAR(FILE, FORMAT, ARG4, DELIMITER_BEG);
          IF DELIMITER_BEG IS NOT NULL THEN
            DO_PUTF_NCHAR(FILE, FORMAT, ARG5, DELIMITER_BEG);
            IF DELIMITER_BEG IS NOT NULL THEN
              PUTF_LINES_NCHAR(FILE, SUBSTR(FORMAT, DELIMITER_BEG));
            END IF;
          END IF;
        END IF;
      END IF;
    END IF;
  END PUTF_NCHAR;


  PROCEDURE PUT_RAW(FILE IN FILE_TYPE, BUFFER IN RAW, AUTOFLUSH IN BOOLEAN DEFAULT FALSE) 
  IS
  BEGIN
    IF (NOT IS_OPEN(FILE)) THEN
      RAISE INVALID_FILEHANDLE;
    ELSIF (BUFFER IS NOT NULL) THEN
      PUT_RAW_INTERFACE(FILE.ID, BUFFER, AUTOFLUSH);
    END IF;

    IF AUTOFLUSH THEN
      FFLUSH(FILE);
    END IF;
  END PUT_RAW;



  PROCEDURE GET_RAW(FILE IN FILE_TYPE, BUFFER OUT NOCOPY RAW, LEN IN BINARY_INTEGER DEFAULT NULL) IS
    BUF RAW(32767);
  BEGIN
    IF (NOT IS_OPEN(FILE)) THEN
      RAISE INVALID_FILEHANDLE;
    ELSIF (FILE.DATATYPE != FILE_TYPE_VARCHAR) THEN
       RAISE CHARSETMISMATCH;
    END IF;

    GET_LINE_RAW_INTERFACE(FILE.ID, LEN, BUF);
    BUFFER := BUF;
  END GET_RAW;

  PROCEDURE FFLUSH(FILE IN FILE_TYPE)
  IS
  BEGIN
    IF (NOT IS_OPEN(FILE)) THEN
      RAISE INVALID_FILEHANDLE;
    END IF;

    IF (FILE.DATATYPE = FILE_TYPE_NVARCHAR) THEN
       PUT_INTO_BUF_NCHAR(FILE);
    ELSE
       PUT_INTO_BUF(FILE);
    END IF;

    FFLUSH_INTERFACE(FILE.ID);
  END FFLUSH;

  PROCEDURE FSEEK(FILE IN OUT FILE_TYPE, ABSOLUTE_OFFSET IN BINARY_INTEGER DEFAULT NULL, RELATIVE_OFFSET IN BINARY_INTEGER DEFAULT NULL)
  IS
  BEGIN
    CHECK_FILE(FILE);
    FSEEK_INTERFACE(FILE.ID, ABSOLUTE_OFFSET, RELATIVE_OFFSET);
  END FSEEK;

  PROCEDURE FREMOVE(LOCATION IN VARCHAR2, FILENAME IN VARCHAR2)
  IS
  BEGIN
    FREMOVE_INTERFACE(LOCATION, FILENAME);
  END FREMOVE;


  PROCEDURE FCOPY(SRC_LOCATION  IN VARCHAR2, SRC_FILENAME  IN VARCHAR2,
                  DEST_LOCATION IN VARCHAR2, DEST_FILENAME IN VARCHAR2,
                  START_LINE    IN BINARY_INTEGER DEFAULT 1, END_LINE IN BINARY_INTEGER DEFAULT NULL)
  IS
  BEGIN
    FCOPY_INTERFACE(SRC_LOCATION, SRC_FILENAME, DEST_LOCATION, DEST_FILENAME, START_LINE, END_LINE);
  END FCOPY;

  PROCEDURE FGETATTR(LOCATION    IN  VARCHAR2, FILENAME    IN  VARCHAR2,
                     FEXISTS     OUT BOOLEAN,  FILE_LENGTH OUT NUMBER,
                     BLOCK_SIZE  OUT BINARY_INTEGER)
  IS
  BEGIN
    FGETATTR_INTERFACE(LOCATION, FILENAME, FEXISTS, FILE_LENGTH, BLOCK_SIZE);
  END FGETATTR;

  FUNCTION FGETPOS(FILE IN FILE_TYPE) RETURN BINARY_INTEGER AS
    POSITION BINARY_INTEGER;
  BEGIN
    CHECK_FILE(FILE);
    POSITION := FGETPOS_INTERFACE(FILE.ID);
    RETURN(POSITION);
 END FGETPOS;

  PROCEDURE FRENAME(SRC_LOCATION   IN VARCHAR2, SRC_FILENAME   IN VARCHAR2,
                    DEST_LOCATION  IN VARCHAR2, DEST_FILENAME  IN VARCHAR2,
                    OVERWRITE      IN BOOLEAN DEFAULT FALSE) IS
  BEGIN
    FRENAME_INTERFACE(SRC_LOCATION, SRC_FILENAME, DEST_LOCATION, DEST_FILENAME, OVERWRITE);
  END FRENAME;

END;
//
