#package_name:utl_inaddr
#author: dachuan.sdc

CREATE OR REPLACE PACKAGE UTL_INADDR AS

  FUNCTION GET_HOST_NAME (
    IP IN VARCHAR2 DEFAULT NULL
  )
  RETURN VARCHAR2;

  FUNCTION GET_HOST_ADDRESS(
    HOST IN VARCHAR2 DEFAULT NULL
  )
  RETURN VARCHAR2;

END UTL_INADDR;
//
