#!/usr/bin/env python2.6
'''java client test script'''
# author: junyue

import getopt
import re
import sys
from subprocess import Popen, PIPE
import shlex
import glob
import errno
import pprint
import os



if __name__ == '__main__':
    ip   = '127.0.0.1'
    port = 3306
    username='admin'
    password='admin'
    database='test'
    result_file= '../r/join_basic.result'
    test_file= '../t/join_basic.test'
    record = False
    oblog_diff = False
    class_path = ''
    logdir=os.getcwd()
    lines = 10
    ps = False
    full_username = ''
    rslist_url = ''
    num = 0
    linesdiff = 0
    connector = '--use_ob_connector true'

    jars = os.listdir(os.path.dirname(sys.argv[0]))
    for jar in jars:
        if jar.find('.jar') != -1 or jar == 'log4j.properties':
            if class_path != '':
                class_path = class_path + ":" + os.path.join(os.path.dirname(sys.argv[0]),jar)
            else:
                class_path = os.path.join(os.path.dirname(sys.argv[0]),jar)

    longargs = ['port=', 'logdir=', 'test-file=', 'result-file=', 'record', 'oblog_diff', 'host=', 'user=', 'password=', 'tmpdir=', 'database=', 'timer-file=', 'tail-lines=', 'silent', 'version','ps-protocol', 'full_username=', 'rslist_url=', 'connector=']

    opts, args = getopt.getopt( sys.argv[1:], 'x', longargs)
    for o, a in opts:
        if o == '--port':
            port = int(a)
        elif o == '--record':
            record = True
        elif o == '--ps-protocol':
            ps = True
        elif o == '--test-file':
            test_file = a
        elif o == '--result-file':
            result_file = a
        elif o == '--host':
            ip = a
        elif o == '--user':
            username = a
        elif o == '--full_username':
            full_username = a
        elif o == '--rslist_url':
            rslist_url = a
        elif o == '--password':
            password = a
        elif o == '--tail-lines':
            lines = int(a)
        elif o == '--database':
            database = a
        elif o == '--oblog_diff':
            oblog_diff = True
        elif o == '--logdir':
            logdir = a
            if os.path.exists(logdir) == False:
                os.mkdir(logdir)
        elif o == '--connector':
            if a == 'oracle':
                connector = '-use_oracle_connector true -abort_on_error false'
            elif a == 'ob':
                connector = '-use_ob_connector true'
            else:
                connector = '-use_mysql_connector true -abort_on_error false'

        elif o == '--version':
            print("Ver 3.3 Distrib 5.5.27 java mysqltest")
            sys.exit(0)
 
    testname = os.path.splitext(os.path.basename(test_file))[0]

#    cmd="java -cp %s com.etao.mytest.main.MyTest -host %s -database %s -username %s -port %d -result_file %s  -test_file %s"%(class_path, ip, database, username, port, result_file, test_file)
    cmd="java -cp %s com.etao.mytest.main.MyTest -full_username %s -host %s -database %s -username %s -port %d -result_file %s  -test_file %s %s"%(class_path, full_username, ip, database, username, port, result_file, test_file, connector)
    if password != '':
       cmd = "%s -password %s"%(cmd, password)
    if record == True:
       cmd = cmd + " -record"
    if oblog_diff == True:
       cmd = cmd + " -oblog_diff"
    if ps == True:
        cmd = cmd + " -ps"
    print(cmd)
    p = Popen(shlex.split(cmd), stdout = PIPE, stderr = PIPE)
    output, errput = p.communicate()

    log_fp = open(os.path.join(logdir, testname) + '.log', "w")
    log_fp.write(output);
    log_fp.close()

    if p.returncode != 0:
        log_fp = open(os.path.join(logdir, testname) + '.log', "r")
        all_line=[]
        for line in log_fp.readlines():
            all_line.append(line)
            num += 1
            if p.returncode == 254:
                if re.search("the result is not expected,here is the diff",line) != None:
                    linesdiff=num
        if p.returncode == 254:
            lines=len(all_line)-linesdiff
        for i in range(lines-2*lines,0):
            if abs(i) <= len(all_line):
                sys.stderr.write(all_line[i])
        log_fp.close()
        sys.exit(p.returncode)
