source t/compat/include_for_obtest/load_data_obdocker_mix.inc;
source t/compat/include_for_obtest/create_mview_obdocker_mix.inc;
source t/compat/include_for_obtest/storage_format_mix_obdocker.inc;
source t/compat/include_for_obtest/trans_obdocker_mix_newleader.inc;
source t/compat/include_for_obtest/trans_obdocker_mix_oldleader.inc;
source t/compat/include_for_obtest/ddl_obdocker_mix.inc;
source t/compat/include_for_obtest/multitable_obdocker_mix.inc;
