set global binlog_row_image='MINIMAL';
alter system set writing_throttling_trigger_percentage=60;
alter system set writing_throttling_maximum_duration='2h';
set global ob_trx_idle_timeout=1200000000;
set global ob_query_timeout= 1000000000000;
set global ob_trx_timeout= 1000000000000;
set global recyclebin='OFF';
set global parallel_servers_target=100;
CREATE TABLEGROUP tg;
select sleep(3);
select sleep(9);
select sleep(9);
select sleep(9);
alter system set major_compact_trigger = 1 ; 
alter system set freeze_trigger_percentage=10 ;
