#!/usr/bin/env python2.6
#coding=utf-8

import os, subprocess, tempfile
import urllib2, urllib
import json
import traceback
import sys
import getpass
import shutil
import getopt
import os

user_list=[]

user_name=''
basedir = os.path.split(os.path.realpath(sys.argv[0]))[0]

def get_mysqltest_log(case):
  try:
    case_log = ''
    log_dir = basedir + '/mysql_test/log/'
    file_list = os.listdir(log_dir)
    file_list.sort()
    file_name = file_list[-1]
    fp = file(log_dir+file_name, 'r')
    lines = fp.readlines()
    i = 0
    line_num = len(lines)
    case_format = "[ " + case + " ]"   
    while i < line_num and case_format not in lines[i]:
      i += 1
    if i == line_num:
      print 'get_mysqltest_log, case:%s not exist in log' % case
      return case_log
    i += 2
    line = lines[i]
    if 'mysqltest' in line and 'query' in line and 'failed' in line:
      case_log = line
    else:
      while '========================' not in line and \
        '<<<<<<<<<<<<<<<<<<<' not in line and line:
        case_log += line
        i += 1
        line = lines[i]
    fp.close()
    return case_log
  except:
    print 'get_mysqltest_log, Error:%s' % traceback.format_exc()
    return ''
  finally:
    fp.close()

def create_bug_content(case):
  cmd = "./deploy.py ob1.mysqltest testset=" + case
  (fd, path) = tempfile.mkstemp(suffix='.filebug',prefix=case,dir=basedir)
  fp = os.fdopen(fd, 'w')
  fp.write('[bug_title]:\n' )
  fp.write('[bug_author]:' + user_name + '\n')
  fp.write('[bug_owner]:\n')
  fp.write('[bug_type(1-功能测试、2-接口测试、7-性能测试、16-压力测试)]:2\n')
  fp.write('[bug_level(1-Blocker、2-Major、3-Normal、4-Trivial)]:3\n')
  fp.write('[bug_priority(1-Urgent、2-High、3-Medium、4-Low]:3\n')
  fp.write('[bug_version(1-oceanbase0.4、2-oceanbase0.5、3-obdatasource、4-filebug_test)]:2\n')
  content="==回归环境==\n接口测试\n==日志==\n" + get_mysqltest_log(case) + "\n==问题描述==\n" + cmd + "\n==自动化CASE==\n"+case+'.test\n'
  fp.write('[bug_description]:\n'+content)
  fp.close()
  return path


def filebug(case,create_type=1):
  level_dict = {"1":(87,'1-Blocker'),
                "2":(88,'2-Major'),
                "3":(89,'3-Normal'),
                "4":(90,'4-Trivial')
                }
  priority_dict = {"1":(94,'1-Urgent'),
                   "2":(95,'2-High'),
                   "3":(96,'3-Medium'),
                   "4":(97,'4-Low')
                  }
  type_dict = {"1":"1-功能测试","2":"2-接口测试","7":"7-性能测试","16":"16-压力测试"}
  
  version_dict = {"1":("65558","oceanbase0.4"),
                  "2":("65559","oceanbase0.5"),
                  "3":("68722","obdatasource"),
                  "4":("74414","filebug_test")
                  }
  
  if create_type == 1:
    path = create_bug_content(case)
  else:
    path = os.getcwd() +'/'+case

  editor = os.getenv('EDITOR', 'vim')
  print(editor, path)
  subprocess.call('%s %s' % (editor, path), shell=True)

  title,author,owner,type,levelId,priorityId,versionId,desc = '','','','','','','',''
  f=open(path, 'r')
  try:
    while 1:
      line = f.readline()
      if not line:
        break
      if(line.startswith('[bug_title]:') == True):
          title = line.partition(':')[-1].strip('\n')
      elif(line.startswith('[bug_author]:') == True):
          author = line.partition(':')[-1].strip()
          user_list.append(author)
      elif(line.startswith('[bug_owner]:') == True):
          owner = line.partition(':')[-1].strip()
          user_list.append(owner)
      elif(line.startswith('[bug_type') == True):
          value = line.partition(':')[-1].strip()
          if len(value) == 0:
            break
          type = type_dict[value]
      elif(line.startswith('[bug_level') == True):
          value = line.partition(':')[-1].strip()
          if len(value) == 0:
            break
          levelId = level_dict[value]
      elif(line.startswith('[bug_priority') == True):
          value = line.partition(':')[-1].strip()
          if len(value) == 0:
            break
          priorityId = priority_dict[value]
      elif(line.startswith('[bug_version') == True):
          value = line.partition(':')[-1].strip() 
          if len(value) == 0:
            break
          versionId = version_dict[value]
      elif(line.startswith('[bug_description]:') == True):
          desc = ''
      else:
          desc = desc + '\n' +line
    content_dict={'title':title,
          'author':author,
          'owner':owner,
          'type':type,
          'levelId':levelId,
          'priorityId':priorityId,
          'versionId':versionId,
          'desc':desc,
          'testname':case,
          'tempfile':path}
    submit(content_dict)
  except:
    print traceback.format_exc()
  finally:
    f.close()
    os.unlink(path)
    return


def submit(content_dict):
  try:
    print "------------------------------------------------"
    print "[bug_title]:" + content_dict['title']
    print "[bug_title]:" + content_dict['title']
    print "[bug_owner]:" + content_dict['owner']
    print "[bug_author]:" + content_dict['author']
    print "[bug_type]:" + content_dict['type']
    print "[bug_level]:" + str(content_dict['levelId'][1])
    print "[bug_priority]:" + content_dict['priorityId'][1]
    print "[bug_version]:" + content_dict['versionId'][1]
    print "[bug_desc]:" + content_dict['desc']
    bug_desc=[('version_id',content_dict['versionId'][0]),                         #项目编号
              ('author',content_dict['author']),                                   #创建人
              ('assigned_to',content_dict['owner']),                               #指派人
              ('tracker_id','6'),                                                  #模板缺陷[功能缺陷：6]
              ('issue[subject]',content_dict['title']),                            #缺陷标题
              ('issue[description]',content_dict['desc'].replace('\n', '<br />')), #缺陷描述
              ('issue[priority_id]',content_dict['priorityId'][0]),                #缺陷优先级
              ('issue[serious_level_id]',content_dict['levelId'][0]),              #缺陷严重程度
              ('issue[custom_field_values][54]',content_dict['type']),             #测试类型
              ('issue[custom_field_values][65]',''),
              ('auth','6edfcfe6f99d1f8016fbfe03ceae6207'),
              ('watcher_user_ids[]',''),
              ('watcher_group_ids[]',178)]                                         #指定跟踪组
    print("-----------------------------------------------")
 #   watcher_list = ['羽兰']
 #   for watcher in watcher_list:
 #     bug_desc.append(('watcher_user_ids[]', watcher))
    
 #   user_list.extend(watcher_list)

    url_value=urllib.urlencode(bug_desc)
    
    check = raw_input("file bug?(y/n):")
    while check != 'y' and check != 'n':
      check = raw_input("file bug?(y/n):")
    if check == 'n':
      saveTempfile(content_dict['testname'], content_dict['tempfile'])
      print 'bug not submit, file saved at %s' % os.getcwd() + '/'+ content_dict['testname'] + '.filebug'
      return 0

    if checkUserListValidity(user_list) == False:
      return 0

    res = urllib2.urlopen("http://k.alibaba-inc.com/api/issues/new",url_value).read()

    result = json.loads(res) 
    if result['code'] == 200:
      print 'submit succ, bug_id:%s' % result['id']
      print 'http://k.alibaba-inc.com/issues/%s' % result['id']
    else:
      print 'submit failed,err_msg:%s' % result['errors']

  except:
    print traceback.format_exc()
  
def checkUserValidity(user_name):
  base_url="http://k.alibaba-inc.com/api/admin/users/search?auth=6edfcfe6f99d1f8016fbfe03ceae6207&user=";
  url=base_url+user_name
  res = urllib2.urlopen(url).read()
  result = json.loads(res)
  if len(result['users']) == 0:
    print 'Invalid user:%s' % user_name
    return False
  for value in result['users']:
    if value['nickname'].encode("utf-8") != user_name:
      print 'Invalid user:%s' % user_name
      return False
  return True

def checkUserListValidity(user_list):
  for user_name in user_list:
    if not checkUserValidity(user_name):
      return False
  print 'all users are valid!!!'
  return True

def saveTempfile(test_name, tempfile):
  save_file=test_name + '.filebug'
  shutil.copy(tempfile,save_file)

def getUsername():
  try:
    base_url="http://k.alibaba-inc.com/api/admin/users/search?auth=6edfcfe6f99d1f8016fbfe03ceae6207&user=";
    url=base_url+getpass.getuser()
    res = urllib2.urlopen(url).read()
    result = json.loads(res)
    user_name=''
    if len(result['users']) == 0:
      print 'Invalid user:%s' % user_name
      return '' 
    user_name = result['users'][0]['nickname'].encode("utf-8")
    return user_name
  except:
    print 'getUsername failed, Error:%s' % traceback.format_exc()
    return ''
    
def help():
  print '  -t    Specify the test name.'
  print '  -f    Submit bug with existed bug_desc_file.'
  print '  -h    Display this help and exit.'
  print ''
  print 'Options are alternative.'
  print ''


if __name__ == '__main__':

  print os.path.split(os.path.realpath(sys.argv[0]))[0]
  if len(sys.argv) < 2:
    help()
    sys.exit(1)
  
  try:
    opts,args = getopt.getopt(sys.argv[1:],'ht:f:')
    print opts,args
  except:
    print  "input opt error!!!"
    help()
    sys.exit(1)

  if len(opts) != 1 or len(args) !=0 :
    help()
    sys.exit(1)
  for op,value in opts:
    if op == '-t':
      user_name = getUsername() 
      filebug(value)
    elif op == '-f':
      filebug(value,0)
    else:
      help()
      sys.exit(1)






