#!/bin/bash
declare -A asource

LOCALDIR="$(dirname $(readlink -f "$0"))"
TESTDIR="${LOCALDIR%/*/*}/test"
rm -rf $TESTDIR/mysql_test
mkdir -p $TESTDIR
time=$(date '+[%m-%d %H:%M:%S]')

# publish test suite cases
echo -e "${time} \033[34mpublish mysqltest suite cases\033[0m\r"
IFS=''
case_array=(substring_index
type_date.test_select_usec_to_time
static_engine.expr_concat
trx_timeout
dist_nest_loop_simple
static_engine.expr_sys_privilege_check
two_order_by
static_engine.expr_conv
static_engine.expr_nextval
static_engine.expr_regexp_func
skyline.skyline_index_back_mysql
geometry.st_aswkb_mysql
executor.full_join
expr.expr_position
geometry.st_srid_mysql
pl.pl_bug_16303638_mysql
datatype.div
empty_input
static_engine.subplan_scan
pl.sp-bugs_mysql
add
pl.pl_dbt2_mysql
storage.rowkey_is_int
column_store.basic_column_group_syntax
subquery.subquery_sj_innodb
topk
compare
px.join_hash
inner_table.user_privileges
merge_uncommitted.reuse_dirty_macro
explain
static_engine.expr_repeat
column_store.add_column
delete.deleteV2
column_store.co_major_without_all_cg
column_store_encoding.filter_const_dict_cs_encoding
static_engine.expr_unhex
static_engine.expr_math
merge_uncommitted.multi_minor_merge
global_index.global_index_lookup_4
merge_uncommitted.query_uncommitted_data
inner_table.tenant_virtual_event_name
replace.replace_null
geometry.st_geometry_columns
pl.pl_function_negative_mysql
join_equivalent_transfer
inner_table.session_variables
px.sql_audit
meta_info.meta_func_floor
sfu_norow_alias
expr.expr_instr
idx_const_basic_one_bool
geometry.st_bestsrid_mysql
datatype.null2
static_engine.expr_regexp
static_engine.expr_length
column_store.tile_project
static_engine.expr_assign
geometry.st_area_mysql
inner_table.all_virtual_sys_parameter_stat
static_engine.expr_is
meta_info.meta_const
trx.tx_free_route
px.unmatched_distribution
merge_uncommitted.update_with_index
inner_table.inner_table_overall
pl.sp_validation_mysql
static_engine.expr_nullif_ifnull
geometry.st_intersects_mysql
type_date.daylight_saving_time
static_engine.expr_location
ms_lose_rollback
index_49_alias
subquery.rqg_subquery_materialization_oop
meta_info.meta_type
static_engine.expr_insert
msdt.hidden_table
truncate_table
merge_uncommitted.select_data_in_fuse_row_cache
bug200747
static_engine.expr_replace
geometry.st_geomfromtext_mysql
static_engine.nested_loop_join
delete.delete_range
func_group_5
expr.func_length
create_using_type
inner_table.session_status
trans_ac
column_store.basic_column_group_scan
bulk_insert
alter.alter_log_archive_option
storage.rowkey_is_null
pl.pl_bit_mysql
foreign_key.dml_147
geometry.st_intersects_mysql_from_pg
merge_uncommitted.big_uncommitted_trans
geometry.st_x_mysql
static_engine.expr_time_diff
merge_uncommitted.get_uncommitted_row_with_fuse_row
bench_count_distinct
meta_info.meta_func_ceil
createsql
major_freeze.tenant_major_freeze
lob.lob_large_mysql
merge_uncommitted.rollback_sql_sequence2
static_engine.expr_and_or
static_engine.expr_get_sys_var
column_store_encoding.add_column_cs_encoding
special_stmt
static_engine.expr_not
inner_table.all_virtual_data_type_class
geometry.st_geomfromewkb_mysql
bug210026
major_freeze.daily_major_freeze_launcher
type_date.type_create_time
inner_table.tenant_virtual_statname
expr.collation_expr
merge_uncommitted.mix_dml_for_uncommitted
aggr_bug200109
msdt.lob
static_engine.expr_xor
table_api.ttl_full
px.default_open_px
expr.mul
sq_from_2
yonyou_test.yonyou_online_ddl
static_engine.subplan_filter
information_schema
merge_uncommitted.lock_row_in_minor
pl.pl_lot_variables_mysql
duplicate_key
px.alloc_material_for_producer_consumer_schedule_mode
geometry.geometry_partition_table_mysql
geometry.st_latitude_mysql
static_engine.expr_find_in_set
geometry.create_spatial_index_mysql
geometry.geometry_filter_mysql
show_create_tablegroup
geometry.geometry_compare_mysql
expr.expr_nseq
px.tsc
update_range
global_index.global_index_lookup_3
type_date.expr_date_add_sub
sfu
px.join_nlj
alias2
skyline.skyline_complicate_mysql
geometry.st_distance_sphere_mysql
static_engine.expr_substring_index
chinese
pk_num_boundary
column_store.co_major_merge
pl.pl_exec_database_mysql
skyline.skyline_basic_mysql
connection
geometry.st_geomfromwkb_mysql
information_schema.information_schema_desc
static_engine.expr_collation
geometry.geometry_ddl_mysql
createvarchar
number.bug229955_positive_int
inner_table.character_sets
geometry.geometry_bugfix_mysql
pl.pl_case_insensitive_mysql
column_store.basic_column_group_scan_with_minor
join.nested_loop_join_right_null_joinon
pl.pl_user_sys_var_mysql
insert.insert_ignore
geometry.st_buffer_mysql
geometry.st_point_mysql
pl.pl_bugs_mysql
global_index.global_index_lookup_1
merge_uncommitted.test_new_buf_minor_with_add_column
largetimeout
datatype.type_varchar_2
ddlrollback
subquery.spf_bug13044302
view
geometry.st_longitude_mysql
pl.pl_var_default_val_mysql
range
static_engine.expr_lower_upper
static_engine.expr_is_serving_tenant
geometry.st_transform_mysql
sys_vars.tx_isolation_basic
inner_table.table_constraints
pl.pl_show_mysql
inner_table.desc_virtual_table_in_mysql
global_index.global_index_lookup_2
storage.rowkey_is_char
static_engine.expr_field
direct_load_data.direct_load_data
identifier_name_length
inner_table.collations
pl.pl_exception_basic_mysql
expr.expr_ceil
inner_table.all_virtual_engine
column_store_encoding.black_special_cs_encoding
skyline.skyline_business_mysql
static_engine.hash_distinct
geometry.__all_tenant_spatial_reference_systems
inner_table.desc_sys_views_in_mysql
yonyou_test.yonyou
idx_unique_many_idx_one_ins
px.join_mj
escape
static_engine.expr_des_hex_str
static_engine.explicit_cast
bug233498_rename_table_jianming
meta_info.meta_build_in_func_test
delete.delete
static_engine.expr_char_length
selectotherdb
static_engine.table_insert
func_group_1
type_date.add_timestamp_column
pl.sp-vars_mysql
static_engine.expr_str
static_engine.expr_datediff
static_engine.expr_ascii
static_engine.expr_get_user_var
trx_6
intersect
px.agg
pl.sp-prelocking_mysql
a_trade_notify
expr.expr_locate
merge_uncommitted.query_uncommitted_data2
geometry.st_covers_mysql
global_index.global_index_select
static_engine.static_engine_case
inner_table.parameter_variable_conflict_check
merge_uncommitted.rollback_trans
column_store_encoding.count_pushdown_cs_encoding
geometry.geometry_ddl_dml_postgis
column_store.basic_column_group_scan_flat
rename_table2
diag_tenant
static_engine.expr_pad
static_engine.expr_nvl
merge_uncommitted.dirty_trx_minor_merge
trx_4
static_engine.table_scan
type_date.timestamp2
merge_uncommitted.multi_get_uncommitted_row
inner_table.views
join_basic
pl.sp_trans_log_mysql
direct_load_data.direct_load_data_heap_table
join_many_table
geometry.geometry_basic_mysql
static_engine.expr_unix_timestamp
outer_join_where_is_null
subquery.optimizer_subquery_bug
bug5910265_update_orderby_limit_dilang
inner_table.table_privileges
non_reserved_keyword
column_store_encoding.basic_cs_encoding
static_engine.expr_neg
inner_table.all_virtual_data_type
pl.pl_exception_mysql
geometry.geometry_dml_mysql
datatype.minus
subquery.idx_with_const_expr_21_subquery_dilang
update_behavior
static_engine.expr_empty_arg
static_engine.expr_date
datatype.replace
geometry.st_dwithin_mysql
type_date.datetime_java
window_function.farm
static_engine.expr_dump
static_engine.px_basic
type_date.timefuncnull
geometry.geometry_index2_mysql
update.update_ignore
join_null
static_engine.merge_set
geometry.geometry_generated_col_mysql
static_engine.expr_elt
a_trade_quick
big_trans_with_mutil_redo
merge_uncommitted.rollback_sql_sequence3
safe_null_test
groupby.group_by_2
join.nested_loop_join_right_null
merge_uncommitted.update_uncommitted_data
count
pdml.insert_all_feature
geometry.geometry_function_mysql
subquery.rqg_subquery_semijoin_mismatch
geometry.st_astext_mysql
static_engine.expr_part_hash
inner_table.parameter_data_type
join_many_table_single_field
index_14_hint
update.update2
geometry.geometry_index1_mysql
distinct
geometry.st_buffer_mysql_from_pg
lob.lob_bug_mysql
expr.func_equal
static_engine.expr_md5
jp_length_utf8
lob.lob_basic_mysql
pdml.pdml_update_part_global_index
insert.insert_and_update_not_null
executor.trx
static_engine.expr_mid
static_engine.expr_substr
alias3
sq_from
merge_uncommitted.rollback_sql_sequence_check_lock
static_engine.expr_aes_encrypt
datatype_java
merge_uncommitted.mini_merge_with_same_sql_sequence
static_engine.expr_left
static_engine.expr_bool
geometry.geometry_type_mysql
merge_uncommitted.rollback_sql_sequence
global_index.global_index_lookup_5
column_alias
static_engine.material
geometry.st_distance_mysql
index_47_NULL
static_engine.expr_space
join_using1
static_engine.expr_trunc
empty_table
join_star
geometry.spatial_relation_join_mysql
geometry.geometry_index_mysql
static_engine.expr_trim
trx.bug_different_tranid_intrx
static_engine.expr_coalesce
static_engine.merge_join
view.dba_ob_tenants
static_engine.expr_abs
system_variable.autocommit
static_engine.expr_from_unixtime
virtual_thread
proxy_related_vtable.all_virtual_proxy_sub_partition
static_engine.monitoring_dump
subquery.rqg_subquery_semijoin_nested_timeout
trx.serializable_constrains
groupby.group_by_basic
static_engine.expr_part_key
get
expr.expr_floor
static_engine.expr_todays
join.anti_semi_join
px.join_pwj
table_redefinition.alter_primary_key
deadlock_detector.trans_deadlock_basic
table_api.ttl_ddl
table_api.ttl_table_ts
proxy_related_vtable.all_virtual_proxy_partition
subquery.subquery_sj_firstmatch
special_hook
inner_table.schemata
trx_5
merge_uncommitted.single_get_uncommitted_row
inner_table.desc_virtual_table_in_sys
static_engine.expr_timestampadd
static_engine.static_engine_hash
subquery.subquery
expr.func_regexp
groupby.group_by_4
pl.pl_function_ddl_negative_mysql
func_group_7
inner_table.desc_sys_views_in_sys
driver5114_bug
merge_uncommitted.commit_after_minor_merge
datatype.bool
proxy_related_vtable.all_virtual_proxy_partition_info
join.nested_loop_join_right_null_joinon_where
pl.pl_func_17623008_mysql
px.add_material
pl.pl_bug_16681136_mysql
major_freeze.virtual_freeze_info
pl.sp_gis_mysql
geometry.geometry_function_postgis
pl.sp-fib_mysql
subquery.order_by_subquery
column_store_encoding.pushdown_cs_encoding
global_index.global_index_lookup_6
static_engine.expr_lnnvl
pl.pl_basic_mysql
merge_uncommitted.delete_uncommitted_data
update_column_use_other
limit
h
trx.trans_weak_read
join.join_merge
parallel_insert
geometry.geometry_cast_mysql
update_delete_limit_unique_key
trx_timeout_bug
update.rowkey_update_datatype_convert
static_engine.static_engine_cmp_null
except
column_store_encoding.cs_add_column
merge_uncommitted.lock_uncommitted_data
pl.pl_basic_recursion_depth_mysql
inner_table.all_virtual_upgrade_inspection
select_basic
type_date.type_modify_time
merge_uncommitted.rollback_and_major
view_2
inner_table.global_variables
inner_table.partitions
bug_setEmptyPwd
pl.sp_stress_case_mysql
executor.basic
meta_info.meta_func
meta_info.meta_test_func_return_type
pl.sp-big_mysql
inner_table.global_status
func_group_6
fin
type_date.updaterowkeymoditime
subquery.rqg_ob_subquery_semijoin_nested_sql_parameterization
column_store_encoding.filter_null_cs_encoding
geometry.st_y_mysql
column_store_encoding.co_cs_major_merge)

function copy_source
{
  IFS=$'\n' 
  local file=$1
  local sources=`egrep "^\s*--\s*source" $file | awk -F'source ' '{print $2}' | uniq`
  local require=`egrep "^\s*--\s*require" $file | awk -F'require ' '{print $2}' | uniq`
  local datas="$(dirname $(dirname $file) |sed -n 's/.*\(mysql_test\/.*\)/\1/p')/data"
  local sources=("${sources[@]}" "${require[@]}")

  if [ ${#sources[@]} -ne 0 ]; then
    for source in ${sources[@]}; do
      source=$(echo "$source" | tr -d '[:space:]' | tr -d '\r')
      echo -e "${time} \033[34mpublish source files ${source}\033[0m\r"
      tar_dir=`dirname $source`
      mkdir -p $TESTDIR/$tar_dir
      cp -f $LOCALDIR/$source $TESTDIR/$tar_dir
      grep -q "$datas/" $LOCALDIR/$source && {
         mkdir -p $TESTDIR/$datas
         cp -r $LOCALDIR/$datas/* $TESTDIR/$datas/
      }
      copy_source $LOCALDIR/$source
    done
  fi
}


for str in ${case_array[@]}; do
  if [[ $str =~ "." ]]
  then 
      IFS='.' && read -a strarr <<< "$str"
      IFS='' && echo -e "${time} \033[32mpublicing the mysqltest ${str}\033[0m\r"
      test_file=mysql_test/test_suite/${strarr[0]}/t/${strarr[1]}.test
      result_file=mysql_test/test_suite/${strarr[0]}/r/mysql/${strarr[1]}.result
      source_result_file=$result_file
      if [[ -f $LOCALDIR/mysql_test/test_suite/${strarr[0]}/r/mysql/${strarr[1]}.ce.result ]]
      then
          source_result_file=mysql_test/test_suite/${strarr[0]}/r/mysql/${strarr[1]}.ce.result 
      fi
  else
      IFS='' && echo -e "${time} \033[32mpublicing the mysqltest ${str}\033[0m\r"
      test_file=mysql_test/t/${str}.test
      result_file=mysql_test/r/mysql/${str}.result
      source_result_file=$result_file
      if [[ -f $LOCALDIR/mysql_test/r/mysql/${str}.ce.result ]]
      then
          source_result_file=mysql_test/r/mysql/${str}.ce.result
      fi
  fi
  # test file
  mkdir -p $TESTDIR/`dirname $test_file`
  cp $LOCALDIR/$test_file $TESTDIR/$test_file

  # result file
  mkdir -p $TESTDIR/`dirname $result_file`
  cp $LOCALDIR/$source_result_file $TESTDIR/$result_file

  # source file
  copy_source $LOCALDIR/$test_file
  

done
