#+Title: happy deploy
#+options: toc:nil

hap.py主体是一个python文件: hap.py， 我们在命令行上指定一个命令，hap.py会按顺序加载两类文件, 扩展文件和配置文件，这两类文件都是合法的python文件。扩展文件会有多个，配置文件只有一个:
1. 扩展文件是被hap/init.py加载的, init.py基本没有什么逻辑，内容就是加载其它的扩展文件。
2. 配置文件，命名符合正则表达式 ./config[0-9].py 按字典序加载最后一个文件，配置文件可能不存在，这种情况下hap.py不会报错.
扩展文件和配置文件本质上没有区别的，都是合法的python文件，会以同样的方式被hap.py加载。只不过习惯上，扩展文件里包含若干功能定义，配置文件里包含若干实体定义。
* init.py
目前init.py只有以下两行:
: load_file("hap/base.py")
: load_ext('obi,ct,mysqltest,obm,old_cfg,sysbench')
1. hap/base.py包含了各种核心功能定义。
2. load_ext加载各种扩展文件，扩展文件命名为 "h/$ext.py", load_ext('obi')等价于load_file('h/obi.py')
* 原理
为了先理解hap.py的功能，我们先看一个例子。 编辑配置文件(比如config9.py)，使得它的内容如下:
: a, b = 1, 2
: c = dict(a=3, b=4)
: def hello(name='', *args, **kw): return 'hello %s!'%(name)
如果我们执行 ./hap.py a ，那么hap.py会最终找到a，并判断a是一个整数，最后把它的值打印出来。
:  ['a', 1]

如果执行./hap.py c.a, hap.py会判断'c'是一个dict，然后在dict中查找到'a', 最后输出
: ['c.a', 3]

如果执行 ./hap.py hello world，hap.py会找到 'hello' 这个函数，并最终执行它:
: ['hello', 'hello world!']

也可以用 ./deploy.py hello name=world 来指定参数。

更一般地，在命令行上给hap.py指定一个'a.b.c'形式的定位符，hap.py根据这个定位符找到对应的对象(把这个过程叫寻址)，然后根据对象的类型执行对应的操作(把这个过程叫执行)。

1. '寻址'的逻辑: hap.py把所有的对象看作是嵌套的字典，这些嵌套的字典就形成了嵌套的作用域。'a.b.c'的意义是在全局作用域中找到a, a必须是一个字典，然后在a寻找b，b必须也是一个字典，这里有个特殊处理：如果a中找不到b，那么会退回到a的上层作用域去寻找b。依次类推，直到最后在b中找到c。
    : a, c = 1, 2
    : b = {'a':3}
    './hap.py a' 会输出 1 ， './hap.py b.a' 会输出 3 , './hap.py b.c' 会输出 2 。
2. '执行'的逻辑: hap.py根据对象类型执行不同的动作：如果是一个函数，就执行它；如果是一个数字就打印它，如果是字符串，处理流程如下:
   1. 首先，所有的字符串都会被模板替换，模板替换的过程是把字符串中的 ${a.b.c} $a 形式的变量进行替换， 替换的规则后面详细解释。
   2. 其次，以'!'开始的字符串会被特殊处理，这种字符串被称为'magic string'。 magic string的处理后面详细解释。

* 模板替换
 '$a bc'中的'$a'会被替换掉
   1. 如果变量a存在，那么'$a' 会被替换为变量a的值
   2. 如果变量a不存在，那么'$a'就保持原样。
   3. 如果变量a是个函数，那么'$a'会被替换为函数调用的返回值。
   4. 替换是会执行多遍的，直到再也没有变量能被替换为止。比如: '$foo_$bar', 假设第一次执行'$bar'被替换为'xxx', 结果变成'$foo_xxx', 如果'foo_xxx'存在的话，会被继续替换。
   5. '${a.b.c}'处理类似, a.b.c会按照之前讲的寻找和执行的逻辑被处理

* magic string的处理
  先用两个例子说明magic string如何被解释:
    1. '!sh: echo "hello world"', 最后会调用到magic_sh('hello world', *args, **kw); 
    2. '!sql: alter system major freeze;'最终会调用到magic_sql('alter systerm major freeze', *args, **kw);
    一般地，'!xxx abc def', 会被调用到magic_xxx('abc def', *args, **kw), 如果magic_xxx未定义，magic string就原样返回。

* 扩展magic handler
  只需要在全局定义magic_xxx函数即可，假设你想把扩展定义在h/foo.py, 那么只需要在h/foo.py中定义:
#+BEGIN_SRC python
@Call
def magic_xxx(cmd, *args, **kw):
    return '%s is executed by magic handler xxx'%(cmd)
#+END_SRC
然后记得在hap/init.py中加入:
: load_ext('foo')
内部的magic_handler都定义在hap/base.py, 通过grep命令可以列出所有的magic_handler
#+BEGIN_EXAMPLE
yuanqi.xhf@OceanBase224004 deploy$ grep 'def magic_' hap/base.py 
def magic_sh(d, cmd, args, kw):
def magic_popen(d, cmd, args, kw):
def magic_tryloop(d, cmd, args, kw):
def magic_ssh(d, cmd, args, kw):
def magic_ssht(d, cmd, args, kw):
def magic_sql(d, cmd, args, kw):
def magic_check(d, cmd, args, kw):
def magic_call(d, cmd, args, kw):
def magic_seq(d, cmd_list, args, kw):
def magic_filter(d, cond, args, kw):
def magic_all(d, cmd, args, kw):
def magic_par(d, cmd, args, kw):
def magic_rand(d, cmd, args, kw):
def magic_second(d, cmd, args, kw):
def magic_checkall(d, cmd, args, kw):
def magic_uniq(d, cmd, args, kw):
#+END_EXAMPLE
* rf运行脚本
hap.py定义了一个特殊的函数rf(), ./hap.py rf a.py 可以解释a.py文件。rf()的特殊之处在于: a.py中不仅可以包含合法的python代码，还可以包含某些非法的python代码，这些非法的python代码会被特殊解释。
比如a.py包含如下的内容:
#+BEGIN_EXAMPLE
def foo(): pass # 合法
ob1.reboot _dryrun_ # 非法
#+END_EXAMPLE
上面这个文件会分为两步执行:
1. wrap: 这一步会把非法的python代码变换为I<<''' src ''' 的形式，让它变成合法的python代码。./hap.py wrap_src a.py可以看到结果:
   : def foo(): pass
   : I<<''' ob1.reboot _dryrun_ '''
2. 执行，让a.py变成合法的python文件后，就可以用execfile执行了。I<<''' src '''最终会调用到Interp.interp(src), 关键是Interp.interp(...)的执行逻辑. 后面详述。

一个例子如下， 把下面的内容保存为a.py, 然后执行./hap.py ob1.rf a.py
#+BEGIN_EXAMPLE
run_file('s/utility.py')
fsql set autocommit=1; # sql中的set和bash的set有歧义，所以要加上fsql

try:
    obi.check_bootstrap
    print 'bootstrap ok'
except Exception as e:
    print 'try reboot'
    obi.reboot

def load_data(**kw):
    vchar = '0' * 255
    for i in range(10):
        values = ','.join(['(%d,%s)'%(i * 1000 + j, vchar) for j in range(1000)])
        insert into t1 values $values;

if select table_id from __all_table where table_name='t1':
    print 'table exists'
else:
    print 'create table and load data'
    CREATE TABLE t1 (rk int primary key, c1 varchar(255));
    load_data
#+END_EXAMPLE

* interp
interp函数原型:
: def interp(cmd, locals, globals, **opt):
:    ...

interp()的执行依赖于一个函数数组，每个函数都相当于是一个特定的interpreter。 interp()按顺序尝试用这些interpreter去解释cmd，直到遇到一个能解释通的; 如果所有的interpreter都不能解释，那么就返回None。

interp()和各个interpreter约定如下:
1. 如果interpreter解释不了cmd，那么就返回None。
2. 如果能解释cmd，那么就返回是一个dict, dict的result属性记录解释的结果。

内部的interpreter都定义在hap/base.py, 可以通过grep命令列出所有的interpreter
#+BEGIN_EXAMPLE
yuanqi.xhf@OceanBase224004 deploy$ grep 'def interp_' hap/base.py                                                                                                                                                                                                                
def interp_magic_str(cmd, locals, globals, head='', **opt):
def interp_simple_hap(cmd, locals, globals, head='', **opt): # ob1.reboot etc
def interp_eval(cmd, locals, globals, head='', **opt):
def interp_suite(cmd, locals, globals, head='', **opt):
def interp_hap(cmd, locals, globals, head='', **opt): # ob1.reboot etc
def interp_popen(cmd, locals, globals, head='', ctx='void', **opt): # mkdir -p xxx
#+END_EXAMPLE
* 扩展interpreter
在h/foo.py中添加如下的代码:
#+BEGIN_SRC python
@Interp
def interp_xxx(cmd, locals, globals, **opt):
    return 'interp by xxx: %s'%(cmd)
#+END_SRC
然后记得在hap/init.py中加入:
: load_ext('foo')

* ish
可以用以下命令启动一个interactive console，用上面介绍的interp的逻辑解释执行命令
: ./hap.py ish
1. ish使用readline读取命令，支持命令行历史，tab补齐，多行编辑(定义函数的时候有用)。
2. ish启动会加载hap/ish.py, 执行shell命令时会加载hap/sh.rc, 缺省的sh.rc会加载 ~/.bashrc, 并且会启用alias.
* rf和ish的运行环境
1. ob1.ish启动的动态shell, local_env=ob1, 这样做的目的是为了便于使用，但是命令行上定义的函数会有限制，比如定义了foo()函数，它处于local作用域，在bar()函数里不能调用foo()函数，因为bar()函数里找不到foo的定义。
2. ob1.rf a.py执行时, a.py中的内容local_env=global_env=globals(). run_file('b.py')执行时local_env=global_env=globals(), 这样做的目的是为了便于理解，在任何一个文件顶层定义的函数和变量都在全局作用域。

* 兼容
1. gcfg去掉了
   : gcfg['_verbose_'] = True
   : gcfg['_quiet_'] = True
   应该改为
   : logger.set_log_level(3)
   : logger.set_log_level(0)

2. ObCfg定义的所有配置项现在都应该直接在全局定义:
   : ObCfg.usr = 'admin'
   应该改为: 
   : usr = 'admin'
   不过为了兼容，ObCfg还留着，在load配置文件之后，ObCfg的所有配置项都patch到globals()

* mysqltest
定义在h/mysqltest.py
: ./hap.py ob1.proxy0.psmalltest
* sysbench
定义在h/sysbench.py, sysbench在github上的地址https://github.com/akopytov/sysbench

修改config2.py
#+BEGIN_EXAMPLE
sql_user = 'root'
sysbench_bin = 'sysbench/sysbench'
sysbench_db = 'test'
sysbench_lua = 'sysbench/select.lua'
sysbench_max_time = 10
sysbench_table_size = 100
sysbench_threads = 1
ob1 = OBI('[rs@100.81.152.34,proxy@100.81.152.40]@[z1,z2,z3]')
#+END_EXAMPLE
然后执行
: ./hap.py ob1.reboot
: ./hap.py ob1.proxy0.sysbench prepare run
执行时需要把sysbench可执行程序和lua脚本都放到sysbench目录, 用下面的命令检查sysbench目录是否有对应的文件。
: ls sysbench/sysbench sysbench/*.lua # 把需要的lua文件都拷贝到sysbench目录
sysbench可执行文件和lua文件可以从http://11.166.86.153:8877/obperf.tar.gz 获得

缺省配置跑ob1.sysbench，性能会很差，因为租户的资源限制没调整。要跑出合理的性能，可以用下面的命令:
: ./hap.py ob1.sbperf testcase=tcbuyer_insert
sbperf命令实际执行了s/sbperf.py文件:
:    sbperf = '!call: rf s/sbperf.py' # sbperf.py会调整租户资源限制
如果要统计各个阶段的耗时，推荐用竹翁的run_sysbench.pl

* cmd and config cookbook
+ 列出tab补全项
: ./hap.py ob1.list_attr _log_=0
+ dooba
: ./hap.py ob1.dooba
+ 在config2.py中配置clog目录
: clog_dir='/data/6'
+ 在config2.py中修改observer配置项
: obs_cfg.update(workers_per_cpu_quota=5)
: ob1 = OBI('[rs@100.81.152.37,100.81.152.41]@[z1,z2,z3]', obs_cfg=dict(xxx='yy'))
+ 在config2.py中修改obproxy配置项
: proxy_cfg.update(syslog_level='INFO')
: ob1 = OBI(server_spec='[100.81.140.76,proxy@100.81.140.76]@zone1', proxy_cfg=dict(foo='bar'))
+ 指定port和mysql_port, obdir
: ob1 = OBI(server_spec='100.81.140.76:20900:20901@test proxy@100.81.140.76:8042@test', obs0=dict(obdir='$HOME/obmonster.z1.obs0'))
用这种方法可以去连接用其它方式启动的observer
+ 指定端口号从某个起始点分配
: port_gen = itertools.count(12345)
: ob1 = OBI(...)
第一个server的port是12345, mysql_port是12346，第二个server的port是12347, 这样依次类推
* ish cookbook
+ ./hap.py ob1.ish即可启动ish，推荐用screen或tmux，开启多个tab，其中一个tab可以专门运行ish
+ C-c可以中断正在执行的命令，如果没有命令执行，就会重启ish, 修改config2.py文件后，需要C-c重启ish，以便刷新配置项。
+ ish当作计算器
: (1049) % (2**10)
+ ish里面做timestamp和ip的转换
: ts2str 1452346125633126 # 实际上是shell alias
: ip2st4 14837
+ ish里执行deploy命令
  首先执行./hap.py ob1.ish, 然后在ish里执行
: update_local_bin
: reboot
: pid
: obs0.less
: obs0.cat |grep ERROR
+ ish里做sql查询
: load_file('h/sql.py') # 依赖于MySQLdb, 也可以在config2.py load_file
: select * from __all_zone
sql连接断开后需要C-c重启ish
+ 切换目录
: cd ~/ob.clog
+ 切换obi
: cd ob2
: cd ob1.obs0
+ 获取shell命令和sql的输出
: a = ls
: tid, tname = select table_id,table_name from __all_table limit 1
: leader_ip = select svr_ip from __all_meta_table where table_id=$tid and role=1;
+ for循环迭代shell和sql的结果
: for f in find . -name '*.py':
:    print f
: for tid,tname in select table_id, table_name from __all_table limit 10:
:    print tid, $tid
:    echo $tid
+ 命令行上定义函数
: def count_case(dir='.', **kw):
:   file_list = find $dir -name '*.test'
:   return len(file_list.split('\n'))
: count_case mysql_test/t # 调用函数
+ 设置缺省的日志级别
  修改hap/ish.py
: logger.set_log_level(1) # INFO日志
+ 设置额外的shell alias
  修改hap/sh.rc
: alias xxx=yyy # 或者直接放到.bashrc
+ 执行单条ish命令
: ./hap.py ob1.obs0.ish 'mysql -h $ip -P $mysql_port -uroot'
: ./hap.py ob1.obs0.ish '!seq: id pid'
: ./hap.py ob1.ish '!all: all_observer kill_by_port'
+ ish中设置log level
: _log_=0 # 关掉日志
: _log_=3 # 打开debug日志
+ ish中强制执行shell命令
: shell for f in *; do echo $f; done
+ ish中强制执行hap cmd
: hap obs0.grep ERROR
+ 强制调用python函数
: foo(a, b) # 加上圆括号即可
* rf的缺陷
** list comprehension不能写成generator的形式
#+BEGIN_EXAMPLE
def foo(**kw):
    for i in range(10):
        values = ','.join('(%d,%s)'%(i * 1000 + j, '0000') for j in range(1000))
foo
#+END_EXAMPLE
上面的脚本运行时会报错, 需要做如下修改:
#+BEGIN_EXAMPLE
        values = ','.join('(%d,%s)'%(i * 1000 + j, '0000') for j in range(1000))
修改为:
        values = ','.join(['(%d,%s)'%(i * 1000 + j, '0000') for j in range(1000)])
#+END_EXAMPLE
** 不支持嵌套的scope
eval/exec只能在locals()中查找symbol，locals()中找不到，再到globals()中去找，而不会到outer scope中去找，它也不知道outer scope是什么。
** 不支持在函数内调用定义在locals()中的函数
和嵌套scope类似，比如函数foo()定义在一个local_env中，函数bar()中用interp想调用foo(), 函数bar()中的locals()是找不到foo的定义，globals()中也找不到foo()的定义，所以函数bar()中用eval/exec是找不到foo这个变量的。
特别的，ish命令行可以调用命令行上定义的函数，但命令行上定义的函数不能调用在命令行上定义的函数。
** batch mode不会执行hap/sh.rc
这样的话hap,sh等alias/function是未定义的。
* 嵌套dict的缺陷
一个dict可以作为多个dict的子dict出现， 但在实现层面上为了简单，也是为了理解起来容易，一个dict只能有一个parent, add_parent_link()实现的时候是深度优先遍历给每个dict添加__parent__属性，
但是同一个层次上，子dict的遍历的顺序是不确定的，所以一个dict的__parent__设置为谁也说不确定的。有两个解决办法:
1. 手工设置__parent__属性。
2. 如果不想让dict A成为dict B的parent，可以让dict A用下划线开始的变量名引用dict B.
* 扩展ObServer和ObInstance
如果想快速给observer添加一个命令，在h/obi.py中搜索observer_extend_cmd, 然后可以照猫画虎:
#+BEGIN_EXAMPLE
yuanqi.xhf@OceanBase224004 deploy$ grep -A 3 observer_extend_cmd h/obi.py
    # observer_extend_cmd example
    rsync = '''!sh: rsync -a bin lib tools $usr@$ip:$obdir/'''
    tail = '''!ssh: tail -f $log_file'''
    grep = '''!ssh: grep $_rest_ $log_file'''
#+END_EXAMPLE
同理，可以grep obi_extend_cmd
#+BEGIN_EXAMPLE
yuanqi.xhf@OceanBase224004 deploy$ grep -A 3 obi_extend_cmd h/obi.py
    # obi_extend_cmd example
    dooba = '!call: obs0.dooba'
    sql = '!call: obs0.sql'
    obmysql = '!call: sql'
#+END_EXAMPLE

h/obi.py目的是实现obi核心的命令，其它比较独立的功能建议放到单独的python文件中。以h/mysqltest.py为例, 扩展observer的方法如下:
#+BEGIN_SRC python
@ObServerBuilder
def ObServerL1(**__kw):
    def minitest(*args, **attr):
        ....
    ...
    return hap_dict(locals(), **__kw)
#+END_SRC
例子中ObServerL1是顺便起的一个名字，只要保证全局唯一即可。上面这个例子给ObServer扩展了minitest方法。ObInstance的扩展方法类似。

原则上可以把python代码写到任何一个文件里。只需要保证在hap/init.py中用load_ext()加载即可。
#+BEGIN_EXAMPLE
yuanqi.xhf@OceanBase224004 deploy$ grep load_ext hap/init.py 
load_ext('obi,ct,mysqltest,obm,old_cfg,sysbench')
#+END_EXAMPLE
* fault test
在配置文件中load_file('fault_test/fault_test.py'), 比如在config2.py中加入以下的两行:
#+BEGIN_EXAMPLE
load_file('fault_test/fault_test.py')
ob1 = OBI('[rs@100.81.152.31,100.81.152.40]@[z1,z2,z3]')
#+END_EXAMPLE
然后运行:
: ./hap.py ob1.fault_test

* 测试机器:
http://10.125.224.2:8002/host-stat.html
