#!/bin/bash

pid=$(cat /var/lib/oceanbase/run/daemon.pid)
kill -9 "$pid"
pid=$(cat /var/lib/oceanbase/run/obshell.pid)
kill -9 "$pid"
pid=$(cat /var/lib/oceanbase/run/observer.pid)
kill -9 "$pid"
systemd-notify "STATUS=seekdb is down"