/*
 * Copyright (c) 2025 OceanBase.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef OCEANBASE_ARCHIVE_OB_ARCHIVE_TASK_H_
#define OCEANBASE_ARCHIVE_OB_ARCHIVE_TASK_H_

#include "lib/queue/ob_link.h"                     // ObLink
#include "share/ob_ls_id.h"                // ObLSID
#include "ob_archive_define.h"                     // ArchiveWorkStation
#include "share/backup/ob_archive_piece.h"         // ObArchivePiece
#include "logservice/palf/lsn.h"         // LSN
#include "share/scn.h"         // SCN
#include <cstdint>

namespace oceanbase
{
namespace archive
{
using oceanbase::share::ObLSID;
using oceanbase::palf::LSN;
using oceanbase::share::ObArchivePiece;
class ObArchiveSendTask;
/*
 * ObArchiveLogFetchTask is the log file read task, generated by ObArchiveSequencer and consumed by ObArchiveFetcher.
 * Since archiving cannot perceive the internal structure of the Palf file system, the LogFetchTask generates tasks at the granularity of an archive file
 *
 * NB: It is a description of a range of log files (A, B) means (start_offset, end_offset), where start_offset and end_offset
 * are the starting and ending offsets of the archive file, respectively. Theoretically, an archive file can be of any size, usually equal to the size of a log file
 *
 * The log file size is fixed. When the last log exceeds the remaining space of that log file, it will be placed in the next log file;
 * and a log in the archive file is determined by its starting LSN. In the above example, this log is located in the previous archive file
 *
 * When the archiving of a log stream falls behind, a single log stream will generate multiple LogFetchTasks, each corresponding to different archive files
 * NB: When a log stream archives up to the latest log, there is only one LogFetchTask, and its end_offset is still the maximum offset of the corresponding archive file
 * Naturally, it also includes the offset of logs not yet produced
 *
 * For example,
 * There are two lss, ls1 is the log stream with archiving lag, ls2 is the log stream archived to the latest
 * ls1 -> {[x * N * M, (x + 1) * N * M), [(x + 1) * N * M, (x + 2) * N * M), ...}
 * ls2 -> {[y * N * M, (y + 1) * N * M)}
 * where x, y are arbitrary numbers representing the number of archive files, and M is the ob log file size
 *
 * Additionally, since each observer may serve archiving for multiple log streams, it is necessary to maintain overall synchronization among multiple log streams.
 * ObArchiveSequencer coordinates the archiving progress of different log streams based on the consumption progress of ObArchiveLogFetchTask.
 *
 * NB: Since ObArchiveSequencer cannot perceive log scn information, the initial LogFetchTask has empty piece info,
 * and ObArchiveFetcher fills in the piece info when consuming, archiving data for cross-piece tasks to multiple pieces
 * For cross-piece archive files, archive files with the same number may appear in multiple pieces, where each piece only contains the log range belonging to that piece
 *
 * NB: start_offset and end_offset are left-closed right-open intervals, such as [0, 64M)
 *
 * */
class ObArchiveLogFetchTask : public common::ObLink
{
public:
  ObArchiveLogFetchTask();
  virtual ~ObArchiveLogFetchTask();
public:
  int init(const uint64_t tenant_id,
           const ObLSID &id,
           const ArchiveWorkStation &station,
           const share::SCN &base_scn,
           const LSN &start_lsn,
           const LSN &end_lsn);
  uint64_t get_tenant_id() const { return tenant_id_; }
  ObLSID get_ls_id() const { return id_; }
  const ArchiveWorkStation &get_station() const { return station_; }
  const share::SCN &get_base_scn() const { return base_scn_; }
  const LSN &get_start_offset() const { return start_offset_; }
  const LSN &get_cur_offset() const { return cur_offset_; }
  const LSN &get_end_offset() const { return end_offset_; }
  const share::SCN &get_max_scn() const { return max_scn_; }
  int64_t get_log_fetch_size() const { return (int64_t)(end_offset_ - cur_offset_); }
  const ObArchivePiece &get_piece() const { return cur_piece_; }
  int set_next_piece(const ObArchivePiece &piece);
  const ObArchivePiece &get_next_piece() const { return next_piece_; }
  ObArchiveSendTask *get_send_task() { return send_task_; }
  int clear_send_task();
  bool is_valid() const;
  bool is_finish() const;
  int back_fill(const ObArchivePiece &cur_piece,
                  const LSN &start_offset,
                  const LSN &end_offset,
                  const share::SCN &max_scn,
                  ObArchiveSendTask *send_task);
  bool has_fetch_log() const { return NULL != send_task_; }
  bool is_continuous_with(const LSN &lsn) const;
  TO_STRING_KV(K_(tenant_id),
               K_(id),
               K_(station),
               K_(cur_piece),
               K_(next_piece),
               K_(base_scn),
               K_(start_offset),
               K_(end_offset),
               K_(cur_offset),
               "unfinished_data_size", get_log_fetch_size(),
               K_(max_scn),
               K_(send_task),
               KP(this));

private:
  uint64_t tenant_id_;
  ObLSID id_;
  ArchiveWorkStation station_;
  ObArchivePiece cur_piece_;    // This piece of data belongs to the ObArchivePiece directory
  ObArchivePiece next_piece_;
  share::SCN base_scn_;
  LSN start_offset_; // start offset of the log file
  LSN end_offset_;   // Pull log file end offset (if it is a full file pull task, this value is infoblock start point)
  LSN cur_offset_;
  share::SCN max_scn_;        // task contains maximum log scn

  ObArchiveSendTask *send_task_;
};

/*
 * The archive file size is not strictly bound to the ob log file size, the archive file can be an integer multiple N of the ob log file, therefore the following constraints are needed:
 * 1. Before the complete archive file size log is not fully backed up, the archive progress cannot advance, otherwise piece switching will lose data from N-1 ob log files
 * 2. Archive supplementary logs, to ensure that the archive progress can meet the requirements (WORM), need to be supplemented based on the difference between increased LSN and archive file size, rather than ob log file size
 * 3. In non-WORM scenarios, due to the restriction of 1, in fact, the archive progress cannot advance before archiving the data of the archive file size
 * 4. Archive file LSN is equivalent to ob log LSN, due to the support for encryption and compression requirements, a layer of conversion relationship is needed, the rule for calculating LSN by archive file id is the same as ob;
 *    The internal table records the ob archive progress LSN, which can be used to calculate the archive file file id
 * 5. The archive file being N times the log file means that the log range it contains is N times that of the ob log file; due to encryption and compression, the actual size of the archive file is unlikely to be exactly N times the size of the ob log file
 *
 * LogFetchTask design:
 * 1. No visibility of ob log file file_id information, only LSN information, start_offset is the starting LSN of the log range contained in the archive file, end_offset is the maximum LSN of the log contained in the archive file
 * 2. Since the log range contained in the archive file is an integer multiple of normal ob files, therefore start_offset and end_offset are also the start and end of the ob log file
 * 3. Compression and encryption units within the archive file are unit-based, the archive file ends based on the remaining length
 *
 * Optimization:
 * 1. The default size of the archive file is equal to the size of the ob log file
 * 2. Archive progress advancement does not consider the scenario where the archive file is not equal to the ob log file, archive progress can advance in real time with the archived data
 * */

/*
 * ObArchiveSendTask is the log data send task, generated by ObArchiveFetcher and consumed by ObArchiveSender.
 * Similar to ObArchiveLogFetchTask, it also describes a segment of a clog file, the difference being that it is already read into memory data buffer.
 * It can be a complete file data or part of a file data
 *
 * Unlike ObArchiveLogFetchTask, individual ObArchiveSendTasks within a single log stream must be consumed in order, as the processing of a single log stream in the ObArchiveSender module is serial.
 * The concurrent archiving capability of a single log stream is guaranteed by the underlying storage interface module
 *
 * */
class ObArchiveSendTask : public common::ObLink
{
public:
  ObArchiveSendTask();
  virtual ~ObArchiveSendTask();
public:
  int init(const uint64_t tenant_id,
           const ObLSID &id,
           const ArchiveWorkStation &station,
           const ObArchivePiece &piece,
           const LSN &start_offset,
           const LSN &end_offset,
           const share::SCN &max_scn);
  bool is_valid() const;
  uint64_t get_tenant_id() const { return tenant_id_;}
  ObLSID get_ls_id() const { return id_; }
  const ArchiveWorkStation &get_station() const { return station_; }
  const ObArchivePiece &get_piece() const { return piece_; }
  const LSN &get_start_lsn() const { return start_offset_; }
  const LSN &get_end_lsn() const { return end_offset_; };
  int get_buffer(char *&data, int64_t &data_len) const;
  int get_origin_buffer(char *&buf, int64_t &buf_size) const;
  int64_t get_buf_size() const { return data_len_;}
  const share::SCN &get_max_scn() const { return max_scn_; }
  int set_buffer(char *buf, const int64_t buf_size);
  bool is_continuous_with(const ObArchiveSendTask &pre_task) const;
  // @brief issue this task to a sender thread, only if its status is initial
  // @ret_code  flase  issue failed, maybe this task is issued by other sender thread
  //            true   issue successfully
  bool issue_task();
  // @brief after the task is issued to a sender thread and archived successfully, finish the task
  // @ret_code  false  finish failed, should not happend
  //            true   finish successfully
  bool finish_task();
  // @brief mark task stale forcely, cases:
  //  1) archive is stop
  //  2) stale archive task after ls archive task station changed
  void mark_stale();
  // @brief after the task is issued to a sender thread and archived failed, retire the task and wait next turn
  // @ret_code  false  retire failed, should not happend
  //            true   retire successfully
  bool retire_task_with_retry();
  bool is_task_finish() const;
  bool is_task_stale() const;
  int update_file(const int64_t file_id, const int64_t file_offset);
  void get_file(int64_t &file_id, int64_t &file_offset);
  TO_STRING_KV(K_(status),
               K_(tenant_id),
               K_(id),
               K_(station),
               K_(piece),
               K_(start_offset),
               K_(end_offset),
               K_(max_scn),
               K_(file_id),
               K_(file_offset),
               K_(data),
               K_(data_len),
               KP(this));
private:
  static const int8_t INITAL_STATUS = 0;
  static const int8_t ISSUE_STATUS = 1;
  static const int8_t FINISH_STATUS = 2;
  static const int8_t STALE_STATUS = 3;

private:
  int8_t status_;           // low 1st bit means issued(1) or not(0), low 2nd bit means finished(1) or not(0)
  uint64_t tenant_id_;
  ObLSID id_;               // ls id
  ArchiveWorkStation station_;     // archive work station, include incarnation/dest_id/round/lease
  ObArchivePiece piece_;
  LSN start_offset_;       // archive data start offset in file
  LSN end_offset_;         // archive data end offset in file
  share::SCN max_scn_;     // this task contains the maximum scn of data
  int64_t file_id_;
  int64_t file_offset_;
  char *data_;             // send data
  int64_t data_len_;       // send data length
};

struct LogFetchTaskCompare final
{
public:
  LogFetchTaskCompare() {}
  ~LogFetchTaskCompare() {}
  bool operator()(const ObArchiveLogFetchTask *left, const ObArchiveLogFetchTask *right)
  {
    return left->get_start_offset() < right->get_start_offset();
  }
};
} // namespace archive
} // namespace oceanbase
#endif /* OCEANBASE_ARCHIVE_OB_ARCHIVE_TASK_H_ */
