CREATE TABLE "RERATING_TASK" ("TASKID" NUMBER(8,0), "TASKNAME" VARCHAR2(32), "TYPEID" NUMBER(6,0), "BILLCYCLE" NUMBER(8,0), "TASK_WHERE" VARCHAR2(512), "PLANTIME" DATE DEFAULT Sysdate + 1/48, "TASKCOUNT" NUMBER(3,0) DEFAULT 1, "BATCHUSER" NUMBER(3,0) DEFAULT 10, "TESTROWS" NUMBER(2,0) DEFAULT 5, "ISTEST" NUMBER(1,0) DEFAULT 0, "WHERETYPE" NUMBER(1,0) DEFAULT 0, "STATUS" NUMBER(1,0) DEFAULT 0, "UPTIME" DATE DEFAULT sysdate, "OPERATOR" VARCHAR2(32), "STATUSTIME" DATE DEFAULT sysdate) ;

CREATE TABLE "RERATING_TYPE" ("TYPEID" NUMBER(6,0), "TYPENAME" VARCHAR2(32), "EVENTID" NUMBER(4,0), "CDRTABLE" VARCHAR2(32), "DBLINKNAME" VARCHAR2(32), "FIELDNAME" VARCHAR2(64), "UNDUP_MODULE" NUMBER(4,0) DEFAULT 0, "CHECK_DUP" NUMBER(1,0) DEFAULT 0, "ROLLBACK_FROM" NUMBER(4,0) DEFAULT 50, "CLEAR_CYCLE" NUMBER(1,0) DEFAULT 0, "FLOW_MODULE" NUMBER(4,0), "STAT_MODULE" NUMBER(4,0) DEFAULT 0, "CHARGING_MODULE" NUMBER(4,0), "FIELD_PREFIX" VARCHAR2(127), "FORMAT_PROC" NUMBER(4,0), "COPYATTRFLAG" NUMBER(1,0), "RERATING_WHERE" VARCHAR2(512), "INUSE" NUMBER(1,0) DEFAULT 1) ;

CREATE TABLE "ROLE_LIST" ("ROLE_ID" NUMBER(4,0), "ROLE_NAME" VARCHAR2(256), "CREATEDATE" DATE, "PREDEF_TYPE" NUMBER(1,0)) ;

CREATE TABLE "RTCC_CLIENT_DEF" ("MMQ_DEVID" NUMBER(8,0), "IPADDR" VARCHAR2(30), "PORT" NUMBER(8,0), "SENDQ" VARCHAR2(30), "RECVQ" VARCHAR2(30), "DISPQ" VARCHAR2(30), "TRACEQ" VARCHAR2(30), "DEVICE_ID" VARCHAR2(30), "DEVICE_VERSION" NUMBER(5,2)) ;

CREATE TABLE "SAFETY_STRATEGY" ("INVALID_CYCLE" NUMBER(4,0) DEFAULT 0, "PWDHIS_LIMIT" NUMBER(4,0) DEFAULT 0, "COMPOSE_LIMIT" VARCHAR2(10), "FAILCOUNT_LIMIT" NUMBER(4,0) DEFAULT 0, "PWDLEN_LIMIT" NUMBER(4,0) DEFAULT 6, "PWDLEN_MAX" NUMBER(4,0) DEFAULT 32, "PWDDUP_MAX" NUMBER(4,0) DEFAULT 3, "INVALID_LIMIT" NUMBER(4,0) DEFAULT 5, "PWDVLD_PROMPT" NUMBER(4,0) DEFAULT 7, "LOGONLOCKDUR" NUMBER(4,0) DEFAULT 30, "WAITLOCKDUR" NUMBER(4,0) DEFAULT 10, "WRONGLOCKDUR" NUMBER(4,0) DEFAULT 30, "LOGONAFTERDAYS" NUMBER(4,0) DEFAULT 90, "LAST_CALL_ET" NUMBER(5,0) DEFAULT 60, "IFCHECKUNIQUEID" NUMBER(1,0) DEFAULT 1, "ADM_PWDLEN_LIMIT" NUMBER(4,0) DEFAULT 8, "DIFCHARACTER_COUNT" NUMBER(2,0) DEFAULT 2, "RELOGONDUR" NUMBER(4,0) DEFAULT 0) ;

CREATE TABLE "SEP_TASK" ("TASKNO" NUMBER(3,0), "NAME" VARCHAR2(100), "RAWBUFFER" NUMBER(6,0), "BUFFER1" NUMBER(6,0), "BUFFER2" NUMBER(6,0), "DATABUFFER" NUMBER(9,0), "ADJUST_RAWBUFFER" NUMBER(8,0) DEFAULT 0, "PROCESSTYPE" NUMBER(2,0) DEFAULT 0, "FILELIST_READ_MODE" NUMBER(1,0) DEFAULT 0, "SERVER_NAME" VARCHAR2(50)) ;

CREATE TABLE "SERVICE_CLASS_DEF" ("SERVICE_CLASS_ID" VARCHAR2(60), "SERVICE_CLASS_NAME" VARCHAR2(120), "SERVICE_TYPE" NUMBER(1,0)) ;

CREATE TABLE "SERVICE_CLASS_PARAM_DEF" ("SERVICE_CLASS_ID" VARCHAR2(60), "PARAM_NAME" VARCHAR2(60), "PARAM_CAPTION" VARCHAR2(120), "DEFAULT_VALUE" VARCHAR2(120), "MANDATORY" NUMBER(1,0) DEFAULT (0), "PARAM_DESC" VARCHAR2(300), "PARAM_TYPE" VARCHAR2(100)) ;

CREATE TABLE "SERVICE_DEF" ("SERVICE_CLASS_ID" VARCHAR2(60), "SERVICE_ID" VARCHAR2(60), "SERVICE_NAME" VARCHAR2(300), "SERVICE_DESC" VARCHAR2(500), "SERVICE_TYPE" NUMBER(1,0), "SERVICE_CATEGORY" VARCHAR2(60)) ;

CREATE TABLE "SERVICE_GROUP_DEF" ("GROUP_CODE" VARCHAR2(50), "GROUP_TYPE" VARCHAR2(20), "GROUP_NAME" VARCHAR2(100), "ZK_SERVER" VARCHAR2(100), "CONNECT_STRATEGY" NUMBER(2,0) DEFAULT 1, "REPORT_INTERVAL" NUMBER(5,0) DEFAULT 10) ;

CREATE TABLE "SERVICE_MAPPING_DEF" ("REGION" NUMBER(4,0) DEFAULT -1, "NODE_ID" NUMBER(4,0) DEFAULT -1, "DATA_NODE_ID" NUMBER(4,0) DEFAULT -1, "SERVICE_NAME" VARCHAR2(50), "SERVICE_GROUP" VARCHAR2(50)) ;

CREATE TABLE "SERVICE_PARAM_DEF" ("SERVICE_ID" VARCHAR2(60), "PARAM_NAME" VARCHAR2(60), "PARAM_VALUE" VARCHAR2(500), "PARAM_TYPE" VARCHAR2(100)) ;

CREATE TABLE "SERVICE_REMIND_DEF" ("REMIND_ID" NUMBER(4,0), "REMIND_NOTE" VARCHAR2(32), "SERVICE_TYPE" VARCHAR2(20), "REMIND_TYPE" NUMBER(4,0), "EVENT_ID" NUMBER(4,0), "PROCESS_SCHEME" NUMBER(5,0), "UNDUP_ID" NUMBER(4,0), "FLOW_ID" NUMBER(4,0), "MERGE_TYPE" NUMBER(1,0) DEFAULT 1) ;

CREATE TABLE "SERVICE_REMIND_FREE_DEF" ("REMIND_ID" NUMBER(4,0), "REGION" NUMBER(4,0), "TARIFFID" NUMBER(8,0), "TARIFFNAME" VARCHAR2(64), "ATTRTYPE" NUMBER(2,0), "ATTRID" VARCHAR2(128), "USAGE_TYPE_LIST" VARCHAR2(20), "FREE_TYPE" NUMBER(1,0), "STDFREE" VARCHAR2(64), "HALFFREE" NUMBER(1,0), "G_STDFREE" VARCHAR2(128), "ENTITY_ID" NUMBER(2,0) DEFAULT 1, "SHARE_CROSS_CYCLE" NUMBER(1,0) DEFAULT 0, "SHARE_USAGE_TYPE_LIST" VARCHAR2(60), "CONDITION" VARCHAR2(512), "G_CONDITION" VARCHAR2(1024), "USAGE_CONFIG_FLAG" NUMBER(1,0) DEFAULT 0) ;

CREATE TABLE "PARAM_ID_CHANGE" ("GROUP_NAME" VARCHAR2(20), "ID_NUMBER" NUMBER(10,0), "CHANGE_TIME" DATE) ;

CREATE TABLE "SET_DEF" ("SET_ID" NUMBER(4,0), "SET_NAME" VARCHAR2(64), "VALUE_NAME" VARCHAR2(64), "MATCH_ORDER" NUMBER(1,0), "SET_PARAM_ATTR" VARCHAR2(20), "OFTEN_USED" NUMBER(1,0) DEFAULT 0) ;

CREATE TABLE "SET_VALUE" ("SET_ID" NUMBER(4,0), "APPLYTIME" DATE, "EXPIRETIME" DATE, "VALUE" VARCHAR2(128), "NOTE" VARCHAR2(128)) ;

CREATE TABLE "STAT_SCOPE" ("MODULE_ID" NUMBER(4,0), "REPORT_VIEW_ID" NUMBER(4,0), "BUFFER_ROWS" NUMBER(10,0), "DUMP_TYPE" NUMBER(1,0)) ;

CREATE TABLE "STATISTICS_MODULE" ("MODULE_ID" NUMBER(4,0), "MODULE_NAME" VARCHAR2(64), "MODULE_TYPE" NUMBER(1,0)) ;

CREATE TABLE "ROLE_PRIV_LIST" ("ROLE_NAME" VARCHAR2(256), "RESOURCE_TYPE" NUMBER(1,0) DEFAULT 0, "RESOURCE_ID" NUMBER(4,0), "PRIV_SET" NUMBER(4,0)) ;

CREATE TABLE "SERVICE_REMIND_BATCH_DEF" ("BATCH_ID" NUMBER(5,0), "NAME" VARCHAR2(32), "REMIND_ID" NUMBER(4,0)) ;



