CREATE TABLE "TARIFF_PLAN_ITEM_REDU" ("TARIFF_PLAN_ID" NUMBER(6,0), "CALCTYPE" NUMBER(1,0), "FEE_ID" NUMBER(9,0), "TARIFF_SCHEMA_ID" NUMBER(9,0), "CHARGING_EVENT_ID" NUMBER(4,0), "PRECEDENCE" NUMBER(4,0), "APPLYTIME" DATE, "EXPIRETIME" DATE, "APPLY_METHOD" NUMBER(1,0), "DISCOUNT_TYPE" NUMBER(1,0), "BASE_FEE_ID" NUMBER(9,0), "DISCOUNT_FEE_ID" NUMBER(9,0), "CHARGING_COND" VARCHAR2(512), "SWITCH_METHOD" NUMBER(2,0), "SWITCH_UNIT" NUMBER(8,0), "G_CHARGING_COND" VARCHAR2(1024), "PARAM_SET_TYPE" VARCHAR2(4), "PARAM_SET_METHOD" VARCHAR2(4), "PARAM_SET_ID" NUMBER(4,0), "ATTR_VALUE" NUMBER(9,0)) ;

CREATE TABLE "TARIFF_PLAN_REDU" ("TARIFF_PLAN_ID" NUMBER(6,0), "TARIFF_PLAN_NAME" VARCHAR2(128), "IS_RECURSIVE" NUMBER(1,0), "PRECEDENCE" NUMBER(9,0), "PROCESS_BEFORE" NUMBER(4,0), "PROCESS_AFTER" NUMBER(4,0), "PLANTYPE" VARCHAR2(4), "NOTE" VARCHAR2(400), "PRECEDENCE_ACCDISC" NUMBER(4,0), "STATUS" NUMBER(1,0)) ;

CREATE TABLE "WRTOFF_ORDER_DEF" ("WRTOFF_ORDER_PLANID" NUMBER(10,0), "ITEMCODE" VARCHAR2(32), "WRTOFF_ORDER" NUMBER(5,0)) ;

CREATE TABLE "WRTOFF_ORDER_PLAN_DEF" ("WRTOFF_ORDER_PLANID" NUMBER(10,0), "WRTOFF_ORDER_PLANNAME" VARCHAR2(64), "IN_USE" NUMBER(1,0)) ;

CREATE TABLE "WRTOFF_PLAN_DEF" ("WRTOFF_PLANID" NUMBER(10,0), "WRTOFF_ORDER_PLANID" NUMBER(10,0), "AMERCE_PLANID" NUMBER(10,0), "SMALL_CHANGE" NUMBER(10,0), "PENALTY_TYPE" NUMBER(10,0), "VALID_CYCLE" NUMBER(10,0), "EXPIRE_CYCLE" NUMBER(10,0), "REGION" NUMBER(5,0)) ;

CREATE TABLE "TARIFF_PLAN_ITEM" ("TARIFF_PLAN_ID" NUMBER(6,0), "CALCTYPE" NUMBER(1,0), "FEE_ID" NUMBER(9,0), "TARIFF_SCHEMA_ID" NUMBER(9,0), "CHARGING_EVENT_ID" NUMBER(4,0), "PRECEDENCE" NUMBER(4,0), "APPLYTIME" DATE, "EXPIRETIME" DATE, "APPLY_METHOD" NUMBER(1,0), "DISCOUNT_TYPE" NUMBER(1,0), "BASE_FEE_ID" NUMBER(9,0), "DISCOUNT_FEE_ID" NUMBER(9,0), "CHARGING_COND" VARCHAR2(512), "SWITCH_METHOD" NUMBER(2,0), "SWITCH_UNIT" NUMBER(8,0), "G_CHARGING_COND" VARCHAR2(1024), "BILLCODE" VARCHAR2(32), "SELECT_METHOD" NUMBER(1,0), "TARIFF_PLAN_ITEM_SN" VARCHAR2(20) DEFAULT 0, "TARIFF_PLAN_ITEM_NAME" VARCHAR2(64), "SERV_ID" NUMBER(4,0), "FEE_ROUND_TYPE" NUMBER(1,0) DEFAULT 0, "FEE_ROUND_SCALE" NUMBER(2,0) DEFAULT 2, "CATALOG_TYPE" VARCHAR2(10) DEFAULT '0') ;

CREATE TABLE "TARIFF_SCHEMA" ("TARIFF_SCHEMA_ID" NUMBER(9,0), "TARIFF_NAME" VARCHAR2(64), "TARIFF_TYPE" NUMBER(2,0), "FIELDCOUNT" NUMBER(4,0), "FIELD_DEF" VARCHAR2(256), "MATCH_ORDER" NUMBER(1,0), "MATCH_TYPE" NUMBER(1,0), "APPLY_METHOD" NUMBER(1,0), "REFID" NUMBER(4,0), "DISCOUNT_FEE_ID" NUMBER(9,0), "G_FIELD_DEF" VARCHAR2(256), "ROUND_METHOD" NUMBER(1,0), "ROUND_SCALE" NUMBER(2,0), "REF_OFFSET" NUMBER(4,0), "EVENT_ID" NUMBER(4,0), "BILLCODE_ORDER" NUMBER(1,0) DEFAULT 0, "CREATETIME" DATE DEFAULT sysdate, "REGION" NUMBER(5,0) DEFAULT 0) ;

CREATE TABLE "AM_TAX_BILLMERGE_DEF" ("RULEID" NUMBER(6,0), "RULENAME" VARCHAR2(32), "RULEORDER" NUMBER(6,0), "DESITEMCODE" VARCHAR2(32), "ITEMCODE" VARCHAR2(32), "PKGCODE" VARCHAR2(32), "TARIFFCODE" VARCHAR2(32), "INUSE" NUMBER(1,0), "REGION" NUMBER(5,0) DEFAULT 999) ;

CREATE TABLE "TOTAL_USAGE_ATTR_DEF" ("ENTITY_ID" NUMBER(4,0), "ATTR_ID" NUMBER(8,0), "USAGE_TYPE" NUMBER(1,0), "RE_ATTR_ID" NUMBER(4,0)) ;

CREATE TABLE "TRACE_SET_DEF" ("PROGNUM" NUMBER(4,0), "PROGNAME" VARCHAR2(64), "OBJECTTYPE" NUMBER(2,0), "VALUE" VARCHAR2(64), "APPLYTIME" DATE, "EXPIRETIME" DATE, "TRACELEVEL" NUMBER(2,0) DEFAULT 1, "TRACEAPP" NUMBER(2,0) DEFAULT 1) ;

CREATE TABLE "TRIGGER_MAPPING_DEF" ("TRIGGER_TYPE" NUMBER(2,0), "SOURCE_EVENT_ID" NUMBER(4,0), "SOURCE_ATTR_ID" NUMBER(4,0), "DEST_EVENT_ID" NUMBER(5,0), "DEST_ATTR_ID" NUMBER(5,0), "IS_KEY" NUMBER(1,0) DEFAULT 0, "SOURCE_TYPE" NUMBER(1,0) DEFAULT 1) ;

CREATE TABLE "TRIGGER_RULE_DEF" ("TRIGGER_TYPE" NUMBER(2,0), "RULE_ID" NUMBER(5,0), "RTCC_FLAG" NUMBER(1,0) DEFAULT 0, "REQUEST_TYPE" VARCHAR2(2) DEFAULT '0', "EVENT_OBJECT" NUMBER(2,0), "FILTER_TYPE" NUMBER(2,0), "TRIGGER_CONDITION" VARCHAR2(64), "DELAY_DAY_LIST" VARCHAR2(100), "DELAY_BEGIN_TIME" VARCHAR2(6) DEFAULT '000000', "DELAY_END_TIME" VARCHAR2(6) DEFAULT '240000', "DELAY_FLAG" NUMBER(1,0) DEFAULT 3, "DIRECT_CALL" NUMBER(5,0) DEFAULT 0, "CALL_SERVER_TYPE" VARCHAR2(60) DEFAULT 'ALL', "APP_TASK_ID" VARCHAR2(60)) ;

CREATE TABLE "TRIGGER_TYPE_DEF" ("NAME" VARCHAR2(20), "TRIGGER_TYPE" NUMBER(2,0), "FLOW_ID" NUMBER(5,0), "DUPLICATE_CHECK" NUMBER(1,0) DEFAULT 1) ;

CREATE TABLE "USAGE_CONFIG_DEF" ("TARIFF_ID" NUMBER(8,0), "ENTITY_ID" NUMBER(2,0), "ATTR_TYPE" NUMBER(2,0), "ATTR_ID" VARCHAR2(128), "NOTE" VARCHAR2(128), "STD_FREE_EXPR" VARCHAR2(512) DEFAULT 0, "G_STD_FREE_EXPR" VARCHAR2(512), "CBE_STD_FREE_EXPR" VARCHAR2(512) DEFAULT 0, "G_CBE_STD_FREE_EXPR" VARCHAR2(512), "HALF_FREE" NUMBER(1,0) DEFAULT 0, "SHARE_CROSS_CYCLE" NUMBER(2,0), "CYCLE_COUNT_EXPR" VARCHAR2(512), "G_CYCLE_COUNT_EXPR" VARCHAR2(512), "START_CYCLE" NUMBER(8,0) DEFAULT 199801, "END_CYCLE" NUMBER(8,0) DEFAULT 999999) ;

CREATE TABLE "UNDUP_MODULE_DEF" ("MODULE_ID" NUMBER(4,0), "UNDUP_ID" NUMBER(4,0), "APPLY_TIME" DATE, "EXPIRE_TIME" DATE) ;

CREATE SEQUENCE  "SEQ_TARIFF_SN"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 138751 CACHE 100 ORDER  CYCLE ;


