CREATE TABLE "CHARGING_CYCLE" ("CYCLE_SCHEMA_ID" NUMBER(4,0), "CYCLE_ID" NUMBER(8,0), "CHARGING_EVENT_ID" NUMBER(4,0), "BILLING_COND" VARCHAR2(512), "G_BILLING_COND" VARCHAR2(512)) ;

CREATE TABLE "CHARGING_EVENT_DEF" ("EVENT_TYPE" NUMBER(1,0), "EVENT_ID" NUMBER(4,0), "EVENT_NAME" VARCHAR2(100), "TABLE_NAME" VARCHAR2(50), "EVENT_SCOPE" NUMBER(5,0), "VERSION" NUMBER(4,0) DEFAULT 1, "SERV_RANGE" VARCHAR2(128), "G_SERV_RANGE" VARCHAR2(256)) ;

CREATE TABLE "CHARGING_MODULE" ("MODULE_ID" NUMBER(4,0), "MODULE_NAME" VARCHAR2(64), "MODULE_TYPE" NUMBER(1,0), "CYCLE_SCHEMA_ID" NUMBER(4,0), "CHARGING_TYPE" NUMBER(1,0) DEFAULT 1) ;

CREATE TABLE "CLEAN_DATASET_ACTION" ("ACTION_ID" VARCHAR2(32), "DATASET_ID" VARCHAR2(32), "ACTION_NAME" VARCHAR2(80), "PROC_ORDER" NUMBER(4,0), "BACKUP_SELECT_SQL" VARCHAR2(2048), "BACKUP_INSERT_SQL" VARCHAR2(2048), "DELETE_SQL" VARCHAR2(512), "BIND_VARS" VARCHAR2(128), "FLOW_SELECT_SQL" VARCHAR2(512), "FLOW_INSERT_SQL" VARCHAR2(512)) ;

CREATE TABLE "CLEAN_DATASET_COND" ("DATASET_COND_ID" VARCHAR2(32), "DATASET_ID" VARCHAR2(32), "COND_NAME" VARCHAR2(80), "PROC_ORDER" NUMBER(4,0), "SQL_TEXT" VARCHAR2(512), "BIND_PARAM" VARCHAR2(128), "SERVER_NAME" VARCHAR2(64)) ;

CREATE TABLE "CLEAN_DATASET_DEF" ("DATASET_ID" VARCHAR2(32), "DATASET_NAME" VARCHAR2(60), "NOTE" VARCHAR2(200)) ;

CREATE TABLE "CLEAN_DATASET_RELATION" ("RELATION_ID" VARCHAR2(32), "DATASET_ID" VARCHAR2(32), "RELATION_NAME" VARCHAR2(80), "PROC_ORDER" NUMBER(4,0), "SQL_TEXT" VARCHAR2(512), "BIND_VARS" VARCHAR2(128), "RELATE_DATASET_ID" VARCHAR2(32)) ;

CREATE TABLE "CLEAN_DATASET_TASK" ("TASK_ID" VARCHAR2(32), "CLEAN_DATASET_ID" VARCHAR2(32), "SCAN_SQL" VARCHAR2(512), "TASK_NOTE" VARCHAR2(200), "DELETE_SQL" VARCHAR2(512), "SOURCE_DB" VARCHAR2(64), "DELETE_DB" VARCHAR2(64), "BACKUP_DB" VARCHAR2(64), "FLOW_DB" VARCHAR2(64)) ;

CREATE TABLE "CLIENT_AUTH_DEF" ("APPNAME" VARCHAR2(32), "CLIENTIP" VARCHAR2(20), "CLIENTPORT" VARCHAR2(10), "LISTTYPE" NUMBER(1,0)) ;

CREATE TABLE "CLUSTER_ATTR" ("CLUSTER_ID" NUMBER(2,0), "ATTR_ID" VARCHAR2(50), "ATTR_ORDER" NUMBER(4,0) DEFAULT 0, "ATTR_VALUE" VARCHAR2(100)) ;

CREATE TABLE "CLUSTER_DEF" ("CLUSTER_ID" NUMBER(2,0), "CLUSTER_NAME" VARCHAR2(50), "NOTE" VARCHAR2(200)) ;

CREATE TABLE "CLUSTER_TASK_DEF" ("TASK_ID" VARCHAR2(32), "TASK_NAME" VARCHAR2(64), "TASK_DESC" VARCHAR2(128), "SUB_TASK_QTY" NUMBER(8,0), "PROC_SCHEMA" NUMBER(2,0), "DB_CONNECTION_NAME" VARCHAR2(32), "TASK_KEY_PARAMLIST" VARCHAR2(256), "CLUSTER_ID" NUMBER(2,0)) ;

CREATE TABLE "CODE_DICT" ("CATALOG" VARCHAR2(32), "CODE" VARCHAR2(32), "NAME" VARCHAR2(128), "NOTE" VARCHAR2(128)) ;

CREATE TABLE "COLLECT_PRIV" ("CHARGE_PRESENT_PLANID" VARCHAR2(10), "USE_REGION" VARCHAR2(10), "RECTYPE" VARCHAR2(32), "ACCESSTYPE" VARCHAR2(32), "PAYTYPE" VARCHAR2(32), "STARTTIME" DATE, "ENDTIME" DATE, "CHARGE_PRESENT_PLANNAME" VARCHAR2(64), "EXT_CHKTYPE" VARCHAR2(64), "PROCESSTYPE" NUMBER(1,0) DEFAULT 0, "PRECEDENCE" NUMBER(8,0) DEFAULT 0) ;

CREATE TABLE "COLLECT_PRIV_DEF" ("CHARGE_PRESENT_PLANID" VARCHAR2(10), "CHARGE_PRESENT_PLANNAME" VARCHAR2(128), "SUBJECTID" VARCHAR2(128), "CONDITION" VARCHAR2(256), "REFERENCE_AMTTYPE" NUMBER(1,0), "LIMITTYPE" NUMBER(1,0), "LIMITCYCLE" NUMBER(10,0), "LIMITTIME" NUMBER(10,0), "PREPAY_SUBJECT" VARCHAR2(32), "PRESENT_SUBJECT" VARCHAR2(32), "PRESENT_ROLL_TYPE" NUMBER(1,0), "OFFSET_CYCLES" NUMBER(8,0), "CYCLE_TYPE" NUMBER(1,0), "VALID_CYCLES" NUMBER(8,0), "CREATETIME" DATE, "IN_USE" NUMBER(1,0), "CONDITIONNAME" VARCHAR2(256), "FEEGROUPID" VARCHAR2(32), "LIMITPRIVILEGE" VARCHAR2(128), "LIMITACCTPRIV" VARCHAR2(128), "GROUPINFO" NUMBER(2,0) DEFAULT 0, "SIMPCONDITION" VARCHAR2(256)) ;

CREATE TABLE "COLLECT_PRIV_ITEM_DEF" ("CHARGE_PRESENT_PLANID" VARCHAR2(10), "CHARGE_PRESENT_PLANITEMID" VARCHAR2(10), "MINVALUE" NUMBER(14,0), "MAXVALUE" NUMBER(14,0), "PRESENTTYPE" NUMBER(1,0), "PRESENT_OBJECTID" VARCHAR2(32), "PRESENT_COMPUTE_METHOD" NUMBER(1,0), "REFERENCE_AMTTYPE" NUMBER(1,0), "PRESENT_PERCENT" NUMBER(14,0), "PRESENT_NUM" NUMBER(12,0) DEFAULT 0, "IS_SUPPORT_CARDNUM" NUMBER(1,0) DEFAULT 0, "BEGIN_CARD_NUM" VARCHAR2(32) DEFAULT 0, "END_CARD_NUM" VARCHAR2(32) DEFAULT 0) ;

CREATE TABLE "COLLECT_SUBJECT_DEF" ("RECTYPE" VARCHAR2(32), "ACCESSTYPE" VARCHAR2(32), "PAYTYPE" VARCHAR2(32), "PREPAYSUBJECTID" VARCHAR2(30), "TEMPSUBJECTID" VARCHAR2(32), "TEMPLATE_NO" VARCHAR2(16) DEFAULT ' ', "SMS_TEMPLATE_NO" VARCHAR2(16) DEFAULT ' ', "RECSUBTYPE" VARCHAR2(32) DEFAULT '*') ;




