CREATE TABLE "BILLING_CYCLE_CONTROL" ("REGION" NUMBER(5,0), "CYCLEID" NUMBER(8,0), "MODIFYTIME" DATE DEFAULT sysdate, "OPENDAY" NUMBER(2,0) DEFAULT 0, "OFFSET_SECOND" NUMBER(6,0) DEFAULT 0) ;

CREATE TABLE "BILLING_DEF" ("EVENT_ID" NUMBER(8,0), "BILLING_COND" VARCHAR2(512), "EXPR_TYPE" NUMBER(1,0), "ITEM_EXPR" VARCHAR2(128), "ITEMCODE" VARCHAR2(32), "ITEMTYPE" NUMBER(2,0), "ITEMADD_TYPE" NUMBER(1,0), "ITEMADD_EXPR" VARCHAR2(128), "START_CYCLE" NUMBER(8,0), "END_CYCLE" NUMBER(8,0), "TEMPITEM_FLAG" NUMBER(1,0), "ITEM_UNIT" NUMBER(2,0), "PAYPLAN_FLAG" NUMBER(1,0), "G_BILLING_COND" VARCHAR2(1024), "G_ITEMADD_EXPR" VARCHAR2(128), "G_ITEM_EXPR" VARCHAR2(1024), "RULEID" NUMBER(4,0) DEFAULT 1, "NEXTRULEID" NUMBER(4,0) DEFAULT 0, "PROCSCHEMAID" NUMBER(5,0) DEFAULT 0, "PROCEVENTID" NUMBER(4,0) DEFAULT 0, "RULENAME" VARCHAR2(32), "FEE_ID" NUMBER(9,0), "SPLITTYPE" NUMBER(1,0) DEFAULT 0, "UNIQUE_ID" NUMBER(10,0), "ROUNDTYPE" NUMBER(1,0) DEFAULT 0) ;

CREATE TABLE "BILLINGCYCLE" ("CYCLE_SCHEMA_ID" NUMBER(4,0), "CYCLE_ID" NUMBER(8,0), "CYCLE_NAME" VARCHAR2(64), "CYCLE_STATUS" NUMBER(1,0), "OPENDATE" DATE, "CLOSEDATE" DATE, "INVOICEDATE" DATE) ;

CREATE TABLE "BILLINGCYCLE_SCHEMA" ("CYCLE_SCHEMA_ID" NUMBER(4,0), "CYCLE_SCHEMA_NAME" VARCHAR2(64), "CYCLE_UNIT" NUMBER(1,0), "UNIT_COUNT" NUMBER(4,0), "OPENDATE" VARCHAR2(32), "INVOICE_DELAY" NUMBER(4,0), "PREBUILT_CYCLES" NUMBER(4,0), "FIRSTCYCLE_OPENDATE" VARCHAR2(32), "STATUS" NUMBER(1,0), "MULTIACTIVATION" NUMBER(1,0), "FIXED_CYCLE" NUMBER(1,0), "CYCLEID_BASE" NUMBER(1,0) DEFAULT 1) ;

CREATE TABLE "BILLITEM_CELL_DEF" ("TEMPLATE_ID" NUMBER(10,0), "CELL_ID" VARCHAR2(32), "ITEMTYPE" NUMBER(1,0), "ITEMCODE" VARCHAR2(32), "ITEMADDCODE" VARCHAR2(32), "ISWRTOFFED" NUMBER(1,0), "INCL_SUBJECTID" VARCHAR2(256), "EXCL_SUBJECTID" VARCHAR2(256), "EXCL_ITEMCODE" VARCHAR2(256), "COEFFICIENT" NUMBER(2,0) DEFAULT 1, "CELL_TYPE" NUMBER(1,0) DEFAULT 1, "INCLUDEPACKAGE" NUMBER(1,0) DEFAULT 0, "GETNAMEORDER" NUMBER(1,0) DEFAULT 0, "FEEGROUPLIMIT" NUMBER(1,0) DEFAULT 0, "SELFDEFAULT" NUMBER(1,0) DEFAULT -1) ;

CREATE TABLE "BUFACCTEXTENT" ("BUFID" NUMBER(8,0), "MINACCTID" NUMBER(15,0), "MAXACCTID" NUMBER(15,0), "ACCTCOUNT" NUMBER(10,0)) ;

CREATE TABLE "BUFSUBSEXTENT" ("BUFID" NUMBER(8,0), "MINSUBSID" NUMBER(15,0), "MAXSUBSID" NUMBER(15,0), "SUBSCOUNT" NUMBER(10,0)) ;

CREATE TABLE "CDR_QUERY_LOG" ("OPERID" VARCHAR2(32), "LOGONID" NUMBER(10,0), "QUERY_TYPE" NUMBER(1,0), "QUERY_TIME" DATE, "QUERY_TABLE" VARCHAR2(254), "EVENT_ID" NUMBER(4,0), "QUERY_MONTH" VARCHAR2(8), "TELNUM" VARCHAR2(25), "QUERY_COND" VARCHAR2(1024)) ;

CREATE TABLE "CDR_SUPPLEMENT_DEF" ("SUPPLEMENT_ID" NUMBER(4,0), "CLUE_CDR_TABLE" VARCHAR2(64), "CLUE_CDR_WHERE_CLAUSE" VARCHAR2(120), "OFFLINE_CDR_TABLE" VARCHAR2(64), "OFFLINE_CDR_WHERE_CLAUSE" VARCHAR2(120), "ONLINE_CDR_TABLE" VARCHAR2(64), "ONLINE_CDR_WHERE_CLAUSE" VARCHAR2(120), "OFFLINE_QUERY_WHERE_CLAUSE" VARCHAR2(120), "ATTR_ID" NUMBER(4,0), "FIRST_SEQ" NUMBER(4,0) DEFAULT 1, "ONLINE_CYCLE" NUMBER(1,0) DEFAULT 2) ;

CREATE TABLE "CDR_SUPPLEMENT_TASK" ("TASK_ID" NUMBER(4,0), "SUPPLEMENT_ID" NUMBER(4,0), "CLUE_EVENT_ID" NUMBER(4,0), "CLUE_QUERY" VARCHAR2(256), "CDR_EVENT_ID" NUMBER(4,0), "FLOW_ID" NUMBER(4,0)) ;

CREATE TABLE "CECONFILEINFO" ("TASK_ID" NUMBER(10,0), "TASK_NOTE" VARCHAR2(128), "CEID" NUMBER(10,0), "CONFILECATA" VARCHAR2(128), "CONFILENAME" VARCHAR2(32), "LOGFILECATA" VARCHAR2(128), "LOGFILENAMEEXP" VARCHAR2(32), "BACKUPCATA" VARCHAR2(128), "CONFIGFILE_TYPE" VARCHAR2(32), "TEST_COMMAND" VARCHAR2(128), "COMMAND_RETURN_STRING" VARCHAR2(256)) ;

CREATE TABLE "CHARGE_RATE" ("RATECODE" NUMBER(8,0), "RATENAME" VARCHAR2(64), "CURRENCY" NUMBER(15,7), "CURRENCYTYPE" NUMBER(1,0), "UNITS" NUMBER(13,3), "UNITTYPE" NUMBER(2,0), "ROUND_UNIT" NUMBER(13,3), "ROUND_TYPE" NUMBER(1,0), "ATTR_CLASS" NUMBER(2,0), "REGION" NUMBER(5,0) DEFAULT 0) ;

