CREATE TABLE "HIGHCOST_USER_INFO" ("REGION" NUMBER(3,0), "SUBSOID" NUMBER(14,0), "ITEMID" VARCHAR2(30), "DAILYLEVEL1" NUMBER(20,2), "DAILYLEVEL2" NUMBER(20,2), "DAILYLEVEL3" NUMBER(20,2), "MONTHLYLEVEL1" NUMBER(20,2), "MONTHLYLEVEL2" NUMBER(20,2), "MONTHLYLEVEL3" NUMBER(20,2)) ;

CREATE TABLE "HIGHCOST_USER_INFOX" ("REGION" NUMBER(3,0), "SUBSOID" NUMBER(14,0), "ITEMID" VARCHAR2(30), "DAILYLEVEL1" NUMBER(20,2), "DAILYLEVEL2" NUMBER(20,2), "DAILYLEVEL3" NUMBER(20,2), "MONTHLYLEVEL1" NUMBER(20,2), "MONTHLYLEVEL2" NUMBER(20,2), "MONTHLYLEVEL3" NUMBER(20,2)) ;

CREATE TABLE "MAPPING_LIST" ("MAPPING_SOUR" VARCHAR2(240), "MAPPING_DEST" VARCHAR2(240), "APPLYTIME" DATE, "EXPIRETIME" DATE, "MAPPING_ID" NUMBER(5,0), "NOTE" VARCHAR2(120)) ;

CREATE TABLE "MAPPING_LISTX" ("MAPPING_SOUR" VARCHAR2(240), "MAPPING_DEST" VARCHAR2(240), "APPLYTIME" DATE, "EXPIRETIME" DATE, "MAPPING_ID" NUMBER(5,0), "NOTE" VARCHAR2(120)) ;

CREATE TABLE "OPERATOR_BOSS" ("OPERID" VARCHAR2(20), "REGION" NUMBER(5,0), "OPERNAME" VARCHAR2(100), "PASSWORD" VARCHAR2(200), "PASSCHGDATE" DATE, "OPERGROUP" VARCHAR2(20), "OPERTYPE" VARCHAR2(16), "OPERLEVEL" VARCHAR2(20), "ISMANAGER" NUMBER(1,0), "CONTACTPHONE" VARCHAR2(20), "ORGID" VARCHAR2(32), "ISRESTRICT" NUMBER(1,0), "STARTTIME" NUMBER(2,0), "ENDTIME" NUMBER(2,0), "ENABLEGPRS" NUMBER(1,0), "GPRSSTARTTIME" NUMBER(2,0), "GPRSENDTIME" NUMBER(2,0), "ISCHKMAC" NUMBER(2,0), "MAC" VARCHAR2(64), "NOTES" VARCHAR2(256), "CREATEDATE" DATE, "STATUS" NUMBER, "STATUSDATE" DATE, "RELE_STAFF_ID" VARCHAR2(20), "START_USING_TIME" DATE, "END_USING_TIME" DATE, "LOGINTYPE" VARCHAR2(16), "AREAID" VARCHAR2(32)) ;

CREATE TABLE "OPERATOR_BOSSX" ("OPERID" VARCHAR2(20), "REGION" NUMBER(5,0), "OPERNAME" VARCHAR2(100), "PASSWORD" VARCHAR2(200), "PASSCHGDATE" DATE, "OPERGROUP" VARCHAR2(20), "OPERTYPE" VARCHAR2(16), "OPERLEVEL" VARCHAR2(20), "ISMANAGER" NUMBER(1,0), "CONTACTPHONE" VARCHAR2(20), "ORGID" VARCHAR2(32), "ISRESTRICT" NUMBER(1,0), "STARTTIME" NUMBER(2,0), "ENDTIME" NUMBER(2,0), "ENABLEGPRS" NUMBER(1,0), "GPRSSTARTTIME" NUMBER(2,0), "GPRSENDTIME" NUMBER(2,0), "ISCHKMAC" NUMBER(2,0), "MAC" VARCHAR2(64), "NOTES" VARCHAR2(256), "CREATEDATE" DATE, "STATUS" NUMBER, "STATUSDATE" DATE, "RELE_STAFF_ID" VARCHAR2(20), "START_USING_TIME" DATE, "END_USING_TIME" DATE, "LOGINTYPE" VARCHAR2(16), "AREAID" VARCHAR2(32)) ;

CREATE TABLE "SET_DEF" ("SET_ID" NUMBER(4,0), "SET_NAME" VARCHAR2(64), "VALUE_NAME" VARCHAR2(64), "MATCH_ORDER" NUMBER(1,0), "SET_PARAM_ATTR" VARCHAR2(20), "OFTEN_USED" NUMBER(1,0) DEFAULT 0) ;

CREATE TABLE cbsparam2."SET_DEF" ("SET_ID" NUMBER(4,0), "SET_NAME" VARCHAR2(64), "VALUE_NAME" VARCHAR2(64), "MATCH_ORDER" NUMBER(1,0), "SET_PARAM_ATTR" VARCHAR2(20), "OFTEN_USED" NUMBER(1,0) DEFAULT 0) ;

CREATE TABLE "SET_VALUE" ("SET_ID" NUMBER(4,0), "APPLYTIME" DATE, "EXPIRETIME" DATE, "VALUE" VARCHAR2(128), "NOTE" VARCHAR2(128)) ;

CREATE TABLE cbsparam2."SET_VALUE" ("SET_ID" NUMBER(4,0), "APPLYTIME" DATE, "EXPIRETIME" DATE, "VALUE" VARCHAR2(128), "NOTE" VARCHAR2(128)) ;

CREATE TABLE "ACCTBUFDEF" ("BUFID" NUMBER(8,0), "KEYID" NUMBER(10,0), "ACCTCOUNT" NUMBER(12,0), "CYCLECOUNT" NUMBER(4,0), "ITEMCYCLECOUNT" NUMBER(4,0), "SUBSCOUNT" NUMBER(12,0), "BILLCOUNT" NUMBER(15,0), "SUBJECTCOUNT" NUMBER(15,0), "FREELISTCOUNT" NUMBER(10,0), "NODEID" NUMBER(4,0), "HOSTNAME" VARCHAR2(128), "STATUS" NUMBER(1,0), "BILLITEMCOUNT" NUMBER(15,0) DEFAULT 0, "BILLCYCLE" NUMBER(10,0), "BILLINGBUFCOUNT" NUMBER(2,0) DEFAULT 20, "FOREWARDCYCLE" NUMBER(2,0) DEFAULT 0, "BACKWARDCYCLE" NUMBER(2,0) DEFAULT 0, "PORT" NUMBER(8,0));

CREATE TABLE "ACCTITEM_DEF" ("ITEMCODE" VARCHAR2(30), "ITEMNAME" VARCHAR2(64), "ITEMLEVEL" NUMBER(2,0), "PARENTITEMCODE" VARCHAR2(32), "WRTOFF_ORDER" NUMBER(2,0), "SERV_ID" VARCHAR2(12) DEFAULT '0', "SUBSERV_ID" VARCHAR2(12), "IN_USE" NUMBER(1,0), "ITEMCODEN" NUMBER(8,0), "FINANCEITEM_CODE" VARCHAR2(32), "IS_NEW_SERVICE" NUMBER(1,0) DEFAULT 1, "IS_CAL_SCORE" NUMBER(1,0) DEFAULT 1, "MONTH_FEE_PRECHARGE_COUNT" NUMBER(4,0) DEFAULT -1, "IN_PAUSE" NUMBER(1,0) DEFAULT 0, "PAUSE_TIME" DATE, "PAUSE_REASON" VARCHAR2(256), "ADD_REASON" VARCHAR2(256), "ODD_ROUND_TYPE" CHAR(1), "UNIT" NUMBER(2,0) DEFAULT 0) ;

CREATE TABLE "ACCTWS_CLIENT_PWD" ("SEQNO" NUMBER(6,0), "PASSWORD" VARCHAR2(128), "EFFECTIVE_DATE" DATE, "EXPIRE_DATE" DATE, "MODIFY_DATE" DATE DEFAULT SYSDATE) ;

CREATE TABLE "AM_ACCT_INOUTMODEBOOK" ("RECTYPE" VARCHAR2(32), "ACCESSTYPE" VARCHAR2(32), "PAYTYPE" VARCHAR2(32), "INOUTMODE" VARCHAR2(128)) ;

CREATE TABLE "AM_ACCT_ITEM" ("ACCT_TYPE" NUMBER(2,0), "ACCT_ITEM" NUMBER(2,0), "FLOW_TYPE" NUMBER(2,0) DEFAULT 0, "NOTE" VARCHAR2(64)) ;

CREATE TABLE "AM_ACCT_ITEMPAYDEF" ("OID" VARCHAR2(32), "ITEMCODE" VARCHAR2(32), "RECTYPE" VARCHAR2(32), "SUBJECTID" VARCHAR2(32), "INUSE" NUMBER(1,0)) ;

CREATE TABLE "AM_ACCT_ITEMPAYDETAIL" ("DEFOID" VARCHAR2(32), "DEDUCTORDER" NUMBER(2,0), "SUBJECTID" VARCHAR2(32), "INUSE" NUMBER(1,0)) ;

CREATE TABLE "AM_ACCT_REBATE_ITEM" ("REBATE_SCHEMA_ID" NUMBER(15,0), "BEGIN_SEQ" NUMBER(5,0), "END_SEQ" NUMBER(5,0), "SUBJECTID" VARCHAR2(32), "FEE" NUMBER(12,0), "MAXUSABLECYCLECOUNT" NUMBER(5,0), "STATUS" NUMBER(1,0), "PROLONG_TYPE" NUMBER(2,0), "PROLONG_DAYS" NUMBER(10,0), "RESTYPE" NUMBER(2,0), "POSTPONE_CHECK" NUMBER(1,0), "POSTPONE_CHECK_AMT" NUMBER(10,0), "RES_FLOWIN_TYPE" NUMBER(1,0), "RECSUBTYPE" VARCHAR2(32), "USABLECYCLETYPE" NUMBER(2,0), "SRC_SUBJECTID" VARCHAR2(32)) ;

CREATE TABLE "AM_ACCT_REBATE_SCHEMA" ("REBATE_SCHEMA_ID" NUMBER(15,0), "REBATE_SCHEMA_NAME" NVARCHAR2(128), "TOTALFEE" NUMBER(12,0), "DATAQUERYID" VARCHAR2(16), "DATAQUERYTYPE" NUMBER(2,0), "CYCLECOUNT" NUMBER(5,0), "OFFSETCYCLES" NUMBER(5,0), "OFFSETDAYS" NUMBER(2,0), "CYCLETYPE" VARCHAR2(3), "CREATE_DATE" DATE DEFAULT sysdate, "PRESENT_BEGIN_TYPE" NUMBER(3,0), "BEGIN_DATE" DATE, "REBATE_DAY" NUMBER(8,0), "CONDITION" VARCHAR2(128), "CONDITIONNAME" VARCHAR2(256), "BRANDID" VARCHAR2(16), "REBATE_REC_TYPE" VARCHAR2(16), "TRANS_CASH_AMT" NUMBER(10,0), "REBATE_DAY_TYPE" NUMBER(2,0), "OWNERLIMIT" NUMBER(1,0), "CANCEL_RULE_TYPE" NUMBER(3,0), "PRODID" VARCHAR2(32), "DES_SUBJECTID" VARCHAR2(16), "CONTRACT_AMT" NUMBER(10,0)) ;

CREATE TABLE "AM_ACCT_RULE" ("SUBJECT_TYPE" NUMBER(1,0), "SUBJECT_ID" VARCHAR2(32) DEFAULT -1, "FLOW_TYPE" NUMBER(2,0), "FLOW_TIME_RANGE" NUMBER(1,0), "FLOW_DIRECTION" NUMBER(1,0), "FEE_SIGN" NUMBER(1,0) DEFAULT -1, "FEE_SOURCE" NUMBER(1,0), "ACCT_TYPE" NUMBER(1,0), "ACCT_ITEM" NUMBER(2,0)) ;

CREATE TABLE "AM_BILL_MIGRATE_DEF" ("DATA_TYPE" VARCHAR2(32), "NAME" VARCHAR2(64), "IS_NEEDUPDATE" NUMBER(1,0) DEFAULT 1, "MIN_INTERVAL" NUMBER(5,0), "MAX_INTERVAL" NUMBER(5,0), "MIN_CYCLE" NUMBER(8,0) DEFAULT 0, "UNCERTAIN_DEALMODE" NUMBER(1,0)) ;


