CREATE TABLE "FREE_USAGE_ATTR_DEF" ("ENTITY_ID" NUMBER(4,0), "ATTR_ID" NUMBER(8,0), "FIXED_FREE_USAGE" NUMBER(15,0), "FREE_LIMIT" NUMBER(15,0), "FREE_TYPE" NUMBER(1,0), "FREE_USE_MODE" NUMBER(1,0) DEFAULT 1, "PRECENDENCE_SCHEME" NUMBER(5,0) DEFAULT 0) ;

CREATE TABLE "GCPS_PARAM_VALUE" ("PARAM_ID" VARCHAR2(60), "PARAM_NAME" VARCHAR2(60), "PARAM_VALUE" VARCHAR2(256)) ;

CREATE TABLE "GENERAL_SERVICE_CONFIG" ("REGION" NUMBER(9,0) DEFAULT -1, "SERVER_NAME" VARCHAR2(64), "GROUP_CODE" VARCHAR2(50), "GROUP_TYPE" VARCHAR2(50), "CENTRE_SEQ" NUMBER(2,0) DEFAULT -1) ;

CREATE TABLE "GLOBAL_CONFIG" ("PARAM_NAME" VARCHAR2(128), "PARAM_VALUE" VARCHAR2(256), "NOTE" NVARCHAR2(128), "INC_APPSYSLIST" VARCHAR2(64), "EXC_APPSYSLIST" VARCHAR2(64), "MODULE_NAME" VARCHAR2(128) DEFAULT 'COMMON', "SCOPE_LEVEL" VARCHAR2(16) DEFAULT 'System', "SCOPE_VALUE" VARCHAR2(32)) ;

CREATE TABLE "HIGHCOSTFILEPROC" ("FILEID" NUMBER(4,0), "PROCSCHEMAID" NUMBER(4,0), "FILETYPE" NUMBER(1,0), "IFHAVEHEAD" NUMBER(1,0), "HSTATMODULEID" NUMBER(4,0), "IFHAVETAIL" NUMBER(1,0), "TSTATMODULEID" NUMBER(4,0), "APPLYTIME" DATE, "EXPIRETIME" DATE, "EMPTYHEADPROCSCHEMAID" NUMBER(4,0), "EMPTYTAILPROCSCHEMAID" NUMBER(4,0)) ;

CREATE TABLE "HIGHCOSTREPORTTYPEDEF" ("PROCESSID" NUMBER(5,0), "REPORTTYPE" VARCHAR2(2), "COMFILENAMEMODULEID" NUMBER(4,0), "SUMFILENAMEMODULEID" NUMBER(4,0)) ;

CREATE TABLE "HOSTNODE_DEF" ("HOSTID" NUMBER(4,0), "HOSTNAME" VARCHAR2(64), "IPADDR0" VARCHAR2(32), "IPADDR1" VARCHAR2(32), "INUSE" NUMBER(1,0), "DB_LINK_NAME" VARCHAR2(32), "CLUSTER_ID" NUMBER(2,0)) ;

CREATE TABLE "INFIRMWORD" ("INFIRMWORD" VARCHAR2(32), "INUSE" NUMBER(1,0) DEFAULT 1) ;

CREATE TABLE "INFOFILEBATCH_DEF" ("BATCHNUM" NUMBER(2,0), "BATCHNAME" NVARCHAR2(128)) ;

CREATE TABLE "INFOFILENAME_DEF" ("FILEID" NUMBER(5,0), "CONORDER" NUMBER(5,0), "CONTYPE" NUMBER(5,0), "CONTENT" VARCHAR2(512)) ;

CREATE TABLE "INFOFILESQL_DEF" ("SQLQUERYID" NUMBER(4,0), "TABLENAME" VARCHAR2(4000), "COND" VARCHAR2(2048), "QRY_CONTENT_SQL" VARCHAR2(3000), "ISDELETE" NUMBER(1,0) DEFAULT null, "CYCLE_FLAG" NUMBER(1,0) DEFAULT null, "INUSE" NUMBER(1,0) DEFAULT null, "SQLQUERYNO" NUMBER(4,0), "UPDATE_SQL" VARCHAR2(1024)) ;

CREATE TABLE "INFOFILETASK_DEF" ("TASKID" NUMBER(4,0), "TASK_NAME" NVARCHAR2(128), "FILEID" NUMBER(4,0), "SQLQUERY_ID" NUMBER(4,0), "MAX_EVENT_COUNT" NUMBER(9,0), "FILESEQBEGIN" NUMBER(6,0), "FILESEQEND" NUMBER(6,0), "TMPPATH" VARCHAR2(256), "DESTPATH" VARCHAR2(256), "FILETYPE" NUMBER(1,0), "BATCHNUM" NUMBER(2,0), "INUSE" NUMBER(1,0) DEFAULT 0, "GENEMPTYFILEFLAG" NUMBER(1,0) DEFAULT 0, "HEADCONTENT" VARCHAR2(512), "TAILCONTENT" VARCHAR2(512), "CHECKFILE_POSTFIX" VARCHAR2(20), "DATAFILE_POSTFIX" VARCHAR2(20)) ;

CREATE TABLE "LC_DYNAMIC_DEF" ("NODE_ID" NUMBER(4,0) DEFAULT 0, "EVENT_ID" NUMBER(4,0) DEFAULT 0, "SUB_EVENT_ID" NUMBER(4,0) DEFAULT 0, "LCPRIOR" NUMBER(4,0) DEFAULT 0, "START_THRESHOLD" NUMBER(8,0) DEFAULT 800, "RESUME_THRESHOLD" NUMBER(8,0) DEFAULT 250, "SMOOTH_CYCLE" NUMBER(2,0) DEFAULT 2, "ADJUST_CYCLE" NUMBER(2,0) DEFAULT 4, "ADJUST_DIVISOR" NUMBER(2,0) DEFAULT 16, "ADJUST_STEP" NUMBER(2,0) DEFAULT 1, "NODE_TYPE" NUMBER(1,0)) ;

CREATE TABLE "LC_ESTIMATE_RESULT" ("NODE_ID" NUMBER(4,0) DEFAULT 0, "EVENT_ID" NUMBER(4,0) DEFAULT 0, "SUB_EVENT_ID" NUMBER(4,0) DEFAULT 0, "LC_STATUS_TIME" DATE DEFAULT sysdate, "LC_STATUS" NUMBER(2,0) DEFAULT 0, "LC_CUR_STEP" NUMBER(2,0) DEFAULT 0, "NODE_TYPE" NUMBER(1,0)) ;

CREATE TABLE "LC_STATIC_DEF" ("NODE_ID" NUMBER(4,0) DEFAULT 0, "EVENT_ID" NUMBER(4,0) DEFAULT 0, "SUB_EVENT_ID" NUMBER(4,0) DEFAULT 0, "CAPS" NUMBER(8,0) DEFAULT 10000, "NODE_TYPE" NUMBER(1,0)) ;

CREATE TABLE "LIMITLOGON" ("LIMITID" NUMBER(5,0), "IPADDR" VARCHAR2(16), "MACADDR" VARCHAR2(20), "STARTHOUR" NUMBER(6,0), "ENDHOUR" NUMBER(6,0), "INUSE" NUMBER(1,0) DEFAULT 1) ;

CREATE TABLE "LOGICAL_DS_DEF" ("DATASTORE_NAME" VARCHAR2(64), "FILENAME_PREFIX" VARCHAR2(8), "TMP_DIR" VARCHAR2(256), "BAK_DIR" VARCHAR2(256), "METHOD" NUMBER(1,0), "DATA_FORMAT" NUMBER(1,0), "INUSE" NUMBER(1,0), "FILETYPE" NUMBER(1,0) DEFAULT 1, "HAVEVERSION" NUMBER(1,0) DEFAULT 1, "STORETYPE" VARCHAR2(1) DEFAULT 'F', "QUEUETABLENAME" VARCHAR2(32), "QUEUECAPICITY" NUMBER(8,0) DEFAULT (0), "QUEUEBLOCKTIME" NUMBER(8,0) DEFAULT (0), "READFILEBYLINE" NUMBER(2,0) DEFAULT 0) ;

CREATE TABLE "MAIN_DB_SERVER_DEF" ("SERVER_NAME" VARCHAR2(50), "SERVER_ID" NUMBER(4,0), "SERVER_DESC" VARCHAR2(200)) ;

