CREATE TABLE "PRODUCT_ATTR" ("PRODUCT_TYPE" VARCHAR2(10), "PRODUCT_CODE" VARCHAR2(60), "ATTR_CODE" VARCHAR2(30), "ATTR_VALUE" VARCHAR2(50)) ;

CREATE TABLE "PRODUCT_DEF" ("PRODUCT_TYPE" VARCHAR2(10), "PRODUCT_CODE" VARCHAR2(60), "PRODUCT_NAME" VARCHAR2(256), "NOTE" VARCHAR2(2000), "HISTORY" VARCHAR2(2000), "MERGE_MODE" NUMBER(1,0) DEFAULT 0, "TRIGGER_RENT" NUMBER(1,0) DEFAULT 0, "TRIGGER_PRESENT" NUMBER(1,0) DEFAULT 0, "CARRYOVER_FLAG" NUMBER(1,0) DEFAULT 0) ;

CREATE TABLE "ENTITY_SYNC_QUEUE" ("REGION" VARCHAR2(30), "CREATE_TIME" DATE, "TRANS_SN" VARCHAR2(60), "REFRESH_INDEX" NUMBER(18,0), "ENTITY_TABLE" VARCHAR2(100), "ENTITY_KEY" VARCHAR2(2000), "REFRESH_TYPE" CHAR(1), "SOURCE_TABLE" VARCHAR2(30), "SOURCE_KEY" VARCHAR2(2000), "PROCESS_FLAG" NUMBER(1,0) DEFAULT 0, "ROUTE_CUSTID" NUMBER(14,0), "PROCESS_TIME" DATE DEFAULT SYSDATE) ;

CREATE TABLE "GLOBAL_CONFIG" ("PARAM_NAME" VARCHAR2(128), "PARAM_VALUE" VARCHAR2(256), "NOTE" NVARCHAR2(128), "INC_APPSYSLIST" VARCHAR2(64), "EXC_APPSYSLIST" VARCHAR2(64), "MODULE_NAME" VARCHAR2(128) DEFAULT 'COMMON', "SCOPE_LEVEL" VARCHAR2(16) DEFAULT 'System', "SCOPE_VALUE" VARCHAR2(32)) ;

CREATE TABLE "PRODUCT_ELEMENT" ("PRODUCT_ELEMENT_TYPE" VARCHAR2(10), "PRODUCT_ELEMENT_CODE" VARCHAR2(60), "PRODUCT_ELEMENT_NAME" VARCHAR2(256), "NOTE" VARCHAR2(2000), "HISTORY" VARCHAR2(2000), "TRIGGER_RENT" NUMBER(1,0) DEFAULT 0, "MERGE_MODE" NUMBER(1,0) DEFAULT 0) ;

CREATE TABLE "PRODUCT_SERVICE_ATTR" ("PRODUCT_TYPE" VARCHAR2(10), "PRODUCT_CODE" VARCHAR2(60), "SERVICE_PLAN_TYPE" VARCHAR2(60), "SERVICE_PLAN_ID" NUMBER(6,0), "ATTR_CODE" VARCHAR2(60), "ATTR_VALUE" VARCHAR2(100), "ATTR_NAME" VARCHAR2(200)) ;

CREATE TABLE "PRODUCT_SERVICE_PLAN" ("PRODUCT_TYPE" VARCHAR2(10), "PRODUCT_CODE" VARCHAR2(60), "SERVICE_PLAN_TYPE" VARCHAR2(20), "SERVICE_PLAN_ID" NUMBER(6,0), "SHARE_SERVICE" VARCHAR2(10), "START_CYCLE" NUMBER(6,0) DEFAULT 200000, "END_CYCLE" NUMBER(6,0) DEFAULT 999999) ;

CREATE TABLE "PRODUCT_TEMPLATE_ATTR_DEF" ("ID" NUMBER(4,0), "BUSINESS" VARCHAR2(60), "SEQUENCE" NUMBER(4,0), "BUSINESS_VALUE" VARCHAR2(60), "ATTR_CODE" VARCHAR2(100), "ATTR_VALUE" VARCHAR2(200), "ATTR_CATALOG" VARCHAR2(60), "NOTE" VARCHAR2(200), "START_TIME" DATE, "END_TIME" DATE) ;

CREATE TABLE "PRODUCT_UNLIMITED_INFO" ("PRODUCT_TYPE" VARCHAR2(2) DEFAULT 'T', "PRODUCT_ID" VARCHAR2(32), "OWNER_ENTITY_TYPE" NUMBER(1,0), "USAGE_TYPE" VARCHAR2(4), "FREE_TIME" NUMBER(1,0) DEFAULT 0, "SERVICE_CODE" VARCHAR2(256), "LAC_CELL_ENTITY_TYPE" NUMBER(1,0) DEFAULT -1, "LAC_CELL_ENTITY_ATTR_ID" VARCHAR2(8), "AREA_CODE" VARCHAR2(32)) ;

CREATE TABLE "PRODUCT_USAGE_ATTR" ("PRODUCT_TYPE" VARCHAR2(10), "PRODUCT_CODE" VARCHAR2(60), "ENTITY_ID" NUMBER(18,0), "ATTR_ID" NUMBER(8,0), "SHARE_SERVICE" VARCHAR2(10), "LIMIT_TYPE" CHAR(1), "LIMIT_VALUE" NUMBER(10,0), "NOTE" VARCHAR2(100), "STDFREE_EXPR" VARCHAR2(64), "G_STDFREE_EXPR" VARCHAR2(128), "USAGE_CLASS" VARCHAR2(4), "USAGE_SUBCLASS" VARCHAR2(4), "USAGE_PRECEDENCE" NUMBER(4,0) DEFAULT 0) ;

CREATE TABLE "PROG_LICENSE_DEF" ("NODEID" NUMBER(2,0), "PROGNAME" VARCHAR2(64), "LICENSETYPE" VARCHAR2(64), "APPLYCODE" VARCHAR2(128), "AUTHCODE" VARCHAR2(256), "LICENSEVALUE" NUMBER(8,0)) ;

CREATE TABLE "Q2F_TASK_DEF" ("TASKID" NUMBER(10,0), "TASKNAME" VARCHAR2(128), "MAXEVENTCOUNT" NUMBER(9,0), "SLEEPSECONDS" NUMBER(9,0), "BATCHMAXCNT" NUMBER(9,0) DEFAULT 0) ;

CREATE TABLE "Q2F_TASK_ITEM" ("TASKID" NUMBER(10,0), "SUBID" NUMBER(10,0), "SUBNAME" VARCHAR2(128), "TRIMEVENTID" NUMBER(4,0), "SOURCETYPE" VARCHAR2(1) DEFAULT 's', "QUEUENAME" VARCHAR2(256), "FILEFORMAT" NUMBER(3,0), "MODULEID" NUMBER(16,0), "DELIMITER" VARCHAR2(10), "PROCESSMODULEID" NUMBER(10,0) DEFAULT 0, "FILEHEAD_EVENTID" NUMBER(5,0), "FILEBODY_EVENTID" NUMBER(5,0), "FILETAIL_EVENTID" NUMBER(5,0), "HEADTAIL_PROCESSSCHEMA" NUMBER(5,0), "FILTER_NONAME_ATTR" NUMBER(1,0) DEFAULT 0, "IS_ORDER_OUT" NUMBER(1,0) DEFAULT 0) ;

CREATE TABLE "QUSAGE_DEF" ("TRANSACTION_CODE" NUMBER(4,0), "CURRENT_QUERY" VARCHAR2(200), "HISTORY_QUERY" VARCHAR2(200)) ;

CREATE TABLE "QUSAGE_ITEM_DEF" ("TRANSACTION_CODE" NUMBER(4,0), "QUERY_ORDER" NUMBER(2,0), "QUERY_NAME" VARCHAR2(50), "ENTITY_ID" NUMBER(2,0) DEFAULT 1, "CACHE_QUERY_ID" NUMBER(9,0), "CORRELATIVE_QUERY_ID" NUMBER(9,0), "CACHE_STORE_PROC" VARCHAR2(200)) ;

CREATE TABLE "RECUPERATING_STRATEGY_DEF" ("STRATEGY_ID" VARCHAR2(20), "NAME" VARCHAR2(80), "UNDUP_MODULE" NUMBER(4,0), "CHECK_DUP" NUMBER(1,0), "ROLLBACK_FROM" NUMBER(2,0), "CLEAR_CYCLE" NUMBER(1,0), "FLOW_MODULE" NUMBER(4,0), "STAT_MODULE" NUMBER(4,0), "CHARGING_MODULE" NUMBER(4,0), "FIELD_PREFIX" VARCHAR2(60), "FORMAT_PROC" NUMBER(5,0), "ROLLBACK_COPY_USAGES" NUMBER(1,0), "ROLLBACK_RENTAL_LOG" NUMBER(1,0) DEFAULT 0, "KEY_TYPE" NUMBER(1,0) DEFAULT 2, "ADDITION_COND" VARCHAR2(500)) ;

CREATE TABLE "RECURRENT_TRIGGER_DEF" ("REGION" NUMBER(5,0), "TASK_NO" NUMBER(4,0), "ENTITY_ID" NUMBER(4,0), "TRIGGER_TYPE" NUMBER(2,0), "DEST_EVENT_ID" NUMBER(5,0), "FILTER_CONDITION" VARCHAR2(256), "G_FILTER_CONDITION" VARCHAR2(256), "FLOW_ID" NUMBER(5,0), "PROCESS_ID" NUMBER(9,0) DEFAULT 0) ;

CREATE TABLE "REFERRED_OBJECT" ("OBJECT_ID" NUMBER(4,0), "OBJECT_NAME" VARCHAR2(40), "ENTITY_ID" NUMBER(9,0), "ISONEINST" NUMBER(1,0), "ENTITY_TYPE" NUMBER(4,0)) ;

CREATE TABLE "REGION_ATTR" ("REGION_ID" NUMBER(4,0), "ATTR_ID" VARCHAR2(30), "VALUE_ORDER" NUMBER(4,0) DEFAULT 0, "ATTR_VALUE" VARCHAR2(50)) ;

CREATE TABLE "REGION_DEF" ("REGION_ID" NUMBER(4,0), "REGION_CODE" VARCHAR2(30), "REGION_TYPE" NUMBER(1,0), "REGION_NAME" NVARCHAR2(50), "NOTE" NVARCHAR2(200)) ;

CREATE TABLE "REGION_ENTITY_SCOPE" ("REGION_ID" NUMBER(4,0), "ENTITY_ID" NUMBER(4,0), "MAX_KEY_ID" NUMBER(13,0), "MIN_KEY_ID" NUMBER(13,0), "ENTITY_MAX" NUMBER(10,0), "STATIC_ATTR_MAX" NUMBER(10,0), "USAGE_ATTR_MAX" NUMBER(10,0), "BILLPLAN_ATTR_MAX" NUMBER(10,0), "STATIC_ATTR_PERCENT" NUMBER(2,0) DEFAULT 0, "STATIC_ATTR_AVG_LEN" NUMBER(6,0) DEFAULT 0) ;

CREATE TABLE "REGION_INDEX_SCOPE" ("REGION_ID" NUMBER(4,0), "ENTITY_ID" NUMBER(4,0), "INDEX_ID" NUMBER(4,0), "INDEX_MAX" NUMBER(10,0)) ;

CREATE TABLE "REGION_RECUPERATING_ENV_INFO" ("REGION" NUMBER(5,0), "DATABASE" VARCHAR2(100), "CDR_DBLINK" VARCHAR2(100), "HOST_ID" VARCHAR2(60), "PROC_COUNT" NUMBER(5,0) DEFAULT 1, "PROC_ID_LIST" VARCHAR2(1000), "LOG_FILE" VARCHAR2(100)) ;

CREATE TABLE "REMIND_BATCH_DEF" ("BATCH_ID" NUMBER(5,0), "NAME" VARCHAR2(32), "REMIND_COND" VARCHAR2(1024), "G_REMIND_COND" VARCHAR2(1024)) ;

CREATE TABLE "REMIND_CONTROL_BATCH" ("REMIND_ENTRY_ID" NUMBER(2,0), "REMIND_SEQ" NUMBER(4,0), "BATCH_TYPE" NUMBER(1,0), "BATCH_ID" NUMBER(4,0) DEFAULT -1, "IS_DYNAMIC" NUMBER(1,0) DEFAULT 0, "STATUS_LOG_TYPE" NUMBER(2,0), "OUTPUT_TYPE" NUMBER(2,0) DEFAULT 1) ;

CREATE TABLE "REMIND_CONTROL_DEF" ("REMIND_ENTRY_ID" NUMBER(2,0), "REMIND_PARAM_ID" NUMBER(4,0), "REMIND_ENTRY_NAME" VARCHAR2(20), "NOTYFY_TYPE" NUMBER(2,0), "TRIGGER_TYPE" NUMBER(1,0), "TRIGGER_EVENT_ID" NUMBER(4,0), "CONDITION" VARCHAR2(256), "G_CONDITION" VARCHAR2(256), "REMIND_ENTITY" NUMBER(2,0) DEFAULT 1, "APPLY_METHOD" NUMBER(1,0) DEFAULT 8) ;

CREATE SEQUENCE  "SEQ_REFRESH_INDEX"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 383163 CACHE 100 NOORDER  NOCYCLE ;

