CREATE TABLE "MAPPING_DEF" ("MAPPING_ID" NUMBER(5,0), "MAPPING_NAME" VARCHAR2(100), "SOUR_FIELD_COUNT" NUMBER(4,0), "MAPPING_SOUR_DEF" VARCHAR2(240), "DEST_FIELD_COUNT" NUMBER(4,0), "MAPPING_DEST_DEF" VARCHAR2(240), "MATCH_ORDER" NUMBER(1,0), "MAPPING_SOUR_ATTR" VARCHAR2(80), "MAPPING_DEST_ATTR" VARCHAR2(80), "OFTEN_USED" NUMBER(1,0) DEFAULT 0, "SOURCE_PROCESS_TYPE" NUMBER(2,0) DEFAULT 0) ;

CREATE TABLE "MAPPING_LIST" ("MAPPING_SOUR" VARCHAR2(240), "MAPPING_DEST" VARCHAR2(240), "APPLYTIME" DATE, "EXPIRETIME" DATE, "MAPPING_ID" NUMBER(5,0), "NOTE" VARCHAR2(120)) ;

CREATE TABLE "PARAM_ID_CHANGE" ("GROUP_NAME" VARCHAR2(20), "ID_NUMBER" NUMBER(10,0), "CHANGE_TIME" DATE) ;

CREATE TABLE "MAPPING_RULE" ("RULE_ID" NUMBER(5,0), "RULE_NAME" VARCHAR2(64), "SOUR_ATTR_DEF" VARCHAR2(256), "DEST_ATTR_DEF" VARCHAR2(256), "MATCH_METHOD" NUMBER(1,0), "MAPPING_ID" NUMBER(5,0), "ERROR_CODE" VARCHAR2(10), "G_SOUR_ATTR" VARCHAR2(256), "G_DEST_ATTR" VARCHAR2(256), "SOUR_EVENT_ID" NUMBER(5,0), "DEST_EVENT_ID" NUMBER(5,0)) ;

CREATE TABLE "MMQ_DEF" ("MMQ_DEVID" NUMBER(8,0), "MMQ_NAME" VARCHAR2(30), "MMQ_DESC" VARCHAR2(60), "MMQ_SIZE" NUMBER(8,0)) ;

CREATE TABLE "MMQ_DEVICE_DEF" ("MMQ_DEVID" NUMBER(8,0), "SHMKEY" NUMBER(8,0), "DCB_SIZE" NUMBER(16,0), "BLOCK_SIZE" NUMBER(8,0), "DCB_NAME" VARCHAR2(30)) ;

CREATE TABLE "MODULE_EVENT_TARIFF_PLAN" ("MODULE_ID" NUMBER(4,0), "EVENT_TARIFF_PLAN_ID" NUMBER(6,0), "STATUS" NUMBER(1,0)) ;

CREATE TABLE "NECONFIGCONTENTINFO" ("TASK_ID" NUMBER(10,0), "OPR_TYPE" VARCHAR2(10), "YN_COLLECT_END_FILE" VARCHAR2(10), "TRANSMIT_PROTOCOL" VARCHAR2(10), "TRANSMIT_SUB_PROTOCOL" VARCHAR2(10), "TRANSMIT_MODE" VARCHAR2(10), "SOURCE_FILE" VARCHAR2(64), "DEST_FILE" VARCHAR2(64), "SOURCE_FILE_DIR" VARCHAR2(128), "DEST_FILE_DIR" VARCHAR2(128), "SOURCE_FILE_BEGIN_NO" NUMBER(10,0), "SOURCE_FILE_END_NO" NUMBER(10,0), "TIME_SPLIT" NUMBER(10,0), "COLLECT_COUNT" NUMBER(10,0), "SOURCE_FILE_TYPE" VARCHAR2(10), "PROCESS_RESULT" VARCHAR2(128), "TRANSMIT_AREA" VARCHAR2(32), "REMARK" VARCHAR2(128), "TEMP_FILE_DIR" VARCHAR2(64), "YN_COLLATE_FILE" VARCHAR2(10), "NEID" NUMBER(10,0), "PRIORITY" NUMBER(3,0) DEFAULT 999, "FILETIME_ADJUST_HOUR" NUMBER(4,0), "INUSE" NUMBER(1,0), "ACTION_CONDITION" VARCHAR2(100), "HARDLINKDIRS" VARCHAR2(4000)) ;

CREATE TABLE "NEINFO" ("NEID" NUMBER(10,0), "NENAME" VARCHAR2(32), "IPADDRESS" VARCHAR2(32), "NEUSERNAME" VARCHAR2(32), "NEPASSWORD" VARCHAR2(256), "OSTYPE" VARCHAR2(32)) ;

CREATE TABLE "OPERATIONCTL" ("OPERATION_NAME" VARCHAR2(64), "DEAL_FLAG" NUMBER(2,0), "ADDTION_INFO" VARCHAR2(256), "NOTES" VARCHAR2(64)) ;

CREATE TABLE "PHYSICAL_DS_DEF" ("DATASTORE_NAME" VARCHAR2(256), "NODEID" NUMBER(4,0), "DIR_NAME" VARCHAR2(256), "TMP_NAME" VARCHAR2(256), "CUR_SEQ" VARCHAR2(32), "INUSE" NUMBER(1,0), "BAK_DIR" VARCHAR2(128), "ATTR_CLASS" NUMBER(3,0) DEFAULT 0, "SUBQ_COUNT" NUMBER(3,0) DEFAULT 0, "BYDATE" NUMBER(1,0) DEFAULT 0, "NO_LOG" NUMBER(1,0) DEFAULT 0, "FILELIST_READ_MODE" NUMBER(1,0) DEFAULT 0, "SERVER_NAME" VARCHAR2(50)) ;

CREATE TABLE "PRESENT_DEF" ("REGION" NUMBER(4,0), "RENTORDERTYPE" NUMBER(2,0) DEFAULT -1, "RENTORDERID" VARCHAR2(64), "ITEMCODE" VARCHAR2(64), "ITEMADDCODE" VARCHAR2(64), "ENTITYTYPE" NUMBER(4,0), "ATTRID" VARCHAR2(512), "PRESENTNAME" NVARCHAR2(64), "SRCEVENTID" NUMBER(10,0) DEFAULT 0, "CONDITION" VARCHAR2(512), "CONDITIONNAME" VARCHAR2(512), "FREEVOLUME" VARCHAR2(512), "FREEVOLUMENAME" VARCHAR2(512), "CYCLECOUNT" VARCHAR2(512), "CYCLECOUNTNAME" VARCHAR2(512), "ADDUPFLAG" NUMBER(1,0) DEFAULT -1, "ATTRIDNAME" VARCHAR2(512), "USAGE_CONFIG_FLAG" NUMBER(1,0) DEFAULT 0, "ITEMCODE_EXP" VARCHAR2(512), "ITEMCODE_NAME" VARCHAR2(512)) ;

CREATE TABLE "PRINT_CUST_DEF" ("ID" NUMBER(5,0), "DATAQUERYID" NUMBER(20,0), "ENTITYID" NUMBER(1,0), "ISUSED" NUMBER(1,0) DEFAULT 1, "HEAD" VARCHAR2(200), "INFO" VARCHAR2(200)) ;

CREATE TABLE "PRIV_DESIGNATE" ("OPERATOR_NAME" VARCHAR2(256), "RESOURCE_TYPE" NUMBER(1,0), "RESOURCE_ID" NUMBER(4,0), "PRIV_SET" NUMBER(4,0)) ;

CREATE TABLE "PRIVILEGE_CALL_FEE" ("HREGION" CHAR(3), "ITEMCODE" VARCHAR2(8), "ITEMNAME" VARCHAR2(200), "OWNER" CHAR(1), "FEETYPE" VARCHAR2(4), "METHOD" CHAR(1), "VALUE" NUMBER(10,2), "BILLINGCODE" NUMBER(8,0)) ;

CREATE TABLE "MODULE_RATEPLAN" ("MODULE_ID" NUMBER(4,0), "TARIFF_PLAN_ID" NUMBER(6,0), "STATUS" NUMBER(1,0)) ;


