CREATE TABLE "DISC_BATCH_LIST" ("BATCH_ID" NUMBER(8,0), "TARIFFPLAN_ID" NUMBER(8,0), "START_CYCLE" NUMBER(8,0), "END_CYCLE" NUMBER(8,0)) ;

CREATE TABLE "DISCITEM_DEF" ("TARIFFPLAN_ID" NUMBER(8,0), "PLANITEM_ID" NUMBER(8,0), "DISCITEM_ID" NUMBER(8,0), "MIN_REFVALUE" NUMBER(16,0), "MAX_REFVALUE" NUMBER(16,0), "CALC_TYPE" NUMBER(1,0), "DISC_VALUE" NUMBER(18,2), "MAX_DISC_VALUE" NUMBER(16,0), "INUSE" NUMBER(1,0), "REFVALUE_ADD" NUMBER(16,0), "DISCT_EXPR" VARCHAR2(128) DEFAULT ' ', "G_DISCT_EXPR" VARCHAR2(200), "DISCITEM_COND" VARCHAR2(256), "G_DISCITEM_COND" VARCHAR2(256)) ;

CREATE TABLE "DISCOUNT_PARAM_DEF" ("PARAMDESC" VARCHAR2(100), "FEETYPE" VARCHAR2(10), "EXCLUSIVE_TYPE" NUMBER(1,0), "SEQ" NUMBER(10,0)) ;

CREATE TABLE "DISCOUNT_PARAM_ITEM" ("FEETYPE" VARCHAR2(10), "FIELD_NAME" VARCHAR2(60)) ;

CREATE TABLE "DISCREFITEM_DEF" ("TARIFFPLAN_ID" NUMBER(8,0), "PLANITEM_ID" NUMBER(8,0), "ITEM_CODE" VARCHAR2(32), "ITEM_DESC" VARCHAR2(64), "INUSE" NUMBER(1,0), "REF_ITEM_EXPR" VARCHAR2(512), "G_REF_ITEM_EXPR" VARCHAR2(512)) ;

CREATE TABLE "DISCVALUEPERCENT_DEF" ("TARIFFPLAN_ID" NUMBER(8,0), "PLANITEM_ID" NUMBER(8,0), "COND_EXPR" VARCHAR2(256), "PERCENT" NUMBER(10,0), "G_COND_EXPR" VARCHAR2(256), "SEQNO" NUMBER(5,0) DEFAULT 0) ;

CREATE TABLE "DIST_PLAN_ITEM" ("PLAN_ID" NUMBER(4,0) DEFAULT 1, "REGION" NUMBER(5,0) DEFAULT 0, "CUST_SHARD" NUMBER(8,0), "CONTAINER_ID" NUMBER(8,0), "NEW_CONTAINER_ID" NUMBER(8,0)) ;

CREATE TABLE "DISTRIBUTED_DB_DEF" ("REGION" NUMBER(5,0), "DBTYPE" NUMBER(2,0), "DISTRIBUTED_TYPE" NUMBER(1,0)) ;

CREATE TABLE "DISTRIBUTED_DBNODE_DEF" ("REGION" NUMBER(5,0), "DBTYPE" NUMBER(2,0), "NODEID" NUMBER(5,0), "NODEDESC" VARCHAR2(32)) ;

CREATE TABLE "EVENT_ACCUMULATE_MAPPING_DEF" ("RULE_ID" NUMBER(4,0), "MATCH_ORDER" NUMBER(4,0) DEFAULT 1, "SUB_ORDER" NUMBER(2,0) DEFAULT 1, "SOURCE_EVENT_FIELDS" VARCHAR2(1000), "BILLING_COND" VARCHAR2(600), "G_BILLING_CODE" VARCHAR2(600), "ITEM_CODE" VARCHAR2(40), "ITEMADD_EXPR" VARCHAR2(130), "G_ITEMADD_EXPR" VARCHAR2(130), "FEE_EXPR" VARCHAR2(130), "G_FEE_EXPR" VARCHAR2(130)) ;

CREATE TABLE "EVENT_ACCUMULATE_MAPPING_RULE" ("RULE_ID" NUMBER(4,0), "AUDIT_CHECK" NUMBER(1,0) DEFAULT 1, "EVENT_ID" NUMBER(4,0), "DST_EVENT_ID" NUMBER(4,0), "ITEM_TYPE" NUMBER(1,0), "SRC_FIELDS_LIST" VARCHAR2(300), "SRC_FIELDS_LIST_TEXT" VARCHAR2(300)) ;

CREATE TABLE "PRODUCT_ELEMENT_TARIFF" ("PRODUCT_ELEMENT_TYPE" VARCHAR2(10), "PRODUCT_ELEMENT_CODE" VARCHAR2(60), "TARIFF_PLAN_ID" NUMBER(6,0)) ;

CREATE TABLE "ENTITY_ATTR_DEF" ("ENTITY_ID" NUMBER(4,0), "ATTR_ID" NUMBER(8,0), "ATTR_NAME" VARCHAR2(32), "ATTR_TYPE" NUMBER(1,0), "MULTIVALUE" NUMBER(1,0), "ISUNIQUE" NUMBER(1,0), "ISRESIDENT" NUMBER(1,0), "ATTR_CLASS" NUMBER(3,0), "DATATYPE" NUMBER(1,0), "LENGTH" NUMBER(4,0), "SCALE" NUMBER(1,0), "EXPIRE_DAYS" NUMBER(6,0), "SERVICE_TYPE" VARCHAR2(32), "UNIT" VARCHAR2(32), "FIXEDFEE_FLAG" NUMBER(1,0) DEFAULT 0, "TABLE_NAME" VARCHAR2(32), "INC_APPSYSLIST" VARCHAR2(64), "EXC_APPSYSLIST" VARCHAR2(64), "ABM_RESOURCE_ID" NUMBER(10,0) DEFAULT 0, "ROUND_TYPE" CHAR(1) DEFAULT 'D', "ROUND_UNIT" NUMBER(10,0) DEFAULT 0, "BASE_UNIT" NUMBER(10,0) DEFAULT 0, "IS_RECORD_OVER_USAGE" CHAR(1) DEFAULT 'T', "ATTR_ADD_CODE_DEF" VARCHAR2(50), "VALID_CYCLE_COUNT" NUMBER(8,0) DEFAULT 0, "VALID_CYCLE_UNIT" NUMBER(1,0) DEFAULT 1, "CYCLE_ATTR_ID" NUMBER(4,0) DEFAULT 0, "NEED_NOTIFY_DETAIL" NUMBER(1,0) DEFAULT 0, "IS_BIND_PRODUCT_INST" NUMBER(1,0) DEFAULT 0, "BIND_PRODUCT_ELEMENT_CODE" VARCHAR2(60), "MERGE_TYPE" NUMBER(1,0) DEFAULT 0, "CARRYOVER_FLAG" NUMBER(1,0) DEFAULT 0, "SHARED_MODE" NUMBER(2,0) DEFAULT -1, "SHARED_MODE_SYNC_FLAG" NUMBER(1,0) DEFAULT 1, "ADDCODE_DEAL_TYPE" NUMBER(1,0) DEFAULT 0) ;

CREATE TABLE "ENTITY_CACHE_DEF" ("SCHEMA_ID" NUMBER(9,0), "ENTITY_ID" NUMBER(9,0), "ATTR_ID" NUMBER(8,0), "CACHE_MODE" NUMBER(1,0)) ;


