CREATE TABLE "SUBITEMLIST" ("UNIQUENO" NUMBER(6,0), "SEQUENCE" NUMBER(3,0), "SUBITEMSEQUENCE" NUMBER(3,0), "ITEMCODE" VARCHAR2(7), "TAGCODE" VARCHAR2(7), "ITEMQTY" CHAR(1) DEFAULT '1', "SELECTOR" CHAR(1), "VALID" CHAR(1)) ;

CREATE TABLE "SUBSCRIBER_MATCH" ("CHARGING_EVENT_ID" NUMBER(4,0), "MATCH_ATTR_CLASS" NUMBER(4,0), "PRECEDENCE" NUMBER(4,0)) ;

CREATE TABLE "SERVICE_REMIND_LIMIT_DEF" ("REMIND_ID" NUMBER(4,0), "PARAID" NUMBER(6,0), "REMIND_COMB_TYPE" VARCHAR2(10), "REMIND_COND" VARCHAR2(1024), "G_REMIND_COND" VARCHAR2(1024), "TEMPLATENO" VARCHAR2(512), "RTCC_TEMPLATENO" VARCHAR2(512), "AVAIL_TIME" DATE, "EXPIRE_TIME" DATE, "RECURRENT_USAGE_EXPR" VARCHAR2(500), "G_RECURRENT_USAGE_EXPR" VARCHAR2(500), "RECURRENT_UNIT" NUMBER(10,0) DEFAULT 0, "RECURRENT_OFFSET" NUMBER(10,0) DEFAULT 0, "SUB_REMIND_ID" NUMBER(8,0) DEFAULT 0, "G_TEMPLATENO" VARCHAR2(512), "G_RTCC_TEMPLATENO" VARCHAR2(512)) ;

CREATE TABLE "SERVICE_REMIND_USAGE_DEF" ("REMIND_ID" NUMBER(4,0), "USAGE_TYPE" NUMBER(1,0), "ATTRTYPE" NUMBER(2,0), "ATTRID" VARCHAR2(128), "FILTER_COND" VARCHAR2(256), "G_FILTER_COND" VARCHAR2(256), "USAGE_EVENT_ATTR_ID" NUMBER(4,0) DEFAULT 0, "ENTITY_ID" NUMBER(2,0) DEFAULT 1, "OFFSET_CYCLE_CNT" NUMBER(2,0) DEFAULT 0) ;

CREATE TABLE "SESSION_INDEX_DEF" ("REGION_ID" NUMBER(4,0), "MODULE_NAME" VARCHAR2(16) DEFAULT 'COMMON', "INDEX_TYPE" NUMBER(1,0), "ATTRID_PATH" VARCHAR2(125), "G_ATTRID_PATH" VARCHAR2(1024), "BUCKET_CNT" NUMBER(10,0), "CHAIN_CNT" NUMBER(10,0), "NODEID" NUMBER(4,0) DEFAULT -1) ;

CREATE TABLE "SESSION_MEM_DEF" ("REGION_ID" NUMBER(4,0), "MODULE_NAME" VARCHAR2(16) DEFAULT 'COMMON', "SHM_KEYID" NUMBER(10,0), "AREA_MATCH" VARCHAR2(128), "EVENT_ID" NUMBER(4,0), "EVENT_SIZE" NUMBER(8,0), "BUCKET_CNT" NUMBER(10,0), "CHAIN_CNT" NUMBER(10,0), "ACCESS_TYPE" NUMBER(1,0) DEFAULT 1, "SERVER_NAME_LIST" VARCHAR2(128), "NODEID" NUMBER(4,0) DEFAULT -1) ;

CREATE TABLE "SHM_ENTITY_ATTR_DEF" ("ENTITY_ID" NUMBER(4,0), "ATTR_ID" NUMBER(8,0), "ENTITY_EVENT_ID" NUMBER(9,0), "ATTR_NAME" NVARCHAR2(80), "IMDB_ENTITY_ID" NUMBER(9,0), "IMDB_ATTR_ID" NUMBER(4,0)) ;

CREATE TABLE "SHM_ENTITY_LOAD_DEF" ("SHM_ENTITY_ID" NUMBER(4,0), "LOAD_ORDER" NUMBER(9,0), "DATA_SOURCE_NAME" VARCHAR2(80), "DATA_QUERY_ID" NUMBER(9,0), "SERVER_LIST" VARCHAR2(128), "ATTR_TYPE" NUMBER(1,0)) ;

CREATE TABLE "SQL_DEF" ("DB_TYPE" VARCHAR2(10), "SQL_ID" VARCHAR2(128), "SQL_SCRIPT" VARCHAR2(4000), "NOTE" VARCHAR2(256)) ;

CREATE TABLE "SUBJECT_DEF" ("SUBJECTID" VARCHAR2(16), "SUBJECTNAME" VARCHAR2(64), "PERCENT_OF_REFUND" NUMBER(5,2), "CYCLES_OF_REFUND" NUMBER(4,0), "DRAW_ORDER" NUMBER(8,0), "OFFSET_SCOPE" VARCHAR2(1024), "AVAILABLE_CYCLE" NUMBER(10,0), "START_CYCLE" NUMBER(10,0), "IN_USE" NUMBER(1,0), "DRAW_AMT" NUMBER(14,0), "FLOWIN_TYPE" NUMBER(8,0), "SUBJECT_SIGN" VARCHAR2(8), "SUBJECT_TYPE" NUMBER(2,0) DEFAULT 1, "SUBJECTIDN" NUMBER(8,0), "MIN_DRAW_AMT" NUMBER(15,0) DEFAULT 0, "REF_TYPE" NUMBER(1,0) DEFAULT 0, "COMP_METHOD" NUMBER(1,0) DEFAULT 0, "BILLFEE_DRAW_AMT" NUMBER(14,0) DEFAULT 0, "BILLFEE_REF_TYPE" NUMBER(1,0) DEFAULT 0, "MAX_DRAW_AMT" NUMBER(15,0), "NOTE" VARCHAR2(200), "IS_CAL_SCORE" NUMBER(1,0) DEFAULT 0, "CYCLE_UNIT" NUMBER(1,0) DEFAULT 1, "IS_VIRTUAL_SUBJECT" NUMBER(1,0) DEFAULT 0, "WRTOFF_HIS_TYPE" NUMBER(2,0) DEFAULT 0, "EXLUDE_OFFSET_SCOPE" VARCHAR2(1024), "CANINVOICE" NUMBER(2,0) DEFAULT 0, "WRTOFFNEGATIVE" NUMBER(1,0) DEFAULT 0, "LIMITFORSUBSID" NUMBER(1,0) DEFAULT 1) ;

CREATE TABLE "TARIFF_ITEM" ("TARIFF_SCHEMA_ID" NUMBER(9,0), "APPLYTIME" DATE, "EXPIRETIME" DATE, "TARIFF_CRITERIA" VARCHAR2(256), "SUBTARIFF_TYPE" NUMBER(1,0), "TARIFF_ID" NUMBER(9,0), "RATIO" NUMBER(5,2), "RATETYPE" CHAR(1), "PARAM_STRING" VARCHAR2(128), "PRECEDENCE" NUMBER(4,0), "EXPR_ID" NUMBER(9,0), "G_PARAM" VARCHAR2(256), "IS_DYNAMIC" NUMBER(1,0) DEFAULT (0), "G_CRITERIA" VARCHAR2(512), "BILLCODE" VARCHAR2(32), "TARIFF_ITEM_SN" VARCHAR2(20) DEFAULT 0, "TARIFF_ITEM_NAME" VARCHAR2(64), "TEMPLATENO" VARCHAR2(32), "USAGE_KEY_INFO" VARCHAR2(500), "G_USAGE_KEY_INFO" VARCHAR2(500), "LEFT_EVAL_FLAG" NUMBER(1,0) DEFAULT 0, "FLAT_RATES_FLAG" NUMBER(2,0) DEFAULT 1) ;

CREATE SEQUENCE  "SEQ_TARIFF_SN"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 138751 CACHE 100 ORDER  CYCLE ;

CREATE TABLE "TARIFF_PLAN" ("TARIFF_PLAN_ID" NUMBER(6,0), "TARIFF_PLAN_NAME" VARCHAR2(128), "IS_RECURSIVE" NUMBER(1,0) DEFAULT 0, "PRECEDENCE" NUMBER(9,0), "PROCESS_BEFORE" NUMBER(4,0) DEFAULT 0, "PROCESS_AFTER" NUMBER(4,0) DEFAULT 0, "PLANTYPE" VARCHAR2(4), "NOTE" VARCHAR2(400), "PRECEDENCE_ACCDISC" NUMBER(4,0), "PRICEPLANTYPE" NUMBER(4,0), "REGION" NUMBER(5,0) DEFAULT 0, "HISTORY" VARCHAR2(2048), "MERGE_MODE" NUMBER(1,0) DEFAULT 1, "DYNAMIC_PRECEDENCE" VARCHAR2(200), "G_DYNAMIC_PRECEDENCE" VARCHAR2(400), "CATALOG_TYPE" VARCHAR2(10) DEFAULT '0', "SERVICE_FLAG" VARCHAR2(500), "G_SERVICE_FLAG" VARCHAR2(500), "SUB_DYNAMIC_PRECEDENCE" VARCHAR2(200), "G_SUB_DYNAMIC_PRECEDENCE" VARCHAR2(400), "PHASE_PRECEDENCE" NUMBER(4,0) DEFAULT 0, "TYPE_PRECEDENCE" NUMBER(4,0) DEFAULT 0, "CARRYOVER_ENTITYID" NUMBER(4,0), "CARRYOVER_ATTRID" NUMBER(8,0)) ;

CREATE TABLE "TARIFF_PLAN_REDU" ("TARIFF_PLAN_ID" NUMBER(6,0), "TARIFF_PLAN_NAME" VARCHAR2(128), "IS_RECURSIVE" NUMBER(1,0), "PRECEDENCE" NUMBER(9,0), "PROCESS_BEFORE" NUMBER(4,0), "PROCESS_AFTER" NUMBER(4,0), "PLANTYPE" VARCHAR2(4), "NOTE" VARCHAR2(400), "PRECEDENCE_ACCDISC" NUMBER(4,0), "STATUS" NUMBER(1,0)) ;

CREATE TABLE "TARIFF_REDU_AUDIT_LOG" ("LOGNUM" VARCHAR2(24), "OPERATOR" VARCHAR2(16), "LOGTIME" DATE, "TABLENAME" VARCHAR2(64), "MAINTAINTYPE" CHAR(1), "KEYVALUE" VARCHAR2(1024), "COLNAME" VARCHAR2(64), "OLDVALUE" VARCHAR2(1024), "NEWVALUE" VARCHAR2(1024), "AUDIT_STATUS" NUMBER(1,0) DEFAULT 0, "REASON" VARCHAR2(128), "AUDIT_TIME" DATE, "AUDIT_OPERATOR" VARCHAR2(20), "COL_DATATYPE" VARCHAR2(106), "CLIENTINFO" VARCHAR2(1024)) ;

