CREATE TABLE "FEEGROUP_ACCITEM_DEF" ("FEEGROUPID" VARCHAR2(32), "ITEMCODE" VARCHAR2(32), "STARTCYCLE" NUMBER(8,0), "ENDCYCLE" NUMBER(8,0), "PRECEDENCE" NUMBER(4,0), "INCLUDEFLAG" CHAR(1) DEFAULT 1) ;

CREATE TABLE "FEEGROUP_DEF" ("FEEGROUPID" VARCHAR2(30), "FEEGROUPNAME" VARCHAR2(64), "DRAWORDER" NUMBER(4,0) DEFAULT 9, "SERVICE_TYPE" VARCHAR2(32), "FEEGROUPIDN" NUMBER(8,0) DEFAULT 0) ;

CREATE TABLE "FILEDESCRIBE" ("PROCESSID" NUMBER(5,0), "FILEID" NUMBER(5,0), "FILENAME" VARCHAR2(100), "FILETYPE" NUMBER(2,0), "SOURPATH" VARCHAR2(80), "DESTPATH" VARCHAR2(80), "BACKPATH" VARCHAR2(80), "ERRORPATH" VARCHAR2(80), "QUEUENAME" VARCHAR2(80), "DBNAME" VARCHAR2(80), "MAXCAPACITY" NUMBER(7,0), "DAYFILECOUNT" NUMBER(4,0), "CREATETIME" VARCHAR2(4), "LOGDBNAME" VARCHAR2(30), "FILENAMESTYLE" VARCHAR2(30), "REDO_FILENO_LIST" VARCHAR2(20) DEFAULT null, "REDO_TABLE" VARCHAR2(32), "REDO_EVENT_ID" NUMBER(10,0), "REDO_WHERE_CLAUSE" VARCHAR2(128)) ;

CREATE TABLE "FILENAME" ("FILEID" NUMBER(5,0), "CONORDER" NUMBER(5,0), "CONTYPE" NUMBER(5,0), "CONTENT" VARCHAR2(20)) ;

CREATE TABLE "FILENAME_ITEM" ("MODULEID" NUMBER(8,0), "PERIODICTYPE" NUMBER(4,0), "PERIODICPARAM" VARCHAR2(64), "TIMEOFFSET" NUMBER(10,0), "TIMES" NUMBER(10,0), "GENFROM" NUMBER(10,0), "GENTO" NUMBER(10,0), "FILENAMEPROCID" NUMBER(10,0), "INITSEQ" NUMBER(10,0), "MAXSEQ" NUMBER(10,0), "BACKWARD" NUMBER(4,0), "TMPPATH" VARCHAR2(128), "DESTPATH" VARCHAR2(128), "EMPTYTYPE" NUMBER(4,0), "EVENTID" NUMBER(4,0)) ;

CREATE TABLE "FILERULE" ("FILEID" NUMBER(5,0), "RELATEORDER" NUMBER(3,0), "SOUREVENTTYPE" NUMBER(3,0), "DESTEVENTTYPE" NUMBER(3,0), "SCHEMAID" NUMBER(5,0), "PROCMETHOD" NUMBER(3,0), "PROCCOUNT" NUMBER(7,0), "PROCORDER" NUMBER(3,0), "NOTE" VARCHAR2(100)) ;

CREATE TABLE "FILESTRUCT" ("FILEID" NUMBER(5,0), "EVENTTYPE" NUMBER(2,0), "EVENTID" NUMBER(5,0), "INITCOUNT" NUMBER(5,0), "ADDCOUNT" NUMBER(5,0), "INITORDER" NUMBER(3,0), "NODE" VARCHAR2(100)) ;

CREATE TABLE "FINANCEITEM_DEF" ("ITEMCODE" VARCHAR2(32), "ITEMNAME" VARCHAR2(128), "DICTID" VARCHAR2(32), "STATUS" CHAR(1), "SORT" NUMBER(10,0)) ;


