CREATE TABLE "COMMODITY_DEF" ("COMMODITY_ID" VARCHAR2(30), "NAME" VARCHAR2(64), "TAX" NUMBER(5,0), "CODE" VARCHAR2(64)) ;

CREATE TABLE "CONST_DEF" ("CONST_ID" NUMBER(4,0), "CONST_NAME" VARCHAR2(64), "DATATYPE" NUMBER(1,0), "VALUE" VARCHAR2(64)) ;

CREATE TABLE "CREDIT_CALC_RULE" ("RULE_ID" NUMBER(5,0), "PRIORITY" NUMBER(6,0), "CONDITION" VARCHAR2(256), "G_CONDITION" VARCHAR2(256), "CREDIT_ENTITY_ID" NUMBER(5,0), "SCHEMA_ENTITY_ID" NUMBER(5,0), "DEST_CREDIT_LEVEL" VARCHAR2(128), "G_DEST_CREDIT_LEVEL" VARCHAR2(128), "CREDIT_VALUE" VARCHAR2(128), "G_CREDIT_VALUE" VARCHAR2(128)) ;

CREATE TABLE "CREDIT_CONTROL_SCHEMA" ("REGIONCODE" VARCHAR2(5), "SCHEMA_CODE" NUMBER(4,0), "CONTROL_METHOD" NUMBER(1,0), "CONTROL_VALUE" NUMBER(12,0), "SORT_ORDER" NUMBER(2,0), "CONTROL_CODE" VARCHAR2(16), "STEP_TYPE" NUMBER(1,0) DEFAULT 0, "DURATION_STEP" NUMBER(10,0) DEFAULT 0, "AMOUNT_STEP" NUMBER(10,0) DEFAULT 0, "CREDIT_CALC_TYPE" VARCHAR2(3) DEFAULT '000', "SCHEMA_ENTITY_ID" NUMBER(5,0) DEFAULT 3, "INTERVAL" NUMBER(10,0) DEFAULT 0, "SMS_ID" NUMBER(10,0) DEFAULT 0, "ACTION_COUNT" NUMBER(10,0) DEFAULT 0, "CTRL_VALUE_EXPR" VARCHAR2(256), "G_CTRL_VALUE_EXPR" VARCHAR2(256), "CREDIT_VALUE_EXPR" VARCHAR2(128), "G_CREDIT_VALUE_EXPR" VARCHAR2(128), "EX_NOTIFY_FLAG" VARCHAR2(2) DEFAULT '10', "CONDITION" VARCHAR2(128), "G_CONDITION" VARCHAR2(128)) ;

CREATE TABLE "CREDIT_CTRL_ALERT_DEF" ("TASK_NO" NUMBER(9,0), "MIN_DAY" NUMBER(2,0), "MAX_DAY" NUMBER(2,0), "MIN_TIME" VARCHAR2(6) DEFAULT '000000', "MAX_TIME" VARCHAR2(6) DEFAULT '235959', "WEEK_DAYS" VARCHAR2(7), "AUDIT_BATCHS" NUMBER(6,0) DEFAULT '10', "PRIORITY" NUMBER(4,0), "MAX_PERCENT" NUMBER(3,0) DEFAULT '100', "MAX_COUNT" NUMBER(8,0) DEFAULT 1, "PROCESS_FLAG" VARCHAR2(1), "IN_USE" NUMBER(1,0) DEFAULT 1) ;

CREATE TABLE "CREDIT_CTRL_DOMAIN_DEF" ("DOMAIN_ID" NUMBER(5,0), "DOMAIN_NAME" VARCHAR2(64), "DEFAULT_STATUS" VARCHAR2(64), "REAL_BALANCE_EXPR" VARCHAR2(64), "G_REAL_BALANCE_EXPR" VARCHAR2(64), "IMAGE_BALANCE_EXPR" VARCHAR2(64), "G_IMAGE_BALANCE_EXPR" VARCHAR2(64), "ADD_BALANCE_EXPR" VARCHAR2(64), "G_ADD_BALANCE_EXPR" VARCHAR2(64), "ADD_BALANCE_STATUS" VARCHAR2(64)) ;

CREATE TABLE "CREDIT_CTRL_RULE_DEF" ("RULE_ID" NUMBER(5,0), "PRIORITY" NUMBER(6,0), "DOMAIN_ID" NUMBER(5,0), "CONDITION" VARCHAR2(256), "G_CONDITION" VARCHAR2(256), "CREDIT_ENTITY_ID" NUMBER(5,0), "SCHEMA_ENTITY_ID" NUMBER(5,0), "DEST_CREDIT_LEVEL" VARCHAR2(64), "G_DEST_CREDIT_LEVEL" VARCHAR2(64), "CREDIT_VALUE" VARCHAR2(64), "G_CREDIT_VALUE" VARCHAR2(64)) ;

CREATE TABLE "CREDIT_CTRL_SCHEMA_DEF" ("REGIONCODE" VARCHAR2(5), "SCHEMA_ENTITY_ID" NUMBER(5,0) DEFAULT 3, "DOMAIN_ID" NUMBER(5,0), "SCHEMA_CODE" NUMBER(4,0), "CONTROL_METHOD" NUMBER(1,0), "SORT_ORDER" NUMBER(2,0), "CONDITION" VARCHAR2(128), "G_CONDITION" VARCHAR2(128), "CTRL_VALUE_EXPR" VARCHAR2(256), "G_CTRL_VALUE_EXPR" VARCHAR2(256), "CONTROL_CODE" VARCHAR2(16), "STEP_TYPE" NUMBER(1,0) DEFAULT 0, "DURATION_STEP" NUMBER(10,0) DEFAULT 0, "AMOUNT_STEP" NUMBER(10,0) DEFAULT 0, "INTERVAL" NUMBER(10,0) DEFAULT 0, "SMS_ID" NUMBER(10,0) DEFAULT 0, "ACTION_COUNT" NUMBER(10,0) DEFAULT 0, "CREDIT_VALUE_EXPR" VARCHAR2(128), "G_CREDIT_VALUE_EXPR" VARCHAR2(128)) ;

CREATE TABLE "CREDIT_CTRL_TASK_DEF" ("TASK_NO" NUMBER(9,0), "TASK_NAME" VARCHAR2(64), "CREDIT_EVENT_ID" NUMBER(6,0), "FLOW_ID" NUMBER(5,0), "PROCESS_ID" NUMBER(9,0), "PROCESS_ALL_DOMAIN" NUMBER(1,0) DEFAULT 1) ;

CREATE TABLE "CREDIT_CTRL_TASK_DOMAINS" ("TASK_NO" NUMBER(9,0), "DOMAIN_ID" NUMBER(4,0)) ;

CREATE TABLE "CREDITDETECT_ALERT_DEF" ("TASKNO" NUMBER(10,0), "MINDAY" NUMBER(2,0), "MAXDAY" NUMBER(2,0), "MINTIME" VARCHAR2(6) DEFAULT '000000', "MAXTIME" VARCHAR2(6) DEFAULT '235959', "WEEKDAYS" VARCHAR2(7), "AUDITBATCHS" NUMBER(6,0) DEFAULT '10', "MAXPERCENT" NUMBER(3,0) DEFAULT '100', "MAXCOUNT" NUMBER(8,0), "PRECEDENCE" NUMBER(4,0), "PROCESSFLAG" VARCHAR2(1), "INUSE" NUMBER(1,0) DEFAULT '1') ;

CREATE TABLE "CREDITDETECT_TASK_DEF" ("TASKNO" NUMBER(10,0), "TASKNAME" VARCHAR2(100), "CREDITEVENTID" NUMBER(6,0), "DOWNEVENTID" NUMBER(6,0), "NODEID" NUMBER(10,0), "LOGPATH" VARCHAR2(64)) ;

CREATE TABLE "CREDITDETECT_TASK_ITEM" ("TASKNO" NUMBER(10,0), "SEQ" NUMBER(10,0), "SUBTASKNAME" VARCHAR2(100), "SOURCETYPE" NUMBER(10,0), "MINACCTID" NUMBER(13,0), "MAXACCTID" NUMBER(13,0), "FLOWID" NUMBER(13,0), "PROCESSID" NUMBER(13,0), "SOURCENAME" VARCHAR2(64), "SOURCECOND" VARCHAR2(256), "PRECEDENCE" NUMBER(3,0) DEFAULT 0) ;

CREATE TABLE "CUST_SHELL" ("ID" VARCHAR2(50), "CONTENT" CLOB, "NOTE" VARCHAR2(100)) ;

CREATE TABLE "CUSTBILL_DEF" ("TEMPLATE_ID" NUMBER(10,0), "TEMPLATE_NAME" VARCHAR2(64), "INUSE" NUMBER(1,0), "OTHERPAYTYPE" NUMBER(1,0) DEFAULT 0, "OFFERTAX" NUMBER(1,0) DEFAULT 0) ;

CREATE TABLE "CUSTBILL_FORMAT_DATABIND" ("RULE_ID" NUMBER(5,0), "FORMAT_ID" VARCHAR2(32), "ENTITY_TYPE" NUMBER(1,0), "TRIGGER_TYPE" VARCHAR2(32)) ;

CREATE TABLE "CREDIT_CTRL_TASK_ITEM_DEF" ("TASK_NO" NUMBER(9,0), "SEQ" NUMBER(9,0), "PRIORITY" NUMBER(6,0) DEFAULT 0, "SUBTASK_NAME" VARCHAR2(128), "SOURCE_TYPE" VARCHAR2(1), "SERVER_NAME" VARCHAR2(20), "SOURCE_PARAM" VARCHAR2(256), "ACTION_TYPE" NUMBER(6,0) DEFAULT 1, "IS_DELETE" NUMBER(1,0) DEFAULT 1) ;


