CREATE TABLE "AM_EMERGENCY_DEF" ("REGION" NUMBER(5,0), "DBTYPE" NUMBER(2,0), "MODULE_NAME" VARCHAR2(20), "DATA_NODEID" NUMBER(5,0), "MEMO" VARCHAR2(64), "STATUS" NUMBER(1,0) DEFAULT 0, "STATUSDATE" DATE DEFAULT sysdate) ;

CREATE TABLE "AM_PROD_PRESENT" ("PRESENT_RULE_ID" NUMBER(12,0), "REGION" NUMBER(5,0), "PRODID" VARCHAR2(32), "PROD_TYPE" VARCHAR2(2) DEFAULT 'P', "EFF_DATE" DATE, "EXP_DATE" DATE, "PRICING_PLAN_ID" VARCHAR2(32)) ;

CREATE TABLE "AM_PROD_PRESENT_ITEM" ("PRESENT_RULE_ID" NUMBER(12,0), "REBATE_SCHEMA_ID" NUMBER(15,0), "PRIORITY" NUMBER(5,0), "INUSE" NUMBER(1,0) DEFAULT 1) ;

CREATE TABLE "AM_TAX_RATE_DEF" ("RATEDEFID" NUMBER(6,0), "ITEMCODE" VARCHAR2(32), "TAXRATE" NUMBER(5,0) DEFAULT 0, "EFFDATE" DATE, "EXPDATE" DATE, "INUSE" NUMBER(1,0), "UPDATETIME" DATE, "COMMODITY_ID" VARCHAR2(30)) ;

CREATE TABLE "AM_TAX_SPLIT_DEF" ("RULEID" NUMBER(6,0), "ITEMCODE" VARCHAR2(32), "PKGCODE" VARCHAR2(32), "SPLITTYPE" NUMBER(1,0), "SPLITVALUE" NUMBER(6,0), "SUBITEMCODE" VARCHAR2(32), "SPLITORDER" NUMBER(2,0), "EFFDATE" DATE, "EXPDATE" DATE, "INUSE" NUMBER(1,0), "UPDATETIME" DATE, "RULETYPE" NUMBER(1,0) DEFAULT 1, "REGION" NUMBER(5,0) DEFAULT 999) ;

CREATE TABLE "AM_TRADE_FREEUNIT_TYPE" ("FU_TYPE_ID" NUMBER(8,0), "FU_TYPE_NAME" VARCHAR2(64), "PRIORITY" NUMBER(8,0), "SERVICE_TYPE" VARCHAR2(32), "ATTR_TYPE" NUMBER(1,0), "BASE_UNIT" NUMBER(10,0), "TRADE_CTAGSET" VARCHAR2(20), "INST_PRIORITY" CHAR(1), "MERGE_TYPE" NUMBER(1,0), "EFF_DATE" DATE, "EXP_DATE" DATE, "CREATE_DATE" DATE, "UPDATE_DATE" DATE, "REMARK" VARCHAR2(200), "STATUS" CHAR(1), "STATUS_DATE" DATE) ;

CREATE TABLE "AMERCE_PLAN_DEF" ("AMERCE_PLANID" NUMBER(10,0), "AMERCE_PLANNAME" VARCHAR2(64), "EXCLUDED_SUBJECT" VARCHAR2(256), "IN_USE" NUMBER(1,0), "ROUND_TYPE" NUMBER(1,0), "MAXLATEFEE" NUMBER(8,0) DEFAULT 0, "CALC_LIMIT_TYPE" NUMBER(1,0) DEFAULT 1) ;

CREATE TABLE "AMERCE_RATE_DEF" ("AMERCE_PLANID" NUMBER(10,0), "ITEMTYPE" NUMBER(1,0), "CYCLE" NUMBER(10,0), "STARTDATE" DATE, "ENDDATE" DATE, "RATE_OF_AMERCE" NUMBER(5,0), "URGEDATE" DATE, "STOPDATE" DATE) ;

CREATE TABLE "APP_BUNDLED_DATANODE" ("APPTYPE" NUMBER(4,0), "NODEID" NUMBER(5,0), "DATA_NODEID" NUMBER(4,0)) ;

CREATE TABLE "APP_ROUTE_DEF" ("APPTYPE" NUMBER(4,0), "ROUTE_TYPE" NUMBER(2,0)) ;

CREATE TABLE "APP_TASK_DEF" ("APP_TASK_ID" VARCHAR2(60), "APP_TASK_NAME" VARCHAR2(500), "APP_NAME" VARCHAR2(60), "TASK_DESC" VARCHAR2(500), "PARENT_TASK" VARCHAR2(60)) ;

CREATE TABLE "APP_TASK_PARAM_DEF" ("APP_TASK_ID" VARCHAR2(60), "PARAM_NAME" VARCHAR2(60), "PARAM_VALUE" VARCHAR2(2000)) ;

CREATE TABLE "ASSEMBLE_ELEMENT_DEF" ("RULE_ID" VARCHAR2(30), "ELEMENT_SEQ" NUMBER(4,0), "ELEMENT_EXPR" VARCHAR2(500), "G_ELEMENT_EXPR" VARCHAR2(1000)) ;

CREATE TABLE "ASSEMBLE_PROCESS_DEF" ("RULE_ID" VARCHAR2(30), "PROC_SEQ" NUMBER(4,0), "RULE_COND" VARCHAR2(500), "G_RULE_COND" VARCHAR2(1000), "TEXT" VARCHAR2(1000), "SOUR_EVENT_ID" NUMBER(4,0), "DEST_EVENT_ID" NUMBER(4,0), "LOOP_EVENT_EXPR" VARCHAR2(300), "G_LOOP_EVENT_EXPR" VARCHAR2(600), "SUB_RULE_ID" VARCHAR2(30)) ;

CREATE TABLE "ASSEMBLE_TEXT_DEF" ("RULE_ID" VARCHAR2(30), "NAME" VARCHAR2(150), "SOUR_EVENT_ID" NUMBER(4,0), "DEST_EVENT_ID" NUMBER(4,0)) ;

CREATE TABLE "BASE_ATTR_DEF" ("ENTITY_ID" NUMBER(4,0), "ATTR_ID" NUMBER(8,0), "BASE_ATTR_TYPE" NUMBER(1,0), "BASE_ATTR_ID" NUMBER(4,0), "CHARGING_EVENT_ID" NUMBER(4,0), "CALL_USAGE_COND" VARCHAR2(256), "ROUND_UNIT" NUMBER(8,0), "ROUND_TYPE" NUMBER(1,0), "G_CALL_USAGE_COND" VARCHAR2(256), "SEQNO" NUMBER(14,0) DEFAULT 0, "CONVERT_UNIT" NUMBER(10,0) DEFAULT -1, "ATTR_ADD_CODE_VALUE" VARCHAR2(100), "G_ATTR_ADD_CODE_VALUE" VARCHAR2(200)) ;

CREATE TABLE "BILL_DISC" ("TARIFFPLAN_ID" NUMBER(8,0), "REGION" VARCHAR2(200), "STARTDATE" DATE, "ENDDATE" DATE) ;

CREATE TABLE "BILLDISC_DEF" ("TARIFFPLAN_ID" NUMBER(8,0), "PLANITEM_ID" NUMBER(8,0), "DISC_ENTITY" NUMBER(1,0), "DISC_COND" VARCHAR2(512), "G_DISC_COND" VARCHAR2(768), "DISC_TYPE" NUMBER(2,0), "REFITEM_TYPE" NUMBER(1,0), "FREEREFITEM_TYPE" NUMBER(1,0), "REFITEM_CODE" VARCHAR2(32), "REFITEM_CYCLES" NUMBER(2,0), "REFITEM_CYCLE_OFFSET" NUMBER(4,0), "REFVALUE_CALC_TYPE" NUMBER(1,0), "REFVALUE_UNIT" NUMBER(2,0), "DISC_OBJECT_TYPE" NUMBER(1,0), "DISC_ITEM_CODE" VARCHAR2(256), "START_CYCLE_OFFSET" NUMBER(4,0), "VALID_CYCLE_TYPE" NUMBER(1,0), "VALID_CYCLES" NUMBER(4,0), "INUSE" NUMBER(1,0), "TARIFFPLAN_TYPE" NUMBER(4,0), "DISC_ITEM_TYPE" NUMBER(1,0) DEFAULT 1, "FREEREFITEM_MIN_USAGE" NUMBER(14,0), "NOTE" VARCHAR2(255), "ISDISCTSPEC" VARCHAR2(1) DEFAULT '0', "SPECDISCT_EXPR" VARCHAR2(512) DEFAULT ' ', "G_SPECDISCT_EXPR" VARCHAR2(512), "CONVERT_TYPE" NUMBER(1,0) DEFAULT 0, "REF_ENTITY_TYPE" NUMBER(2,0) DEFAULT 0, "DISC_SOURCE" VARCHAR2(64), "G_DISC_SOURCE" VARCHAR2(64), "DISC_SOURCE_FACTOR" NUMBER(8,0) DEFAULT 1, "DISC_ITEM_EXPR_ID" NUMBER(4,0), "FORCE_OUTPUT_EVENT" NUMBER(1,0) DEFAULT 0, "DISC_SOURCE_TYPE" NUMBER(1,0) DEFAULT 0) ;

CREATE TABLE "BILLING_CHECK_DEF" ("EVENTID" NUMBER(6,0), "ATTRID" NUMBER(6,0), "ATTRTYPE" NUMBER(3,0), "NOTES" VARCHAR2(16)) ;


