CREATE TABLE "EVENT_TARIFF_ITEM" ("PLAN_ID" NUMBER(6,0), "ITEM_VALUE" VARCHAR2(128), "TARIFF_PLAN_ID" NUMBER(6,0), "APPLYTIME" DATE, "EXPIRETIME" DATE, "NOTE" VARCHAR2(400)) ;

CREATE TABLE "EVENT_TARIFF_PLAN" ("PLAN_ID" NUMBER(6,0), "PLAN_NAME" VARCHAR2(128), "EVENT_ID" NUMBER(4,0), "COND" VARCHAR2(512), "G_COND" VARCHAR2(1024), "ITEM_EXPR" VARCHAR2(256), "G_ITEM_EXPR" VARCHAR2(1024), "MATCH_ORDER" NUMBER(1,0), "MATCH_TYPE" NUMBER(1,0), "APPLY_METHOD" NUMBER(1,0), "NOTE" VARCHAR2(400)) ;

CREATE TABLE "EVENT_UNDUP_DEF" ("UNDUP_ID" NUMBER(4,0), "UNDUP_NAME" VARCHAR2(32), "EVENT_ID" NUMBER(4,0), "KEY_TABLE" VARCHAR2(64), "DUPEVENT_TABLE" VARCHAR2(64), "UNDUP_CON" VARCHAR2(512), "G_UNDUP_COND" VARCHAR2(800), "UNDUP_COND" VARCHAR2(512)) ;

CREATE TABLE "EXPR_MAPPING_LIST" ("RULE_ID" NUMBER(5,0), "DEST_ATTR_ID" VARCHAR2(10), "EXPR_COND" VARCHAR2(512), "EXPR" VARCHAR2(256), "EXPR_TYPE" NUMBER(1,0), "G_DEST_ATTR" VARCHAR2(64), "G_EXPR_COND" VARCHAR2(768), "G_EXPR" VARCHAR2(320), "SEQNO" NUMBER(6,0) DEFAULT 0, "NOTE" VARCHAR2(256), "PROCESS_SCHEMA_ID" NUMBER(5,0)) ;

CREATE TABLE "EXPR_MAPPING_RULE" ("RULE_ID" NUMBER(5,0), "RULE_NAME" VARCHAR2(64), "SOUR_EVENT_ID" NUMBER(5,0), "DEST_EVENT_ID" NUMBER(5,0)) ;

CREATE TABLE "EXTRACTIVE" ("UNIQUENO" NUMBER(6,0), "EXTRACTTYPE" CHAR(1), "SEQUENCE" NUMBER(3,0) DEFAULT 0, "EXTRACTSEQUENCE" NUMBER(3,0), "STARTBYTE" NUMBER(5,0), "STARTBIT" NUMBER(3,0) DEFAULT 0, "QUATITY" NUMBER(5,0), "UNIT" CHAR(1), "OPERATE" CHAR(1)) ;

