CREATE TABLE "PRIVILEGE_USAGE_DEF" ("HREGION" CHAR(3), "BILLINGCODE" VARCHAR2(8), "ITEMNAME" VARCHAR2(60), "FREEVOLUME" NUMBER(15,2), "ATTR_ID" NUMBER(5,0), "FREETYPE" NUMBER(4,0), "STARTCYCLE" NUMBER(10,0) DEFAULT 0, "ENDCYCLE" NUMBER(10,0) DEFAULT 88888888, "ENTITY_ID" NUMBER(4,0) DEFAULT 1, "SHARE_ENTITY_ID" NUMBER(4,0) DEFAULT 0, "SHARE_ATTRID" NUMBER(4,0) DEFAULT 0, "LIMIT_ATTRID" NUMBER(4,0) DEFAULT 0, "LIMIT_ENTITY" NUMBER(4,0) DEFAULT 0, "LIMIT_TYPE" NUMBER(4,0) DEFAULT 0, "HALFTYPE" NUMBER(1,0)) ;

CREATE TABLE "PRODUCT_TEMPLATE_BUSINESS_DEF" ("ID" NUMBER(4,0), "SEQUENCE" NUMBER(4,0), "BUSINESS_COND" VARCHAR2(200), "BUSINESS" VARCHAR2(60), "BUSINESS_KEY" VARCHAR2(200), "NOTE" VARCHAR2(200)) ;

CREATE TABLE "PROCDESCRIBE" ("PROCESSID" NUMBER(5,0), "OPERATION" NUMBER(2,0), "STATUS" NUMBER(2,0), "NOTE" VARCHAR2(100), "FILELIST_READ_MODE" NUMBER(1,0) DEFAULT 0, "SERVER_NAME" VARCHAR2(50)) ;

CREATE TABLE "PROCESS_FLOW" ("PROCESS_STEP_ID" NUMBER(5,0), "PROCESS_STEP_NAME" VARCHAR2(50), "PROCESS_ORDER" NUMBER(4,0), "RULE_COND" VARCHAR2(256), "IF_RULE_TYPE" NUMBER(1,0), "IF_RULE_ID" NUMBER(5,0), "ELSE_RULE_TYPE" NUMBER(1,0), "ELSE_RULE_ID" NUMBER(5,0), "APPLYTIME" DATE, "EXPIRETIME" DATE, "SEQUENCENO" NUMBER(5,0), "G_RULE_COND" VARCHAR2(512), "SOUR_EVENT_ID" NUMBER(5,0), "DEST_EVENT_ID" NUMBER(5,0), "IF_RULE_NAME" VARCHAR2(100), "ELSE_RULE_NAME" VARCHAR2(100)) ;

CREATE TABLE "PROCESS_SCHEMA" ("PROC_SCHEMA_ID" NUMBER(5,0), "PROC_SCHEMA_NAME" VARCHAR2(64)) ;

CREATE TABLE "PROCESSED_EVENT" ("PROC_SCHEMA_ID" NUMBER(5,0), "SOURCE_EVENT_ID" NUMBER(4,0), "DEST_EVENT_ID" NUMBER(4,0), "START_STEP_ID" NUMBER(5,0), "PROCESS_COND" VARCHAR2(512), "G_PROCESS_COND" VARCHAR2(512), "PREPROCESS_NAME" VARCHAR2(50), "PROCESS_ORDER" NUMBER(4,0) DEFAULT 0) ;


