CREATE TABLE "ENTITY_CACHE_SCHEMA" ("SCHEMA_ID" NUMBER(9,0), "SCHEMA_NAME" NVARCHAR2(80)) ;

CREATE TABLE "ENTITY_DEF" ("ENTITY_ID" NUMBER(9,0), "ENTITY_TABLE" VARCHAR2(30), "ENTITY_NAME" VARCHAR2(80), "ENTITY_EVENT_ID" NUMBER(9,0), "HAS_KEY" CHAR(1), "DEFAULT_QUERY_INSTANCE_ID" NUMBER(9,0), "SCAN_QUERY_ID" NUMBER(9,0), "INSERT_SQL" VARCHAR2(4000), "UPDATE_SQL" VARCHAR2(4000), "DELETE_SQL" VARCHAR2(4000), "ATTR_EVENT_ID" NUMBER(9,0), "DBTYPE" NUMBER(2,0), "MODULE_NAME" VARCHAR2(20), "AUDIT_ENTITY_TYPE" VARCHAR2(20), "AUDIT_KEY_ID" VARCHAR2(20), "UPDATE_CHECK_SQL" VARCHAR2(4000)) ;

CREATE TABLE "ENTITY_DEPENDENCY_DEF" ("ENTITY_ID" NUMBER(9,0), "DEPENDENT_ENTITY_ID" NUMBER(9,0)) ;

CREATE TABLE "ENTITY_INDEX_DEF" ("ENTITY_ID" NUMBER(4,0), "INDEX_ID" NUMBER(4,0), "INDEX_NAME" VARCHAR2(32), "ATTR_ID" NUMBER(8,0), "INDEX_TYPE" NUMBER(1,0) DEFAULT 1) ;

CREATE TABLE "ENTITY_MEM_REGION" ("REGION_ID" NUMBER(4,0), "REGION_NAME" VARCHAR2(32), "SHM_KEYID" NUMBER(10,0), "QUEUE_NAME" VARCHAR2(32), "NODE_ID" NUMBER(2,0), "AREA_COUNT" NUMBER(2,0), "AREA_ID" VARCHAR2(64), "PORT" NUMBER(8,0)) ;

CREATE TABLE "ENTITY_QUERY_DEF" ("ENTITY_ID" NUMBER(9,0), "QUERY_NAME" VARCHAR2(160), "DATA_QUERY_ID" NUMBER(9,0)) ;

CREATE TABLE "ENTITY_STORE_DEF" ("RULE_ID" NUMBER(9,0), "ENTITY_ID" NUMBER(9,0), "ATTR_ID" NUMBER(8,0), "RULE_TYPE" VARCHAR2(30), "RULE_PARAM" VARCHAR2(200), "RULE_PRIORITY" NUMBER(9,0), "STORE_TYPE" VARCHAR2(30), "IS_STORE" CHAR(1)) ;

CREATE TABLE "EVENT_ATTR_DATATYPE_DEF" ("EVENT_ID" NUMBER(4,0), "ATTR_ID" NUMBER(4,0), "MINVERSION" NUMBER(4,0) DEFAULT 1, "MAXVERSION" NUMBER(4,0) DEFAULT 0, "DATATYPE" NUMBER(5,0), "NOTE" VARCHAR2(32)) ;

CREATE TABLE "EVENT_ATTR_DEF" ("EVENT_ID" NUMBER(4,0), "ATTR_ID" NUMBER(4,0) DEFAULT -1, "ATTR_NAME" VARCHAR2(30), "DATATYPE" NUMBER(3,0), "ATTR_CLASS" NUMBER(3,0), "NULL_OK" NUMBER(1,0), "DEFAULT_VALUE" VARCHAR2(50), "AMBIGUOUS_VALUE" VARCHAR2(50), "ISUNIQUE" NUMBER(1,0), "POSITION" NUMBER(5,0), "LENGTH" NUMBER(5,0), "SCALE" NUMBER(1,0), "ALIGN_STYLE" NUMBER(1,0), "PADDED_CHAR" VARCHAR2(1), "FIELD_NAME" VARCHAR2(30), "FEE_ID" NUMBER(3,0), "VERSION" NUMBER(4,0), "DISPLAYSEQUENCE" NUMBER(4,0) DEFAULT 0, "SUB_EVENT_ID" NUMBER(4,0) DEFAULT 0, "ATTR_DESC" VARCHAR2(128), "OUT_SEQUENCE" NUMBER(4,0) DEFAULT 0) ;

CREATE TABLE "EVENT_FLOW_DEF" ("MODULE_ID" NUMBER(4,0), "FLOW_ID" NUMBER(4,0), "FLOW_NAME" VARCHAR2(64), "FLOW_COND" VARCHAR2(512), "FLOW_TYPE" NUMBER(1,0), "STORE_TYPE" CHAR(1), "STORE_NAME" VARCHAR2(100), "PRECEDENCE" NUMBER(4,0), "APPLY_TIME" DATE, "EXPIRE_TIME" DATE, "G_FLOW_COND" VARCHAR2(512), "EVENT_ID" NUMBER(4,0), "LOG_TYPE" CHAR(1) DEFAULT 'D', "NAME_MODE" CHAR(1) DEFAULT 'N', "EVENT_FLAG" VARCHAR2(5) DEFAULT ' ', "NEXT_SECTION" VARCHAR2(32), "STORE_PRIORITY" NUMBER(2,0) DEFAULT 50, "APPTYPE" NUMBER(4,0), "CLASSID" NUMBER(3,0), "PROC_SEGMENT" NUMBER(2,0) DEFAULT 0, "NOSET_APPROUTEID" NUMBER(1,0) DEFAULT 0) ;

CREATE TABLE "EVENT_FLOW_MODULE" ("MODULE_ID" NUMBER(4,0), "MODULE_NAME" VARCHAR2(40), "MODULE_NOTE" VARCHAR2(30), "SOURCE_FILE_FLAG" NUMBER(1,0) DEFAULT 0, "FLOW_SECTION" VARCHAR2(32)) ;

CREATE TABLE "EVENT_KEY_DEF" ("UNDUP_ID" NUMBER(4,0), "SEQUENCENO" NUMBER(4,0), "ATTR_ID" NUMBER(4,0), "STARTPOS" NUMBER(4,0), "LEN" NUMBER(4,0)) ;

CREATE TABLE "EVENT_MATCH_COND" ("EVENT_MATCH_ID" NUMBER(4,0), "TARGET_ATTR_ID" NUMBER(4,0), "MATCH_EXPRESSION" VARCHAR2(500), "SEQUENCE_NO" NUMBER(4,0)) ;

CREATE TABLE "EVENT_MATCH_DEF" ("EVENT_MATCH_ID" NUMBER(4,0), "SRC_EVENT_ID" NUMBER(4,0), "SRC_TABLE_FROM" VARCHAR2(64), "SRC_TABLE_TO" VARCHAR2(64), "TARGET_EVENT_ID" NUMBER(4,0), "TARGET_TABLE_FROM" VARCHAR2(64), "TARGET_TABLE_TO" VARCHAR2(64)) ;

CREATE TABLE "EVENT_RTCC_DEF" ("EVENTID" NUMBER(4,0), "PRECEDENCE" NUMBER(4,0), "MATCHCOND" VARCHAR2(256), "EVENTTYPE" NUMBER(2,0), "SLICETYPE" NUMBER(2,0), "SLICEVALUE" NUMBER(8,0), "SLICEMINVALUE" NUMBER(8,0), "SLICEATTRID" NUMBER(4,0), "RATESWITCHTIME" VARCHAR2(64), "BALANCETHRESHOLD" NUMBER(12,2), "UPDATETIMER" NUMBER(8,0), "FCIENABLE" NUMBER(1,0), "G_MATCHCOND" VARCHAR2(512), "OVERDRAFTSUM" NUMBER(8,0) DEFAULT 0, "ISSPLIT" NUMBER(2,0) DEFAULT 0, "SPLITCOND" VARCHAR2(256), "G_SPLITCOND" NVARCHAR2(512), "ATTR_LIST" VARCHAR2(64), "G_ATTR_LIST" VARCHAR2(512), "AUTH_CALC_TYPE" NUMBER(1,0) DEFAULT 0, "PARAM_PROC_SCHEMA_ID" NUMBER(5,0) DEFAULT 0) ;

CREATE TABLE "EVENT_STORE_DEF" ("EVENT_ID" NUMBER(4,0), "TABLE_NAME" VARCHAR2(32), "CYCLE_FLAG" NUMBER(1,0), "TABLE_TYPE" VARCHAR2(1) DEFAULT 0, "TABLE_CHINESENAME" VARCHAR2(32), "EVENT_TYPE" VARCHAR2(5), "REGION" NUMBER(1,0) DEFAULT 0) ;






