git add    abs.result
git add    abs.result.reject
git add    all_server_table_stat.result
git add    alter_varchar_length_extra.result
git add    alter_varchar_length_index.result
git add    alter_varchar_length_normal.result
git add    alter_varchar_length_primary_key.result
git add    alter_varchar_length_storing.result
git add    aproject_account.result
git add    binary_protocol.result.reject
git add    bool.result.reject
git add    bug200820.result.my
git add    bug5825976_create_drop_table_index_dilang.result
git add    bug5910265_update_orderby_limit_dilang.result
git add    bug6090045_query_range_index_dilang.result
git add    bug_104532.result
git add    build_in_func_test.result.reject
git add    compressor.result
git add    compressor.result.reject
git add    conv.result
git add    create_index_in_table.reject
git add    create_index_in_table.result
git add    create_index_in_table.result.reject
git add    create_index_in_table4.result.reject
git add    create_index_in_table_olap.result
git add    create_index_in_table_other_option.result
git add    create_index_in_table_select_get.result
git add    create_index_in_table_select_scan.result
git add    create_table_with_index.result
git add    ddlrollback.result
git add    decimal_2m_bug5223363.result.reject
git add    decode.result
git add    decode_col_convert.result
git add    decode_extra.result
git add    decode_extra_jdbc.result
git add    decode_null.result
git add    decode_ps.result
git add    decode_ps_return_type.result
git add    decode_ps_tbl.result
git add    decode_return_type.result
git add    default_value_test.reject
git add    default_value_test.result.reject
git add    distinct.result
git add    driver5114_bug.reject
git add    expire_bug5328455.result
git add    expire_index_trxdel.result
git add    expire_trx.result
git add    expire_trx2.result
git add    expire_trx_drop_tbl.result
git add    expire_trx_modifydata.result
git add    expire_trx_nop.result
git add    expire_trx_replace.result
git add    expire_trx_replace2.result
git add    expire_trx_update.result
git add    expire_unique_index_trxdel.result
git add    expr_nseq.result
git add    forbid_ddl.result
git add    func_decode.result
git add    func_group_5.result.my
git add    func_like.reject
git add    func_like_index.reject
git add    func_like_index.result
git add    func_sign.result
git add    grant.result
git add    hex_ip_java.result
git add    idx_unique_datatype_convert.result
git add    idx_unique_many_idx_one_ins.result
git add    idx_unique_replace.result
git add    in_typeconvert_decimal.result
git add    index_31_unique_ps.result
git add    index_51_orderby_delete.result
git add    index_51_orderby_select.result
git add    index_51_orderby_unique.result
git add    index_51_orderby_update.result
git add    index_orderby_select_unique_idx.result
git add    largetimeout.result
git add    like_goes_index_dilang.result
git add    like_goes_index_misc_dilang.reject
git add    like_goes_index_misc_dilang.result
git add    limitnegative.result
git add    many_number_pk.result
git add    many_number_pk_decimal.result
git add    many_number_pk_large_than_58.result
git add    many_number_pk_timestamp.result
git add    many_number_pk_varchar.result
git add    many_table_join.result
git add    multiget_2M_size_bug5361920.result
git add    neg.result
git add    nested_loop_join_cache_joinon.result
git add    nested_loop_join_idx_joinon.result
git add    nested_loop_join_idx_joinon_where.result
git add    nested_loop_join_idx_usenl_joinon.result
git add    nested_loop_join_idx_usenl_joinon_where.result
git add    nested_loop_join_joinon.result
git add    nested_loop_join_joinon_where.result
git add    nested_loop_join_prepare_joinon.result
git add    nested_loop_join_prepare_joinon_where.result
git add    nested_loop_join_right_null_joinon.result
git add    nested_loop_join_right_null_joinon_where.result
git add    no1ddl.result
git add    one_out_for_other_in.result
git add    parallel_create_table.result
git add    parallel_insert.result
git add    parallel_insert_rollback.result
git add    parallel_insert_uni_idx.result
git add    parallel_insert_uni_idx_rollback.result
git add    parallel_update.result
git add    parallel_update_rollback.result
git add    parawhen_manytimes_outwaitlock.result
git add    parawhen_manytimes_waitlock.result
git add    pk_num_boundary.result
git add    prejoin_update_basic.result
git add    ps_order_by.result
git add    rename_table.result
git add    result_column_type.result
git add    safe_null.result
git add    safe_null_test.result
git add    schema_mem_recycle.result
git add    sel_in_and_or.reject
git add    sel_in_and_or.result
git add    selbug.result
git add    set.reject
git add    sfu_norow_alias.result
git add    sfu_norow_basic.result
git add    sfu_norow_basic_idx.result
git add    sfu_norow_basic_uni_idx.result
git add    sfu_norow_complex.result
git add    sfu_norow_compound.result
git add    sfu_norow_dml.result
git add    sfu_norow_null.result
git add    sfu_norow_one_select.result
git add    sfu_norow_one_select_idx.result
git add    sfu_norow_one_select_uni_idx.result
git add    sfu_norow_ps.result
git add    sfu_norow_row_join.result
git add    sfu_norow_type.result
git add    sql_audit.result
git add    sql_audit_c_ps.result
git add    sql_filter.result
git add    tablenamelenth.result
git add    test.reject
git add    test.result
git add    test.sh
git add    test_func_return_type.result
git add    testlimit.reject
git add    testlimit.result
git add    testlimit_index.result
git add    timestamp.reject
git add    trx_cons_dirty_read_wirte_test.result
git add    trx_cons_dirty_read_wirte_test_idx.result
git add    trx_cons_dirty_read_wirte_test_unique.result
git add    trx_cons_for_join_alter.result
git add    trx_cons_for_join_alter_unique.result
git add    trx_cons_for_update.result
git add    trx_expire_alter_drop_add_col.result
git add    trx_expire_alter_drop_add_col_idx.result
git add    trx_expire_idx_unique_merge_step.result
git add    trx_expire_index_ps_1.result
git add    trx_expire_index_ps_2.result
git add    trx_expire_more_oper.result
git add    trx_expire_step_merge_num.result
git add    trx_select_for_update2.result
git add    trx_timeout_bug.result
git add    trx_write_para.result
git add    tsc.result
git add    two_order_by.result
git add    type_numeric_pri_idx_modify.result
git add    type_numeric_pri_index.result
git add    type_numeric_pri_index2.result
git add    unique_numeric_primary.result
git add    update_column_use_other.result
git add    update_delete_compund.result
git add    update_delete_compund_idx.result
git add    update_delete_compund_uni.result
git add    update_delete_limit_index.result
git add    update_delete_limit_merge.result
git add    update_delete_limit_merge_alltype.result
git add    update_delete_limit_merge_idx.result
git add    update_delete_limit_merge_idx_part.result
git add    update_delete_limit_merge_unique_idx.result
git add    update_delete_limit_merge_unique_idx_part.result
git add    update_delete_limit_part.result
git add    update_delete_limit_ps.result
git add    update_delete_limit_unique_key.result
git add    update_delete_many_data.result
git add    update_delete_orderby_limit.result
git add    update_delete_orderby_limit_idx.result
git add    update_delete_orderby_limit_unique.result
git add    update_rowkey_and_other_col_expr.result
git add    write_consistency_byjiuman.result
git add    write_consistency_index.result
git add    write_consistency_unique_index_replace.result
git add    write_consistency_unique_index_update.result
git add    za_zhuanyistring.result
git add    zaddlmajor_gt64times.result
git add    zaddlmajor_gt64times_expire_trx.result
