CREATE TABLE "IM_PR_BILLCLASS" 
("BILLCLASS" NUMBER(11,0), 
"BILLTYPE" NUMBER(3,0), 
"CLASSNAME" VARCHAR2(64), 
"PRICE" NUMBER(14,0), 
"BILLLENGTH" NUMBER(3,0), 
"MEMO" VARCHAR2(255), 
"CITYID" VARCHAR2(14)
);
 
CREATE TABLE "BASE_CHG_REQ" 
("REQID" NUMBER(11,0), 
"TABNAME" VARCHAR2(32), 
"OPRTYPE" VARCHAR2(2), 
"MAINKEYS" VARCHAR2(255), 
"OLDVALUE" VARCHAR2(255), 
"NEWVALUE" VARCHAR2(255), 
"OPRTIME" DATE, 
"CHGGZ" NUMBER(2,0), 
"CHGDG" NUMBER(2,0)
);

CREATE SEQUENCE  "CHG_REQ_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 108000083 CACHE 20000 NOORDER  NOCYCLE ;


CREATE TABLE "IM_PR_BILLSECT" 
("BILLSECT" NUMBER(11,0), 
"BEGBILLNO" VARCHAR2(32), 
"ENDBILLNO" VARCHAR2(32), 
"BILLTYPE" NUMBER(3,0), 
"CITYID" VARCHAR2(14)
);

CREATE TABLE "IM_PR_COM" 
("COMID" NUMBER(14,0), 
"COMPRICE" NUMBER(14,0), 
"COMCLASSID" NUMBER(6,0), 
"COMTYPE" NUMBER(6,0), 
"COMFREEZE" DATE, 
"COMKEEP" NUMBER(6,0), 
"COMVALID" DATE, 
"COMNAME" VARCHAR2(128), 
"COMSOURCE" VARCHAR2(30), 
"COLORDES" VARCHAR2(40), 
"ACCESSORY" VARCHAR2(40), 
"PRESENTDES" VARCHAR2(40), 
"ACTIVE" NUMBER(3,0), 
"COMLENGTH" NUMBER(3,0), 
"ITEM" VARCHAR2(20), 
"CITYID" VARCHAR2(14), 
"COMCODE" VARCHAR2(40), 
"COMSTATE" NUMBER(6,0) DEFAULT 1
);

CREATE TABLE "IM_PR_IMSISECT" 
("IMSISECTID" NUMBER(8,0), 
"BEGINIMSINO" VARCHAR2(15), 
"ENDIMSINO" VARCHAR2(15), 
"INTIME" DATE, 
"STARTTIME" DATE, 
"IMSISECTSTATE" NUMBER(3,0), 
"NOGROUPID" NUMBER(8,0), 
"BOSSAREA" VARCHAR2(14)
);

CREATE TABLE "IM_RE_NOFEETPL" 
("TPLID" NUMBER(8,0), 
"TPLNAME" VARCHAR2(20), 
"DEFAULTFEE" NUMBER(14,0), 
"VALID" NUMBER(3,0), 
"WAYID" VARCHAR2(18) DEFAULT '-1'
);

CREATE TABLE "IM_RE_NOFEETPLDTL" 
("TPLID" NUMBER(8,0), 
"NOSTR" VARCHAR2(15), 
"STRTYPE" NUMBER(3,0), 
"SELNOFEE" NUMBER(14,0)
);

CREATE TABLE "IM_PR_NOGROUP" 
("NOGROUPID" NUMBER(8,0), 
"NOGROUPNAME" VARCHAR2(32) DEFAULT '-1', 
"CITYCOMPID" VARCHAR2(14), 
"NETCELLID" NUMBER(8,0), 
"BACKCELLID" NUMBER(8,0), 
"NOGROUPSTATE" NUMBER(3,0)
);

CREATE TABLE "IM_PR_NOSECT" 
("NOSECTID" NUMBER(8,0) DEFAULT -1, 
"STARTTIME" DATE, 
"INTIME" DATE, 
"BEGINNO" VARCHAR2(12), 
"ENDNO" VARCHAR2(12), 
"NOSECTSTATE" NUMBER(3,0), 
"IMSISECTID" NUMBER(8,0) DEFAULT 0, 
"NOGROUPID" NUMBER(8,0), 
"SCPID" NUMBER(8,0), 
"BOSSAREA" VARCHAR2(14)
);

   