
create sequence CAS.CPL_ATR_NUM_SEQ
minvalue 1
maxvalue 99999999
start with 6557206
increment by 1
nocache
cycle;


create sequence CAS.SEQ_SYS_LOG
minvalue 1
maxvalue 9999999
start with 3818148
increment by 1
cache 20
cycle;





create table CAS.B
(
  terr_cd VARCHAR2(10),
  app_num NUMBER
)
;
create table CAS.TAPP_MENUS
(
  menu_cd         VARCHAR2(20) not null,
  menu_label      VARCHAR2(60) not null,
  menu_label_eng  VARCHAR2(60),
  menu_typ        VARCHAR2(1) not null,
  menu_icon       VARCHAR2(20),
  parent_menu_cd  VARCHAR2(20),
  parent_menu_typ VARCHAR2(1),
  menu_desc       VARCHAR2(100),
  menu_desc_eng   VARCHAR2(100),
  fcn_nm          VARCHAR2(40),
  fcn_typ         VARCHAR2(10),
  app_cd          VARCHAR2(6) not null,
  menu_owner      VARCHAR2(200),
  private_ind     VARCHAR2(1),
  rlse_dt         DATE,
  privilege_ind   VARCHAR2(1) default 'N',
  special_ind     VARCHAR2(1) default 'N'
)
;
create table CAS.TAP_APPLICATIONS
(
  terr_cd VARCHAR2(10) not null,
  pol_num VARCHAR2(10),
  app_num NUMBER
)
;
create table CAS.TCLIENT_BANK_ACCOUNTS
(
  cli_num              VARCHAR2(10) not null,
  bank_acct_typ        NUMBER(4) not null,
  bank_cd              VARCHAR2(3) not null,
  bank_acct_nm         VARCHAR2(40) not null,
  bank_acct_num        VARCHAR2(50) not null,
  id_num               VARCHAR2(20) not null,
  id_typ               VARCHAR2(1) not null,
  bank_sv_kd           VARCHAR2(1),
  acct_eff_dt          DATE,
  id_iss_dt            DATE,
  id_iss_plc           VARCHAR2(100),
  card_num             VARCHAR2(20),
  own_dob              DATE,
  acct_id_typ          VARCHAR2(1),
  bank_branch          VARCHAR2(50),
  open_acct_terr       VARCHAR2(50),
  bank_acct_country_cd VARCHAR2(3),
  open_acct_prov       VARCHAR2(10),
  open_acct_city       VARCHAR2(10)
)
;
create table CAS.TCLIENT_POLICY_LINKS
(
  pol_num            VARCHAR2(10) not null,
  cli_num            VARCHAR2(10) not null,
  link_typ           VARCHAR2(1) not null,
  rec_status         VARCHAR2(1) not null,
  rel_to_insrd       VARCHAR2(2),
  addr_typ           NUMBER(4),
  bank_acct_typ      NUMBER(4),
  xcpt_addr_typ      NUMBER(2),
  payo_bank_acct_typ NUMBER(4),
  id_copy_ind        VARCHAR2(1),
  dda_rel_to_owner   VARCHAR2(2),
  rel_to_owner       VARCHAR2(2),
  bio_facial_typ     VARCHAR2(2),
  id_copy_ind_nb     VARCHAR2(1)
)
;
create table CAS.TCONN_EXT_USERS
(
  user_id    VARCHAR2(30) not null,
  user_desc  VARCHAR2(100),
  rec_status VARCHAR2(1) not null
)
;
create table CAS.TCONN_EXT_USER_CTL_PARM
(
  user_id    VARCHAR2(30) not null,
  parm_typ   VARCHAR2(30) not null,
  parm_valu  VARCHAR2(20) not null,
  rec_status VARCHAR2(1) not null,
  parm_desc  VARCHAR2(50),
  data_typ   VARCHAR2(10)
)
;
create table CAS.TCONTROL_PARAMETERS
(
  terr_cd    VARCHAR2(5) not null,
  state_cd   VARCHAR2(2) not null,
  parm_typ   VARCHAR2(30) not null,
  parm_valu  VARCHAR2(20) not null,
  rec_status VARCHAR2(1) not null,
  parm_desc  VARCHAR2(50),
  glob_ind   VARCHAR2(1),
  data_typ   VARCHAR2(10),
  app_cd     VARCHAR2(3),
  crcy_code  VARCHAR2(2) not null
)
;
create table CAS.TCPL_AUDIT_LOG
(
  pol_num         VARCHAR2(10) not null,
  cli_num         VARCHAR2(10) not null,
  link_typ        VARCHAR2(1) not null,
  col_nm          VARCHAR2(30),
  trxn_dt         DATE not null,
  cpl_atr_num     NUMBER(8) not null,
  old_valu        VARCHAR2(50),
  old_valu_ref    VARCHAR2(30),
  new_valu        VARCHAR2(50),
  new_valu_ref    VARCHAR2(30),
  terr_cd         VARCHAR2(5),
  old_valu_expand VARCHAR2(10),
  user_id         VARCHAR2(30),
  action_cd       VARCHAR2(1)
)
;
create table CAS.TCURRENCY_MASTER
(
  crcy_code    VARCHAR2(2) not null,
  crcy_abbr    VARCHAR2(5),
  crcy_desc    VARCHAR2(20),
  prem_tol_amt NUMBER(5,2) not null,
  crcy_symbl   VARCHAR2(5) not null,
  loan_tol_amt NUMBER(5,2) not null,
  ntk_tol_amt  NUMBER(5,2) not null
)
;
create table CAS.TIPA_REG_INFO
(
  pol_num          VARCHAR2(10) not null,
  terr_cd          VARCHAR2(5),
  pol_own_nm       VARCHAR2(40),
  pol_own_id       VARCHAR2(20),
  bank_acct_typ    NUMBER(4),
  bank_cd          VARCHAR2(3),
  bank_acct_nm     VARCHAR2(40),
  bank_acct_num    VARCHAR2(50),
  id_num           VARCHAR2(20),
  id_typ           VARCHAR2(1),
  bank_sv_kd       VARCHAR2(1),
  pac_bk_ctr       VARCHAR2(1),
  ipa_amt          NUMBER(11,2),
  acct_eff_dt      DATE,
  reg_user_id      VARCHAR2(30),
  reg_dt           DATE,
  gen_auto_user_id VARCHAR2(30),
  gen_auto_dt      DATE,
  ipa_stat_cd      VARCHAR2(1),
  dda_rel_to_owner VARCHAR2(2)
)
;
create table CAS.TPLAN_PARAMETERS
(
  parm_typ        VARCHAR2(30) not null,
  plan_code       VARCHAR2(5) not null,
  vers_num        VARCHAR2(2) not null,
  eff_dt          DATE not null,
  parm_valu       VARCHAR2(40),
  parm_desc       VARCHAR2(200),
  rpu_rndrule_ind VARCHAR2(1),
  eti_rndrule_ind VARCHAR2(1),
  dist_chnl_cat   VARCHAR2(2),
  dist_chnl_cd    VARCHAR2(10)
)
;
create table CAS.TPOLICYS
(
  pol_num                VARCHAR2(10) not null,
  mode_prem              NUMBER(11,2) not null,
  ovr_loan_ind           VARCHAR2(1) not null,
  frez_code              VARCHAR2(1) not null,
  ipo_ind                VARCHAR2(1) not null,
  vp_ind                 VARCHAR2(1) not null,
  reins_ind              VARCHAR2(1) not null,
  bill_mthd              VARCHAR2(1) not null,
  crcy_code              VARCHAR2(2) not null,
  last_avy_dt            DATE not null,
  last_pd_to_dt          DATE not null,
  pd_to_dt               DATE not null,
  pol_eff_dt             DATE not null,
  pol_iss_dt             DATE,
  pol_reiss_dt           DATE,
  cnfrm_acpt_dt          DATE,
  pol_rlse_dt            DATE,
  sbmt_dt                DATE not null,
  pol_stat_cd            VARCHAR2(1) not null,
  state_cd               VARCHAR2(2) not null,
  pol_trmn_dt            DATE,
  div_opt                VARCHAR2(1) not null,
  terr_cd                VARCHAR2(5) not null,
  dscnt_prem             NUMBER(11,2) not null,
  pol_susp               NUMBER(13,2) not null,
  pmt_susp               NUMBER(11,2) not null,
  ipo_last_refu_yr       NUMBER(4),
  pmt_mode               VARCHAR2(5) not null,
  bill_prem              NUMBER(11,2) default 0 not null,
  bill_to_dt             DATE not null,
  pac_loan_repy          NUMBER(11,2),
  pac_bk_ctr             VARCHAR2(1),
  pac_eff_dt             DATE,
  medic_code             VARCHAR2(10),
  medic_dt               DATE,
  incmplt_cd             VARCHAR2(2),
  pend_cd                VARCHAR2(2),
  subj_to_cd             VARCHAR2(2),
  uwg_clas               VARCHAR2(30),
  fran_num               VARCHAR2(4),
  agt_code               VARCHAR2(8),
  nfo_opt                VARCHAR2(1) not null,
  nfo_eff_dt             DATE,
  zap_ind                VARCHAR2(1),
  aea_ind                VARCHAR2(1) not null,
  lnb_ind                VARCHAR2(1) not null,
  hiv_ind                VARCHAR2(1) not null,
  pol_rmrk               VARCHAR2(100),
  apl_laps_dt            DATE,
  pc_typ                 VARCHAR2(10),
  pc_recv_dt             DATE,
  pc_pend_reasn          VARCHAR2(10),
  pc_efft_date           DATE,
  apl_ext_days           NUMBER(3),
  nyr_mode_prem          NUMBER(11,2) not null,
  nyr_dscnt_prem         NUMBER(11,2) not null,
  renw_yr                NUMBER(3) not null,
  run_num                NUMBER(2),
  pol_app_dt             DATE,
  tlia_code_1            VARCHAR2(10),
  tlia_code_2            VARCHAR2(10),
  tlia_code_3            VARCHAR2(10),
  disab_clas             VARCHAR2(3),
  restr_case_cnt_ind     VARCHAR2(1) not null,
  comm_wthld_dt          DATE,
  nb_user_id             VARCHAR2(30) not null,
  last_actv_dt           DATE,
  joint_cli_dth_ind      VARCHAR2(1) not null,
  comprop_prem           NUMBER(11,2),
  resv_dnr_amt           NUMBER(13,2),
  xcpt_bill_cd           VARCHAR2(1),
  nb_pc_pol_tot          NUMBER(9),
  cnfrm_prt_dt           DATE,
  os_anty_susp           NUMBER(13,2),
  payo_mthd              VARCHAR2(1),
  anty_stat_cd           VARCHAR2(1),
  nxt_eff_mode_prem      NUMBER(11,2),
  nxt_eff_dscnt_prem     NUMBER(11,2),
  nxt_eff_prem_dt        DATE,
  ctr_prem               NUMBER(11,2),
  nxt_eff_ctr_prem       NUMBER(11,2),
  lump_sum_ind           VARCHAR2(1),
  lump_sum_pmt_amt       NUMBER(11,2),
  proc_fee_ind           VARCHAR2(1),
  dist_chnl_cd           VARCHAR2(10) not null,
  tot_prem_appy          NUMBER(15,2),
  prefix_cd              VARCHAR2(3),
  oth_rqmts_text         VARCHAR2(60),
  mort_cd                VARCHAR2(6),
  chg_insrd_opt          VARCHAR2(1),
  convrt_fr_pol          VARCHAR2(10),
  apl_lapse_ind          VARCHAR2(1),
  div_upto_dt            DATE,
  endow_ctl              VARCHAR2(1),
  sa_cd_2                VARCHAR2(8),
  wa_cd_1                VARCHAR2(8),
  wa_cd_2                VARCHAR2(8),
  vp_point               DATE,
  override_bill_day      NUMBER(2),
  plan_code_base         VARCHAR2(5),
  vers_num_base          VARCHAR2(2),
  plan_prem              NUMBER(11,2),
  db_opt                 VARCHAR2(1),
  ins_typ_base           VARCHAR2(1),
  pric_rsrv_dt           DATE,
  rebal_ind              VARCHAR2(1),
  recurr_bill_ind        VARCHAR2(1),
  recurr_bill_st_dt      DATE,
  fnd_switch_ctr         NUMBER(3),
  fnd_wthdr_ctr          NUMBER(3),
  mvy_ded_to_dt          DATE,
  lst_fnd_valn_dt        DATE,
  corridor_pct           NUMBER(3),
  nb_update_date         DATE,
  pickup_debit_day       NUMBER(2),
  pickup_eff_dt          DATE,
  nxt_rebal_date         DATE,
  dth_susp               NUMBER(13,2),
  curr_debit_day         NUMBER(2),
  nxt_debit_day          NUMBER(2),
  nxt_pac_eff_dt         DATE,
  iio_opt                VARCHAR2(1),
  iio_pct                NUMBER(3),
  special_clas           VARCHAR2(2),
  occ_cd                 VARCHAR2(6),
  insrd_mort             VARCHAR2(4),
  bnh_code               VARCHAR2(5),
  reins_mthd             VARCHAR2(1),
  reins_cd               VARCHAR2(3),
  restrict_cd_1          VARCHAR2(5),
  restrict_cd_2          VARCHAR2(5),
  restrict_cd_3          VARCHAR2(5),
  open_flag              VARCHAR2(5),
  no_lapse_gurt_ind      VARCHAR2(1),
  disable_dt             DATE,
  wrk_area               VARCHAR2(7),
  pol_clm_dt             DATE,
  autopay_susp_dt        DATE,
  frez_dt                DATE,
  orig_plan_prem         NUMBER(13,2),
  waive_to_dt            DATE,
  ipa_ind                VARCHAR2(1),
  rgl_top_up             NUMBER(11,2) default 0 not null,
  ipa_gen_ind            VARCHAR2(1),
  vpo_opt                VARCHAR2(1),
  own_ins_rel            VARCHAR2(2),
  bancas_ind             VARCHAR2(1),
  frst_iss_dt            DATE,
  apl_month              NUMBER(6) default 0,
  lst_yr_fnd_valn_dt     DATE,
  fnd_valn_dt_itrm       DATE,
  dump_in                NUMBER(13,2),
  chrg_free_dt           DATE,
  invest_st_dt_opt       VARCHAR2(1),
  invest_st_ind          VARCHAR2(1),
  invest_st_dt           DATE,
  top_up_dur             NUMBER(3),
  cli_call_dt_typ        VARCHAR2(1),
  cli_call_dt_desc       VARCHAR2(100),
  dist_b02_agt_cd        VARCHAR2(8),
  dist_chnl_cat          VARCHAR2(2) not null,
  inv_acpt_dt            DATE,
  anty_strt_dt           DATE,
  inv_plan_code          VARCHAR2(5),
  inv_vers_num           VARCHAR2(2),
  dist_b01_agt_cd        VARCHAR2(8),
  cmp_acpt_dt            DATE,
  ybt_ind                VARCHAR2(1),
  oth_susp               NUMBER(13,2),
  ann_prem               NUMBER(13,2),
  ann_dscnt_prem         NUMBER(13,2),
  print_ind              VARCHAR2(1),
  inv_tndncy             VARCHAR2(2),
  inv_tndncy_match_grade VARCHAR2(1),
  nb_pmt_mode            VARCHAR2(5),
  nb_pd_to_dt            DATE,
  pkg_plan_code_base     VARCHAR2(5),
  cvg_plan_code_base     VARCHAR2(5),
  cv_opt                 VARCHAR2(2),
  upd_iss_dt             VARCHAR2(1),
  uw_iss_dt              DATE,
  pay_year               NUMBER(3),
  ltr_deliv_opt          VARCHAR2(1),
  invest_end_dt_opt      VARCHAR2(1),
  invest_end_dt          DATE,
  pol_xpry_dt            DATE,
  invest_cvg_xpry_dt     DATE,
  invest_cvg_eff_dt      DATE,
  apl_ind                VARCHAR2(1) default '0',
  renw_ind               VARCHAR2(1) default '0',
  cv_opt_sel_ind         VARCHAR2(1),
  app_num                VARCHAR2(10),
  anty_ptd               DATE,
  comp_name              VARCHAR2(200),
  credit_amt             NUMBER(20),
  credit_num             VARCHAR2(100),
  nyr_bill_prem          NUMBER(13,2) default 0,
  camp_cd                VARCHAR2(30),
  dist_chnl_trxn_id      VARCHAR2(35),
  ntk_strt_dt            DATE,
  dist_b03_agt_cd        VARCHAR2(8),
  dist_b04_agt_cd        VARCHAR2(8),
  high_prem_ind          VARCHAR2(1),
  nb_bill_mthd           VARCHAR2(2),
  bnfy_legal_ind         VARCHAR2(1),
  nxt_renw_dt            DATE,
  dist_b05_agt_cd        VARCHAR2(8),
  app_chnl               VARCHAR2(10) not null,
  init_prem_bill_mthd    VARCHAR2(2),
  init_prem_settle_mthd  VARCHAR2(2),
  init_prem_settle_dt    DATE,
  init_prem_pmt_chnl     VARCHAR2(5),
  eapp_comm_qc_ind       VARCHAR2(1),
  app_cnfrm_num          VARCHAR2(20),
  app_dscnt_prem         NUMBER(13,2),
  wsm_ind                VARCHAR2(1),
  renew_inv_gen_opt      VARCHAR2(1),
  autopay_pend_ind       VARCHAR2(1),
  cprt_de_chk_cd         VARCHAR2(1),
  sign_terr_cd           VARCHAR2(5),
  free_ind               VARCHAR2(1),
  pol_stat_cd_real       VARCHAR2(1),
  pol_app_admin_cd       VARCHAR2(10),
  is_short_term          VARCHAR2(1),
  anty_pay_stat          VARCHAR2(1),
  pol_stat_cd_2nd        VARCHAR2(1),
  delivery_mthd          VARCHAR2(1) not null,
  pol_app_city_admin_cd  VARCHAR2(10),
  rapl_ind               VARCHAR2(1),
  hnw_ind                VARCHAR2(1),
  anty_opt               VARCHAR2(1),
  int_chnl_cat           VARCHAR2(10) not null,
  ext_chnl_cat           VARCHAR2(10) not null,
  part                   VARCHAR2(5),
  entry_source           VARCHAR2(30),
  prem_app_mthd          VARCHAR2(2),
  prem_comm_mode         VARCHAR2(10),
  ext_cvg_typ            VARCHAR2(1),
  nb_agt_code            VARCHAR2(8),
  e_cnfrm_acpt_dt        DATE,
  ybt_pre_offline_uw     VARCHAR2(1),
  ul_opt                 VARCHAR2(3),
  cont_type              VARCHAR2(4),
  cnfrm_acpt_mthd        VARCHAR2(10),
  pol_eff_time           VARCHAR2(8),
  ext_terr_cd            VARCHAR2(5) not null,
  pd_sus_due_dt          DATE,
  e_sign_ind             VARCHAR2(1),
  last_eff_mode_prem     NUMBER(11,2),
  last_eff_dscnt_prem    NUMBER(11,2),
  last_eff_bill_prem     NUMBER(11,2),
  last_eff_prem_dt       DATE,
  tel_cnfrm_acpt_dt      DATE,
  mail_typ               VARCHAR2(4),
  sbmt_dt_real           DATE,
  is_nf_pol              VARCHAR2(1),
  pre_app_ind            VARCHAR2(1)
)
;
create table CAS.TPRINT_CONTROLS
(
  request_id   NUMBER(10) not null,
  fcn_id       VARCHAR2(20) not null,
  report_desc  VARCHAR2(50) not null,
  user_id      VARCHAR2(30) not null,
  request_date DATE not null,
  pol_num      VARCHAR2(10),
  last_printed DATE,
  status       VARCHAR2(1),
  lst_prt_dt   DATE
)
;
create table CAS.TROLE_MENUS
(
  role_id VARCHAR2(30) not null,
  app_cd  VARCHAR2(5) not null,
  menu_cd VARCHAR2(10) not null
)
;
create table CAS.TSYSTEM_LOGS
(
  seq_num     VARCHAR2(15),
  trxn_cas_dt DATE not null,
  trxn_sys_dt DATE not null,
  user_id     VARCHAR2(30),
  fcn_nm      VARCHAR2(61),
  pol_num     VARCHAR2(10),
  log_typ     VARCHAR2(1),
  fcn_return  NUMBER,
  chk_pt      NUMBER,
  sqlcode     NUMBER,
  sqlerrm     VARCHAR2(500),
  app_cd      VARCHAR2(10),
  agt_code    VARCHAR2(8),
  app_num     VARCHAR2(30),
  proposal_id VARCHAR2(100),
  pol_num_02  VARCHAR2(30)
)
;
create table CAS.TUSER_MENUS
(
  user_id VARCHAR2(30) not null,
  app_cd  VARCHAR2(5) not null,
  menu_cd VARCHAR2(10) not null
)
;
create table CAS.TUSER_PROFILES
(
  user_id         VARCHAR2(30) not null,
  user_role       VARCHAR2(30) not null,
  rec_status      VARCHAR2(1) not null,
  team_id         VARCHAR2(2),
  user_name       VARCHAR2(40),
  def_printer     VARCHAR2(10) not null,
  oper_id         VARCHAR2(2),
  nxt_cmp_seq     NUMBER(5),
  pwd_exp_dt      DATE not null,
  print_access    VARCHAR2(1),
  curr_fcn        VARCHAR2(20),
  terr_cd         VARCHAR2(5) default 'SH' not null,
  user_chin_nm    VARCHAR2(50),
  user_ext_num    VARCHAR2(20),
  ur_dur_lmt      NUMBER(3),
  ur_dur_lmt_unit VARCHAR2(1),
  ur_incls        VARCHAR2(1),
  dept_id         VARCHAR2(20),
  phone_num       VARCHAR2(20),
  pwd_encrypt_ind VARCHAR2(1) default 'Y',
  iedms_ind       VARCHAR2(1),
  gp_role         VARCHAR2(20),
  aps_reg_code    VARCHAR2(8),
  aps_db_key      VARCHAR2(200)
)
;
create table CAS.TUSER_ROLES
(
  user_id VARCHAR2(30) not null,
  role_id VARCHAR2(30) not null
)
;
create table CAS.TUSER_TERR_PRIVS
(
  map_id   VARCHAR2(10) not null,
  user_id  VARCHAR2(30) not null,
  map_cd   VARCHAR2(20) not null,
  map_typ  VARCHAR2(1) not null,
  app_cd   VARCHAR2(10) not null,
  priv_typ VARCHAR2(1) not null,
  stat_cd  VARCHAR2(1) not null
)
;
create table CAS.TUSER_TERR_PRIVS_BK
(
  map_id   VARCHAR2(10) not null,
  user_id  VARCHAR2(30) not null,
  map_cd   VARCHAR2(20) not null,
  map_typ  VARCHAR2(1) not null,
  app_cd   VARCHAR2(10) not null,
  priv_typ VARCHAR2(1) not null,
  stat_cd  VARCHAR2(1) not null
)
;
create table CAS.TWIP_POLICYS
(
  pol_num                VARCHAR2(10) not null,
  mode_prem              NUMBER(11,2) not null,
  ovr_loan_ind           VARCHAR2(1) not null,
  frez_code              VARCHAR2(1) not null,
  ipo_ind                VARCHAR2(1) not null,
  vp_ind                 VARCHAR2(1) not null,
  reins_ind              VARCHAR2(1) not null,
  bill_mthd              VARCHAR2(1) not null,
  crcy_code              VARCHAR2(2) not null,
  last_avy_dt            DATE not null,
  last_pd_to_dt          DATE not null,
  pd_to_dt               DATE not null,
  pol_eff_dt             DATE not null,
  pol_iss_dt             DATE,
  pol_reiss_dt           DATE,
  cnfrm_acpt_dt          DATE,
  pol_rlse_dt            DATE,
  sbmt_dt                DATE not null,
  pol_stat_cd            VARCHAR2(1) not null,
  state_cd               VARCHAR2(2) not null,
  pol_trmn_dt            DATE,
  div_opt                VARCHAR2(1) not null,
  terr_cd                VARCHAR2(5) not null,
  dscnt_prem             NUMBER(11,2) not null,
  pol_susp               NUMBER(13,2) not null,
  pmt_susp               NUMBER(11,2) not null,
  ipo_last_refu_yr       NUMBER(4),
  pmt_mode               VARCHAR2(5) not null,
  bill_prem              NUMBER(11,2) not null,
  bill_to_dt             DATE not null,
  pac_loan_repy          NUMBER(11,2),
  pac_bk_ctr             VARCHAR2(1),
  pac_eff_dt             DATE,
  medic_code             VARCHAR2(10),
  medic_dt               DATE,
  incmplt_cd             VARCHAR2(2),
  pend_cd                VARCHAR2(2),
  subj_to_cd             VARCHAR2(2),
  uwg_clas               VARCHAR2(30),
  fran_num               VARCHAR2(4),
  agt_code               VARCHAR2(8),
  nfo_opt                VARCHAR2(1) not null,
  nfo_eff_dt             DATE,
  zap_ind                VARCHAR2(1),
  aea_ind                VARCHAR2(1) not null,
  lnb_ind                VARCHAR2(1) not null,
  hiv_ind                VARCHAR2(1) not null,
  pol_rmrk               VARCHAR2(100),
  apl_laps_dt            DATE,
  pc_typ                 VARCHAR2(10),
  pc_recv_dt             DATE,
  pc_pend_reasn          VARCHAR2(10),
  pc_efft_date           DATE,
  apl_ext_days           NUMBER(3),
  nyr_mode_prem          NUMBER(11,2) not null,
  nyr_dscnt_prem         NUMBER(11,2) not null,
  renw_yr                NUMBER(3) not null,
  run_num                NUMBER(2),
  pol_app_dt             DATE,
  tlia_code_1            VARCHAR2(10),
  tlia_code_2            VARCHAR2(10),
  tlia_code_3            VARCHAR2(10),
  disab_clas             VARCHAR2(3),
  restr_case_cnt_ind     VARCHAR2(1) not null,
  comm_wthld_dt          DATE,
  nb_user_id             VARCHAR2(30) not null,
  last_actv_dt           DATE,
  joint_cli_dth_ind      VARCHAR2(1) not null,
  comprop_prem           NUMBER(11,2),
  resv_dnr_amt           NUMBER(13,2),
  xcpt_bill_cd           VARCHAR2(1),
  nb_pc_pol_tot          NUMBER(9),
  cnfrm_prt_dt           DATE,
  os_anty_susp           NUMBER(13,2),
  payo_mthd              VARCHAR2(1),
  anty_stat_cd           VARCHAR2(1),
  nxt_eff_mode_prem      NUMBER(11,2),
  nxt_eff_dscnt_prem     NUMBER(11,2),
  nxt_eff_prem_dt        DATE,
  ctr_prem               NUMBER(11,2),
  nxt_eff_ctr_prem       NUMBER(11,2),
  lump_sum_ind           VARCHAR2(1),
  lump_sum_pmt_amt       NUMBER(11,2),
  proc_fee_ind           VARCHAR2(1),
  dist_chnl_cd           VARCHAR2(10) not null,
  tot_prem_appy          NUMBER(15,2),
  prefix_cd              VARCHAR2(3),
  oth_rqmts_text         VARCHAR2(60),
  mort_cd                VARCHAR2(6),
  chg_insrd_opt          VARCHAR2(1),
  convrt_fr_pol          VARCHAR2(10),
  apl_lapse_ind          VARCHAR2(1),
  div_upto_dt            DATE,
  endow_ctl              VARCHAR2(1),
  sa_cd_2                VARCHAR2(8),
  wa_cd_1                VARCHAR2(8),
  wa_cd_2                VARCHAR2(8),
  vp_point               DATE,
  override_bill_day      NUMBER(2),
  plan_code_base         VARCHAR2(5),
  vers_num_base          VARCHAR2(2),
  plan_prem              NUMBER(11,2),
  db_opt                 VARCHAR2(1),
  ins_typ_base           VARCHAR2(1),
  pric_rsrv_dt           DATE,
  rebal_ind              VARCHAR2(1),
  recurr_bill_ind        VARCHAR2(1),
  recurr_bill_st_dt      DATE,
  fnd_switch_ctr         NUMBER(3),
  fnd_wthdr_ctr          NUMBER(3),
  mvy_ded_to_dt          DATE,
  lst_fnd_valn_dt        DATE,
  corridor_pct           NUMBER(3),
  nb_update_date         DATE,
  pickup_debit_day       NUMBER(2),
  pickup_eff_dt          DATE,
  nxt_rebal_date         DATE,
  dth_susp               NUMBER(13,2),
  curr_debit_day         NUMBER(2),
  nxt_debit_day          NUMBER(2),
  nxt_pac_eff_dt         DATE,
  iio_opt                VARCHAR2(1),
  iio_pct                NUMBER(3),
  special_clas           VARCHAR2(2),
  occ_cd                 VARCHAR2(6),
  insrd_mort             VARCHAR2(4),
  bnh_code               VARCHAR2(5),
  reins_mthd             VARCHAR2(1),
  reins_cd               VARCHAR2(3),
  restrict_cd_1          VARCHAR2(5),
  restrict_cd_2          VARCHAR2(5),
  restrict_cd_3          VARCHAR2(5),
  open_flag              VARCHAR2(5),
  no_lapse_gurt_ind      VARCHAR2(1),
  disable_dt             DATE,
  wrk_area               VARCHAR2(7),
  pol_clm_dt             DATE,
  autopay_susp_dt        DATE,
  frez_dt                DATE,
  orig_plan_prem         NUMBER(13,2),
  waive_to_dt            DATE,
  ipa_ind                VARCHAR2(1),
  rgl_top_up             NUMBER(11,2) not null,
  ipa_gen_ind            VARCHAR2(1),
  vpo_opt                VARCHAR2(1),
  own_ins_rel            VARCHAR2(2),
  bancas_ind             VARCHAR2(1),
  frst_iss_dt            DATE,
  apl_month              NUMBER(6),
  lst_yr_fnd_valn_dt     DATE,
  fnd_valn_dt_itrm       DATE,
  dump_in                NUMBER(13,2),
  chrg_free_dt           DATE,
  invest_st_dt_opt       VARCHAR2(1),
  invest_st_ind          VARCHAR2(1),
  invest_st_dt           DATE,
  top_up_dur             NUMBER(3),
  cli_call_dt_typ        VARCHAR2(1),
  cli_call_dt_desc       VARCHAR2(100),
  dist_b02_agt_cd        VARCHAR2(8),
  dist_chnl_cat          VARCHAR2(2) not null,
  inv_acpt_dt            DATE,
  anty_strt_dt           DATE,
  inv_plan_code          VARCHAR2(5),
  inv_vers_num           VARCHAR2(2),
  dist_b01_agt_cd        VARCHAR2(8),
  cmp_acpt_dt            DATE,
  ybt_ind                VARCHAR2(1),
  oth_susp               NUMBER(13,2),
  ann_prem               NUMBER(13,2),
  ann_dscnt_prem         NUMBER(13,2),
  print_ind              VARCHAR2(1),
  inv_tndncy             VARCHAR2(2),
  inv_tndncy_match_grade VARCHAR2(1),
  nb_pmt_mode            VARCHAR2(5),
  nb_pd_to_dt            DATE,
  pkg_plan_code_base     VARCHAR2(5),
  cvg_plan_code_base     VARCHAR2(5),
  cv_opt                 VARCHAR2(2),
  upd_iss_dt             VARCHAR2(1),
  uw_iss_dt              DATE,
  pay_year               NUMBER(3),
  ltr_deliv_opt          VARCHAR2(1),
  invest_end_dt_opt      VARCHAR2(1),
  invest_end_dt          DATE,
  pol_xpry_dt            DATE,
  invest_cvg_xpry_dt     DATE,
  invest_cvg_eff_dt      DATE,
  apl_ind                VARCHAR2(1),
  renw_ind               VARCHAR2(1),
  cv_opt_sel_ind         VARCHAR2(1),
  app_num                VARCHAR2(10),
  anty_ptd               DATE,
  comp_name              VARCHAR2(200),
  credit_amt             NUMBER(20),
  credit_num             VARCHAR2(100),
  nyr_bill_prem          NUMBER(13,2),
  camp_cd                VARCHAR2(30),
  dist_chnl_trxn_id      VARCHAR2(35),
  ntk_strt_dt            DATE,
  dist_b03_agt_cd        VARCHAR2(8),
  dist_b04_agt_cd        VARCHAR2(8),
  high_prem_ind          VARCHAR2(1),
  nb_bill_mthd           VARCHAR2(2),
  bnfy_legal_ind         VARCHAR2(1),
  nxt_renw_dt            DATE,
  dist_b05_agt_cd        VARCHAR2(8),
  app_chnl               VARCHAR2(10) not null,
  init_prem_bill_mthd    VARCHAR2(2),
  init_prem_settle_mthd  VARCHAR2(2),
  init_prem_settle_dt    DATE,
  init_prem_pmt_chnl     VARCHAR2(5),
  eapp_comm_qc_ind       VARCHAR2(1),
  app_cnfrm_num          VARCHAR2(20),
  app_dscnt_prem         NUMBER(13,2),
  wsm_ind                VARCHAR2(1),
  renew_inv_gen_opt      VARCHAR2(1),
  autopay_pend_ind       VARCHAR2(1),
  cprt_de_chk_cd         VARCHAR2(1),
  sign_terr_cd           VARCHAR2(5),
  free_ind               VARCHAR2(1),
  pol_stat_cd_real       VARCHAR2(1),
  pol_app_admin_cd       VARCHAR2(10),
  is_short_term          VARCHAR2(10),
  anty_pay_stat          VARCHAR2(1),
  pol_stat_cd_2nd        VARCHAR2(1),
  delivery_mthd          VARCHAR2(1) not null,
  pol_app_city_admin_cd  VARCHAR2(10),
  rapl_ind               VARCHAR2(1),
  hnw_ind                VARCHAR2(1),
  anty_opt               VARCHAR2(1),
  int_chnl_cat           VARCHAR2(10) not null,
  ext_chnl_cat           VARCHAR2(10) not null,
  part                   VARCHAR2(5),
  entry_source           VARCHAR2(30),
  prem_app_mthd          VARCHAR2(2),
  prem_comm_mode         VARCHAR2(10),
  ext_cvg_typ            VARCHAR2(1),
  nb_agt_code            VARCHAR2(8),
  e_cnfrm_acpt_dt        DATE,
  ybt_pre_offline_uw     VARCHAR2(1),
  ul_opt                 VARCHAR2(3),
  cont_type              VARCHAR2(4),
  cnfrm_acpt_mthd        VARCHAR2(10),
  pol_eff_time           VARCHAR2(8),
  ext_terr_cd            VARCHAR2(5) not null,
  pd_sus_due_dt          DATE,
  e_sign_ind             VARCHAR2(1),
  last_eff_mode_prem     NUMBER(11,2),
  last_eff_dscnt_prem    NUMBER(11,2),
  last_eff_bill_prem     NUMBER(11,2),
  last_eff_prem_dt       DATE,
  tel_cnfrm_acpt_dt      DATE,
  mail_typ               VARCHAR2(4),
  sbmt_dt_real           DATE,
  is_nf_pol              VARCHAR2(1),
  pre_app_ind            VARCHAR2(1)
)
;
create table CAS.VPOLICYS_ALL
(
  terr_cd VARCHAR2(10) not null,
  pol_num VARCHAR2(10)
)
;

create or replace  view cas.vuser_menus as
select ur.user_id     user_id,
           rm.app_cd      app_cd,
           rm.menu_cd     menu_cd,
           'ROLE'         menu_typ
      from tuser_roles    ur,
           trole_menus    rm
     where ur.role_id = rm.role_id
     union
   (select um.user_id,
           um.app_cd,
           um.menu_cd,
           'USER'
      from tuser_menus    um
     minus
    select sur.user_id     user_id,
           srm.app_cd      app_cd,
           srm.menu_cd     menu_cd,
           'USER'
      from tuser_roles    sur,
           trole_menus    srm
     where sur.role_id = srm.role_id)
  order by 1, 2, 3;
  
  
  