class GlobalConf {
  static String  host
  static String  port
  static String  username
  static String  password
  static BigDecimal delay
  static Map COLUMN_DEF = [
    "general" : [
      [ "name"     : "QPS",
        "formular" : "SQL_SELECT_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "TPS",
        "formular" : "(SQL_INSERT_COUNT_DIFF + SQL_REPLACE_COUNT_DIFF + SQL_UPDATE_COUNT_DIFF + SQL_DELETE_COUNT_DIFF) / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "CPS",
        "formular" : "TRANS_COMMIT_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "QPS_RT",
        "formular" : "SQL_SELECT_TIME_DIFF / SQL_SELECT_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "TPS_RT",
        "formular" : "(SQL_INSERT_TIME_DIFF + SQL_REPLACE_TIME_DIFF + SQL_UPDATE_TIME_DIFF + SQL_DELETE_TIME_DIFF) / (SQL_INSERT_COUNT_DIFF + SQL_REPLACE_COUNT_DIFF + SQL_UPDATE_COUNT_DIFF + SQL_DELETE_COUNT_DIFF)",
        "width"    : 6 ],

      [ "name"     : "CPS_RT",
        "formular" : "TRANS_COMMIT_TIME_DIFF / TRANS_COMMIT_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "QT",
        "formular" : "REQUEST_QUEUE_TIME_DIFF / REQUEST_ENQUEUE_COUNT_DIFF",
        "width"    : 6 ],

    ],

    "clog" : [

      [ "name"     : "CLPS",
        "formular" : "CLOG_WRITE_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "CLPSRT",
        "formular" : "CLOG_WRITE_TIME_DIFF / CLOG_WRITE_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "BTCHSZ",
        "formular" : "CLOG_TASK_CB_COUNT_DIFF / CLOG_WRITE_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "CRPCRT",
        "formular" : "CLOG_RPC_DELAY_TIME_DIFF / CLOG_RPC_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "SUCCCT",
        "formular" : "ON_SUCCESS_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "SUCCRT",
        "formular" : "ON_SUCCESS_TIME_DIFF / ON_SUCCESS_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "ILPS",
        "formular" : "ILOG_WRITE_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "ILPSRT",
        "formular" : "ILOG_WRITE_TIME_DIFF / ILOG_WRITE_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "BTCHQT",
        "formular" : "CLOG_BATCH_BUFFER_QUEUE_TIME_DIFF / CLOG_FLUSH_TASK_GENERATE_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "WRTRQT",
        "formular" : "CLOG_LOG_WRITER_QUEUE_TIME_DIFF / CLOG_WRITE_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "CLFPS",
        "formular" : "CLOG_FETCH_LOG_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "CLFSPS",
        "formular" : "CLOG_DISK_READ_SIZE_DIFF / 1024 / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "CBQC",
        "formular" : "CLOG_TASK_CB_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "CBQT",
        "formular" : "CLOG_CB_QUEUE_TIME_DIFF / CLOG_TASK_CB_COUNT_DIFF",
        "width"    : 6 ],

    ],

    "trx" : [
      [ "name"     : "TRANST",
        "formular" : "TRANS_TOTAL_USED_TIME_DIFF / TRANS_COMMIT_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "RBPS",
        "formular" : "TRANS_ROLLBACK_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 4 ],

      [ "name"     : "TOPS",
        "formular" : "TRANS_TIMEOUT_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 4 ],

      [ "name"     : "",
        "formular" : "",
        "width"    : 6 ],

      [ "name"     : "",
        "formular" : "",
        "width"    : 6 ],

      [ "name"     : "",
        "formular" : "",
        "width"    : 6 ],

      [ "name"     : "",
        "formular" : "",
        "width"    : 6 ],

    ],
    "storage" : [

      [ "name"     : "MST",
        "formular" : "ACTIVE_MEMSTORE_USED / 1024 / 1024 / 1024",
        "width"    : 3 ],

      [ "name"     : "IORPS",
        "formular" : "IO_READ_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "IOWPS",
        "formular" : "IO_WRITE_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "IORPST",
        "formular" : "IO_READ_DELAY_DIFF / IO_READ_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "IOWPST",
        "formular" : "IO_WRITE_DELAY_DIFF / IO_WRITE_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "IORSPS",
        "formular" : "IO_READ_BYTES_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "IOWSPS",
        "formular" : "IO_WRITE_BYTES_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "",
        "formular" : "",
        "width"    : 6 ],

      [ "name"     : "",
        "formular" : "",
        "width"    : 6 ],

    ],

    "cache" : [
    ],

    "sql" : [

      [ "name"     : "SPS",
        "formular" : "SQL_SELECT_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "IPS",
        "formular" : "SQL_INSERT_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "RPS",
        "formular" : "SQL_REMOTE_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "UPS",
        "formular" : "SQL_UPDATE_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "DPS",
        "formular" : "SQL_DELETE_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "OPS",
        "formular" : "SQL_OTHER_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "SPSRT",
        "formular" : "SQL_SELECT_TIME_DIFF / SQL_SELECT_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "IPSRT",
        "formular" : "SQL_INSERT_TIME_DIFF / SQL_INSERT_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "RPSRT",
        "formular" : "SQL_REPLACE_TIME_DIFF / SQL_REPLACE_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "UPSRT",
        "formular" : "SQL_UPDATE_TIME_DIFF / SQL_UPDATE_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "DPSRT",
        "formular" : "SQL_DELETE_TIME_DIFF / SQL_DELETE_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "LOCL",
        "formular" : "SQL_LOCAL_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "RMT",
        "formular" : "SQL_REMOTE_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 3 ],

      [ "name"     : "DST",
        "formular" : "SQL_DISTRIBUTED_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 3 ],

      [ "name"     : "",
        "formular" : "",
        "width"    : 6 ],

    ],

    "net" : [

      [ "name"     : "SQLIN",
        "formular" : "MYSQL_PACKET_IN_BYTES_DIFF / 1024 / INTERVAL_SECONDS",
        "width"    : 6,
        "scale"    : 3],

      [ "name"     : "SQLOUT",
        "formular" : "MYSQL_PACKET_OUT_BYTES_DIFF / 1024 / INTERVAL_SECONDS",
        "width"    : 6,
        "scale"    : 3],

      [ "name"     : "RPCC",
        "formular" : "RPC_PACKET_IN_DIFF / INTERVAL_SECONDS",
        "width"    : 6],

      [ "name"     : "RPCS",
        "formular" : "RPC_PACKET_IN_BYTES_DIFF / 1024 / INTERVAL_SECONDS",
        "width"    : 6,
        "scale"    : 3 ],

      [ "name"     : "RPCRT",
        "formular" : "RPC_NET_DELAY_DIFF / RPC_PACKET_IN_DIFF",
        "width"    : 6 ],

      [ "name"     : "",
        "formular" : "",
        "width"    : 6 ],

    ],

    "memstore" : [

      [ "name"     : "MSPS",
        "formular" : "MEMSTORE_SCAN_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "MGPS",
        "formular" : "MEMSTORE_GET_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "MAPS",
        "formular" : "MEMSTORE_APPLY_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "MSPSRT",
        "formular" : "MEMSTORE_SCAN_TIME_DIFF / MEMSTORE_SCAN_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "MGPSRT",
        "formular" : "MEMSTORE_GET_TIME_DIFF / MEMSTORE_GET_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "MAPSRT",
        "formular" : "MEMSTORE_APPLY_TIME_DIFF / MEMSTORE_APPLY_COUNT_DIFF",
        "width"    : 6 ],

      [ "name"     : "RLPS",
        "formular" : "MEMSTORE_READ_LOCK_SUCC_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "WLPS",
        "formular" : "MEMSTORE_WRITE_LOCK_SUCC_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 6 ],

      [ "name"     : "RLWT",
        "formular" : "MEMSTORE_WAIT_READ_LOCK_TIME_DIFF / INTERVAL_SECONDS / 1024",
        "width"    : 6,
        "scale"    : 3 ],

      [ "name"     : "WLWT",
        "formular" : "MEMSTORE_WAIT_WRITE_LOCK_TIME_DIFF / INTERVAL_SECONDS / 1024",
        "width"    : 6,
        "scale"    : 3 ],

      [ "name"     : "RLF",
        "formular" : "MEMSTORE_READ_LOCK_FAIL_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 3 ],

      [ "name"     : "WLF",
        "formular" : "MEMSTORE_WRITE_LOCK_FAIL_COUNT_DIFF / INTERVAL_SECONDS",
        "width"    : 3 ],

      [ "name"     : "",
        "formular" : "",
        "width"    : 6 ],

      [ "name"     : "",
        "formular" : "",
        "width"    : 6 ],

    ]


]
  static Map STAT_ID_NAME_MAP = [
10000: 'RPC_PACKET_IN',
10001: 'RPC_PACKET_IN_BYTES',
10002: 'RPC_PACKET_OUT',
10003: 'RPC_PACKET_OUT_BYTES',
10004: 'RPC_DELIVER_FAIL',
10005: 'RPC_NET_DELAY',
10006: 'RPC_NET_FRAME_DELAY',
10007: 'MYSQL_PACKET_IN',
10008: 'MYSQL_PACKET_IN_BYTES',
10009: 'MYSQL_PACKET_OUT',
10010: 'MYSQL_PACKET_OUT_BYTES',
10011: 'MYSQL_DELIVER_FAIL',
20000: 'REQUEST_ENQUEUE_COUNT',
20001: 'REQUEST_DEQUEUE_COUNT',
20002: 'REQUEST_QUEUE_TIME',
30000: 'TRANS_COMMIT_LOG_SYNC_TIME',
30001: 'TRANS_COMMIT_LOG_SYNC_COUNT',
30002: 'TRANS_COMMIT_LOG_SUBMIT_COUNT',
30003: 'TRANS_SYSTEM_TRANS_COUNT',
30004: 'TRANS_USER_TRANS_COUNT',
30005: 'TRANS_START_COUNT',
30006: 'TRANS_TOTAL_USED_TIME',
30007: 'TRANS_COMMIT_COUNT',
30008: 'TRANS_COMMIT_TIME',
30009: 'TRANS_ROLLBACK_COUNT',
30010: 'TRANS_ROLLBACK_TIME',
30011: 'TRANS_TIMEOUT_COUNT',
30012: 'TRANS_LOCAL_COUNT',
30013: 'TRANS_DIST_COUNT',
30017: 'TRANS_READONLY_COUNT',
40000: 'SQL_SELECT_COUNT',
40001: 'SQL_SELECT_TIME',
40002: 'SQL_INSERT_COUNT',
40003: 'SQL_INSERT_TIME',
40004: 'SQL_REPLACE_COUNT',
40005: 'SQL_REPLACE_TIME',
40006: 'SQL_UPDATE_COUNT',
40007: 'SQL_UPDATE_TIME',
40008: 'SQL_DELETE_COUNT',
40009: 'SQL_DELETE_TIME',
40018: 'SQL_OTHER_COUNT',
40019: 'SQL_OTHER_TIME',
40010: 'SQL_LOCAL_COUNT',
40011: 'SQL_REMOTE_COUNT',
40012: 'SQL_DISTRIBUTED_COUNT',
40013: 'ACTIVE_SESSIONS',
40014: 'SQL_SINGLE_QUERY_COUNT',
40015: 'SQL_MULTI_QUERY_COUNT',
40016: 'SQL_MULTI_ONE_QUERY_COUNT',
40100: 'SQL_INNER_SELECT_COUNT',
40101: 'SQL_INNER_SELECT_TIME',
40102: 'SQL_INNER_INSERT_COUNT',
40103: 'SQL_INNER_INSERT_TIME',
40104: 'SQL_INNER_REPLACE_COUNT',
40105: 'SQL_INNER_REPLACE_TIME',
40106: 'SQL_INNER_UPDATE_COUNT',
40107: 'SQL_INNER_UPDATE_TIME',
40108: 'SQL_INNER_DELETE_COUNT',
40109: 'SQL_INNER_DELETE_TIME',
40110: 'SQL_INNER_OTHER_COUNT',
40111: 'SQL_INNER_OTHER_TIME',
50000: 'ROW_CACHE_HIT',
50001: 'ROW_CACHE_MISS',
50002: 'BLOCK_INDEX_CACHE_HIT',
50003: 'BLOCK_INDEX_CACHE_MISS',
50004: 'BLOOM_FILTER_CACHE_HIT',
50005: 'BLOOM_FILTER_CACHE_MISS',
50006: 'BLOOM_FILTER_FILTS',
50007: 'BLOOM_FILTER_PASSES',
50008: 'BLOCK_CACHE_HIT',
50009: 'BLOCK_CACHE_MISS',
50010: 'LOCATION_CACHE_HIT',
50011: 'LOCATION_CACHE_MISS',
50012: 'LOCATION_CACHE_WAIT',
50013: 'LOCATION_CACHE_PROXY_HIT',
50014: 'LOCATION_CACHE_PROXY_MISS',
50015: 'LOCATION_CACHE_CLEAR_LOCATION',
50016: 'LOCATION_CACHE_CLEAR_LOCATION_IGNORED',
50017: 'LOCATION_CACHE_NONBLOCK_HIT',
50018: 'LOCATION_CACHE_NONBLOCK_MISS',
50019: 'LOCATION_CACHE_RPC_CHECK_LEADER',
50020: 'LOCATION_CACHE_RPC_CHECK_MEMBER',
50021: 'LOCATION_CACHE_RPC_CHECK',
50022: 'LOCATION_CACHE_RENEW',
50023: 'LOCATION_CACHE_RENEW_IGNORED',
60000: 'IO_READ_COUNT',
60001: 'IO_READ_DELAY',
60002: 'IO_READ_BYTES',
60003: 'IO_WRITE_COUNT',
60004: 'IO_WRITE_DELAY',
60005: 'IO_WRITE_BYTES',
60006: 'IO_READ_QUEUE_DELAY',
60007: 'IO_WRITE_QUEUE_DELAY',
60008: 'IO_READ_CB_ALLOC_DELAY',
60009: 'IO_READ_CB_PROCESS_DELAY',
60006: 'MEMSTORE_SCAN_COUNT',
60007: 'MEMSTORE_SCAN_SUCC_COUNT',
60008: 'MEMSTORE_SCAN_FAIL_COUNT',
60009: 'MEMSTORE_GET_COUNT',
60010: 'MEMSTORE_GET_SUCC_COUNT',
60011: 'MEMSTORE_GET_FAIL_COUNT',
60012: 'MEMSTORE_APPLY_COUNT',
60013: 'MEMSTORE_APPLY_SUCC_COUNT',
60014: 'MEMSTORE_APPLY_FAIL_COUNT',
60015: 'MEMSTORE_ROW_COUNT',
60016: 'MEMSTORE_GET_TIME',
60017: 'MEMSTORE_SCAN_TIME',
60018: 'MEMSTORE_APPLY_TIME',
60019: 'MEMSTORE_READ_LOCK_SUCC_COUNT',
60020: 'MEMSTORE_READ_LOCK_FAIL_COUNT',
60021: 'MEMSTORE_WRITE_LOCK_SUCC_COUNT',
60022: 'MEMSTORE_WRITE_LOCK_FAIL_COUNT',
60023: 'MEMSTORE_WAIT_WRITE_LOCK_TIME',
60024: 'MEMSTORE_WAIT_READ_LOCK_TIME',
60025: 'IO_READ_MICRO_INDEX_COUNT',
60026: 'IO_READ_MICRO_INDEX_BYTES',
60027: 'IO_READ_PREFETCH_MICRO_COUNT',
60028: 'IO_READ_PREFETCH_MICRO_BYTES',
60029: 'IO_READ_UNCOMP_MICRO_COUNT',
60030: 'IO_READ_UNCOMP_MICRO_BYTES',
60031: 'STORAGE_READ_ROW_COUNT',
60032: 'STORAGE_DELETE_ROW_COUNT',
60033: 'STORAGE_INSERT_ROW_COUNT',
60034: 'STORAGE_UPDATE_ROW_COUNT',
60035: 'MEMSTORE_MUTATOR_REPLAY_TIME',
60036: 'MEMSTORE_MUTATOR_REPLAY_COUNT',
60037: 'MEMSTORE_ROW_PURGE_COUNT',
60038: 'MEMSTORE_ROW_COMPACTION_COUNT',
70000: 'REFRESH_SCHEMA_COUNT',
70001: 'REFRESH_SCHEMA_TIME',
70002: 'INNER_SQL_CONNECTION_EXECUTE_COUNT',
70003: 'INNER_SQL_CONNECTION_EXECUTE_TIME',
70004: 'PARTITION_TABLE_OPERATOR_GET_COUNT',
70005: 'PARTITION_TABLE_OPERATOR_GET_TIME',
80001: 'CLOG_SW_SUBMITTED_LOG_COUNT',
80002: 'CLOG_SW_SUBMITTED_LOG_SIZE',
80003: 'CLOG_INDEX_LOG_FLUSHED_LOG_COUNT',
80004: 'CLOG_INDEX_LOG_FLUSHED_LOG_SIZE',
80005: 'CLOG_FLUSHED_COUNT',
80006: 'CLOG_FLUSHED_SIZE',
80007: 'CLOG_READ_SIZE',
80008: 'CLOG_READ_COUNT',
80009: 'CLOG_DISK_READ_SIZE',
80010: 'CLOG_DISK_READ_COUNT',
80011: 'CLOG_DISK_READ_TIME',
80012: 'CLOG_FETCH_LOG_SIZE',
80013: 'CLOG_FETCH_LOG_COUNT',
80014: 'CLOG_FETCH_LOG_BY_LOCATION_SIZE',
80015: 'CLOG_FETCH_LOG_BY_LOCATION_COUNT',
80016: 'CLOG_READ_REQUEST_SUCC_SIZE',
80017: 'CLOG_READ_REQUEST_SUCC_COUNT',
80018: 'CLOG_READ_REQUEST_FAIL_COUNT',
80019: 'CLOG_LEADER_CONFIRM_TIME',
80020: 'CLOG_FLUSH_TASK_GENERATE_COUNT',
80021: 'CLOG_FLUSH_TASK_RELEASE_COUNT',
80022: 'CLOG_RPC_DELAY_TIME',
80023: 'CLOG_RPC_COUNT',
80024: 'CLOG_NON_KV_CACHE_HIT_COUNT',
80025: 'CLOG_RPC_REQUEST_HANDLE_TIME',
80026: 'CLOG_RPC_REQUEST_COUNT',
80027: 'CLOG_CACHE_HIT_COUNT',
80028: 'CLOG_STATE_LOOP_COUNT',
80029: 'CLOG_STATE_LOOP_TIME',
80030: 'CLOG_REPLAY_LOOP_COUNT',
80031: 'CLOG_REPLAY_LOOP_TIME',
80032: 'CLOG_TO_LEADER_ACTIVE_COUNT',
80033: 'CLOG_TO_LEADER_ACTIVE_TIME',
80034: 'ON_SUCCESS_COUNT',
80035: 'ON_SUCCESS_TIME',
80036: 'ON_LEADER_REVOKE_COUNT',
80037: 'ON_LEADER_REVOKE_TIME',
80038: 'ON_LEADER_TAKEOVER_COUNT',
80039: 'ON_LEADER_TAKEOVER_TIME',
80040: 'CLOG_WRITE_COUNT',
80041: 'CLOG_WRITE_TIME',
80042: 'ILOG_WRITE_COUNT',
80043: 'ILOG_WRITE_TIME',
80044: 'CLOG_FLUSHED_TIME',
80045: 'CLOG_TASK_CB_COUNT',
80046: 'CLOG_CB_QUEUE_TIME',
80049: 'CLOG_ACK_COUNT',
80050: 'CLOG_ACK_TIME',
80051: 'CLOG_FIRST_ACK_COUNT',
80052: 'CLOG_FIRST_ACK_TIME',
80053: 'CLOG_LEADER_CONFIRM_COUNT',
90001: 'ELECTION_CHANGE_LEAER_COUNT',
90002: 'ELECTION_LEADER_REVOKE_COUNT',
110000: 'STANDBY_FETCH_LOG_BYTES',
110001: 'STANDBY_FETCH_LOG_BANDWIDTH_LIMIT',
120000: 'LOCATION_CACHE_SIZE',
120001: 'CLOG_CACHE_SIZE',
120002: 'INDEX_CLOG_CACHE_SIZE',
120003: 'USER_TABLE_COL_STAT_CACHE_SIZE',
120004: 'INDEX_CACHE_SIZE',
120005: 'SYS_BLOCK_CACHE_SIZE',
120006: 'USER_BLOCK_CACHE_SIZE',
120007: 'SYS_ROW_CACHE_SIZE',
120008: 'USER_ROW_CACHE_SIZE',
120009: 'BLOOM_FILTER_CACHE_SIZE',
130000: 'ACTIVE_MEMSTORE_USED',
130001: 'TOTAL_MEMSTORE_USED',
130002: 'MAJOR_FREEZE_TRIGGER',
130004: 'MEMSTORE_LIMIT',
140001: 'MIN_MEMORY_SIZE',
140002: 'MAX_MEMORY_SIZE',
140003: 'MEMORY_USAGE',
140004: 'MIN_CPUS',
140005: 'MAX_CPUS',
140006: 'CPU_USAGE',
140007: 'DISK_USAGE',
140012: 'WORKER_TIME',
140013: 'CPU_TIME',
150001: 'CLOG_DISK_FREE_SIZE',
150002: 'CLOG_DISK_FREE_RATIO',
150003: 'CLOG_LAST_CHECK_LOG_FILE_COLLECT_TIME',
160001: 'OBLOGGER_WRITE_SIZE' ]

}

