## hosts for observer and obproxy
1.obs_hosts=HOST
2.obs_hosts=HOST
3.obs_hosts=HOST
1.proxy_hosts = HOST

1.ct_hosts = HOST

# ob静态数据目录配置
data_path = HOME_PATH/upgrade_data/datadir

# clog/ilog等目录配置
clog_path = HOME_PATH/upgrade_data/datadir

# ob工作目录配置
workdir = HOME_PATH/upgrade_data/workdir
# shared_storage模式
shared_storage= miniourl
ob_startup_mode=shared_storage
# 端口配置
proxy_port=proxy_port
port_base=PORT_BASE
#指定仲裁ip和端口
1.asvr_hosts = HOST
asvr_port = 9878
# 内存配置
memory_size_limit=80G
log_disk_size=150G
# cpu配置
node_cpu_count = 20

# 是否收集core文件
save_core=1

# 是否收集日志文件，默认收集在obtest/collected_log
save_log=1
#结束时是否陈升pstack
gen_pstack=1
# 打开独立子进程
enable_obesi=1
# 启动case前，是否清空环境(配置中所有机器)
cleanup=1
# case运行完后， 是否清空环境(配置中所有机器)
cleanup_after=1
## delete core when rebooting if value is 1
delete_core_on_reboot=0
##配置是否需要统计覆盖率 with_coverage=1时，每个case结束都会stop obs
with_coverage=0
# configserver配置
obconfig=http://ob-jenkins.alibaba.net:8081/oceanbase_configer/v2/
configServer=http://ob-jenkins.alibaba.net:8081/diamond/cgi/a.py
# 数据盘大小配置
disk_avail_space=60G

# 系统日志自动回收复用时，最多保留多少个
max_syslog_file_count = 10
# proxy和server日志级别配置info/trace/debug
proxy_log_level=info
server_log_level=info
#租户创建后调整合并和备份配置项
extra_tenant_params=ob_compaction_schedule_interval = '3s',compaction_low_thread_score = 100,compaction_mid_thread_score = 100,compaction_high_thread_score = 100,merger_check_interval = '10s',ha_high_thread_score = 100,ha_mid_thread_score = 100,ha_low_thread_score = 100,major_freeze_duty_time = 'disable'
# docker上不带bond0,这里配置网卡为eth0
dev=devport
