using System.Diagnostics;
using System.IO;
using System.ServiceProcess;
using System.Text;

namespace seekdbConfigurator;

/// <summary>Applies wizard settings by writing seekdb.cnf and invoking seekdb.exe (same idea as tools/windows/seekdb_manage.ps1).</summary>
public sealed class ConfiguratorEngine
{
    public static string? FindSeekdbExe()
    {
        var exeDir = Path.GetDirectoryName(Environment.ProcessPath);
        if (string.IsNullOrEmpty(exeDir))
            return null;

        var candidates = new[]
        {
            Path.Combine(exeDir, "seekdb.exe"),
            Path.GetFullPath(Path.Combine(exeDir, "..", "bin", "seekdb.exe")),
            Path.GetFullPath(Path.Combine(exeDir, "..", "..", "bin", "seekdb.exe")),
        };

        foreach (var c in candidates)
        {
            if (File.Exists(c))
                return c;
        }

        return null;
    }

    /// <summary>Typical MSI layout: installation root containing bin/ and etc/</summary>
    public static string? FindDefaultEtcCnf(string seekdbExe)
    {
        var bin = Path.GetDirectoryName(seekdbExe);
        if (string.IsNullOrEmpty(bin))
            return null;
        var installRoot = Path.GetFullPath(Path.Combine(bin, ".."));
        var cnf = Path.Combine(installRoot, "etc", "seekdb.cnf");
        return File.Exists(cnf) ? cnf : null;
    }

    public static void WriteCnf(string targetCnfPath, WizardConfig cfg)
    {
        cfg.NormalizeDataDirectory();
        cfg.ApplyConfigTypePresets();
        var baseDir = cfg.BaseDirForCnf;
        var sb = new StringBuilder();
        sb.AppendLine("# seekdb Configuration File (generated by seekdb Configurator)");
        sb.AppendLine("# These parameters are permanently valid");
        sb.AppendLine($"base-dir={baseDir}");
        sb.AppendLine($"data-dir={baseDir}/store");
        sb.AppendLine($"redo-dir={baseDir}/store/redo");
        sb.AppendLine();
        sb.AppendLine("# Valid at initialization / runtime as applicable");
        sb.AppendLine($"port={cfg.Port}");
        sb.AppendLine($"cpu_count={cfg.CpuCount}");
        sb.AppendLine($"memory_limit={cfg.MemoryLimit}");
        File.WriteAllText(targetCnfPath, sb.ToString(), Encoding.UTF8);
    }

    public static void EnsureDirectories(WizardConfig cfg)
    {
        cfg.NormalizeDataDirectory();
        var root = cfg.DataDirectory.TrimEnd('\\');
        Directory.CreateDirectory(root);
        Directory.CreateDirectory(Path.Combine(root, "store"));
        Directory.CreateDirectory(Path.Combine(root, "store", "redo"));
    }

    public static int RunProcess(string fileName, string arguments, Action<string>? onLine = null)
    {
        var psi = new ProcessStartInfo(fileName, arguments)
        {
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = true,
        };
        using var p = new Process { StartInfo = psi };
        p.OutputDataReceived += (_, e) => { if (e.Data != null) onLine?.Invoke(e.Data); };
        p.ErrorDataReceived += (_, e) => { if (e.Data != null) onLine?.Invoke(e.Data); };
        p.Start();
        p.BeginOutputReadLine();
        p.BeginErrorReadLine();
        p.WaitForExit();
        return p.ExitCode;
    }

    public static void TryAddFirewallRule(int port, Action<string> log)
    {
        var ruleName = $"seekdb TCP {port}";
        var psi = new ProcessStartInfo("netsh", $"advfirewall firewall add rule name=\"{ruleName}\" dir=in action=allow protocol=TCP localport={port}")
        {
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = true,
        };
        try
        {
            using var p = Process.Start(psi);
            p?.WaitForExit();
            log($"Firewall rule '{ruleName}' add exit code: {p?.ExitCode ?? -1}");
        }
        catch (Exception ex)
        {
            log($"Firewall: {ex.Message}");
        }
    }

    public static bool NeedsInit(WizardConfig cfg)
    {
        cfg.NormalizeDataDirectory();
        var baseDir = cfg.DataDirectory.TrimEnd('\\');
        var meta = Path.Combine(baseDir, ".meta");
        var dataDir = Path.Combine(baseDir, "store");
        if (File.Exists(meta))
            return false;
        if (!Directory.Exists(dataDir))
            return true;
        return !Directory.EnumerateFileSystemEntries(dataDir).Any();
    }

    public static int RunInit(string seekdbExe, WizardConfig cfg, string cnfPath, Action<string>? log)
    {
        cfg.ApplyConfigTypePresets();
        var args = new StringBuilder();
        args.Append($"--base-dir=\"{cfg.BaseDirForCnf}\" --nodaemon");
        args.Append($" --port={cfg.Port}");
        args.Append($" --parameter memory_limit={cfg.MemoryLimit}");
        args.Append($" --parameter cpu_count={cfg.CpuCount}");

        log?.Invoke($"{seekdbExe} {args}");
        return RunProcess(seekdbExe, args.ToString(), log);
    }

    public static int RunInstallService(string seekdbExe, WizardConfig cfg, string cnfPath, Action<string>? log)
    {
        cfg.ApplyConfigTypePresets();
        var args = new StringBuilder();
        args.Append($"--install-service {cfg.ServiceName} --base-dir=\"{cfg.BaseDirForCnf}\"");
        args.Append($" --port={cfg.Port}");
        args.Append($" --parameter memory_limit={cfg.MemoryLimit}");
        args.Append($" --parameter cpu_count={cfg.CpuCount}");
        log?.Invoke($"{seekdbExe} {args}");
        return RunProcess(seekdbExe, args.ToString(), log);
    }

    public static void SetServiceStartMode(string serviceName, bool autoStart)
    {
        var mode = autoStart ? "auto" : "demand";
        RunProcess("sc.exe", $"config {serviceName} start= {mode}");
    }

    public static void TryStartService(string serviceName, Action<string> log)
    {
        try
        {
            using var sc = new ServiceController(serviceName);
            if (sc.Status == ServiceControllerStatus.Running)
            {
                log("Service already running.");
                return;
            }
            sc.Start();
            sc.WaitForStatus(ServiceControllerStatus.Running, TimeSpan.FromMinutes(2));
            log("Service started.");
        }
        catch (Exception ex)
        {
            log($"Start service: {ex.Message}");
        }
    }
}
