CREATE TABLE "PSI_CFG_VENDOR_SUPPLYINFO" 
   ("REGION" NUMBER(5,0), 
	"OID" VARCHAR2(32), 
	"VENDOR_ID" VARCHAR2(32), 
	"SUPPLIER_TYPE" VARCHAR2(32), 
	"RES_TYPE_ID" VARCHAR2(32), 
	"SUPPLY_MONTH" VARCHAR2(32), 
	"SUPPLY_NUM" VARCHAR2(32), 
	"LEFT_NUM" VARCHAR2(32), 
	"OPER_ID" VARCHAR2(32), 
	"CREATE_DATE" DATE DEFAULT sysdate, 
	"MEMO" VARCHAR2(2000), 
	"BRAND_ID" VARCHAR2(32), 
	"MANUAL_FLAG" VARCHAR2(32)
   )
  PARTITION BY RANGE ("REGION") 
 (PARTITION "P_530"  VALUES LESS THAN (531) , 
 PARTITION "P_999"  VALUES LESS THAN (1000) ) ;
 
CREATE TABLE "IM_RES_TYPE" 
("RES_TYPE_ID" VARCHAR2(32), 
"RES_TYPE_NAME" VARCHAR2(64), 
"RES_TABLE_NAME" VARCHAR2(50), 
"IF_STOCKS" VARCHAR2(32), 
"PARENT_RES_ID" VARCHAR2(32), 
"IF_BASE" VARCHAR2(32), 
"SUPPLIER_ID" VARCHAR2(32) DEFAULT 'UNKNOWN', 
"IF_SEQUENCE" VARCHAR2(32), 
"RES_TYPE_MEMO" VARCHAR2(500), 
"STATUS" VARCHAR2(32), 
"EFF_DATE" DATE, 
"EXP_DATE" DATE, 
"CREATE_ORG_ID" VARCHAR2(32), 
"RES_KIND_ID" VARCHAR2(32), 
"IF_PHYSICAL" VARCHAR2(32), 
"VERSION_NUMBER" VARCHAR2(50), 
"RES_LIMIT" VARCHAR2(32), 
"INV_NAME" VARCHAR2(32), 
"INV_ID_LENGTH" NUMBER(3,0) DEFAULT 0, 
"INV_SEG_LEN" NUMBER(3,0) DEFAULT 0, 
"NET_TYPE" VARCHAR2(32) DEFAULT 'ALL', 
"REGION" NUMBER(6,0), 
"LAST_BUSI_ID" VARCHAR2(32), 
"STATUS_DATE" DATE DEFAULT sysdate, 
"OPER_ID" VARCHAR2(32), 
"BRAND_ID" VARCHAR2(32), 
"SPECTPLT_ID" VARCHAR2(32), 
"MEASURE_UNIT" VARCHAR2(32), 
"IS_BATCH_MGR" NUMBER(1,0), 
"RES_MODULE_TYPE" NUMBER(1,0), 
"IF_SYN" VARCHAR2(32), 
"GOODS_KIND_ID" VARCHAR2(32), 
"PARENT_GOODS_ID" VARCHAR2(32), 
"CREATE_DATE" DATE DEFAULT sysdate, 
"PARTICULAR_ATTR" VARCHAR2(128), 
"RES_SPECIAL_MODEL" VARCHAR2(32)
);
 
 
 