CREATE TABLE "PSI_FLOW_APPLY_BATCH" 
   ("REGION" NUMBER(5,0), 
	"BATCH_ID" VARCHAR2(32), 
	"FLOW_ID" VARCHAR2(32), 
	"RES_TYPE_ID" VARCHAR2(32), 
	"COLOR" VARCHAR2(32), 
	"SUPPLIER_ID" VARCHAR2(32), 
	"APPLY_NUM" NUMBER(9,0), 
	"ARRIVE_NUM" NUMBER(9,0), 
	"RECEIVE_ORG" VARCHAR2(32), 
	"ORDER_ID" VARCHAR2(32), 
	"STATUS" VARCHAR2(32), 
	"MEMO" VARCHAR2(128), 
	"BRAND_ID" VARCHAR2(32), 
	"SETTLE_MODE" VARCHAR2(32), 
	"RECEIVE_ADDR" VARCHAR2(128), 
	"ORDER_DETAIL_ID" VARCHAR2(32), 
	"ORIG_NUM" NUMBER(9,0), 
	"CREATE_DATE" DATE, 
	"RECEIVE_DATE" DATE, 
	"RECEIVE_LAST_DATE" DATE, 
	"STOCKUP_NUM" NUMBER(9,0), 
	"UNIT_PRICE" VARCHAR2(32), 
	"IS_GIFT" NUMBER(1,0) DEFAULT 0, 
	"GIFT_BATCH_ID" VARCHAR2(32), 
	"MAX_APPLY_NUMBER" VARCHAR2(32), 
	"RWD_LEVEL_ID" VARCHAR2(32), 
	"TOTAL_PRICE" VARCHAR2(32), 
	"TOTAL_DISC" VARCHAR2(32), 
	"PRIV_DESC" VARCHAR2(512), 
	"MAPPING_RESTYPE" VARCHAR2(32), 
	"RES_KIND_ID" VARCHAR2(32)
   );
   
  CREATE TABLE "PSI_FLOW_APPLY" 
   (	"REGION" NUMBER(5,0), 
	"FLOW_ID" VARCHAR2(32), 
	"FLOW_STATUS" VARCHAR2(32), 
	"RES_KIND_ID" VARCHAR2(32), 
	"ORG_LEVEL" VARCHAR2(32), 
	"ORG_ID" VARCHAR2(32), 
	"APPLY_CYCLE" NUMBER(8,0), 
	"CYCLE_TYPE" VARCHAR2(32), 
	"APPLY_TYPE" VARCHAR2(32), 
	"APPLY_CLASS" VARCHAR2(32), 
	"CHANNEL_TYPE" VARCHAR2(32), 
	"PROJECT_ID" VARCHAR2(64), 
	"IF_BASE" VARCHAR2(32), 
	"PARENT_FLOW_ID" VARCHAR2(32), 
	"LINK_MAN" VARCHAR2(64), 
	"CONTACT_PHONE" VARCHAR2(32), 
	"RECEIVE_DATE" DATE, 
	"RECEIVE_LAST_DATE" DATE, 
	"CREATE_DATE" DATE, 
	"CREATE_OPER" VARCHAR2(32), 
	"CREATE_ORG_ID" VARCHAR2(32), 
	"DES_ORG_ID" VARCHAR2(32), 
	"MEMO" VARCHAR2(512), 
	"LOCK_STATUS" VARCHAR2(32), 
	"STATUS_DATE" DATE, 
	"DES_REGION" NUMBER(5,0), 
	"DES_STORE_ID" VARCHAR2(32), 
	"SRC_STORE_ID" VARCHAR2(32), 
	"SRC_ORG_ID" VARCHAR2(32), 
	"SUM_PRICE" VARCHAR2(32), 
	"PAY_TYPE" VARCHAR2(32), 
	"PAY_OID" VARCHAR2(64), 
	"SUM_APPLY_NUM" NUMBER(9,0), 
	"PAY_PRICE" VARCHAR2(32), 
	"ADDRESS" VARCHAR2(256), 
	"ORDER_PRIV_ID" VARCHAR2(32), 
	"ORDER_PRIV_DESC" VARCHAR2(128), 
	"ORDER_PRIV_DISC" NUMBER(10,0), 
	"PAY_STATUS" VARCHAR2(32), 
	"UNLOCKED_EXPDATE" DATE, 
	"OTHER_COUPONS" NUMBER(10,0), 
	"ALREADY_PAY_PRICE" NUMBER(12,0), 
	"PAYPLAT_TYPE" VARCHAR2(32), 
	"COUNTY_ID" VARCHAR2(32) DEFAULT NULL, 
	"SUPPLIER_ID" VARCHAR2(32), 
	"SETTLE_MODE" VARCHAR2(32), 
	"CLOSE_FLAG" VARCHAR2(32), 
	"ADD_STATUS" VARCHAR2(32) DEFAULT NULL, 
	"COMMENT_TIMES" NUMBER(2,0) DEFAULT 0, 
	"OUT_ORDER_ID" VARCHAR2(32)
   ) ;

CREATE OR REPLACE SYNONYM "DICT_ITEM" FOR "COMMON_QZQ"."SA_DB_DICTITEM";

CREATE OR REPLACE SYNONYM "PSI_CFG_VENDOR_SUPPLYINFO" FOR "IM_DICT_QZQ"."PSI_CFG_VENDOR_SUPPLYINFO";

CREATE TABLE "IM_IF_BB_PROPACKAGES" 
("INTF_DATE" VARCHAR2(8), 
"REC_SEQ" NUMBER(14,0), 
"PACKAGE_CODE" VARCHAR2(16), 
"PACKAGE_CONTENT" VARCHAR2(1023), 
"STATUS" VARCHAR2(32), 
"STATUS_DATE" DATE, 
"MEMO" VARCHAR2(50)
);
 
CREATE OR REPLACE SYNONYM "PC_PROD_IMEI_PRIV" FOR "COMMON_QZQ"."PC_PROD_IMEI_PRIV";

CREATE TABLE "IM_INV_MOBTEL" 
("REGION" NUMBER(6,0), 
"INV_ID" VARCHAR2(32), 
"INV_STATUS" VARCHAR2(32) DEFAULT 'INSTORE', 
"CHECK_STATUS" VARCHAR2(32) DEFAULT 'NORMAL', 
"STATUS_REASON" VARCHAR2(32), 
"STATUS_DATE" DATE DEFAULT SYSDATE, 
"OPER_ID" VARCHAR2(32), 
"ACTOR_TYPE" VARCHAR2(32), 
"ACTOR_ID" VARCHAR2(32), 
"LDSTORE_BUSI_ID" VARCHAR2(32), 
"LAST_BUSI_ID" VARCHAR2(32), 
"STORE_ID" VARCHAR2(32), 
"REAL_STORE_ID" VARCHAR2(32), 
"ORG_ID" VARCHAR2(32), 
"RES_TYPE_ID" VARCHAR2(32), 
"PHYSICAL_STATUS" VARCHAR2(32) DEFAULT 'NORMAL', 
"CUR_OWNER" VARCHAR2(50), 
"BUSI_STATUS" VARCHAR2(32) DEFAULT 'USABLE', 
"REAL_CONFIG" VARCHAR2(200), 
"REAL_COLOR" VARCHAR2(32), 
"REAL_PRICE" NUMBER(7,0) DEFAULT 0, 
"COST_PRICE" NUMBER(12,0) DEFAULT 0, 
"SERVICE_PRICE" NUMBER(7,0) DEFAULT 0, 
"SUPPLIER_ID" VARCHAR2(32) DEFAULT 'UNKNOWN', 
"SETTLE_MODE" VARCHAR2(32), 
"AGENT_ID" VARCHAR2(32), 
"SETTLE_STATUS" VARCHAR2(32) DEFAULT 'UNSETTLE', 
"LDSTORE_DATE" DATE DEFAULT SYSDATE, 
"LDSTORE_TYPE" VARCHAR2(32), 
"REWARD_STATUS" VARCHAR2(32) DEFAULT 'UNSETTLE', 
"ORDER_ID" VARCHAR2(32), 
"CUR_SETTLE_TASK_ID" VARCHAR2(32), 
"CUSTOMIZATION_BRAND" VARCHAR2(32), 
"OWNER_TYPE" VARCHAR2(32), 
"MARKETING_CHANNEL" VARCHAR2(32), 
"IS_BAK" VARCHAR2(32), 
"IF_PAY" VARCHAR2(32), 
"PURCHASE_PRICE" NUMBER(10,0) DEFAULT 0, 
"PRODUCT_TYPE" VARCHAR2(32), 
"OWNER_OPER_ID" VARCHAR2(32), 
"ASIGOUT_BUSI_ID" VARCHAR2(32), 
"ASIGIN_BUSI_ID" VARCHAR2(32), 
"SALE_BUSI_ID" VARCHAR2(32), 
"UNSALE_BUSI_ID" VARCHAR2(32), 
"ERP_BATCH_ID" VARCHAR2(64), 
"FORBID_FORCE_DATE" DATE, 
"SELF_SALE_DATE" DATE, 
"SHELF_ID" VARCHAR2(32), 
"AREA_ID" VARCHAR2(32), 
"FUTURE_COST_PRICE" NUMBER(7,0) DEFAULT -1, 
"FUTURE_EFF_DATE" DATE, 
"AGEREVERT_DATE" DATE, 
"ISPICKCOLOR" NUMBER(1,0), 
"ADDDATA1" VARCHAR2(128), 
"ADDDATA2" VARCHAR2(128), 
"ADDDATA3" VARCHAR2(128), 
"IS_PROTOTYPE" NUMBER(2,0), 
"PROTOTYPE_ORGID" VARCHAR2(32)
);

CREATE TABLE "LOC_MOBTEL_CHANGE_LOG" 
("INV_ID" VARCHAR2(32), 
"OLDVALUE" VARCHAR2(1024), 
"NEWVALUE" VARCHAR2(1024), 
"CORRECT" NUMBER, 
"INTIME" DATE, 
"HOST" VARCHAR2(32), 
"OS_USER" VARCHAR2(32), 
"IP_ADDRESS" VARCHAR2(32)
);

CREATE OR REPLACE SYNONYM "IM_RES_TYPE" FOR "IM_DICT_QZQ"."IM_RES_TYPE";


CREATE TABLE "IM_ESHOP_TELNUM_INLOG" 
("REGION" NUMBER(5,0), 
"INV_ID" VARCHAR2(32), 
"STATUS" VARCHAR2(6), 
"INTIME" DATE DEFAULT sysdate, 
"PROCESSED" NUMBER(1,0) DEFAULT 0, 
"PROCESSDATE" DATE, 
"PROCESSINFO" VARCHAR2(128), 
"IS_SYNC" VARCHAR2(1) DEFAULT 0
);


CREATE TABLE "IM_INV_TELNUM" 
("REGION" NUMBER(6,0), 
"INV_ID" VARCHAR2(32), 
"RES_TYPE_ID" VARCHAR2(32), 
"INV_STATUS" VARCHAR2(32), 
"STATUS_DATE" DATE, 
"STATUS_REASON" VARCHAR2(32), 
"LDSTORE_BUSI_ID" VARCHAR2(32), 
"LAST_BUSI_ID" VARCHAR2(32), 
"STORE_ID" VARCHAR2(32), 
"ORG_ID" VARCHAR2(32), 
"PHYSICAL_STATUS" VARCHAR2(32), 
"BUSI_STATUS" VARCHAR2(32), 
"HLR_STATUS" VARCHAR2(32), 
"HLR_ID" VARCHAR2(32) DEFAULT 'HLR001', 
"GROUP_ID" VARCHAR2(32), 
"USE_CNT" NUMBER(6,0) DEFAULT 0, 
"PRE_PRICE" NUMBER(8,0) DEFAULT 0, 
"BUNDLE_IMSI" VARCHAR2(32), 
"OPER_ID" VARCHAR2(32), 
"USE_ORG_ID" VARCHAR2(32), 
"BRAND_ID" VARCHAR2(32), 
"PRODUCT_ID" VARCHAR2(256), 
"TELNUM_GRADE" VARCHAR2(32), 
"CREATE_DATE" DATE, 
"MEMO" VARCHAR2(500), 
"USER_PASSWORD" VARCHAR2(32), 
"ADDDATA1" VARCHAR2(32), 
"ADDDATA2" VARCHAR2(32), 
"RECYCLE_DATE" DATE, 
"LDSTORE_DATE" DATE DEFAULT SYSDATE, 
"TELNUM_CLASS" VARCHAR2(32) DEFAULT '0', 
"LOW_CONSUM_PRE" NUMBER(10,0) DEFAULT 0, 
"LOW_CONSUM_FEE" NUMBER(10,0) DEFAULT 0, 
"LOW_INSERVICE_TIME" NUMBER(10,0) DEFAULT 0, 
"TELNUMTAIL8" VARCHAR2(32), 
"TELNUMTAIL7" VARCHAR2(32), 
"TELNUMTAIL6" VARCHAR2(32), 
"TELNUMTAIL5" VARCHAR2(32), 
"TELNUMTAIL4" VARCHAR2(32), 
"TELNUMTAIL3" VARCHAR2(32), 
"TELNUM_CLASSNAME" VARCHAR2(32), 
"MATCH_PATTERN" VARCHAR2(32), 
"NEXT_CALCGRADE_DATE" DATE
);

CREATE TABLE "IM_INV_REALSIGN" 
("REGION" NUMBER(6,0), 
"INV_ID" VARCHAR2(32), 
"RES_TYPE_ID" VARCHAR2(32), 
"INV_STATUS" VARCHAR2(32), 
"CHECK_STATUS" VARCHAR2(32), 
"STATUS_DATE" DATE, 
"STATUS_REASON" VARCHAR2(32), 
"LDSTORE_BUSI_ID" VARCHAR2(32), 
"LAST_BUSI_ID" VARCHAR2(32), 
"STORE_ID" VARCHAR2(32), 
"ORG_ID" VARCHAR2(32), 
"PHYSICAL_STATUS" VARCHAR2(32), 
"BUSI_STATUS" VARCHAR2(32), 
"OPER_ID" VARCHAR2(32), 
"USE_ORG_ID" VARCHAR2(32), 
"ASSET_ID" VARCHAR2(32), 
"SUPPLIER_ID" VARCHAR2(32) DEFAULT 'UNKNOWN', 
"FORMAT_ID" VARCHAR2(32), 
"MEMO" VARCHAR2(500), 
"ADDDATA1" VARCHAR2(32), 
"ADDDATA2" VARCHAR2(32), 
"ADDDATA3" VARCHAR2(32), 
"ADDDATA4" VARCHAR2(32), 
"ADDDATA5" VARCHAR2(32), 
"LDSTORE_DATE" DATE DEFAULT SYSDATE, 
"COST_PRICE" VARCHAR2(9), 
"ERP_BATCH_ID" VARCHAR2(64), 
"SHELF_ID" VARCHAR2(32), 
"AREA_ID" VARCHAR2(32), 
"WBANDDEVGRADE" NUMBER(2,0)
);

CREATE TABLE "IM_INV_WIREDEV_TRACK" 
("REGION" NUMBER(5,0), 
"RES_TYPE_ID" VARCHAR2(32), 
"INV_ID" VARCHAR2(32), 
"STATUS_DATE" DATE, 
"STORE_ID" VARCHAR2(32), 
"ORG_ID" VARCHAR2(32), 
"INTIME" DATE DEFAULT SYSDATE, 
"OPER_ID" VARCHAR2(20), 
"OPER_ORG_ID" VARCHAR2(32), 
"IFRETREADS" VARCHAR2(32), 
"ZZOPERID" VARCHAR2(20), 
"OPER_TYPE" VARCHAR2(32), 
"ADDDATA1" VARCHAR2(256), 
"ADDDATA2" VARCHAR2(256), 
"ADDDATA3" VARCHAR2(256), 
"OPERINPUTSN" VARCHAR2(32)
);

CREATE OR REPLACE VIEW "OPERATOR" ("OPERID", "REGION", "OPERNAME", "PASSWORD", "PASSCHGDATE", "OPERGROUP", "OPERTYPE", "OPERLEVEL", "ISMANAGER", "CONTACTPHONE", "ORGID", "ISRESTRICT", "STARTTIME", "ENDTIME", "ENABLEGPRS", "GPRSSTARTTIME", "GPRSENDTIME", "ISCHKMAC", "MAC", "NOTES", "CREATEDATE", "STATUS", "STATUSDATE", "RELE_STAFF_ID", "START_USING_TIME", "END_USING_TIME", "LOGINTYPE", "AREAID", "ISCHECKTICKET", "BBOSSOPERID") AS
SELECT
    BASIC.STAFFID             OPERID,
    BASIC.CURRENTREGION       region,
    BASIC.STAFFNAME           OPERNAME,
    pwd.PASSWORD              PASSWORD,
    pwd.UPDATEDATE            PASSCHGDATE,
    BASIC.PteamId             OPERGROUP,
    BASIC.StaffType           OPERTYPE,
    BASIC.DlevelId            OPERLEVEL,
    BASIC.isManager           ISMANAGER,
    BASIC.TELNO              CONTACTPHONE,
    BASIC.CURRENTORGAID     orgid,
    RESTRICT.isRestrict       ISRESTRICT,
    RESTRICT.StartTime        STARTTIME,
    RESTRICT.EndTime          ENDTIME,
    RESTRICT.enableGRPS       ENABLEGPRS,
    RESTRICT.GPRSStartTime    GPRSSTARTTIME,
    RESTRICT.GPRSEndTime      GPRSENDTIME,
    RESTRICT.MacMode          ISCHKMAC,
    Mac.Macvalue              MAC,
    BASIC.Remark              NOTES,
    BASIC.CreateDate          CREATEDATE,
    to_number(decode(BASIC.STAFFIDSTATUS,'01','1','02','2','03','0',BASIC.STAFFIDSTATUS))       STATUS,
    BASIC.StatusDate          STATUSDATE,
    BASIC.RELESTAFFID         RELE_STAFF_ID,
    BASIC.BeginDate           START_USING_TIME,
    BASIC.EndDate             END_USING_TIME,
    BASIC.LOGINTYPE           LOGINTYPE,
    BASIC.areaid              areaid,
    RESTRICT.ISCHECKTICKET    ISCHECKTICKET,
    BBOSSINFO.BBOSSSTAFFID    BBOSSOPERID
from ICDPUB_QZQ.T_UCP_STAFFBASICINFO BASIC ,
    ICDPUB_QZQ.T_UCP_PASSWORD    pwd,
    ICDPUB_QZQ.T_UCP_STAFFEXTENDINFO EXTEND,
    ICDPUB_QZQ.T_UCP_STAFFRESTRICTINFO RESTRICT,
    ICDPUB_QZQ.T_UCP_StaffMac Mac,
    ICDPUB_QZQ.T_UCP_STAFF_BBOSS_INFO BBOSSINFO
WHERE BASIC.Staffid = pwd.staffid(+)
  AND BASIC.Staffid = EXTEND.Staffid(+)
  AND BASIC.Staffid = RESTRICT.Staffid(+)
  AND BASIC.Staffid = Mac.Staffid(+)
  AND BASIC.Staffid = BBOSSINFO.Staffid(+)
;

CREATE OR REPLACE FORCE VIEW "OPERATOR" ("OPERID", "REGION", "OPERNAME", "PASSWORD", "PASSCHGDATE", "OPERGROUP", "OPERTYPE", "OPERLEVEL", "ISMANAGER", "CONTACTPHONE", "ORGID", "ISRESTRICT", "STARTTIME", "ENDTIME", "ENABLEGPRS", "GPRSSTARTTIME", "GPRSENDTIME", "ISCHKMAC", "MAC", "NOTES", "CREATEDATE", "STATUS", "STATUSDATE", "RELE_STAFF_ID", "START_USING_TIME", "END_USING_TIME", "LOGINTYPE", "AREAID", "ISCHECKTICKET", "BBOSSOPERID") AS
SELECT
    BASIC.STAFFID             OPERID,
    BASIC.CURRENTREGION       region,
    BASIC.STAFFNAME           OPERNAME,
    pwd.PASSWORD              PASSWORD,
    pwd.UPDATEDATE            PASSCHGDATE,
    BASIC.PteamId             OPERGROUP,
    BASIC.StaffType           OPERTYPE,
    BASIC.DlevelId            OPERLEVEL,
    BASIC.isManager           ISMANAGER,
    BASIC.TELNO              CONTACTPHONE,
    BASIC.CURRENTORGAID     orgid,
    RESTRICT.isRestrict       ISRESTRICT,
    RESTRICT.StartTime        STARTTIME,
    RESTRICT.EndTime          ENDTIME,
    RESTRICT.enableGRPS       ENABLEGPRS,
    RESTRICT.GPRSStartTime    GPRSSTARTTIME,
    RESTRICT.GPRSEndTime      GPRSENDTIME,
    RESTRICT.MacMode          ISCHKMAC,
    Mac.Macvalue              MAC,
    BASIC.Remark              NOTES,
    BASIC.CreateDate          CREATEDATE,
    to_number(decode(BASIC.STAFFIDSTATUS,'01','1','02','2','03','0',BASIC.STAFFIDSTATUS))       STATUS,
    BASIC.StatusDate          STATUSDATE,
    BASIC.RELESTAFFID         RELE_STAFF_ID,
    BASIC.BeginDate           START_USING_TIME,
    BASIC.EndDate             END_USING_TIME,
    BASIC.LOGINTYPE           LOGINTYPE,
    BASIC.areaid              areaid,
    RESTRICT.ISCHECKTICKET    ISCHECKTICKET,
    BBOSSINFO.BBOSSSTAFFID    BBOSSOPERID
from ICDPUB_QZQ.T_UCP_STAFFBASICINFO BASIC ,
    ICDPUB_QZQ.T_UCP_PASSWORD    pwd,
    ICDPUB_QZQ.T_UCP_STAFFEXTENDINFO EXTEND,
    ICDPUB_QZQ.T_UCP_STAFFRESTRICTINFO RESTRICT,
    ICDPUB_QZQ.T_UCP_StaffMac Mac,
    ICDPUB_QZQ.T_UCP_STAFF_BBOSS_INFO BBOSSINFO
WHERE BASIC.Staffid = pwd.staffid(+)
  AND BASIC.Staffid = EXTEND.Staffid(+)
  AND BASIC.Staffid = RESTRICT.Staffid(+)
  AND BASIC.Staffid = Mac.Staffid(+)
  AND BASIC.Staffid = BBOSSINFO.Staffid(+)
;

CREATE TABLE "IM_INV_REALSIGN_USE" 
("REGION" NUMBER(6,0), 
"INV_ID" VARCHAR2(32), 
"RES_TYPE_ID" VARCHAR2(32), 
"INV_STATUS" VARCHAR2(32), 
"CHECK_STATUS" VARCHAR2(32), 
"STATUS_DATE" DATE, 
"STATUS_REASON" VARCHAR2(32), 
"LDSTORE_BUSI_ID" VARCHAR2(32), 
"LAST_BUSI_ID" VARCHAR2(32), 
"STORE_ID" VARCHAR2(32), 
"ORG_ID" VARCHAR2(32), 
"PHYSICAL_STATUS" VARCHAR2(32), 
"BUSI_STATUS" VARCHAR2(32), 
"OPER_ID" VARCHAR2(32), 
"USE_ORG_ID" VARCHAR2(32), 
"ASSET_ID" VARCHAR2(32), 
"SUPPLIER_ID" VARCHAR2(32) DEFAULT 'UNKNOWN', 
"FORMAT_ID" VARCHAR2(32), 
"MEMO" VARCHAR2(500), 
"ADDDATA1" VARCHAR2(32), 
"ADDDATA2" VARCHAR2(32), 
"ADDDATA3" VARCHAR2(32), 
"ADDDATA4" VARCHAR2(32), 
"ADDDATA5" VARCHAR2(32), 
"SALE_DATE" DATE, 
"LDSTORE_DATE" DATE DEFAULT SYSDATE, 
"COST_PRICE" VARCHAR2(9), 
"ERP_BATCH_ID" VARCHAR2(64), 
"WBANDDEVGRADE" NUMBER(2,0)
);

CREATE TABLE "LOC_IM_INV_FLAG" 
("REGION" NUMBER(6,0), 
"INV_ID" VARCHAR2(32), 
"INV_STATUS" VARCHAR2(32), 
"STORE_ID" VARCHAR2(32), 
"ORG_ID" VARCHAR2(32), 
"ORDER_ID" VARCHAR2(32), 
"APPLY_TYPE" VARCHAR2(32), 
"CHANNEL_TYPE" VARCHAR2(32), 
"INT_DATE" DATE, 
"FLAG" VARCHAR2(2)
);

CREATE TABLE "PSI_INFO_DEPOSIT" 
("OID" VARCHAR2(32), 
"REGION" NUMBER(5,0), 
"AGENT_ID" VARCHAR2(32), 
"AGENT_NAME" VARCHAR2(128), 
"DEPOSIT_ID" VARCHAR2(32), 
"PRJ_ID" VARCHAR2(32), 
"SUPPLIER_ID" VARCHAR2(32), 
"DEPOSIT" NUMBER(10,0), 
"AGENT_ALIAS" VARCHAR2(128), 
"TELE_NUM" VARCHAR2(32), 
"CUST_NAME" VARCHAR2(64), 
"BANK_ACCOUNT" VARCHAR2(64), 
"EFF_DATE" DATE, 
"EXP_DATE" DATE, 
"CREATE_DATE" DATE, 
"CREATE_OPER_ID" VARCHAR2(32), 
"CREATE_ORG_ID" VARCHAR2(32), 
"NOTES" VARCHAR2(128), 
"SUM_ORDER_NUM" NUMBER(10,0), 
"BILL_NO" VARCHAR2(64), 
"DEPOSIT_TYPE" VARCHAR2(32)
);

CREATE TABLE "PSI_INFO_DEPOSIT_RESTYPE" 
("DEPOSIT_OID" VARCHAR2(32), 
"BRAND_ID" VARCHAR2(32), 
"BRAND_NAME" VARCHAR2(64), 
"RES_TYPE_ID" VARCHAR2(32), 
"RES_TYPE_NAME" VARCHAR2(64), 
"ORDER_NUM" NUMBER(10,0) DEFAULT '0', 
"LEFT_NUM" NUMBER(10,0) DEFAULT '0', 
"UNIT_PRICE" NUMBER(10,0) DEFAULT '0', 
"TOTAL_PRICE" NUMBER(10,0) DEFAULT '0', 
"ORDER_FEE" NUMBER(10,0) DEFAULT '0'
);

CREATE TABLE "IM_INV_UNSIGN" 
("REGION" NUMBER(6,0), 
"RES_TYPE_ID" VARCHAR2(32), 
"STORE_ID" VARCHAR2(32), 
"INV_STATUS" VARCHAR2(32) DEFAULT 'INSTORE', 
"CHECK_STATUS" VARCHAR2(32) DEFAULT 'NORMAL', 
"PHYSICAL_STATUS" VARCHAR2(32) DEFAULT 'NORMAL', 
"BUSI_STATUS" VARCHAR2(32) DEFAULT 'USABLE', 
"STORE_AMOUNT" NUMBER(12,0) DEFAULT 0, 
"ORG_ID" VARCHAR2(32), 
"REAL_CONFIG" VARCHAR2(200), 
"STATUS_REASON" VARCHAR2(32), 
"OPER_ID" VARCHAR2(32), 
"LAST_BUSI_ID" VARCHAR2(32), 
"CHANGE_DATE" DATE, 
"EXP_DATE" DATE DEFAULT to_date('20371231','yyyy-mm-dd'), 
"BATCH_ID" VARCHAR2(32) DEFAULT '000000000000000000000000', 
"RELA_ID" VARCHAR2(32), 
"LDSTORE_DATE" DATE DEFAULT sysdate, 
"COST_PRICE" NUMBER(14,0) DEFAULT 0, 
"STORAGE_ID" VARCHAR2(32), 
"ERP_BATCH_ID" VARCHAR2(64), 
"EFF_DATE" DATE
);

CREATE TABLE "IM_WT_TELNUM_INLOG" 
("REGION" NUMBER(5,0), 
"INV_ID" VARCHAR2(32), 
"STATUS" VARCHAR2(6), 
"INTIME" DATE DEFAULT sysdate, 
"PROCESSED" NUMBER(1,0) DEFAULT 0, 
"PROCESSDATE" DATE, 
"PROCESSINFO" VARCHAR2(128), 
"IS_SYNC" VARCHAR2(1) DEFAULT 0
);









